== `StreamSourceProvider` -- Streaming Source Provider

`StreamSourceProvider` trait defines a <<contract, contract>> for objects that can <<createSource, create a streaming `Source`>> for a format (e.g. text file) or system (e.g. Apache Kafka) by their names.

NOTE: `StreamSourceProvider` is used when `DataSource` is requested for the link:spark-sql-datasource.adoc#sourceSchema[name and schema of a `Source`] or link:spark-sql-datasource.adoc#createSource[creates one].

.Streaming Source Providers
[cols="1,3",options="header",width="100%"]
|===
| Name | Description
| link:spark-sql-streaming-TextSocketSourceProvider.adoc[TextSocketSourceProvider] | Creates link:spark-sql-streaming-TextSocketSource.adoc[TextSocketSources] (for `socket` format).
| link:spark-sql-streaming-KafkaSourceProvider.adoc[KafkaSourceProvider] | Creates link:spark-sql-streaming-KafkaSourceProvider.adoc[KafkaSourceProvider] (for `kafka` format).
|===

=== [[contract]] `StreamSourceProvider` Contract

`StreamSourceProvider` contract defines two methods:

1. <<sourceSchema, sourceSchema>> that returns the name and link:spark-sql-schema.adoc[schema] of the link:spark-sql-streaming-source.adoc[Source].
2. <<createSource, createSource>> that produces a streaming link:spark-sql-streaming-source.adoc[Source] (to continually read data).

==== [[sourceSchema]] `sourceSchema` Method

[source, scala]
----
sourceSchema(
  sqlContext: SQLContext,
  schema: Option[StructType],
  providerName: String,
  parameters: Map[String, String]): (String, StructType)
----

==== [[createSource]] `createSource` Method

[source, scala]
----
createSource(
  sqlContext: SQLContext,
  metadataPath: String,
  schema: Option[StructType],
  providerName: String,
  parameters: Map[String, String]): Source
----
