== [[ClusteringEvaluator]] ClusteringEvaluator -- Evaluator of Clustering Models

`ClusteringEvaluator` is an link:spark-mllib-Evaluator.adoc[Evaluator] of clustering models (e.g. `FPGrowth`, `GaussianMixture`, link:spark-mllib-ALS.adoc[ALS], `KMeans`, `LinearSVC`, `RandomForestRegressor`, `GeneralizedLinearRegression`, link:spark-mllib-LinearRegression.adoc[LinearRegression], `GBTRegressor`, `DecisionTreeRegressor`, `NaiveBayes`)

NOTE: `ClusteringEvaluator` is available since Spark 2.3.0.

[[isLargerBetter]]
`ClusteringEvaluator` finds the best model by maximizing the model evaluation metric (i.e. link:spark-mllib-Evaluator.adoc#isLargerBetter[isLargerBetter] is always turned on).

```
import org.apache.spark.ml.evaluation.ClusteringEvaluator
val cluEval = new ClusteringEvaluator().
  setPredictionCol("prediction").
  setFeaturesCol("features").
  setMetricName("silhouette")

scala> cluEval.isLargerBetter
res0: Boolean = true

scala> println(cluEval.explainParams)
featuresCol: features column name (default: features, current: features)
metricName: metric name in evaluation (silhouette) (default: silhouette, current: silhouette)
predictionCol: prediction column name (default: prediction, current: prediction)
```

[[parameters]]
.ClusteringEvaluator' Parameters
[cols="1,1,2",options="header",width="100%"]
|===
| Parameter
| Default Value
| Description

| [[featuresCol]] `featuresCol`
| `features`
| Name of the column with features (of type `VectorUDT`)

| [[metricName]] `metricName`
| `silhouette`
a| Name of the classification metric for evaluation

NOTE: `metricName` can only be `silhouette`.

| [[predictionCol]] `predictionCol`
| `prediction`
| Name of the column with prediction (of type `NumericType`)
|===

=== [[evaluate]] Evaluating Model Output -- `evaluate` Method

[source, scala]
----
evaluate(dataset: Dataset[_]): Double
----

NOTE: `evaluate` is part of link:spark-mllib-Evaluator.adoc#evaluate[Evaluator Contract].

`evaluate`...FIXME
