== [[LocationStrategy]] LocationStrategy -- Preferred Hosts per Topic Partitions

`LocationStrategy` allows a link:spark-streaming-kafka-DirectKafkaInputDStream.adoc[DirectKafkaInputDStream] to request Spark executors to execute Kafka consumers as close topic leaders of topic partitions as possible.

`LocationStrategy` is used when link:spark-streaming-kafka-DirectKafkaInputDStream.adoc#compute[`DirectKafkaInputDStream` computes a `KafkaRDD` for a given batch interval] and is a means of distributing processing Kafka records across Spark executors.

.Location Strategies in Spark Streaming
[cols="1,2",options="header",width="100%"]
|===
| Location Strategy | Description
| PreferBrokers
| Use when executors are on the same nodes as your Kafka brokers.

| PreferConsistent
| Use in most cases as it consistently distributes partitions across all executors.

| PreferFixed
| Use to place particular ``TopicPartition``s on particular hosts if your load is uneven.

Accepts a collection of topic partition and host pairs. Any topic partition not specified uses a consistent location.
|===

NOTE: A topic partition is described using Kafka's https://kafka.apache.org/0100/javadoc/org/apache/kafka/common/TopicPartition.html[TopicPartition].

You can create a `LocationStrategy` using <<LocationStrategies, LocationStrategies factory object>>.

[source, scala]
----
import org.apache.spark.streaming.kafka010.LocationStrategies
val preferredHosts = LocationStrategies.PreferConsistent
----

=== [[LocationStrategies]] LocationStrategies Factory Object

`LocationStrategies` holds the factory methods to access `LocationStrategy` objects.

[source, scala]
----
PreferBrokers: LocationStrategy
PreferConsistent: LocationStrategy
PreferFixed(hostMap: collection.Map[TopicPartition, String]): LocationStrategy
----
