== [[StreamingListener]] Streaming Listeners

*Streaming listeners* are Spark listeners interested in <<StreamingListenerEvent, streaming events>> like batch submitted, started or completed.

Streaming listeners implement http://spark.apache.org/docs/latest/api/scala/#org.apache.spark.streaming.scheduler.StreamingListener[org.apache.spark.streaming.scheduler.StreamingListener] listener interface and process http://spark.apache.org/docs/latest/api/scala/#org.apache.spark.streaming.scheduler.StreamingListenerEvent[StreamingListenerEvent] events.

The following streaming listeners are available in Spark Streaming:

* <<StreamingJobProgressListener, StreamingJobProgressListener>>
* link:spark-streaming-backpressure.adoc#RateController[RateController]

=== [[StreamingListenerEvent]] StreamingListenerEvent Events

* `StreamingListenerBatchSubmitted` is posted when link:spark-streaming-jobscheduler.adoc#submitJobSet[streaming jobs are submitted for execution] and triggers `StreamingListener.onBatchSubmitted` (see <<StreamingJobProgressListener-onBatchSubmitted, StreamingJobProgressListener.onBatchSubmitted>>).

* `StreamingListenerBatchStarted` triggers `StreamingListener.onBatchStarted`

* `StreamingListenerBatchCompleted` is posted to inform that link:spark-streaming-jobscheduler.adoc#JobCompleted[a collection of streaming jobs has completed], i.e. all the streaming jobs in link:spark-streaming-jobscheduler.adoc#JobSet[JobSet] have stopped their execution.

=== [[StreamingJobProgressListener]] StreamingJobProgressListener

`StreamingJobProgressListener` is a streaming listener that collects information for link:spark-streaming-StreamingSource.adoc[StreamingSource] and link:spark-streaming-webui.adoc[Streaming page in web UI].

NOTE: A `StreamingJobProgressListener` is created while link:spark-streaming-streamingcontext.adoc#creating-instance[`StreamingContext` is created] and later registered as a `StreamingListener` and link:../spark-SparkListener.adoc[SparkListener] when link:spark-streaming-webui.adoc[Streaming tab] is created.

==== [[StreamingJobProgressListener-onBatchSubmitted]] onBatchSubmitted

For `StreamingListenerBatchSubmitted(batchInfo: BatchInfo)` events, it stores `batchInfo` batch information in the internal `waitingBatchUIData` registry per batch time.

The number of entries in `waitingBatchUIData` registry contributes to `numUnprocessedBatches` (together with `runningBatchUIData`), `waitingBatches`, and `retainedBatches`. It is also used to look up the batch data for a batch time (in `getBatchUIData`).

`numUnprocessedBatches`, `waitingBatches` are used in link:spark-streaming-StreamingSource.adoc[StreamingSource].

NOTE: `waitingBatches` and `runningBatches` are displayed together in link:spark-streaming-webui.adoc#active-batches[Active Batches in Streaming tab in web UI].

==== onBatchStarted

CAUTION: FIXME

==== [[onBatchCompleted]] onBatchCompleted

CAUTION: FIXME

==== [[retainedBatches]] Retained Batches

`retainedBatches` are waiting, running, and completed batches that link:spark-streaming-webui.adoc[web UI uses to display streaming statistics].

The number of retained batches is controlled by link:spark-streaming-settings.adoc[spark.streaming.ui.retainedBatches].
