== [[ConsumerStrategy]] ConsumerStrategy -- Kafka Consumers' Post-Configuration API

`ConsumerStrategy` is a contract to create Kafka Consumers in Spark Streaming that allows for their custom configuration after consumers are created.

NOTE: Kafka consumers read messages from topics in a Kafka cluster.

`ConsumerStrategy[K, V]` is an abstract class with two methods, i.e. <<executorKafkaParams, executorKafkaParams>> and <<onStart, onStart>>.

.ConsumerStrategy Contract and DirectKafkaInputDStream
[frame="topbot",cols="1,2",options="header",width="100%"]
|======================
| Consumer Strategy | DirectKafkaInputDStream Usage
| <<executorKafkaParams, executorKafkaParams>> | Used when a link:spark-streaming-kafka-DirectKafkaInputDStream.adoc#creating-instance[`DirectKafkaInputDStream` is created] to initialize internal state.
| <<onStart, onStart>> | Used to link:spark-streaming-kafka-DirectKafkaInputDStream.adoc#consumer[create a Kafka consumer (in `DirectKafkaInputDStream`)]
|======================

The following table are the Kafka Consumer strategies currently available in Spark 2.0.

.Kafka Consumer Strategies in Spark Streaming
[frame="topbot",cols="1,2",options="header",width="100%"]
|======================
| Consumer Strategy | Description
| <<Assign, Assign>> |
| <<Subscribe, Subscribe>> |
| <<SubscribePattern, SubscribePattern>> |
|======================

You can access the predefined `ConsumerStrategy` implementations using <<ConsumerStrategies, ConsumerStrategies factory object>>.

[source, scala]
----
import org.apache.spark.streaming.kafka010.ConsumerStrategies

val topics = List("topic1")
import org.apache.kafka.common.serialization.StringDeserializer
val kafkaParams = Map(
  "bootstrap.servers" -> "localhost:9092",
  "key.deserializer" -> classOf[StringDeserializer],
  "value.deserializer" -> classOf[StringDeserializer],
  "group.id" -> "spark-streaming-notes",
  "auto.offset.reset" -> "earliest"
)
import org.apache.kafka.common.TopicPartition
val offsets = Map(new TopicPartition("topic3", 0) -> 2L)

val subscribeStrategy = ConsumerStrategies.Subscribe[String, String](topics, kafkaParams, offsets)
----

=== [[executorKafkaParams]] `executorKafkaParams` Method

[source, scala]
----
executorKafkaParams: ju.Map[String, Object]
----

=== [[onStart]] `onStart` Method

[source, scala]
----
onStart(currentOffsets: ju.Map[TopicPartition, jl.Long]): Consumer[K, V]
----

=== [[Assign]] Assign Strategy

=== [[Subscribe]] Subscribe Strategy

=== [[SubscribePattern]] SubscribePattern Strategy

=== [[ConsumerStrategies]] ConsumerStrategies Factory Object
