= The Internals Of Apache Spark {page-component-version}

Welcome to *The Internals Of Apache Spark* gitbook! I'm very excited to have you here and hope you will enjoy exploring the internals of Apache Spark (Core) as much as I have.

[quote, Flannery O'Connor]
I write to discover what I know.

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], a freelance IT consultant, software engineer and technical instructor specializing in https://spark.apache.org/[Apache Spark], https://kafka.apache.org/[Apache Kafka], https://delta.io/[Delta Lake] and https://kafka.apache.org/documentation/streams/[Kafka Streams] (with https://www.scala-lang.org/[Scala] and https://www.scala-sbt.org/[sbt]).

I offer software development and consultancy services with hands-on in-depth workshops and mentoring. Reach out to me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss opportunities.

Consider joining me at http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups in Warsaw, Poland.

TIP: I'm also writing other books in the "The Internals Of" series about https://bit.ly/spark-sql-internals[Spark SQL], https://bit.ly/spark-structured-streaming[Spark Structured Streaming], https://delta.japila.pl/[Delta Lake], https://bit.ly/apache-kafka-internals[Apache Kafka] and https://bit.ly/kafka-streams-internals[Kafka Streams].

Expect text and code snippets from a variety of public sources. Attribution follows.

Now, let me introduce you to <<spark-overview.adoc#, Apache Spark>>.
