= [[MapOutputTrackerWorker]] MapOutputTrackerWorker

*MapOutputTrackerWorker* is the xref:ROOT:MapOutputTracker.adoc[MapOutputTracker] for executors.

`MapOutputTrackerWorker` uses Java's thread-safe https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html[java.util.concurrent.ConcurrentHashMap] for xref:ROOT:MapOutputTracker.adoc#mapStatuses[`mapStatuses` internal cache] and any lookup cache miss triggers a fetch from the driver's xref:ROOT:MapOutputTrackerMaster.adoc[MapOutputTrackerMaster].

NOTE: The only difference between `MapOutputTrackerWorker` and the base abstract class `MapOutputTracker` is that the xref:ROOT:MapOutputTracker.adoc#mapStatuses[`mapStatuses` internal registry] is an instance of the thread-safe https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html[java.util.concurrent.ConcurrentHashMap].

== [[logging]] Logging

Enable `ALL` logging level for `org.apache.spark.MapOutputTrackerWorker` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

[source]
----
log4j.logger.org.apache.spark.MapOutputTrackerWorker=ALL
----

Refer to xref:ROOT:spark-logging.adoc[Logging].
