= [[MapOutputTrackerMasterEndpoint]] MapOutputTrackerMasterEndpoint

*MapOutputTrackerMasterEndpoint* is a xref:ROOT:spark-rpc-RpcEndpoint.adoc[RpcEndpoint] for xref:ROOT:MapOutputTrackerMaster.adoc[MapOutputTrackerMaster].

MapOutputTrackerMasterEndpoint handles the following <<messages, messages>>:

* <<GetMapOutputStatuses, GetMapOutputStatuses>>
* <<StopMapOutputTracker, StopMapOutputTracker>>

== [[creating-instance]] Creating Instance

MapOutputTrackerMasterEndpoint takes the following to be created:

* [[rpcEnv]] xref:ROOT:spark-rpc-RpcEnv.adoc[RpcEnv]
* [[tracker]] xref:ROOT:MapOutputTrackerMaster.adoc[MapOutputTrackerMaster]
* [[conf]] xref:ROOT:spark-SparkConf.adoc[SparkConf]

While being created, MapOutputTrackerMasterEndpoint prints out the following DEBUG message to the logs:

```
init
```

== [[messages]] Messages

=== [[GetMapOutputStatuses]] GetMapOutputStatuses

[source, scala]
----
GetMapOutputStatuses(shuffleId: Int)
----

When GetMapOutputStatuses arrives, MapOutputTrackerMasterEndpoint reads the host and the port of the sender.

You should see the following INFO message in the logs:

```
Asked to send map output locations for shuffle [shuffleId] to [hostPort]
```

MapOutputTrackerMasterEndpoint xref:ROOT:MapOutputTrackerMaster.adoc#post[posts a `GetMapOutputMessage` to `MapOutputTrackerMaster`] (with `shuffleId` and the current `RpcCallContext`).

GetMapOutputStatuses is posted when MapOutputTracker is requested to xref:ROOT:MapOutputTracker.adoc#getStatuses[fetch shuffle map outputs remotely].

=== [[StopMapOutputTracker]] StopMapOutputTracker

[source, scala]
----
StopMapOutputTracker
----

When StopMapOutputTracker arrives, you should see the following INFO message in the logs:

```
INFO MapOutputTrackerMasterEndpoint stopped!
```

MapOutputTrackerMasterEndpoint confirms the request (by replying `true`) and link:spark-rpc-RpcEndpoint.adoc#stop[stops itself] (and stops accepting messages).

StopMapOutputTracker is posted when MapOutputTrackerMaster is requested to xref:ROOT:MapOutputTrackerMaster.adoc#stop[stop].

== [[logging]] Logging

Enable `ALL` logging level for `org.apache.spark.MapOutputTrackerMasterEndpoint` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

[source]
----
log4j.logger.org.apache.spark.MapOutputTrackerMasterEndpoint=ALL
----

Refer to xref:ROOT:spark-logging.adoc[Logging].
