= [[BlockDataManager]] BlockDataManager Contract -- Block Storage Management API

`BlockDataManager` is the <<contract, abstraction>> of <<implementations, block data managers>> that manage storage for blocks of data (aka _block storage management API_).

`BlockDataManager` uses <<spark-BlockId.adoc#, BlockIds>> to uniquely identify blocks of data and <<spark-ManagedBuffer.adoc#, ManagedBuffers>> to refer to them.

[[implementations]]
NOTE: <<BlockManager.adoc#, BlockManager>> is the default and only implementation of the <<contract, BlockDataManager Contract>> in Apache Spark.

[[contract]]
.BlockDataManager Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| getBlockData
a| [[getBlockData]]

[source, scala]
----
getBlockData(blockId: BlockId): ManagedBuffer
----

Fetches a block data (as a <<spark-ManagedBuffer.adoc#, ManagedBuffer>>) for the given <<spark-BlockId.adoc#, BlockId>>

Used when:

* `NettyBlockRpcServer` is requested to <<spark-NettyBlockRpcServer.adoc#receive-OpenBlocks, handle a OpenBlocks message>>

* `ShuffleBlockFetcherIterator` is requested to <<spark-ShuffleBlockFetcherIterator.adoc#fetchLocalBlocks, fetchLocalBlocks>>

| putBlockData
a| [[putBlockData]]

[source, scala]
----
putBlockData(
  blockId: BlockId,
  data: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Boolean
----

Stores (_puts_) a block data (as a <<spark-ManagedBuffer.adoc#, ManagedBuffer>>) for the given <<spark-BlockId.adoc#, BlockId>>. Returns `true` when completed successfully or `false` when failed.

Used exclusively when `NettyBlockRpcServer` is requested to <<spark-NettyBlockRpcServer.adoc#receive-UploadBlock, handle an UploadBlock message>>

| putBlockDataAsStream
a| [[putBlockDataAsStream]]

[source, scala]
----
putBlockDataAsStream(
  blockId: BlockId,
  level: StorageLevel,
  classTag: ClassTag[_]): StreamCallbackWithID
----

Stores a block data that will be received as a stream

Used exclusively when `NettyBlockRpcServer` is requested to <<spark-NettyBlockRpcServer.adoc#receiveStream, receiveStream>>

| releaseLock
a| [[releaseLock]]

[source, scala]
----
releaseLock(
  blockId: BlockId,
  taskAttemptId: Option[Long]): Unit
----

Releases a lock

Used when:

* `TorrentBroadcast` is requested to <<spark-TorrentBroadcast.adoc#releaseLock, releaseLock>>

* `BlockManager` is requested to <<BlockManager.adoc#handleLocalReadFailure, handleLocalReadFailure>>, <<BlockManager.adoc#getLocalValues, getLocalValues>>, <<BlockManager.adoc#getOrElseUpdate, getOrElseUpdate>>, <<BlockManager.adoc#doPut, doPut>>, and <<BlockManager.adoc#releaseLockAndDispose, releaseLockAndDispose>>

|===
