== [[TransportContext]] TransportContext

`TransportContext` is...FIXME

=== [[createChannelHandler]] `createChannelHandler` Internal Method

[source, java]
----
TransportChannelHandler createChannelHandler(Channel channel, RpcHandler rpcHandler)
----

`createChannelHandler`...FIXME

NOTE: `createChannelHandler` is used exclusively when `TransportContext` is requested to <<initializePipeline, initializePipeline>>.

=== [[initializePipeline]] `initializePipeline` Method

[source, java]
----
TransportChannelHandler initializePipeline(SocketChannel channel) // <1>
TransportChannelHandler initializePipeline(
  SocketChannel channel,
  RpcHandler channelRpcHandler)
----
<1> Simply calls the other `initializePipeline` with the <<rpcHandler, RpcHandler>>

`initializePipeline`...FIXME

[NOTE]
====
`initializePipeline` is used when:

* `TransportServer` is requested to link:spark-TransportServer.adoc#init[init]

* `TransportClientFactory` is requested to link:spark-TransportClientFactory.adoc#createClient[createClient]
====

=== [[createServer]] Creating TransportServer on Host and Port -- `createServer` Method

[source, java]
----
TransportServer createServer()  // <1>
TransportServer createServer(int port, List<TransportServerBootstrap> bootstraps) // <2>
TransportServer createServer(List<TransportServerBootstrap> bootstraps) // <3>
TransportServer createServer(
  String host, int port, List<TransportServerBootstrap> bootstraps)
----
<1> Uses `0` for the port and no bootstraps. Used exclusively for testing
<2> Uses `null` for the host
<3> Used exclusively for testing

`createServer` simply creates a TransportServer (with the current `TransportContext`, the host, the port, the <<rpcHandler, RpcHandler>> and the bootstraps).

[NOTE]
====
`createServer` is used when:

* `NettyBlockTransferService` is requested to link:spark-NettyBlockTransferService.adoc#createServer[createServer]

* `NettyRpcEnv` is requested to `startServer`

* `ExternalShuffleService` is requested to xref:deploy:ExternalShuffleService.adoc#start[start]

* Spark on YARN's `YarnShuffleService` is requested to `serviceInit`
====
