= FileCommitProtocol

`FileCommitProtocol` is an <<contract, abstraction>> of <<implementations, job and task committers>> that can setup, commit or abort a job or task.

[[contract]]
.FileCommitProtocol Contract (Abstract Methods Only)
[cols="30m,70",options="header",width="100%"]
|===
| Method
| Description

| abortJob
a| [[abortJob]]

[source, scala]
----
abortJob(
  jobContext: JobContext): Unit
----

Used when...FIXME

| abortTask
a| [[abortTask]]

[source, scala]
----
abortTask(
  taskContext: TaskAttemptContext): Unit
----

Used when...FIXME

| commitJob
a| [[commitJob]]

[source, scala]
----
commitJob(
  jobContext: JobContext,
  taskCommits: Seq[TaskCommitMessage]): Unit
----

Used when...FIXME

| commitTask
a| [[commitTask]]

[source, scala]
----
commitTask(
  taskContext: TaskAttemptContext): TaskCommitMessage
----

Used when...FIXME

| newTaskTempFile
a| [[newTaskTempFile]]

[source, scala]
----
newTaskTempFile(
  taskContext: TaskAttemptContext,
  dir: Option[String],
  ext: String): String
----

Used when...FIXME

| newTaskTempFileAbsPath
a| [[newTaskTempFileAbsPath]]

[source, scala]
----
newTaskTempFileAbsPath(
  taskContext: TaskAttemptContext,
  absoluteDir: String,
  ext: String): String
----

Used when...FIXME

| onTaskCommit
a| [[onTaskCommit]]

[source, scala]
----
onTaskCommit(
  taskCommit: TaskCommitMessage): Unit = {}
----

Used when...FIXME

| setupJob
a| [[setupJob]]

[source, scala]
----
setupJob(
  jobContext: JobContext): Unit
----

Used when...FIXME

| setupTask
a| [[setupTask]]

[source, scala]
----
setupTask(
  taskContext: TaskAttemptContext): Unit
----

Used when...FIXME

|===

[[implementations]]
.FileCommitProtocols
[cols="30,70",options="header",width="100%"]
|===
| FileCommitProtocol
| Description

| <<spark-internal-io-HadoopMapReduceCommitProtocol.adoc#, HadoopMapReduceCommitProtocol>>
| [[HadoopMapReduceCommitProtocol]]

| <<spark-internal-io-HadoopMapRedCommitProtocol.adoc#, HadoopMapRedCommitProtocol>>
| [[HadoopMapRedCommitProtocol]]

|===

== [[deleteWithJob]] `deleteWithJob` Method

[source, scala]
----
deleteWithJob(
  fs: FileSystem,
  path: Path,
  recursive: Boolean): Boolean
----

`deleteWithJob`...FIXME

NOTE: `deleteWithJob` is used when...FIXME
