== [[TransportServer]] TransportServer

`TransportServer` is...FIXME

`TransportServer` is <<creating-instance, created>> exclusively when `TransportContext` is requested to link:spark-TransportContext.adoc#createServer[createServer].

=== [[init]] `init` Internal Method

[source, java]
----
void init(String hostToBind, int portToBind)
----

`init`...FIXME

NOTE: `init` is used exclusively when `TransportServer` is <<creating-instance, created>>.

=== [[getPort]] `getPort` Method

[source, java]
----
int getPort()
----

`getPort`...FIXME

[NOTE]
====
`getPort` is used when:

* `NettyRpcEnv` is requested for the `address`

* Spark on YARN's `YarnShuffleService` is requested to `serviceInit`
====

=== [[creating-instance]] Creating TransportServer Instance

`TransportServer` takes the following when created:

* [[context]] link:spark-TransportContext.adoc[TransportContext]
* [[hostToBind]] Host name to bind to
* [[portToBind]] Port number to bind to
* [[appRpcHandler]] link:spark-RpcHandler.adoc[RpcHandler]
* [[bootstraps]] `TransportServerBootstraps`

When created, `TransportServer` <<init, init>> with the <<hostToBind, host>> and <<portToBind, port>> to bind to.
