= ReliableCheckpointRDD

*ReliableCheckpointRDD* is an xref:rdd:CheckpointRDD.adoc[CheckpointRDD]...FIXME

== [[creating-instance]] Creating Instance

ReliableCheckpointRDD takes the following to be created:

* [[sc]] xref:ROOT:spark-SparkContext.adoc[SparkContext]
* [[checkpointPath]] Checkpoint directory
* [[_partitioner]] Optional xref:rdd:Partitioner.adoc[Partitioner] (default: undefined)

ReliableCheckpointRDD is created when:

* ReliableCheckpointRDD utility is used to <<writeRDDToCheckpointDirectory, created one>>.

* SparkContext is requested to xref:ROOT:spark-SparkContext.adoc#checkpointFile[checkpointFile]

== [[writeRDDToCheckpointDirectory]] Writing RDD to Checkpoint Directory

[source, scala]
----
writeRDDToCheckpointDirectory[T: ClassTag](
  originalRDD: RDD[T],
  checkpointDir: String,
  blockSize: Int = -1): ReliableCheckpointRDD[T]
----

writeRDDToCheckpointDirectory...FIXME

writeRDDToCheckpointDirectory is used when ReliableRDDCheckpointData is requested to xref:rdd:ReliableRDDCheckpointData.adoc#doCheckpoint[doCheckpoint].
