== Mastering Apache Spark

Welcome to Mastering Apache Spark (aka #SparkNotes)!

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], an *independent consultant* who offers development and training services for *Apache Spark* (and Scala, sbt with a bit of Hadoop YARN, Apache Kafka, Apache Hive, Apache Mesos, Akka Actors/Stream/HTTP, and Docker). I lead http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups.

Contact me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss Spark opportunities, e.g. courses, workshops, or other mentoring or development services.

If you like the Apache Spark notes you should seriously consider participating in my own, very hands-on https://github.com/jaceklaskowski/spark-workshop#spark-workshops-for-developers-administrators-and-operators[Spark Workshops for Developers, Administrators and Operators].

This collections of notes (what some may rashly call a "book") serves as the ultimate place of mine to collect all the nuts and bolts of using https://spark.apache.org[Apache Spark]. The notes aim to help me designing and developing better products with Spark. It is also a viable proof of my understanding of Apache Spark. I do eventually want to reach the highest level of mastery in Apache Spark.

It _may_ become a book one day, but surely serves as *the study material* for trainings, workshops, videos and courses about Apache Spark. Follow me on twitter https://twitter.com/jaceklaskowski[@jaceklaskowski] to know it early. You will also learn about the upcoming events about Apache Spark.

Expect text and code snippets from http://spark.apache.org/community.html[Spark's mailing lists], http://spark.apache.org/docs/latest/[the official documentation of Apache Spark], http://stackoverflow.com/tags/apache-spark/info[StackOverflow], blog posts, http://search.oreilly.com/?q=learning+spark[books from O'Reilly], press releases, YouTube/Vimeo videos, http://www.quora.com/Apache-Spark[Quora], https://github.com/apache/spark[the source code of Apache Spark], etc. Attribution follows.
