== Mastering Apache Spark book

I'm Jacek who is the note-taker and https://pl.linkedin.com/in/jaceklaskowski[the founder of Japila.pl] that offers development and training services for *Apache Spark*. Contact me at jacek@japila.pl to discuss Spark opportunities.

This collections of notes (what some may rashly call a "book") serves as the ultimate place of mine to collect all the nuts and bolts of using https://spark.apache.org[Apache Spark]. The notes aim to help me designing and developing better products with Spark. I do eventually want to reach the highest level of mastery in Apache Spark.

It _may_ become a book one day, but surely is going to serve as *the study material* for my upcoming videos and courses about Apache Spark. Follow me on twitter https://twitter.com/jaceklaskowski[@jaceklaskowski] to know it early. You will also learn about the upcoming courses, trainings and workshops about Apache Spark.

Expect text and code snippets from http://spark.apache.org/community.html[Spark's mailing lists], http://spark.apache.org/docs/latest/[the official documentation of Apache Spark], http://stackoverflow.com/tags/apache-spark/info[StackOverflow], blog posts, http://search.oreilly.com/?q=learning+spark[books from O'Reilly], press releases, YouTube/Vimeo videos, http://www.quora.com/Apache-Spark[Quora], https://github.com/apache/spark[the source code of Apache Spark], etc. Attribution follows.
