== The Internals of Apache Spark {{ book.version }}

Welcome to *The Internals of Apache Spark* gitbook! I'm very excited to have you here and hope you will enjoy exploring the internals of Apache Spark (Core) as much as I have.

[quote, Flannery O'Connor]
I write to discover what I know.

I'm https://pl.linkedin.com/in/jaceklaskowski[Jacek Laskowski], a freelance IT consultant, software engineer and technical instructor specializing in *Apache Spark*, Apache Kafka and Kafka Streams (with Scala and sbt).

I offer software development and consultancy services with hands-on in-depth workshops and mentoring. Reach out to me at jacek@japila.pl or https://twitter.com/jaceklaskowski[@jaceklaskowski] to discuss opportunities.

Consider joining me at http://www.meetup.com/WarsawScala/[Warsaw Scala Enthusiasts] and http://www.meetup.com/Warsaw-Spark[Warsaw Spark] meetups in Warsaw, Poland.

TIP: I'm also writing https://bit.ly/mastering-spark-sql[The Internals of Spark SQL], https://bit.ly/spark-structured-streaming[The Internals of Spark Structured Streaming], https://bit.ly/mastering-kafka-streams[The Internals of Kafka Streams], and https://bit.ly/mastering-apache-kafka[The Internals of Apache Kafka] gitbooks.

Expect text and code snippets from a variety of public sources. Attribution follows.

Now, let me introduce you to <<spark-overview.adoc#, Apache Spark>>.
