== Mastering Apache Spark book

I'm https://pl.linkedin.com/in/jaceklaskowski[a technology evangelist for Apache Spark at deepsense.io] and this collections of notes (what some may rashly call a "book") serves as the ultimate place of mine to collect all the nuts and bolts of using http://spark.apache.org/[Apache Spark] to design and develop a better product at http://deepsense.io/[deepsense.io] with all the bells and whistles that have proven so helpful for the team to reach the highest level of mastery in Apache Spark.

It _may_ become a book one day, but surely is going to serve as *the study material* for my upcoming videos and courses about Apache Spark. Follow me on twitter https://twitter.com/jaceklaskowski[@jaceklaskowski] to know it early. You may also consider following https://twitter.com/deepsense_io[@deepsense_io] to know about the courses, trainings and workshops about Apache Spark.

Expect text and code snippets from http://spark.apache.org/community.html[Spark's mailing lists], http://spark.apache.org/docs/latest/[the official documentation of Apache Spark], http://stackoverflow.com/tags/apache-spark/info[StackOverflow], blog posts, http://search.oreilly.com/?q=learning+spark[books from O'Reilly], press releases, YouTube/Vimeo videos, http://www.quora.com/Apache-Spark[Quora], etc.
Attribution follows.
