== Receivers

*Receivers* run on worker nodes to receive external data.

It is represented by https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/receiver/Receiver.scala[abstract class Receiver] that is parameterized by link:spark-rdd-caching.adoc#storage-levels[StorageLevel].

NOTE: Receivers must have link:spark-streaming-receiversupervisors.adoc[ReceiverSupervisors] attached because `store` and management methods pass calls on to them.

The abstract `Receiver` class requires the following methods to be implemented:

* `onStart()` that starts the receiver when the application starts.
* `onStop()` that stops the receiver.

A receiver is identified by the unique identifier `Receiver.streamId` (that corresponds to the unique identifier of the receiver input stream it is associated with).

NOTE: The StorageLevel is used to instantiate `ReceivedBlockHandler` in link:spark-streaming-receiversupervisors.adoc#ReceiverSupervisorImpl[ReceiverSupervisorImpl].

A receiver uses `store` methods to store received data as a data block into Spark's memory.

A receiver can be in one of the three states: `Initialized`, `Started`, and `Stopped`.
