== [[LogicalPlan]] Logical Query Plan

CAUTION: FIXME

*Logical Plan* is an abstract representation of a query (that "produces" a link:spark-sql-dataset.adoc[Dataset]).

It is modelled as `LogicalPlan` abstract class which is a custom link:spark-sql-query-plan.adoc[QueryPlan].

It may or may not be *analyzed* which is to denote that the plan (including children) has gone through analysis and verification. It may also be *resolved* to a specific schema.

`LogicalPlan` knows the size of objects that are results of SQL operators, like `join` through `Statistics` object.

`LogicalPlan` knows the maximum number of rows it can compute.

=== [[specialized-logical-plans]] Specialized LogicalPlans

* `LeafNode`
* `UnaryNode`
* `BinaryNode`

=== [[Join]] Join Logical Plan

`Join` is a `LogicalPlan` that acts on two `LogicalPlan` objects. It has a join type and an optional expression for the join.

The following is a list of join types:

* INNER
* LEFT OUTER
* RIGHT OUTER
* FULL OUTER
* LEFT SEMI
* NATURAL
