== [[BroadcastExchangeExec]] BroadcastExchangeExec Unary Physical Operator

`BroadcastExchangeExec` is a link:spark-sql-SparkPlan.adoc#UnaryExecNode[unary physical operator] (i.e. with one <<child, child>> physical operator) to broadcast a table to executors.

[[outputPartitioning]]
`BroadcastExchangeExec` uses `BroadcastPartitioning` partitioning scheme (with the input <<mode, BroadcastMode>>).

`BroadcastExchangeExec` is <<creating-instance, created>> exclusively when `EnsureRequirements` physical query plan optimization link:spark-sql-EnsureRequirements.adoc#ensureDistributionAndOrdering[ensures BroadcastDistribution of the input data of a physical operator] (that _seemingly_ can be either link:spark-sql-SparkPlan-BroadcastHashJoinExec.adoc[BroadcastHashJoinExec] or link:spark-sql-SparkPlan-BroadcastNestedLoopJoinExec.adoc[BroadcastNestedLoopJoinExec]).

[[metrics]]
.BroadcastExchangeExec SQLMetrics
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[dataSize]] `dataSize`
| data size (bytes)

| [[broadcastTime]] `broadcastTime`
| time to broadcast (ms)

| [[buildTime]] `buildTime`
| time to build (ms)

| [[collectTime]] `collectTime`
| time to collect (ms)
|===

=== [[creating-instance]] Creating BroadcastExchangeExec Instance

`BroadcastExchangeExec` takes the following when created:

* [[mode]] `BroadcastMode`
* [[child]] link:spark-sql-SparkPlan.adoc[SparkPlan]
