== [[CreateDataSourceTableCommand]] CreateDataSourceTableCommand Logical Command

`CreateDataSourceTableCommand` is a link:spark-sql-LogicalPlan-RunnableCommand.adoc[logical command] that <<run, creates a new table>> (in a session-scoped `SessionCatalog`).

`CreateDataSourceTableCommand` is created exclusively when link:spark-sql-SessionState.adoc#DataSourceAnalysis[DataSourceAnalysis] evaluation rule resolves `CreateTable` logical operator for a non-Hive table provider with no query.

`CreateDataSourceTableCommand` takes a `table` metadata and `ignoreIfExists` flag.

=== [[run]] `run` Method

[source, scala]
----
run(sparkSession: SparkSession): Seq[Row]
----

`run` link:spark-sql-SessionCatalog.adoc#createTable[creates a new table] in a session-scoped `SessionCatalog`.

NOTE: `run` uses the input `SparkSession` to link:spark-sql-SparkSession.adoc#sessionState[access SessionState] that in turn is used to link:spark-sql-SessionState.adoc#catalog[access the current SessionCatalog].

Internally, `run` link:spark-sql-DataSource.adoc#resolveRelation[creates a BaseRelation] to access the table's schema.

CAUTION: FIXME

NOTE: `run` accepts tables only (not views) with the provider defined.

NOTE: `run` is a part of link:spark-sql-LogicalPlan-RunnableCommand.adoc#run[RunnableCommand Contract].
