== [[AggregateProcessor]] AggregateProcessor

`AggregateProcessor` is <<apply, created>> and used exclusively when `WindowExec` physical operator is executed.

`AggregateProcessor` supports link:spark-sql-Expression-AggregateFunction-DeclarativeAggregate.adoc[DeclarativeAggregate] and link:spark-sql-Expression-AggregateFunction-ImperativeAggregate.adoc[ImperativeAggregate] aggregate <<functions, functions>> only (which link:spark-sql-SparkPlan-WindowExec.adoc#windowFrameExpressionFactoryPairs[happen to] be link:spark-sql-Expression-AggregateFunction.adoc[AggregateFunction] in link:spark-sql-Expression-AggregateExpression.adoc[AggregateExpression] or link:spark-sql-Expression-AggregateWindowFunction.adoc[AggregateWindowFunction]).

NOTE: `AggregateProcessor` is <<creating-instance, created>> using `AggregateProcessor` factory object (using <<apply, apply>> method).

=== [[initialize]] `initialize` Method

[source, scala]
----
initialize(size: Int): Unit
----

CAUTION: FIXME

NOTE: `initialize` is used when...FIXME

=== [[update]] `update` Method

[source, scala]
----
update(input: InternalRow): Unit
----

CAUTION: FIXME

NOTE: `update` is used when...FIXME

=== [[evaluate]] `evaluate` Method

[source, scala]
----
evaluate(target: InternalRow): Unit
----

CAUTION: FIXME

NOTE: `evaluate` is used when...FIXME

=== [[apply]][[functions]] `apply` Factory Method

[source, scala]
----
apply(
  functions: Array[Expression],
  ordinal: Int,
  inputAttributes: Seq[Attribute],
  newMutableProjection: (Seq[Expression], Seq[Attribute]) => MutableProjection): AggregateProcessor
----

NOTE: `apply` is used exclusively when `WindowExec` is link:spark-sql-SparkPlan-WindowExec.adoc#doExecute[executed] (and creates link:spark-sql-WindowFunctionFrame.adoc[WindowFunctionFrame] per `AGGREGATE` window aggregate functions, i.e. link:spark-sql-Expression-AggregateExpression.adoc[AggregateExpression] or link:spark-sql-Expression-AggregateWindowFunction.adoc[AggregateWindowFunction])

=== [[creating-instance]] Creating AggregateProcessor Instance

`AggregateProcessor` takes the following when created:

* [[bufferSchema]] Schema of the buffer (as a collection of `AttributeReferences`)
* [[initialProjection]] Initial `MutableProjection`
* [[updateProjection]] Update `MutableProjection`
* [[evaluateProjection]] Evaluate `MutableProjection`
* [[imperatives]] link:spark-sql-Expression-AggregateFunction-ImperativeAggregate.adoc[ImperativeAggregate] expressions for aggregate functions
* [[trackPartitionSize]] Flag whether to track partition size
