== [[ExperimentalMethods]] ExperimentalMethods

`ExperimentalMethods` holds extra <<extraStrategies, strategies>> and <<extraOptimizations, optimizations>> (as `Rule[LogicalPlan]`) that are used in link:spark-sql-SparkPlanner.adoc[SparkPlanner] and link:spark-sql-SparkOptimizer.adoc[SparkOptimizer], respectively.

[[attributes]]
.ExperimentalMethods' Attributes (in alphabetical order)
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| [[extraStrategies]] extraStrategies
a| Collection of `Strategy` objects that are used when:

* `SessionState` link:spark-sql-SessionState.adoc#planner[is requested for `SparkPlanner`]

| [[extraOptimizations]] extraOptimizations
a| Collection of link:spark-sql-catalyst-RuleExecutor.adoc#Rule[rules] to optimize link:spark-sql-LogicalPlan.adoc[LogicalPlans] (i.e. `Rule[LogicalPlan]` objects) that are used when:

* `SparkOptimizer` link:spark-sql-SparkOptimizer.adoc[is requested for the batches] (with "User Provided Optimizers" batch for the extra optimizations)
|===
