== [[DataSource]] DataSource

`DataSource` case class belongs to the Data Source API (along with link:spark-sql-dataframereader.adoc[DataFrameReader] and link:spark-sql-dataframewriter.adoc[DataFrameWriter]).

CAUTION: FIXME Review `DataSource` case class.

=== [[write]] write

CAUTION: FIXME

=== [[createSource]] createSource

[source, scala]
----
createSource(metadataPath: String): Source
----

CAUTION: FIXME

=== [[sourceSchema]] sourceSchema

CAUTION: FIXME

=== [[inferFileFormatSchema]] inferFileFormatSchema

[source, scala]
----
inferFileFormatSchema(format: FileFormat): StructType
----

`inferFileFormatSchema` private method computes (aka _infers_) schema (as link:spark-sql-dataframe-structtype.adoc[StructType]). It returns `userSpecifiedSchema` if specified or uses `FileFormat.inferSchema`. It throws a `AnalysisException` when is unable to infer schema.

It uses `path` option for the list of directory paths.

NOTE: It is used by <<sourceSchema, DataSource.sourceSchema>> and <<createSource, DataSource.createSource>> when `FileFormat` is processed.
