== [[RowDataSourceScanExec]] RowDataSourceScanExec Leaf Physical Operator

`RowDataSourceScanExec` is a link:spark-sql-SparkPlan-DataSourceScanExec.adoc[DataSourceScanExec] (and so indirectly a link:spark-sql-SparkPlan.adoc#LeafExecNode[leaf physical operator]) for scanning data from a relation.

`RowDataSourceScanExec` is <<creating-instance, created>> for link:spark-sql-LogicalPlan-LogicalRelation.adoc[LogicalRelation] with different kinds of relations (in link:spark-sql-SparkStrategy-DataSourceStrategy.adoc#apply[DataSourceStrategy] execution planning strategy).

=== [[doProduce]] Generating Java Source Code -- `doProduce` Method

[source, scala]
----
doProduce(ctx: CodegenContext): String
----

NOTE: `doProduce` is a part of link:spark-sql-CodegenSupport.adoc#doProduce[CodegenSupport Contract] to generate a Java source code for...FIXME

`doProduce`...FIXME

=== [[creating-instance]] Creating RowDataSourceScanExec Instance

`RowDataSourceScanExec` takes the following when created:

* [[output]] Output schema link:spark-sql-Expression-Attribute.adoc[attributes]
* [[rdd]] RDD of link:spark-sql-InternalRow.adoc[internal binary rows]
* [[relation]] link:spark-sql-BaseRelation.adoc[BaseRelation]
* [[outputPartitioning]] Output partitioning
* [[metadata]] Metadata (as a collection of pairs)
* [[metastoreTableIdentifier]] Optional `TableIdentifier`
