== [[ShuffleManager]] ShuffleManager -- Pluggable Shuffle Systems

`ShuffleManager` is the <<contract, pluggable mechanism>> for *shuffle systems* that track link:spark-dagscheduler-ShuffleMapStage.adoc[shuffle dependencies for `ShuffleMapStage`] on the driver and executors.

NOTE: link:spark-SortShuffleManager.adoc[SortShuffleManager] (short name: `sort` or `tungsten-sort`) is the one and only `ShuffleManager` in Spark 2.0.

<<spark_shuffle_manager, spark.shuffle.manager>> Spark property sets up the default shuffle manager.

The driver and executor access their `ShuffleManager` instances using link:spark-sparkenv.adoc#shuffleManager[SparkEnv].

[source, scala]
----
val shuffleManager = SparkEnv.get.shuffleManager
----

The driver registers shuffles with a shuffle manager, and executors (or tasks running locally in the driver) can ask to read and write data.

It is network-addressable, i.e. it is available on a host and port.

There can be many shuffle services running simultaneously and a driver registers with all of them when link:spark-SchedulerBackend.adoc[CoarseGrainedSchedulerBackend] is used.

=== [[contract]] ShuffleManager Contract

[source, scala]
----
trait ShuffleManager {
  def registerShuffle[K, V, C](
      shuffleId: Int,
      numMaps: Int,
      dependency: ShuffleDependency[K, V, C]): ShuffleHandle
  def getWriter[K, V](
    handle: ShuffleHandle,
    mapId: Int,
    context: TaskContext): ShuffleWriter[K, V]
  def getReader[K, C](
    handle: ShuffleHandle,
    startPartition: Int,
    endPartition: Int,
    context: TaskContext): ShuffleReader[K, C]
  def unregisterShuffle(shuffleId: Int): Boolean
  def shuffleBlockResolver: ShuffleBlockResolver
  def stop(): Unit
}
----

NOTE: `ShuffleManager` is a `private[spark]` contract.

.ShuffleManager Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[registerShuffle]] `registerShuffle`
| Executed when link:spark-rdd-ShuffleDependency.adoc#creating-instance[`ShuffleDependency` is created and registers itself].

| [[getWriter]] `getWriter`
| Used when a link:spark-taskscheduler-ShuffleMapTask.adoc#runTask[`ShuffleMapTask` runs] (and requests a link:spark-ShuffleWriter.adoc[ShuffleWriter] to write records for a partition).

| [[getReader]] `getReader`
| Returns a link:spark-ShuffleReader.adoc[ShuffleReader] for a range of partitions (to read key-value records for a link:spark-rdd-ShuffleDependency.adoc[ShuffleDependency] dependency).

Used when link:spark-rdd-cogroupedrdd.adoc#compute[CoGroupedRDD], link:spark-rdd-ShuffledRDD.adoc#compute[ShuffledRDD], link:spark-rdd-SubtractedRDD.adoc#compute[SubtractedRDD], and link:spark-sql-ShuffledRowRDD.adoc#compute[ShuffledRowRDD] compute their partitions.

| [[unregisterShuffle]] `unregisterShuffle`
| Executed when ??? removes the metadata of a shuffle.

| [[shuffleBlockResolver]] `shuffleBlockResolver`
| Used when:

1. link:spark-blockmanager.adoc#getBlockData[`BlockManager` requests a `ShuffleBlockResolver`] capable of retrieving shuffle block data (for a link:spark-blockdatamanager.adoc#ShuffleBlockId[ShuffleBlockId])

2. link:spark-blockmanager.adoc#getLocalBytes[`BlockManager` requests a `ShuffleBlockResolver` for local shuffle block data as bytes].

| [[stop]] `stop`
| Used when link:spark-sparkenv.adoc#stop[`SparkEnv` stops].
|===

TIP: Review https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/shuffle/ShuffleManager.scala[`ShuffleManager` sources].

=== [[settings]] Settings

.Spark Properties
[cols="1,1,2",options="header",width="100%"]
|===
| Spark Property
| Default Value
| Description

| [[spark_shuffle_manager]] `spark.shuffle.manager`
| `sort`
| <<ShuffleManager, ShuffleManager>> for a Spark application.

You can use a short name or the fully-qualified class name of a custom implementation.

The predefined aliases are `sort` and `tungsten-sort` with `org.apache.spark.shuffle.sort.SortShuffleManager` being the one and only `ShuffleManager`.

|===

=== [[i-want-more]] Further Reading or Watching

1. (slides) http://www.slideshare.net/colorant/spark-shuffle-introduction[Spark shuffle introduction] by http://blog.csdn.net/colorant/[Raymond Liu] (aka _colorant_).
