== [[StorageMemoryPool]] StorageMemoryPool

`StorageMemoryPool` is...FIXME

=== [[memoryFree]] `memoryFree` Method

[source, scala]
----
memoryFree: Long
----

`memoryFree`...FIXME

NOTE: `memoryFree` is used when...FIXME

=== [[acquireMemory]] `acquireMemory` Method

[source, scala]
----
acquireMemory(blockId: BlockId, numBytes: Long): Boolean  // <1>
acquireMemory(
  blockId: BlockId,
  numBytesToAcquire: Long,
  numBytesToFree: Long): Boolean
----
<1> Calls `acquireMemory` with `numBytesToFree` as a difference between `numBytes` and <<memoryFree, memoryFree>>

`acquireMemory`...FIXME

[NOTE]
====
`acquireMemory` is used when:

* `StaticMemoryManager` is requested to link:spark-StaticMemoryManager.adoc#acquireUnrollMemory[acquireUnrollMemory] and link:spark-StaticMemoryManager.adoc#acquireStorageMemory[acquireStorageMemory]

* `UnifiedMemoryManager` is requested to link:spark-UnifiedMemoryManager.adoc#acquireStorageMemory[acquireStorageMemory]
====

=== [[freeSpaceToShrinkPool]] `freeSpaceToShrinkPool` Method

[source, scala]
----
freeSpaceToShrinkPool(spaceToFree: Long): Long
----

`freeSpaceToShrinkPool`...FIXME

NOTE: `freeSpaceToShrinkPool` is used exclusively when `UnifiedMemoryManager` is requested to link:spark-UnifiedMemoryManager.adoc#acquireExecutionMemory[acquireExecutionMemory].
