== [[QueryPlan]] Structured Query Plan

`QueryPlan` is a part of *Catalyst* to model a link:spark-sql-catalyst-TreeNode.adoc[tree of relational operators].

Scala-specific, `QueryPlan` is an abstract class that is the base class of link:spark-sql-catalyst-SparkPlan.adoc[SparkPlan] and link:spark-sql-catalyst-LogicalPlan.adoc[LogicalPlan] abstract classes.

A `QueryPlan` has an <<output, output>> (that is a sequence of <<Attribute, Attributes>>), a collection of link:spark-sql-catalyst-Expression.adoc[expressions] and a <<schema, schema>>.

`QueryPlan` introduces <<statePrefix, statePrefix>> that is used when displaying a plan with `!` to indicate an invalid plan, and `'` to indicate an unresolved plan.

A `QueryPlan` is *invalid* if `missingInput` attributes and `children` subnodes are non-empty.

A `QueryPlan` is *unresolved* if ...

=== [[schema]] schema

You can request the schema of a `QueryPlan` using `schema` that builds link:spark-sql-StructType.adoc[StructType] from the <<output, output attributes>>.

=== [[output]] Output Attributes

=== [[Attribute]] Attribute

A `QueryPlan` uses `Attributes` to build a link:spark-sql-StructType.adoc[schema] of the query.

=== [[statePrefix]] `statePrefix` method

[source, scala]
----
statePrefix: String
----

`statePrefix` method is used when printing a plan with `!` to indicate an invalid plan and `'` to indicate an unresolved plan.
