== [[HashPartitioner]] HashPartitioner

`HashPartitioner` is a `Partitioner` that uses `partitions` configurable number of partitions to shuffle data around.

.`HashPartitioner` Attributes and Method
[cols="1,3",options="header",width="100%"]
|===
| Property | Description
| `numPartitions` | Exactly `partitions` number of partitions
| `getPartition` | `0` for `null` keys and Java's link:++https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--++[Object.hashCode] for non-``null`` keys (modulo `partitions` number of partitions or `0` for negative hashes).
| `equals` | `true` for ``HashPartitioner``s with `partitions` number of partitions. Otherwise, `false`.
| `hashCode` | Exactly `partitions` number of partitions
|===

NOTE: `HashPartitioner` is the default `Partitioner` for link:spark-rdd-partitions.adoc#coalesce[coalesce] transformation with `shuffle` enabled, e.g. calling link:spark-rdd-partitions.adoc#repartition[repartition].

It is possible to re-shuffle data despite all the records for the key `k` being already on a single Spark executor (i.e. link:spark-blockmanager.adoc[BlockManager] to be precise). When ``HashPartitioner``'s result for `k1` is `3` the key `k1` will go to the third executor.
