== [[ReorderJoin]] ReorderJoin Logical Plan Optimization

`ReorderJoin` is a logical plan optimization in link:spark-sql-Optimizer.adoc#Operator-Optimizations[Operator Optimizations] batch of rules in link:spark-sql-Optimizer.adoc#ReorderJoin[Optimizer] that <<apply, transforms `Filter` (with CROSS and INNER join types) and `Join` logical plans>> with 3 or more joins and non-empty join conditions.

NOTE: Operator Optimizations is a link:spark-sql-Optimizer.adoc#fixedPoint[fixed-point batch of rules].

=== [[apply]] Transforming Logical Plan -- `apply` Method

`apply` transforms `Filter` (with CROSS and INNER join types) and link:spark-sql-LogicalPlan-Join.adoc[Join] logical plans.

=== [[createOrderedJoin]] `createOrderedJoin` Recursive Method

CAUTION: FIXME

=== [[ExtractFiltersAndInnerJoins-flattenJoin]] `flattenJoin` Method (of ExtractFiltersAndInnerJoins)

[source, scala]
----
flattenJoin(plan: LogicalPlan, parentJoinType: InnerLike = Inner)
  : (Seq[(LogicalPlan, InnerLike)], Seq[Expression])
----

`flattenJoin` takes CROSS and INNER join types...FIXME
