== [[ShuffleExchange]] `ShuffleExchange` Physical Operator

`ShuffleExchange` is a link:spark-sql-catalyst-SparkPlan.adoc#UnaryExecNode[unary physical operator]. It corresponds to `Repartition` (with shuffle enabled) and `RepartitionByExpression` logical operators (as translated in link:spark-sql-BasicOperators.adoc[`BasicOperators` strategy]).

`ShuffleExchange` uses a `Partitioning` and an optional `ExchangeCoordinator` to work with the one `child` link:spark-sql-catalyst-SparkPlan.adoc[physical operator].

.`ShuffleExchange` Metrics
[frame="topbot",cols="1,2",options="header",width="100%"]
|======================
| Name | Description
| [[dataSize]] `dataSize` | data size total (min, med, max)
|======================

`nodeName` depends on the optional `ExchangeCoordinator` but always uses `Exchange` prefix and possibly `(coordinator id: [coordinator-hash-code])`.

`outputPartitioning` is the new input `Partitioning`.

While link:spark-sql-catalyst-SparkPlan.adoc#doPrepare[preparing execution] (using `doPrepare`), `ShuffleExchange` registers itself with the `ExchangeCoordinator` if defined.

When link:spark-sql-catalyst-SparkPlan.adoc#doExecute[executed] (using `doExecute`), compute a `ShuffledRowRDD` and cache it if the `ShuffleExchange` operator is used by multiple plans.

CAUTION: FIXME Describe _compute_ part.
