== [[SparkListener]] Spark Listeners

`SparkListener` is an abstract link:spark-LiveListenerBus.adoc#SparkListenerInterface[SparkListenerInterface] with empty no-op implementation for all the _callbacks_.

The one and only goal of the class is to simplify creating highly specialized *Spark listeners* that are only processing a subset of events.

TIP: Developing a custom SparkListener is an excellent introduction to low-level details of link:spark-execution-model.adoc[Spark's Execution Model]. Check out the exercise link:exercises/spark-exercise-custom-scheduler-listener.adoc[Developing Custom SparkListener to monitor DAGScheduler in Scala].

=== [[known-implementations]] Known Implementations

The following is the complete list of all known Spark listeners:

* link:spark-scheduler-listeners-eventlogginglistener.adoc[EventLoggingListener]
* `ExecutorsListener` that prepares information to be displayed on the *Executors* tab in link:spark-webui.adoc[web UI].
* `SparkFirehoseListener` that allows users to receive all SparkListener events by overriding the `onEvent` method only.
* `ExecutorAllocationListener`
* link:spark-sparkcontext-HeartbeatReceiver.adoc[HeartbeatReceiver]
* web UI and link:spark-scheduler-listeners-eventlogginglistener.adoc[EventLoggingListener] listeners

CAUTION: FIXME Make it complete.
