== [[MapOutputTrackerMasterEndpoint]] MapOutputTrackerMasterEndpoint

`MapOutputTrackerMasterEndpoint` is a link:spark-rpc-RpcEndpoint.adoc[RpcEndpoint] for link:spark-service-MapOutputTrackerMaster.adoc[MapOutputTrackerMaster].

`MapOutputTrackerMasterEndpoint` handles the following messages:

* <<GetMapOutputStatuses, GetMapOutputStatuses>>
* <<StopMapOutputTracker, StopMapOutputTracker>>

[TIP]
====
Enable `INFO` or `DEBUG` logging levels for `org.apache.spark.MapOutputTrackerMasterEndpoint` logger to see what happens in `MapOutputTrackerMasterEndpoint`.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.MapOutputTrackerMasterEndpoint=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[creating-instance]] Creating MapOutputTrackerMasterEndpoint Instance

`MapOutputTrackerMasterEndpoint` takes the following when created:

1. `rpcEnv` -- link:spark-rpc.adoc[RpcEnv]
2. `tracker` -- link:spark-service-MapOutputTrackerMaster.adoc[MapOutputTrackerMaster]
3. `conf` -- link:spark-SparkConf.adoc[SparkConf]

When created, you should see the following DEBUG message in the logs:

```
DEBUG init
```

NOTE: `MapOutputTrackerMasterEndpoint` is created when link:spark-sparkenv.adoc#MapOutputTrackerMasterEndpoint[`SparkEnv` is created] for the driver and executors.

=== [[GetMapOutputStatuses]] `GetMapOutputStatuses` Message

[source, scala]
----
GetMapOutputStatuses(shuffleId: Int)
extends MapOutputTrackerMessage
----

When `GetMapOutputStatuses` arrives, `MapOutputTrackerMasterEndpoint` reads the host and the port of the sender.

You should see the following INFO message in the logs:

```
INFO Asked to send map output locations for shuffle [shuffleId] to [hostPort]
```

`MapOutputTrackerMasterEndpoint` link:spark-service-MapOutputTrackerMaster.adoc#post[posts a `GetMapOutputMessage` to `MapOutputTrackerMaster`] (with `shuffleId` and the current `RpcCallContext`).

NOTE: `GetMapOutputStatuses` is posted when link:spark-service-mapoutputtracker.adoc#getStatuses[`MapOutputTracker` fetches shuffle map outputs remotely].

=== [[StopMapOutputTracker]] `StopMapOutputTracker` Message

[source, scala]
----
StopMapOutputTracker
extends MapOutputTrackerMessage
----

When `StopMapOutputTracker` arrives, you should see the following INFO message in the logs:

```
INFO MapOutputTrackerMasterEndpoint stopped!
```

`MapOutputTrackerMasterEndpoint` confirms the request (by replying `true`) and link:spark-rpc-RpcEndpoint.adoc#stop[stops itself] (and stops accepting messages).

NOTE: `StopMapOutputTracker` is posted when link:spark-service-MapOutputTrackerMaster.adoc#stop[`MapOutputTrackerMaster` stops].
