== ShuffledRDD

*ShuffledRDD* is the result RDD from a link:spark-rdd-shuffle.adoc[shuffle], i.e. after calling the `coalesce` transformation with `shuffle` input parameter is `true` (defaults to `false`).

A parent RDD is of type `RDD[_ <: Product2[K, V]]`, i.e. a dataset of `(K, V)` pairs, which means ShuffleRDD works with RDDs of pairs.

It is also the result of RDD transformations using Scala implicits:

* `repartitionAndSortWithinPartitions`
* `sortByKey`
* `combineByKeyWithClassTag` (only when the input partitioner is different from the current one in an RDD)
* `partitionBy` (only when the input partitioner is different from the current one in an RDD)

It uses link:spark-rdd-partitions.adoc#partitioner[Partitioner].

RDD Dependencies are always a single-element `ShuffleDependency` and `ShuffledRDDPartition`.

It uses link:spark-service-mapoutputtracker.adoc#MapOutputTrackerMaster[MapOutputTrackerMaster] to get preferred locations for a shuffle.

[CAUTION]
====
FIXME

* Where's `mapSideCombine` flag used?
====
