== Shuffle Service

A *Shuffle Service* is a Spark service that tracks link:spark-dagscheduler.adoc#ShuffleMapStage[shuffle dependencies for ShuffleMapStage]. The driver and executors all have their own Shuffle Service.

The driver registers shuffles with it, and executors (or tasks running locally in the driver) can ask to read and write data.

It is network-addressable, i.e. it is available on a host and port.

There can be many shuffle services running simultaneously and a driver registers with all of them when link:spark-execution-model.adoc#scheduler-backends[CoarseGrainedSchedulerBackend] is used.

The service is available under `SparkEnv.get.shuffleManager`.

When link:spark-rdd-shuffledrdd.adoc[ShuffledRDD] is computed it reads partitions from it.

The name appears https://github.com/apache/spark/commit/2da3a9e98e5d129d4507b5db01bba5ee9558d28e[here], twice in link:spark-building-from-sources.adoc[the build's output] and others.

Review the code in `network/shuffle` module.

* When is data eligible for shuffling?
* When and how to set up external shuffle service?
* Get the gist of _"The shuffle files are not currently cleaned up when using Spark on Mesos with the external shuffle service"_

=== [[shuffle-manager]] Shuffle Manager

Spark comes with three implementations of Shuffle Manager:

* `sort` (default) - `org.apache.spark.shuffle.sort.SortShuffleManager`
* `hash` - `org.apache.spark.shuffle.hash.HashShuffleManager`
* `tungsten-sort` - `org.apache.spark.shuffle.sort.SortShuffleManager`

The setting `spark.shuffle.manager` (default: `sort`) is to choose the default Shuffle Manager from the above list (using their short names) or be a custom implementation.

CAUTION: FIXME Exercise for a custom implementation of Shuffle Manager using `private[spark] ShuffleManager` trait.

=== [[settings]] Settings

* `spark.shuffle.service.enabled` (default: `false`) -  If shuffle service is enabled, the Spark driver will register with the shuffle service. It is used in link:spark-mesos.adoc#CoarseMesosSchedulerBackend[CoarseMesosSchedulerBackend] to instantiate `MesosExternalShuffleClient`. This is for cleaning up shuffle files reliably.
* `spark.shuffle.service.port` (default: `7337`)
