== [[ExpressionEncoder]] ExpressionEncoder

[source, scala]
----
case class ExpressionEncoder[T](
  schema: StructType,
  flat: Boolean,
  serializer: Seq[Expression],
  deserializer: Expression,
  clsTag: ClassTag[T])
extends Encoder[T]
----

`ExpressionEncoder` is the one and only implementation of the `Encoder` trait in Spark 2.0 with additional properties, i.e. `flat`, one or many `serializers` and a `deserializer` expressions.

A `ExpressionEncoder` can be *flat* is which case there is only one Catalyst expression for the serializer.

*Serializer expressions* are used to encode an object of type `T` to a link:spark-sql-InternalRow.adoc[InternalRow]. It is assumed that all serializer expressions contain at least one and the same `BoundReference`.

CAUTION: FIXME What's `BoundReference`?

*Deserializer expression* is used to decode an link:spark-sql-InternalRow.adoc[InternalRow] to an object of type `T`.

Internally, a `ExpressionEncoder` creates a `UnsafeProjection` (for the input serializer), a link:spark-sql-InternalRow.adoc[InternalRow] (of size `1`), and a safe `Projection` (for the input deserializer). They are all internal lazy attributes of the encoder.

=== [[resolveAndBind]] `resolveAndBind` Method

CAUTION: FIXME
