== Pool

`Pool` is a link:spark-taskscheduler-schedulable.adoc[Schedulable].

It requires a name, a scheduling mode, initial `minShare` and `weight` when created.

NOTE: An instance of `Pool` is created when link:spark-taskschedulerimpl.adoc#initialize[TaskSchedulerImpl is initialized].

=== [[getSortedTaskSetQueue]] getSortedTaskSetQueue

NOTE: `getSortedTaskSetQueue` is part of the link:spark-taskscheduler-schedulable.adoc#contract[Schedulable Contract].

`getSortedTaskSetQueue` sorts all the link:spark-taskscheduler-schedulable.adoc[Schedulables] in link:spark-taskscheduler-schedulable.adoc#contract[schedulableQueue] queue by a <<SchedulingAlgorithm, SchedulingAlgorithm>> (as the internal `taskSetSchedulingAlgorithm`).

=== [[SchedulingAlgorithm]] SchedulingAlgorithm

`SchedulingAlgorithm` is the interface for a sorting algorithm to sort link:spark-taskscheduler-schedulable.adoc[Schedulables].

There are currently two `SchedulingAlgorithms`:

* <<FIFOSchedulingAlgorithm, FIFOSchedulingAlgorithm>> for FIFO scheduling mode.
* <<FairSchedulingAlgorithm, FairSchedulingAlgorithm>> for FAIR scheduling mode.

==== [[FIFOSchedulingAlgorithm]] FIFOSchedulingAlgorithm

`FIFOSchedulingAlgorithm` is a scheduling algorithm that compares `Schedulables` by their `priority` first and, when equal, by their `stageId`.

NOTE: `priority` and `stageId` are part of link:spark-taskscheduler-schedulable.adoc#contract[Schedulable Contract].

CAUTION: FIXME _A picture is worth a thousand words._ How to picture the algorithm?

==== [[FairSchedulingAlgorithm]] FairSchedulingAlgorithm

`FairSchedulingAlgorithm` is a scheduling algorithm that compares `Schedulables` by their `minShare`, `runningTasks`, and `weight`.

NOTE: `minShare`, `runningTasks`, and `weight` are part of link:spark-taskscheduler-schedulable.adoc#contract[Schedulable Contract].

Internally, `runningTasks` is compared to `minShare` for each `Schedulable` (`s1Needy` and `s2Needy` flags). `minShareRatio` is computed as `runningTasks` by `minShare` (but at least `1`). `taskToWeightRatio` is `runningTasks` by `weight`.

It then checks the flags `s1Needy` and `s2Needy`.

[width="80%"]
|=======
|                  |s1Needy = `true` |s1Needy = `false`
|s2Needy = `true`  |compare `minShareRatio` | `false`
|s2Needy = `false` |`true`           |compare `taskToWeightRatio`
|=======

It then checks the `compare` result.

[width="80%"]
|=======
|             |`compare` < 0 | `compare` > 0 | `compare` == 0
|final result | `true`       | `false` | compare `name`
|=======

CAUTION: FIXME _A picture is worth a thousand words._ How to picture the algorithm? A decision tree?
