== [[StorageStatusListener]] `StorageStatusListener` Spark Listener

`StorageStatusListener` is a link:spark-SparkListener.adoc[SparkListener] that tracks status of link:spark-blockmanager.adoc[BlockManager]s on "nodes" in a Spark application, i.e. the driver and the executors.

NOTE: `StorageStatusListener` is created and registered when a link:spark-webui-SparkUI.adoc#create[`SparkUI` is created]. It is later used to create link:spark-webui-executors-ExecutorsListener.adoc[ExecutorsListener] and link:spark-webui-StorageListener.adoc[StorageListener] Spark listeners.

.`StorageStatusListener` Registries
[cols="1,2",options="header",width="100%"]
|===
| Registry | Description
| [[executorIdToStorageStatus]] `executorIdToStorageStatus` | The lookup table for `StorageStatus` per executor or the driver.
| [[deadExecutorStorageStatus]] `deadExecutorStorageStatus` | A collection of ``StorageStatus``s of removed/inactive ``BlockManager``s.
|===

.`StorageStatusListener` Event Handlers
[cols="1,2",options="header",width="100%"]
|===
| Event Handler | Description
| `onUnpersistRDD` |
Removes the RDD blocks for the unpersisted `rddId` from every ``StorageStatus``s in <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry.

| `onBlockManagerAdded` | Registers a link:spark-blockmanager.adoc[BlockManager] on an executor in <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry.

Removes any other `BlockManager` that may have been registered for the executor earlier in <<deadExecutorStorageStatus, deadExecutorStorageStatus>> internal registry.

| `onBlockManagerRemoved` | Removes an executor from <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry and adds the removed `StorageStatus` to <<deadExecutorStorageStatus, deadExecutorStorageStatus>> internal registry.

Removes the oldest `StorageStatus` when the number of entries in <<deadExecutorStorageStatus, deadExecutorStorageStatus>> is bigger than link:spark-webui.adoc#spark_ui_retainedDeadExecutors[spark.ui.retainedDeadExecutors].

| `onBlockUpdated` | Updates `StorageStatus` for an executor in <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry, i.e. removes a block for link:spark-rdd-StorageLevel.adoc[`NONE` storage level] and updates otherwise.
|===
