== DataFrameWriter

`DataFrameWriter` is an interface to write the result of executing link:spark-sql-Dataset.adoc[structured query] to an external storage system in a batch fashion.

NOTE: Structured Streaming's `DataStreamWriter` is responsible for writing in a streaming fashion.

`DataFrameWriter` is available using link:spark-sql-DataFrame.adoc#write[write] method of a `Dataset`.

[source, scala]
----
import org.apache.spark.sql.DataFrameWriter

val nums: Dataset[Long] = ...
val writer: DataFrameWriter[Row] = nums.write
----

`DataFrameWriter` has a direct support for many <<writing-dataframes-to-files, file formats>>, <<jdbc, JDBC databases>> and <<format, an extension point to plug in new formats>>. It assumes <<parquet, parquet>> as the default data source that you can change using link:spark-sql-settings.adoc[spark.sql.sources.default] setting or <<format, format>> method.

[source, scala]
----
// see above for writer definition

// Save dataset in Parquet format
writer.save(path = "nums")

// Save dataset in JSON format
writer.format("json").save(path = "nums-json")
----

In the end, you trigger the actual saving of the content of a `Dataset` using <<save, save>> method.

[source, scala]
----
writer.save
----

NOTE: `DataFrameWriter` is really a type constructor in Scala and keeps a reference to a source `DataFrame` during its lifecycle (starting right from the moment it was created).

=== [[runCommand]] `runCommand` Internal Method

[source, scala]
----
runCommand
  (session: SparkSession, name: String)
  (command: LogicalPlan): Unit
----

CAUTION: FIXME

=== [[internal-state]] Internal State

`DataFrameWriter` uses the following mutable attributes to build a properly-defined write specification for <<insertInto, insertInto>>, <<saveAsTable, saveAsTable>>, and <<save, save>>:

.Attributes and Corresponding Setters
[cols="1,2",options="header"]
|===
|Attribute |Setters
|`source`        |<<format, format>>
|`mode` | <<mode, mode>>
|`extraOptions` | <<option, option>>, <<options, options>>, <<save, save>>
|`partitioningColumns` | <<partitionBy, partitionBy>>
|`bucketColumnNames` | <<bucketBy, bucketBy>>
|`numBuckets` | <<bucketBy, bucketBy>>
|`sortColumnNames` | <<sortBy, sortBy>>
|===

=== [[saveAsTable]] `saveAsTable` Method

[source, scala]
----
saveAsTable(tableName: String): Unit
----

`saveAsTable` saves the content of a `DataFrame` as the `tableName` table.

First, `tableName` is parsed to an internal table identifier. `saveAsTable` then checks whether the table exists or not and uses <<mode, save mode>> to decide what to do.

`saveAsTable` uses the link:spark-sql-SessionCatalog.adoc[SessionCatalog] for the current session.

.``saveAsTable``'s Behaviour per Save Mode
[cols="1,1,2",options="header"]
|===
| Does table exist? |Save Mode | Behaviour
| yes       | `Ignore` | Do nothing
| yes       | `ErrorIfExists` | Throws a `AnalysisException` exception with `Table [tableIdent] already exists.` error message.
| _anything_       | _anything_ | It creates a `CatalogTable` and link:spark-sql-SessionState.adoc#executePlan[executes the `CreateTable` plan].
|===

[source, scala]
----
val ints = 0 to 9 toDF
val options = Map("path" -> "/tmp/ints")
ints.write.options(options).saveAsTable("ints")
sql("show tables").show
----

=== [[save]] Saving DataFrame -- `save` Method

[source, scala]
----
save(): Unit
----

`save` saves the result of a structured query (the content of a link:spark-sql-Dataset.adoc[Dataset]) to a data source.

Internally, `save` <<runCommand, runs>> a link:spark-sql-LogicalPlan-RunnableCommand.adoc#SaveIntoDataSourceCommand[SaveIntoDataSourceCommand] runnable command under the name `save`.

NOTE: `save` does not support saving to Hive (when `source` is `hive`) and bucketing.

CAUTION: FIXME What does `bucketing` mean? What about `assertNotBucketed`?

CAUTION: FIXME What is `partitioningColumns`?

NOTE: `save` uses `source`, `partitioningColumns`, `extraOptions`, and `mode` internal properties.

=== [[jdbc]] `jdbc` Method

[source, scala]
----
jdbc(url: String, table: String, connectionProperties: Properties): Unit
----

`jdbc` method saves the content of the `DataFrame` to an external database table via JDBC.

You can use <<mode, mode>> to control *save mode*, i.e. what happens when an external table exists when `save` is executed.

It is assumed that the `jdbc` save pipeline is not <<partitionBy, partitioned>> and <<bucketBy, bucketed>>.

All <<options, options>> are overriden by the input `connectionProperties`.

The required options are:

* `driver` which is the class name of the JDBC driver (that is passed to Spark's own `DriverRegistry.register` and later used to `connect(url, properties)`).

When `table` exists and the <<mode, override save mode>> is in use, `DROP TABLE table` is executed.

It creates the input `table` (using `CREATE TABLE table (schema)` where `schema` is the schema of the `DataFrame`).

=== [[bucketBy]] `bucketBy` Method

CAUTION: FIXME

=== [[partitionBy]] `partitionBy` Method

[source, scala]
----
partitionBy(colNames: String*): DataFrameWriter[T]
----

CAUTION: FIXME

=== [[mode]] Defining Write Behaviour Per Sink's Existence (aka Save Mode) -- `mode` Method

[source, scala]
----
mode(saveMode: String): DataFrameWriter[T]
mode(saveMode: SaveMode): DataFrameWriter[T]
----

`mode` defines the behaviour of <<save, save>> when an external file or table (Spark writes to) already exists, i.e. `SaveMode`.

[[SaveMode]]
.Types of SaveMode (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `Append`
| Records are appended to existing data.

| `ErrorIfExists`
| Exception is thrown.

| `Ignore`
| Do not save the records and not change the existing data in any way.

| `Overwrite`
| Existing data is overwritten by new records.
|===

=== [[option]][[options]] Writer Configuration -- `option` and `options` Methods

CAUTION: FIXME

=== [[writing-dataframes-to-files]] Writing DataFrames to Files

CAUTION: FIXME

=== [[format]] Specifying Alias or Fully-Qualified Class Name of DataSource -- `format` Method

CAUTION: FIXME Compare to DataFrameReader.

=== [[parquet]] Parquet

CAUTION: FIXME

NOTE: Parquet is the default data source format.

=== [[insertInto]] `insertInto` Method

CAUTION: FIXME
