== [[SchedulingMode]] Scheduling Mode -- `spark.scheduler.mode` Spark Property

*Scheduling Mode* (aka _order task policy_ or _scheduling policy_ or _scheduling order_) defines a policy to sort tasks in order for execution.

The scheduling mode `schedulingMode` attribute is part of the link:spark-TaskScheduler.adoc#schedulingMode[TaskScheduler Contract].

The only implementation of the `TaskScheduler` contract in Spark -- link:spark-TaskSchedulerImpl.adoc[TaskSchedulerImpl] -- uses link:spark-TaskSchedulerImpl.adoc#spark_scheduler_mode[spark.scheduler.mode] setting to configure `schedulingMode` that is _merely_ used to set up the link:spark-TaskScheduler.adoc#rootPool[rootPool] attribute (with `FIFO` being the default). It happens when link:spark-TaskSchedulerImpl.adoc#initialize[`TaskSchedulerImpl` is initialized].

There are three acceptable scheduling modes:

* `FIFO` with no pools but a single top-level unnamed pool with elements being link:spark-TaskSetManager.adoc[TaskSetManager] objects; lower priority gets link:spark-taskscheduler-schedulable.adoc[Schedulable] sooner or earlier stage wins.
* `FAIR` with a link:spark-taskscheduler-FairSchedulableBuilder.adoc#buildPools[hierarchy of `Schedulable` (sub)pools] with the link:spark-TaskScheduler.adoc#rootPool[rootPool] at the top.
* *NONE* (not used)

NOTE: Out of three possible `SchedulingMode` policies only `FIFO` and `FAIR` modes are supported by link:spark-TaskSchedulerImpl.adoc[TaskSchedulerImpl].

[NOTE]
====
After the root pool is initialized, the scheduling mode is no longer relevant (since the link:spark-taskscheduler-schedulable.adoc[Schedulable] that represents the root pool is fully set up).

The root pool is later used when link:spark-TaskSchedulerImpl.adoc#submitTasks[`TaskSchedulerImpl` submits tasks (as `TaskSets`) for execution].
====

NOTE: The link:spark-TaskScheduler.adoc#rootPool[root pool] is a `Schedulable`. Refer to link:spark-taskscheduler-schedulable.adoc[Schedulable].

=== [[fair-scheduling-sparkui]] Monitoring FAIR Scheduling Mode using Spark UI

CAUTION: FIXME Describe me...
