== ExternalClusterManager

`ExternalClusterManager` is a <<contract, contract for pluggable cluster managers>>.

NOTE: It was introduced in https://issues.apache.org/jira/browse/SPARK-13904[SPARK-13904 Add support for pluggable cluster manager].

It is link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[assumed that `ExternalClusterManager` implementations are available as Java services] (with service markers under `META-INF/services` directory).

NOTE: `ExternalClusterManager` is a `private[spark]` trait in `org.apache.spark.scheduler` package.

NOTE: The only known implementation of the <<contract, ExternalClusterManager contract>> in Spark is link:yarn/spark-yarn-YarnClusterManager.adoc[YarnClusterManager].

NOTE: SparkContext finds a `ExternalClusterManager` for a master URL using an internal link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[getClusterManager].

=== [[contract]] ExternalClusterManager Contract

==== [[initialize]] initialize

[source, scala]
----
initialize(scheduler: TaskScheduler, backend: SchedulerBackend): Unit
----

==== [[canCreate]] canCreate

[source, scala]
----
canCreate(masterURL: String): Boolean
----

NOTE: It is used when link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[finding the external cluster manager for a master URL (in `SparkContext`)].

==== [[createTaskScheduler]] createTaskScheduler

[source, scala]
----
createTaskScheduler(sc: SparkContext, masterURL: String): TaskScheduler
----

==== [[createSchedulerBackend]] createSchedulerBackend

[source, scala]
----
createSchedulerBackend(sc: SparkContext,
  masterURL: String,
  scheduler: TaskScheduler): SchedulerBackend
----
