== [[SchedulableBuilder]] Schedulable Builders

`SchedulableBuilder` is a <<contract, contract>> of <<implementations, schedulable builders>>.

NOTE: `SchedulableBuilder` is a `private[spark]` Scala trait. You can find the sources in https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/SchedulableBuilder.scala[org.apache.spark.scheduler.SchedulableBuilder].

=== [[contract]] SchedulableBuilder Contract

Every `SchedulableBuilder` follows the following contract:

* It has a <<rootPool, root pool>>.

* It can <<buildPools, build pools>>.

* It can <<addTaskSetManager, add a Schedulable with properties>>.

=== [[rootPool]] Root Pool (rootPool method)

[source, scala]
----
rootPool: Pool
----

`rootPool` link:spark-taskscheduler-pool.adoc[Pool] (of link:spark-taskscheduler-schedulable.adoc[Schedulables])

=== [[buildPools]] Build Pools (buildPools method)

[source, scala]
----
buildPools(): Unit
----

=== [[addTaskSetManager]] Add Schedulable (addTaskSetManager method)

[source, scala]
----
addTaskSetManager(manager: Schedulable, properties: Properties): Unit
----

`addTaskSetManager` registers the `manager` link:spark-taskscheduler-schedulable.adoc[Schedulable] with additional `properties`.

NOTE: `addTaskSetManager` is used by link:spark-taskschedulerimpl.adoc#submitTasks[TaskSchedulerImpl to submit a task set for a stage for execution].

=== [[implementations]] Schedulable Builders

There are currently two types of `Schedulable` entities:

There are currently two implementations of the <<contract, SchedulableBuilder Contract>>:

* <<FIFOSchedulableBuilder, FIFOSchedulableBuilder>>
* <<FairSchedulableBuilder, FairSchedulableBuilder>>

=== [[FIFOSchedulableBuilder]] FIFOSchedulableBuilder

`FIFOSchedulableBuilder` is a _very basic_ `SchedulableBuilder`.

* `rootPool` is given as a mandatory input parameter to the constructor.

* <<buildPools, buildPools>> does nothing.

* `addTaskSetManager(manager: Schedulable, properties: Properties)` adds the `manager` Schedulable to `rootPool` (using `Pool.addSchedulable`).

=== [[FairSchedulableBuilder]] FairSchedulableBuilder

CAUTION: FIXME
