== ReceiverInputDStreams

`ReceiverInputDStream` is a specialized abstract class for defining link:spark-streaming-inputdstreams.adoc[InputDStreams] that start a link:spark-streaming-receivers.adoc[receiver] (and hence the name `ReceiverInputDStream` which stands for an `InputDStream` with a receiver).

`ReceiverInputDStream` abstract class defines the following abstract method that custom implementations use to create receivers:

```
def getReceiver(): Receiver[T]
```

The receiver is then sent to and run on workers (when link:spark-streaming-receivertracker.adoc#starting[ReceiverTracker is started]).

[NOTE]
====
A fine example of a very minimalistic yet still useful implementation of `ReceiverInputDStream` class is the pluggable input stream `org.apache.spark.streaming.dstream.PluggableInputDStream` (https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/dstream/PluggableInputDStream.scala[the sources on GitHub]). It requires a `Receiver` to be instantiated and simply returns it in `getReceiver`.

`PluggableInputDStream` is used by link:spark-streaming-streamingcontext.adoc#creating-receivers[StreamingContext.receiverStream].
====

`ReceiverInputDStream` uses `ReceiverRateController` when link:spark-streaming-settings.adoc[spark.streaming.backpressure.enabled] is enabled.

[NOTE]
====
Both, `start()` and `stop` methods are implemented, but do nothing since it is link:spark-streaming-receivertracker.adoc[ReceiverTracker] to manage `ReceiverInputDStream`.

Read link:spark-streaming-receivertracker.adoc#ReceiverTrackerEndpoint-startReceiver[ReceiverTrackerEndpoint.startReceiver] for more details.
====

The source code of `ReceiverInputDStream` is https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/dstream/ReceiverInputDStream.scala[at GitHub].

=== [[compute]] Generate RDDs (using compute method)

The abstract `compute(validTime: Time): Option[RDD[T]]` method (from link:spark-streaming-dstreams.adoc[DStream]) uses link:spark-streaming-dstreams.adoc#DStreamGraph[DStreamGraph.startTime] which is the start time of StreamingContext.

If the time to generate RDDs (`validTime`) is earlier than the start time of StreamingContext, an empty `BlockRDD` is generated.

Otherwise, link:spark-streaming-receivertracker.adoc[ReceiverTracker] is requested for all the blocks that have been allocated to this stream for this batch (using `ReceiverTracker.getBlocksOfBatch`).

The number of records received for the batch for the input stream (as `StreamInputInfo` aka *input blocks information*) is registered to link:spark-streaming-jobscheduler.adoc#InputInfoTracker[InputInfoTracker] (using `InputInfoTracker.reportInfo`).

If all link:spark-blockmanager.adoc#BlockId[BlockIds] have `WriteAheadLogRecordHandle`, a `WriteAheadLogBackedBlockRDD` is generated. Otherwise, a `BlockRDD` is.
