== [[TreeNode]] TreeNode -- Node in Catalyst Tree

`TreeNode` is a node in link:spark-sql-catalyst.adoc[Catalyst] tree with zero or more <<children, children>> (and can build link:spark-sql-Expression.adoc[expression] or link:spark-sql-catalyst-QueryPlan.adoc[structured query plan] trees).

`TreeNode` offers not only functions that you may have used from Scala Collection API, e.g. `map`, `flatMap`, `collect`, `collectFirst`, `foreach`, but also `mapChildren`, `transform`, `transformDown`, `transformUp`, `foreachUp`, `numberedTreeString`, `p`, `asCode`, `prettyJson`, etc. that are particularly useful for tree manipulation or debugging.

NOTE: Scala-specific, `TreeNode` is an abstract class that is the base class of link:spark-sql-Expression.adoc[Expression] and Catalyst's link:spark-sql-catalyst-QueryPlan.adoc[QueryPlan] abstract classes.

[TIP]
====
`TreeNode` abstract type is a quite advanced Scala type definition (at least comparing to the other Scala types in Spark) so understanding its behaviour even outside Spark might be worthwhile by itself.

[source, scala]
----
abstract class TreeNode[BaseType <: TreeNode[BaseType]] extends Product {
  self: BaseType =>

  // ...
}
----
====

=== [[contract]] TreeNode Contract

[source, scala]
----
package org.apache.spark.sql.catalyst.trees

abstract class TreeNode[BaseType <: TreeNode[BaseType]] extends Product {
  self: BaseType =>

  // only required methods that have no implementation
  def children: Seq[BaseType]
  def verboseString: String
}
----

.(Subset of) TreeNode Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[children]] `children`
|

| [[verboseString]] `verboseString`
|
|===

=== [[withNewChildren]] `withNewChildren` Method

CAUTION: FIXME
