== Physical Plan Preparations Rules

[NOTE]
====
For the time being, this page *Physical Plan Preparations Rules* serves mainly as a placeholder for the menu layout so the physical plan preparation rules show up nicely in the menu.

The page is _merely_ a compilation of what you may have found on link:spark-sql-QueryExecution.adoc[QueryExecution] page.
====

---

`QueryExecution` has multiple link:spark-sql-QueryExecution.adoc#execution-pipeline[phases of query execution] in a so-called *Structured Query Execution Pipeline*.

Among the phases is the link:spark-sql-QueryExecution.adoc#executedPlan[executedPlan] phase that is one of the last phases in a query execution which is the result of link:spark-sql-QueryExecution.adoc#prepareForExecution[executing physical preparation rules] on a physical plan of a structured query.

*Physical preparation rules* are link:spark-sql-catalyst-RuleExecutor.adoc#Rule[rules] that transform a link:spark-sql-SparkPlan.adoc[physical plan] and produce a physical plan (i.e. `Rule[SparkPlan]`).

link:spark-sql-QueryExecution.adoc[QueryExecution] defines  link:spark-sql-QueryExecution.adoc#preparations[preparations] batch of rules that are applied to a link:spark-sql-SparkPlan.adoc[physical plan] sequentially and include the following:

1. `ExtractPythonUDFs`
1. `PlanSubqueries`
1. link:spark-sql-EnsureRequirements.adoc[EnsureRequirements]
1. link:spark-sql-CollapseCodegenStages.adoc[CollapseCodegenStages]
1. `ReuseExchange`
1. `ReuseSubquery`
