== QueryPlanner

`QueryPlanner` transforms a link:spark-sql-catalyst-LogicalPlan.adoc[LogicalPlan] through a chain of `GenericStrategy` objects to produce a  physical execution plan, i.e. link:spark-sql-catalyst-SparkPlan.adoc[SparkPlan] for link:spark-sql-SparkPlanner.adoc[SparkPlanner] or the <<HiveSessionState, Hive-Specific SparkPlanner>>.

=== [[contract]] QueryPlanner Contract

`QueryPlanner` contract defines the following operations:

* <<strategies, strategies>>
* <<plan, plan>>
* <<collectPlaceholders, collectPlaceholders>>
* <<prunePlans, prunePlans>>

==== [[strategies]] strategies

The abstract `strategies` method that returns a collection of `GenericStrategy` objects (that are used in the other `plan` method).

==== [[plan]] plan

`plan(plan: LogicalPlan)` that returns an `Iterator[PhysicalPlan]` with elements being the result of applying each `GenericStrategy` object from `strategies` collection to `plan` input parameter.

==== [[collectPlaceholders]] collectPlaceholders

`collectPlaceholders` that returns a collection of pairs of a physical plan and a corresponding link:spark-sql-catalyst-LogicalPlan.adoc[LogicalPlan].

==== [[prunePlans]] prunePlans

`prunePlans` that prunes bad physical plans.

=== [[SparkStrategies]] SparkStrategies

`SparkStrategies` is an abstract base `QueryPlanner` that produces a link:spark-sql-catalyst-SparkPlan.adoc[SparkPlan].

`SparkStrategies` merely serves as a "container" with concrete `SparkStrategy` objects, e.g. `FileSourceStrategy`, `SpecialLimits`, `JoinSelection`, `StatefulAggregationStrategy`, `Aggregation`, `InMemoryScans`, `StreamingRelationStrategy`, etc.

NOTE: `Strategy` is a type alias of `SparkStrategy` that is defined in https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/package.scala#L43[org.apache.spark.sql package object].

NOTE: link:spark-sql-SparkPlanner.adoc[SparkPlanner] is the one and only concrete implementation of `SparkStrategies` available.

CAUTION: FIXME What is `singleRowRdd` for?

=== [[HiveSessionState]] Hive-Specific SparkPlanner for HiveSessionState

`HiveSessionState` class uses an custom anonymous  link:spark-sql-SparkPlanner.adoc[SparkPlanner] for `planner` method (part of the link:spark-sql-sessionstate.adoc[SessionState] contract).

The custom anonymous `SparkPlanner` uses `Strategy` objects defined in `HiveStrategies`.
