== [[CodegenSupport]] CodegenSupport -- Physical Operators with Java Code Generation

`CodegenSupport` is an extension of link:spark-sql-SparkPlan.adoc[physical operators] that support *Java code generation*.

[[supportCodegen]]
`CodegenSupport` allows custom implementations to optionally disable codegen using `supportCodegen` predicate (that is enabled by default, i.e. `true`).

[TIP]
====
Use the following to review ``CodegenSupport``-generated code:

* link:spark-sql-debugging-execution.adoc#debugCodegen[debugCodegen] method
* ...FIXME
====

=== [[contract]] CodegenSupport Contract

[source, scala]
----
package org.apache.spark.sql.execution

trait CodegenSupport extends SparkPlan {
  // only required methods with no implementation
  def doProduce(ctx: CodegenContext): String
  def inputRDDs(): Seq[RDD[InternalRow]]
}
----

.(Subset of) CodegenSupport Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[doProduce]] `doProduce`
a|

Used exclusively in the final <<produce, produce>>.

| [[inputRDDs]] `inputRDDs`
|
|===

=== [[produce]] `produce` Method

[source, scala]
----
produce(ctx: CodegenContext, parent: CodegenSupport): String
----

`produce`...FIXME

NOTE: `produce` is used mainly when `WholeStageCodegenExec` is requested to link:spark-sql-SparkPlan-WholeStageCodegenExec.adoc#doCodeGen[generate the JVM code for a subtree].

=== [[operators]] Codegen Operators

`SparkPlan` plans that support codegen extend `CodegenSupport`.

* `ProjectExec` for `as`
* `FilterExec` for `where` or `filter`
* `Range`
* <<SampleExec, SampleExec>> for `sample`
* <<RangeExec, RangeExec>> for link:spark-sql-sqlcontext.adoc#range[SQLContext.range]
* `RowDataSourceScanExec`

CAUTION: FIXME Where is `RowDataSourceScanExec` used?

* `BatchedDataSourceScanExec`
* `ExpandExec`
* `BaseLimitExec`
* `SortExec`
* link:spark-sql-SparkPlan-WholeStageCodegenExec.adoc[WholeStageCodegenExec] and `InputAdapter`
* `TungstenAggregate`
* link:spark-sql-SparkPlan-BroadcastHashJoinExec.adoc[BroadcastHashJoinExec]
* `SortMergeJoinExec`

==== [[SampleExec]] SampleExec

[source, scala]
----
scala> spark.range(10).sample(false, 0.4).explain
== Physical Plan ==
WholeStageCodegen
:  +- Sample 0.0, 0.4, false, -7634498724724501829
:     +- Range 0, 1, 8, 10, [id#15L]
----

==== [[RangeExec]] RangeExec

[source, scala]
----
scala> spark.range(10).explain
== Physical Plan ==
WholeStageCodegen
:  +- Range 0, 1, 8, 10, [id#20L]
----
