== [[AMEndpoint]] AMEndpoint -- ApplicationMaster RPC Endpoint

=== [[onStart]] onStart Callback

When `onStart` is called, `AMEndpoint` communicates with the driver (the `driver` remote RPC Endpoint reference) by sending a one-way `RegisterClusterManager` message with a reference to itself.

After `RegisterClusterManager` has been sent (and received by link:spark-yarn-cluster-YarnSchedulerEndpoint.adoc#RegisterClusterManager[YarnSchedulerEndpoint]) the communication between the RPC endpoints of <<ApplicationMaster, ApplicationMaster>> (YARN) and link:spark-yarn-yarnschedulerbackend.adoc[YarnSchedulerBackend] (the Spark driver) is considered established.

=== [[messages]] RPC Messages

==== [[RequestExecutors]] RequestExecutors

[source, scala]
----
RequestExecutors(
  requestedTotal: Int,
  localityAwareTasks: Int,
  hostToLocalTaskCount: Map[String, Int])
extends CoarseGrainedClusterMessage
----

When `RequestExecutors` arrives, `AMEndpoint` link:spark-yarn-YarnAllocator.adoc#requestTotalExecutorsWithPreferredLocalities[requests `YarnAllocator` for executors given locality preferences].

If the `requestedTotal` number of executors is different than the current number of executors requested earlier, <<resetAllocatorInterval, resetAllocatorInterval>> is executed.

In case when `YarnAllocator` is not available yet, you should see the following WARN message in the logs:

```
WARN Container allocator is not ready to request executors yet.
```

The response is `false` then.

=== [[resetAllocatorInterval]] resetAllocatorInterval

CAUTION: FIXME
