== Schedulable

`Schedulable` is a <<contract, contract>> of <<entities, schedulable entities>>.

NOTE: `Schedulable` is a `private[spark]` Scala trait. You can find the sources in https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/Schedulable.scala[org.apache.spark.scheduler.Schedulable].

=== [[contract]] Schedulable Contract

Every `Schedulable` follows the following contract:

* It has a `name`.
+
[source, scala]
----
name: String
----

* It has a `parent` link:spark-taskscheduler-pool.adoc[Pool].
+
[source, scala]
----
parent: Pool
----

* It has a `schedulableQueue`, a `schedulingMode`, `weight`, `minShare`, `runningTasks`, `priority`, `stageId`.
+
[source, scala]
----
schedulableQueue: ConcurrentLinkedQueue[Schedulable]
schedulingMode: SchedulingMode
weight: Int
minShare: Int
runningTasks: Int
priority: Int
stageId: Int
----

* It manages a collection of `Schedulables` and can add or remove one.
+
[source, scala]
----
addSchedulable(schedulable: Schedulable): Unit
removeSchedulable(schedulable: Schedulable): Unit
----

* It can query for a `Schedulable` by name.
+
[source, scala]
----
getSchedulableByName(name: String): Schedulable
----

* It can <<getSortedTaskSetQueue, return a sorted collection of TaskSetManagers>>.
+
[source, scala]
----
getSortedTaskSetQueue: ArrayBuffer[TaskSetManager]
----

* It can be informed about lost link:spark-executor.adoc[executors].
+
[source, scala]
----
executorLost(executorId: String, host: String, reason: ExecutorLossReason): Unit
----

* It checks speculatable tasks.
+
[source, scala]
----
checkSpeculatableTasks(): Boolean
----

==== [[getSortedTaskSetQueue]] getSortedTaskSetQueue

[source, scala]
----
getSortedTaskSetQueue: ArrayBuffer[TaskSetManager]
----

`getSortedTaskSetQueue` is almost exclusively used in link:spark-taskschedulerimpl.adoc#resourceOffers[TaskSchedulerImpl to handle resource offers] (to link:spark-tasksetmanager.adoc#executorAdded[let every TaskSetManager know about a new executor]).

NOTE: It is also used in link:spark-taskscheduler-pool.adoc[Pool] to recursively compute its own `getSortedTaskSetQueue`.

=== [[entities]] Schedulable Entities

There are currently two types of `Schedulable` entities:

* link:spark-taskscheduler-pool.adoc[Pool]
* link:spark-tasksetmanager.adoc[TaskSetManager]
