== [[MemoryPlan]] `MemoryPlan` Logical Operator

`MemoryPlan` is a link:spark-sql-LogicalPlan.adoc#LeafNode[leaf logical operator] that is used to query the data that has been written into a link:spark-sql-streaming-sink.adoc#MemorySink[MemorySink]. `MemoryPlan` is created when link:spark-sql-streaming-DataStreamWriter.adoc#start[starting continuous writing] (to a `MemorySink`).

TIP: See the example in link:spark-sql-streaming-MemoryStream.adoc[MemoryStream].

```
scala> intsOut.explain(true)
== Parsed Logical Plan ==
SubqueryAlias memstream
+- MemoryPlan org.apache.spark.sql.execution.streaming.MemorySink@481bf251, [value#21]

== Analyzed Logical Plan ==
value: int
SubqueryAlias memstream
+- MemoryPlan org.apache.spark.sql.execution.streaming.MemorySink@481bf251, [value#21]

== Optimized Logical Plan ==
MemoryPlan org.apache.spark.sql.execution.streaming.MemorySink@481bf251, [value#21]

== Physical Plan ==
LocalTableScan [value#21]
```

When executed, `MemoryPlan` is translated to link:spark-sql-spark-plan-LocalTableScanExec.adoc[`LocalTableScanExec` physical operator] in a link:spark-sql-SparkPlan.adoc[physical execution plan] (similar to link:spark-sql-logical-plan-LocalRelation.adoc[`LocalRelation` logical query plan]) that happens in link:spark-sql-BasicOperators.adoc[`BasicOperators` strategy].
