== [[StorageListener]] StorageListener -- Spark Listener To...FIXME

`StorageListener` is a link:spark-webui-BlockStatusListener.adoc[BlockStatusListener] that...FIXME

[[internal-registries]]
.StorageListener's Internal Registries and Counters
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[_rddInfoMap]] `_rddInfoMap`
| Lookup table of `RDDInfo` per...FIXME

Used when...FIXME
|===

=== [[onBlockUpdated]] Intercepting Notifications about Changes in Block Status (on BlockManager on Executor) -- `onBlockUpdated` Method

[source, scala]
----
onBlockUpdated(blockUpdated: SparkListenerBlockUpdated): Unit
----

`onBlockUpdated`...FIXME

NOTE: `onBlockUpdated` is a part of link:spark-SparkListener.adoc#onBlockUpdated[SparkListener contract] to announce that there was a change in a block status (on a `BlockManager` on an executor).

=== [[updateRDDInfo]] `updateRDDInfo` Internal Method

[source, scala]
----
updateRDDInfo(updatedBlocks: Seq[(BlockId, BlockStatus)]): Unit
----

CAUTION: FIXME

NOTE: `updateRDDInfo` is used when `StorageListener` <<onBlockUpdated, gets notified about a change in a block status (on a `BlockManager` on an executor)>>.

=== [[creating-instance]] Creating StorageListener Instance

`StorageListener` takes the following when created:

* [[storageStatusListener]] link:spark-webui-StorageStatusListener.adoc[StorageStatusListener]

`StorageListener` initializes the <<internal-registries, internal registries and counters>>.

NOTE: `StorageListener` is created when `SparkUI` link:spark-webui-SparkUI.adoc#create[is created].

=== [[activeStorageStatusList]] Finding Active BlockManagers -- `activeStorageStatusList` Method

[source, scala]
----
activeStorageStatusList: Seq[StorageStatus]
----

`activeStorageStatusList` requests <<storageStatusListener, StorageStatusListener>> for link:spark-webui-StorageStatusListener.adoc#storageStatusList[active BlockManagers (on executors)].

[NOTE]
====
`activeStorageStatusList` is used when:

* `AllRDDResource` does `rddList` and `getRDDStorageInfo`
* `StorageListener` <<updateRDDInfo, updateRDDInfo>>
====
