== [[SparkPlanner]] SparkPlanner -- Query Planner

`SparkPlanner` is a concrete link:spark-sql-queryplanner.adoc[QueryPlanner] (indirectly through extending link:spark-sql-queryplanner.adoc#SparkStrategies[SparkStrategies]) that allows for `extraStrategies`, i.e. a collection of additional link:spark-sql-queryplanner.adoc#SparkStrategy[SparkStrategy] transformations (beside the ones defined in `SparkPlanner` itself).

`SparkPlanner` requires a link:spark-sparkcontext.adoc[SparkContext], a link:spark-sql-SQLConf.adoc[SQLConf], and a collection of `Strategy` objects (as `extraStrategies`) when created.

`SparkPlanner` defines `numPartitions` method that returns the value of link:spark-sql-settings.adoc#spark.sql.shuffle.partitions[spark.sql.shuffle.partitions] for the number of partitions to use for joins and aggregations.

`strategies` collection uses the constructor's `extraStrategies` and the predefined collection of `Strategy` objects.

Among the `SparkStrategy` objects are link:spark-sql-FileSourceStrategy.adoc[FileSourceStrategy] and link:spark-sql-JoinSelection.adoc[JoinSelection].
