== Spark MLlib

CAUTION: I really wish I'd know what the page says :)

=== FP-growth Algorithm

Spark 1.5 have significantly improved on frequent pattern mining capabilities with new algorithms for association rule generation and sequential pattern mining.

* *Frequent Itemset Mining* using the *Parallel FP-growth* algorithm (since Spark 1.3)
** https://spark.apache.org/docs/latest/mllib-frequent-pattern-mining.html[Frequent Pattern Mining in MLlib User Guide]
** *frequent pattern mining*
*** reveals the most frequently visited site in a particular period
*** finds popular routing paths that generate most traffic in a particular region
** models its input as a set of *transactions*, e.g. a path of nodes.
** A transaction is a set of *items*, e.g. network nodes.
** the algorithm looks for common *subsets of items* that appear across transactions, e.g. sub-paths of the network that are frequently traversed.
** A naive solution: generate all possible itemsets and count their occurrence
** A subset is considered *a pattern* when it appears in some minimum proportion of all transactions - *the support*.
** the items in a transaction are unordered
** analyzing traffic patterns from network logs
** the algorithm finds all frequent itemsets without generating and testing all candidates
* suffix trees (FP-trees) constructed and grown from filtered transactions
* Also available in Mahout, but slower.
* Distributed generation of https://en.wikipedia.org/wiki/Association_rule_learning[association rules] (since Spark 1.5).
** in a retailer’s transaction database, a rule `{toothbrush, floss} => {toothpaste}` with a confidence value `0.8` would indicate that `80%` of customers who buy a toothbrush and floss also purchase a toothpaste in the same transaction. The retailer could then use this information, put both toothbrush and floss on sale, but raise the price of toothpaste to increase overall profit.
** http://spark.apache.org/docs/latest/mllib-frequent-pattern-mining.html#fp-growth[FPGrowth] model
* *parallel sequential pattern mining* (since Spark 1.5)
** *PrefixSpan* algorithm with modifications to parallelize the algorithm for Spark.
** extract frequent sequential patterns like routing updates, activation failures, and broadcasting timeouts that could potentially lead to customer complaints and proactively reach out to customers when it happens.

=== Power Iteration Clustering

* since Spark 1.3
* unsupervised learning including clustering
* identifying similar behaviors among users or network clusters
* *Power Iteration Clustering (PIC)* in MLlib, a simple and scalable graph clustering method
** https://spark.apache.org/docs/latest/mllib-clustering.html#power-iteration-clustering-pic[PIC in MLlib User Guide]
** `org.apache.spark.mllib.clustering.PowerIterationClustering`
** a graph algorithm
** Among the first MLlib algorithms built upon link:spark-graphx.adoc[GraphX].
** takes an undirected graph with similarities defined on edges and outputs clustering assignment on nodes
** uses truncated http://en.wikipedia.org/wiki/Power_iteration[power iteration] to find a very low-dimensional embedding of the nodes, and this embedding leads to effective graph clustering.
** stores the normalized similarity matrix as a graph with normalized similarities defined as edge properties
** The edge properties are cached and remain static during the power iterations.
** The embedding of nodes is defined as node properties on the same graph topology.
** update the embedding through power iterations, where aggregateMessages is used to compute matrix-vector multiplications, the essential operation in a power iteration method
** k-means is used to cluster nodes using the embedding.
** able to distinguish clearly the degree of similarity – as represented by the Euclidean distance among the points – even though their relationship is non-linear

== Further reading

* https://databricks.com/blog/2015/09/28/improved-frequent-pattern-mining-in-spark-1-5-association-rules-and-sequential-patterns.html[Improved Frequent Pattern Mining in Spark 1.5: Association Rules and Sequential Patterns]
* https://databricks.com/blog/2015/04/17/new-mllib-algorithms-in-spark-1-3-fp-growth-and-power-iteration-clustering.html[New MLlib Algorithms in Spark 1.3: FP-Growth and Power Iteration Clustering]
