== StreamingContext

`StreamingContext` is the main entry point for all Spark Streaming functionality.

=== [[creating-instance]] Creating Instance

When you create a new instance of `StreamingContext` (and you will eventually) it first checks whether a link:spark-sparkcontext.adoc[SparkContext] or the checkpoint directory are given.

[TIP]
====
`StreamingContext` will warn you when you use `local` or `local[1]` link:spark-deployment-environments.adoc#master-urls[master URLs]:

```
WARN StreamingContext: spark.master should be set as local[n], n > 1 in local mode if you have receivers to get data, otherwise Spark jobs will not get resources to process the received data.
```
====

A link:spark-streaming.adoc#DStreamGraph[DStreamGraph] is created.

A link:spark-streaming-jobscheduler.adoc[JobScheduler] is created.

A link:spark-streaming.adoc#StreamingJobProgressListener[StreamingJobProgressListener] is created.

The link:spark-streaming.adoc#StreamingTab[Streaming tab] in web UI is created (when spark.ui.enabled is set).

A link:spark-streaming.adoc#StreamingSource[StreamingSource] is instantiated.

At this point, it is assumed that the StreamingContext is `INITIALIZED`.

=== [[stopping]] Stopping

CAUTION: FIXME
