== [[SparkStrategies]] SparkStrategies -- Container of Execution Planning Strategies

`SparkStrategies` is an abstract Catalyst link:spark-sql-catalyst-QueryPlanner.adoc[query planner] that _merely_ serves as a "container" (or a namespace) of the concrete link:spark-sql-SparkStrategy.adoc[execution planning strategies] (for link:spark-sql-SparkPlanner.adoc[SparkPlanner]):

* link:spark-sql-SparkStrategy-Aggregation.adoc[Aggregation]
* link:spark-sql-SparkStrategy-BasicOperators.adoc[BasicOperators]
* `FlatMapGroupsWithStateStrategy`
* link:spark-sql-SparkStrategy-InMemoryScans.adoc[InMemoryScans]
* link:spark-sql-SparkStrategy-JoinSelection.adoc[JoinSelection]
* `SpecialLimits`
* `StatefulAggregationStrategy`
* `StreamingDeduplicationStrategy`
* `StreamingRelationStrategy`

[[singleRowRdd]]
`SparkStrategies` has a single lazily-instantiated `singleRowRdd` value that is an `RDD` of link:spark-sql-InternalRow.adoc[InternalRow] that link:spark-sql-SparkStrategy-BasicOperators.adoc[BasicOperators] execution planning strategy uses when link:spark-sql-SparkStrategy-BasicOperators.adoc#OneRowRelation[converting `OneRowRelation` to `RDDScanExec` physical operator].

NOTE: `OneRowRelation` logical operator represents SQL's link:spark-sql-AstBuilder.adoc#visitQuerySpecification[SELECT clause without FROM clause] or link:spark-sql-AstBuilder.adoc#visitExplain[EXPLAIN DESCRIBE TABLE].
