== ApplicationMaster

`ApplicationMaster` is a standalone application to...FIXME

<<ExecutorLauncher, ExecutorLauncher>> is a custom `ApplicationMaster` for client deploy mode.

`ApplicationMaster` and `ExecutorLauncher` are called by link:spark-yarn-client.adoc[Client] to...FIXME

=== [[main]] main

`main` defines `ApplicationMaster` as a standalone application.

It parses command-line arguments using `ApplicationMasterArguments` class.

CAUTION: FIXME What does `ApplicationMasterArguments` do?

It then uses `SparkHadoopUtil.get.runAsSparkUser` to run the main code with a Hadoop `UserGroupInformation` as a thread local variable (distributed to child threads) for authenticating HDFS and YARN calls.

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.deploy.SparkHadoopUtil` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.deploy.SparkHadoopUtil=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

When running with `DEBUG` log level set for `org.apache.spark.deploy.SparkHadoopUtil` (see above TIP) you should see the following message in the logs:

```
DEBUG running as user: [user]
```

`SparkHadoopUtil.get.runAsSparkUser` function executes a block that instantiates a `ApplicationMaster` instance first to call <<run, run>> method upon it afterwards.

=== [[run]] run

When `run` executes you should see the following INFO in the logs:

```
INFO ApplicationAttemptId: [appAttemptId]
```

=== [[ExecutorLauncher]] ExecutorLauncher

`ExecutorLauncher` is a helper class to run `ApplicationMaster` under another class name and thus allowing for easier identification of the client-mode ApplicationMaster (as `ExecutorLauncher`) and the cluster-mode ApplicationMaster (as `ApplicationMaster`) when using tools such as `ps` or `jps`.

NOTE: Consider `ExecutorLauncher` a `ApplicationMaster` for client deploy mode.
