== BlockTransferService

`BlockTransferService` is a contract for specialized link:spark-shuffleclient.adoc[ShuffleClient] objects that can <<contract, fetch and upload blocks synchronously or asynchronously>>.

NOTE: `BlockTransferService` is a `private[spark] abstract class`.

NOTE: link:spark-NettyBlockTransferService.adoc[NettyBlockTransferService] is the only available implementation of <<contract, BlockTransferService Contract>>.

=== [[contract]][[init]] `BlockTransferService` Contract

Every `BlockTransferService` offers the following:

* `init` that accepts link:spark-blockdatamanager.adoc[BlockDataManager] for storing or fetching blocks. It is assumed that the method is called before the service is considered fully operational.
+
[source, scala]
----
init(blockDataManager: BlockDataManager): Unit
----

* `port` the service listens to.
+
[source, scala]
----
port: Int
----

* `hostName` the service listens to.
+
[source, scala]
----
hostName: String
----

[[uploadBlock]]
* `uploadBlock` to upload a block (of `ManagedBuffer` identified by `BlockId`) to a remote `hostname` and `port`.
+
[source, scala]
----
uploadBlock(
  hostname: String,
  port: Int,
  execId: String,
  blockId: BlockId,
  blockData: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Future[Unit]
----

* Synchronous (and hence blocking) `fetchBlockSync` to fetch one block `blockId` (that corresponds to the link:spark-shuffleclient.adoc[ShuffleClient] parent's asynchronous link:spark-shuffleclient.adoc#fetchBlocks[fetchBlocks]).
+
[source, scala]
----
fetchBlockSync(
  host: String,
  port: Int,
  execId: String,
  blockId: String): ManagedBuffer
----
+
`fetchBlockSync` is a mere wrapper around link:spark-shuffleclient.adoc#fetchBlocks[fetchBlocks] to fetch one `blockId` block that waits until the fetch finishes.

=== [[uploadBlockSync]] `uploadBlockSync` Method

[source, scala]
----
uploadBlockSync(
  hostname: String,
  port: Int,
  execId: String,
  blockId: BlockId,
  blockData: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Unit
----

`uploadBlockSync` is a mere blocking wrapper around <<uploadBlock, uploadBlock>> that waits until the upload finishes.

NOTE: `uploadBlockSync` is only executed when link:spark-blockmanager.adoc#replicate[`BlockManager` replicates a block to another node(s)] (i.e. when a link:spark-rdd-caching.adoc#StorageLevel[replication level is greater than 1]).
