== [[CodegenSupport]] CodegenSupport -- Physical Operators with Optional Java Code Generation

`CodegenSupport` is an extension of link:spark-sql-SparkPlan.adoc[physical operators] that support *Java code generation* (aka *codegen*).

`CodegenSupport` allows physical operators to <<supportCodegen, disable codegen>>.

TIP: Use link:spark-sql-debugging-execution.adoc#debugCodegen[debugCodegen] method to review ``CodegenSupport``-generated code.

[source, scala]
----
val q = spark.range(1)

import org.apache.spark.sql.execution.debug._
scala> q.debugCodegen
Found 1 WholeStageCodegen subtrees.
== Subtree 1 / 1 ==
*Range (0, 1, step=1, splits=8)

Generated code:
...

// The above is equivalent to the following method chain
scala> q.queryExecution.debug.codegen
Found 1 WholeStageCodegen subtrees.
== Subtree 1 / 1 ==
*Range (0, 1, step=1, splits=8)

Generated code:
...
----

=== [[contract]] CodegenSupport Contract

[source, scala]
----
package org.apache.spark.sql.execution

trait CodegenSupport extends SparkPlan {
  // only required methods that have no implementation
  def doProduce(ctx: CodegenContext): String
  def inputRDDs(): Seq[RDD[InternalRow]]
}
----

.(Subset of) CodegenSupport Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[doProduce]] `doProduce`
| Used exclusively in the final <<produce, produce>> to create a Java source code for processing the rows from input RDD.

| [[inputRDDs]] `inputRDDs`
|
|===

=== [[supportCodegen]] `supportCodegen` Flag

[source, scala]
----
supportCodegen: Boolean = true
----

NOTE: `supportCodegen` is used exclusively when `CollapseCodegenStages` link:spark-sql-CollapseCodegenStages.adoc#supportCodegen[checks if a physical operator supports codegen].

[NOTE]
====
`supportCodegen` is disabled for the following physical operators:

* `GenerateExec`
* link:spark-sql-SparkPlan-HashAggregateExec.adoc[HashAggregateExec] with `ImperativeAggregate`
* `SortMergeJoinExec` for most of the link:spark-sql-joins.adoc#join-types[join types] except `INNER` and `CROSS`
====

=== [[produce]] Producing Java Source Code -- `produce` Method

[source, scala]
----
produce(ctx: CodegenContext, parent: CodegenSupport): String
----

`produce` creates a Java source code for processing the rows from input RDD.

Internally, `produce` link:spark-sql-SparkPlan.adoc#executeQuery[executes a "query"] that creates a Java source code with the result of <<doProduce, doProduce>>.

NOTE: _Executing a "query"_ is about link:spark-sql-SparkPlan.adoc#prepare[preparing the query for execution] followed by link:spark-sql-SparkPlan.adoc#waitForSubqueries[waitForSubqueries].

NOTE: `produce` is used mainly when `WholeStageCodegenExec` is requested to link:spark-sql-SparkPlan-WholeStageCodegenExec.adoc#doCodeGen[generate the JVM code for a subtree].
