== [[CacheManager]] CacheManager -- In-Memory Cache for Tables and Views

`CacheManager` is an in-memory cache for tables and views (as link:spark-sql-LogicalPlan.adoc[logical plans]). It uses the internal <<cachedData, cachedData>> collection of <<CachedData, CachedData>> to track logical plans and their cached link:spark-sql-LogicalPlan-InMemoryRelation.adoc[InMemoryRelation] representation.

`CacheManager` is shared across `SparkSessions` through link:spark-sql-SparkSession.adoc#sharedState[SharedState].

[source, scala]
----
sparkSession.sharedState.cacheManager
----

NOTE: A Spark developer can use `CacheManager` to cache ``Dataset``s using link:spark-sql-caching.adoc#cache[cache] or link:spark-sql-caching.adoc#persist[persist] operators.

=== [[cachedData]] Cached Queries -- `cachedData` Internal Registry

`cachedData` is a collection of <<CachedData, CachedData>> with link:spark-sql-LogicalPlan.adoc[logical plans] and their cached link:spark-sql-LogicalPlan-InMemoryRelation.adoc[InMemoryRelation] representation.

A new <<CachedData, CachedData>> is added when <<cacheQuery, a Dataset is cached>> and removed when a <<uncacheQuery, Dataset is uncached>> or when <<invalidateCachedPath, invalidating cache data with a resource path>>.

`cachedData` is <<clearCache, cleared>> when...FIXME

=== [[invalidateCachedPath]] `invalidateCachedPath` Method

CAUTION: FIXME

=== [[invalidateCache]] `invalidateCache` Method

CAUTION: FIXME

=== [[lookupCachedData]] `lookupCachedData` Method

CAUTION: FIXME

=== [[uncacheQuery]] `uncacheQuery` Method

CAUTION: FIXME

=== [[isEmpty]] `isEmpty` Method

CAUTION: FIXME

=== [[cacheQuery]] Caching Dataset (by Registering Logical Plan as InMemoryRelation) -- `cacheQuery` Method

[source, scala]
----
cacheQuery(
  query: Dataset[_],
  tableName: Option[String] = None,
  storageLevel: StorageLevel = MEMORY_AND_DISK): Unit
----

Internally, `cacheQuery` registers link:spark-sql-Dataset.adoc#logicalPlan[logical plan] of the input `query` in <<cachedData, cachedData>> internal registry of cached queries.

While registering, `cacheQuery` creates a link:spark-sql-LogicalPlan-InMemoryRelation.adoc#apply[InMemoryRelation] with the following properties:

* link:spark-sql-SQLConf.adoc#spark.sql.inMemoryColumnarStorage.compressed[spark.sql.inMemoryColumnarStorage.compressed] (enabled by default)
* link:spark-sql-SQLConf.adoc#spark.sql.inMemoryColumnarStorage.batchSize[spark.sql.inMemoryColumnarStorage.batchSize] (default: `10000`)
* Input `storageLevel` link:spark-rdd-StorageLevel.adoc[storage level]
* link:spark-sql-QueryExecution.adoc#executedPlan[Physical plan] ready for execution (after `planToCache` logical plan was link:spark-sql-SessionState.adoc#executePlan[executed])
* Input `tableName`

If however the input `query` has already been cached, `cacheQuery` simply prints the following WARN message to the logs and exits:

```
WARN CacheManager: Asked to cache already cached data.
```

[NOTE]
====
`cacheQuery` is used when:

* ``Dataset``'s link:spark-sql-caching.adoc#persist[persist] operator is executed
* `CatalogImpl` is requested to link:spark-sql-CatalogImpl.adoc#cacheTable[cache a table or view in-memory] or link:spark-sql-CatalogImpl.adoc#refreshTable[refreshTable]
====

=== [[clearCache]] Removing All Cached Tables From In-Memory Cache -- `clearCache` Method

[source, scala]
----
clearCache(): Unit
----

`clearCache` acquires a write lock and unpersists ``RDD[CachedBatch]``s of the queries in <<cachedData, cachedData>> before removing them altogether.

NOTE: `clearCache` is executed when the link:spark-sql-Catalog.adoc#CatalogImpl[CatalogImpl] is requested to link:spark-sql-Catalog.adoc#contract[clearCache].

=== [[CachedData]] CachedData

CAUTION: FIXME
