== [[MapStatus]] MapStatus -- Shuffle Map Output Status

`MapStatus` is the link:spark-taskscheduler-ShuffleMapTask.adoc#runTask[result of running a `ShuffleMapTask`] that includes <<contract, information about the `BlockManager` and estimated size of the reduce blocks>>.

There are two types of `MapStatus`:

* *CompressedMapStatus* that compresses the estimated map output size to 8 bits (`Byte`) for efficient reporting.
* *HighlyCompressedMapStatus* that stores the average size of non-empty blocks, and a compressed bitmap for tracking which blocks are empty.

When the number of blocks (the size of `uncompressedSizes`) is greater than *2000*, `HighlyCompressedMapStatus` is chosen.

CAUTION: FIXME What exactly is 2000? Is this the number of tasks in a job?

=== [[contract]] `MapStatus` Contract

[source, scala]
----
trait MapStatus {
  def location: BlockManagerId
  def getSizeForBlock(reduceId: Int): Long
}
----

NOTE: `MapStatus` is a `private[spark]` contract.

.`MapStatus` Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[location]] `location`
| The link:spark-blockmanager.adoc[BlockManager] where a `ShuffleMapTask` ran and the result is stored.

| [[getSizeForBlock]] `getSizeForBlock`
| The estimated size for the reduce block (in bytes).
|===
