== ReceiverTracker

`ReceiverTracker` manages execution of the receivers of link:spark-streaming-dstreams.adoc#ReceiverInputDStream[ReceiverInputDStreams].

NOTE: It is started when link:spark-streaming-jobscheduler.adoc[JobScheduler] starts.

If there is at least one `ReceiverInputDStreams` the RPC endpoint `ReceiverTracker` (in <<ReceiverTrackerEndpoint, ReceiverTrackerEndpoint>>) is set up.

`ReceiverTracker` can be in one of the following states:

* `Initialized` - it is in the state after having been instantiated.
* `Started`
* `Stopping`
* `Stopped`

When `ReceiverTracker` starts, you should see the following INFO message in the logs:

```
INFO ReceiverTracker: Starting [receivers.length] receivers
```

It posts <<ReceiverTrackerEndpoint-StartAllReceivers, StartAllReceivers>> to <<ReceiverTrackerEndpoint, ReceiverTracker RPC endpoint>>.

You should then see the following INFO message in the logs:

```
INFO ReceiverTracker: ReceiverTracker started
```

=== [[ReceiverTrackerEndpoint]] ReceiverTrackerEndpoint

CAUTION: FIXME

==== [[ReceiverTrackerEndpoint-StartAllReceivers]] StartAllReceivers

`StartAllReceivers(receivers)` is a local message sent from `ReceiverTracker.launchReceivers()`.

It schedules receivers (using `ReceiverSchedulingPolicy.scheduleReceivers(receivers, getExecutors)`).

CAUTION: FIXME What does `ReceiverSchedulingPolicy.scheduleReceivers(receivers, getExecutors)` do?

It does _some_ bookkeeping.

CAUTION: FIXME What is _the_ bookkeeping?

It finally starts every receiver (using the helper method <<ReceiverTrackerEndpoint-startReceiver, ReceiverTrackerEndpoint.startReceiver>>).

==== [[ReceiverTrackerEndpoint-startReceiver]] ReceiverTrackerEndpoint.startReceiver

CAUTION: FIXME
