== [[DataSource]] DataSource

`DataSource` case class belongs to the Data Source API (along with link:spark-sql-dataframereader.adoc[DataFrameReader] for loading datasets and link:spark-sql-dataframewriter.adoc[DataFrameWriter] for saving datasets).

`DataSource` acts as the canonical set of parameters that describe a data source. It uses a link:spark-sql-sparksession.adoc[SparkSession], a class name, a collection of `paths`, optional user-specified link:spark-sql-schema.adoc[schema], a collection of partition columns, a bucket specification, and options.

=== [[creating-instance]] Creating DataSource Instance

When being created, `DataSource` first <<lookupDataSource, looks up the providing class>> for the input `className` and computes the <<sourceSchema, name and schema>> of the data source.

==== [[lookupDataSource]] lookupDataSource Internal Method

CAUTION: FIXME Describe me.

It searches the classpath for available link:spark-sql-DataSourceRegister.adoc[DataSourceRegister] classes (using Java's link:++https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html#load-java.lang.Class-java.lang.ClassLoader-++[ServiceLoader.load] method).

==== [[sourceSchema]] sourceSchema Internal Method

CAUTION: FIXME Describe me.

=== [[write]] write

CAUTION: FIXME

=== [[createSource]] createSource

[source, scala]
----
createSource(metadataPath: String): Source
----

CAUTION: FIXME

=== [[sourceSchema]] sourceSchema

CAUTION: FIXME

=== [[inferFileFormatSchema]] inferFileFormatSchema

[source, scala]
----
inferFileFormatSchema(format: FileFormat): StructType
----

`inferFileFormatSchema` private method computes (aka _infers_) schema (as link:spark-sql-schema.adoc#StructType[StructType]). It returns `userSpecifiedSchema` if specified or uses `FileFormat.inferSchema`. It throws a `AnalysisException` when is unable to infer schema.

It uses `path` option for the list of directory paths.

NOTE: It is used by <<sourceSchema, DataSource.sourceSchema>> and <<createSource, DataSource.createSource>> when `FileFormat` is processed.

=== [[resolveRelation]] resolveRelation

[source, scala]
----
resolveRelation(checkPathExist: Boolean = true): BaseRelation
----

`resolveRelation` creates a `BaseRelation` for a given `DataSource`.

CAUTION: FIXME What's `BaseRelation`? Why is the name?
