== [[AggregateFunction]] AggregateFunction

`AggregateFunction` is the <<contract, contract>> for link:spark-sql-catalyst-Expression.adoc[expressions] that...FIXME

NOTE: Aggregate functions are not link:spark-sql-catalyst-Expression.adoc#[foldable], i.e. FIXME

[[top-level-expressions]]
.AggregateFunction Top-Level Expressions
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Behaviour
| Examples

| [[DeclarativeAggregate]] `DeclarativeAggregate`
|
|

| [[ImperativeAggregate]] `ImperativeAggregate`
|
|

| [[TypedAggregateExpression]] `TypedAggregateExpression`
|
|
|===

=== [[contract]] AggregateFunction Contract

[source, scala]
----
abstract class AggregateFunction extends Expression {
  def aggBufferSchema: StructType
  def aggBufferAttributes: Seq[AttributeReference]
  def inputAggBufferAttributes: Seq[AttributeReference]
  def defaultResult: Option[Literal] = None
}
----

.AggregateFunction Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[aggBufferSchema]] `aggBufferSchema`
| link:spark-sql-StructType.adoc[Schema] of an aggregation buffer to hold partial aggregate results.

Used mostly in link:spark-sql-ImperativeAggregate-ScalaUDAF.adoc[ScalaUDAF] and `AggregationIterator` (for `initializeAggregateFunctions`).

| [[aggBufferAttributes]] `aggBufferAttributes`
|

| [[inputAggBufferAttributes]] `inputAggBufferAttributes`
|

| [[defaultResult]] `defaultResult`
| Defaults to `None`.

|===
