== [[DataSourceScanExec]] DataSourceScanExec -- Contract for Leaf Physical Operators with Code Generation

`DataSourceScanExec` is a <<contract, contract>> for link:spark-sql-SparkPlan.adoc#LeafExecNode[leaf physical operators] with link:spark-sql-CodegenSupport.adoc[support for code generation] that...FIXME

NOTE: The prefix for variable names for `DataSourceScanExec` operators in link:spark-sql-CodegenSupport.adoc[CodegenSupport]-generated code is *scan*.

[[nodeNamePrefix]]
The default *node name prefix* is an empty string that is used as part of <<simpleString, simple description>> for...FIXME

[[known-implementations]]
.DataSourceScanExec's Known Implementations
[width="100%",cols="1,2",options="header"]
|===
| DataSourceScanExec
| Description

| link:spark-sql-SparkPlan-FileSourceScanExec.adoc[FileSourceScanExec]
|

| link:spark-sql-SparkPlan-RowDataSourceScanExec.adoc[RowDataSourceScanExec]
|
|===

=== [[contract]] DataSourceScanExec Contract

[source, scala]
----
package org.apache.spark.sql.execution

trait DataSourceScanExec extends LeafExecNode with CodegenSupport {
  // only required vals and methods that have no implementation
  val metastoreTableIdentifier: Option[TableIdentifier]
  val relation: BaseRelation
  def metadata: Map[String, String]
}
----

.(Subset of) DataSourceScanExec Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[metadata]] `metadata`
| Metadata (as a collection of key-value pairs) that describes this scan.

Used for <<simpleString, simpleString>>

| [[metastoreTableIdentifier]] `metastoreTableIdentifier`
| `TableIdentifier` that...FIXME

| [[relation]] `relation`
| link:spark-sql-BaseRelation.adoc[BaseRelation] that...FIXME
|===

=== [[simpleString]] Simple One-Line Description -- `simpleString` Method

[source, scala]
----
simpleString: String
----

NOTE: `simpleString` is a part of link:spark-sql-catalyst-QueryPlan.adoc#simpleString[QueryPlan Contract] to..FIXME.

`simpleString`...FIXME
