== [[TaskLocation]] TaskLocation

`TaskLocation` is a location where a link:spark-taskscheduler-tasks.adoc[task] should run.

`TaskLocation` can either be a host alone or a (host, executorID) pair (as <<ExecutorCacheTaskLocation, ExecutorCacheTaskLocation>>).

With `ExecutorCacheTaskLocation` the Spark scheduler prefers to launch the task on the given executor, but the next level of preference is any executor on the same host if this is not possible.

NOTE: `TaskLocation` is a Scala `private[spark] sealed` trait (i.e. all the available implementations of `TaskLocation` trait are in a single Scala file).

.Available TaskLocations
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[HostTaskLocation]] `HostTaskLocation`
| A location on a host.

| [[ExecutorCacheTaskLocation]] `ExecutorCacheTaskLocation`
| A location that includes both a host and an executor id on that host.

| [[HDFSCacheTaskLocation]] `HDFSCacheTaskLocation`
| A location on a host that is cached by Hadoop HDFS.

Used exclusively when link:spark-rdd-hadooprdd.adoc#getPreferredLocations[HadoopRDD] and link:spark-rdd-NewHadoopRDD.adoc#getPreferredLocations[NewHadoopRDD] are requested for their placement preferences (aka _preferred locations_).
|===
