== [[CatalystConf]] CatalystConf

`CatalystConf` is...FIXME

NOTE: The default `CatalystConf` is link:spark-sql-SQLConf.adoc[SQLConf] that is...FIXME

[[configuration-methods]]
.CatalystConf's Internal Properties (in alphabetical order)
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Initial Value
| Description

| [[caseSensitiveAnalysis]] `caseSensitiveAnalysis`
|
|

| [[cboEnabled]] `cboEnabled`
|
| Enables cost-based optimizations (CBO) for estimation of plan statistics when enabled.

Used in link:spark-sql-Optimizer-CostBasedJoinReorder.adoc[CostBasedJoinReorder] logical plan optimization and `Project`, `Filter`, `Join` and `Aggregate` logical operators.

| [[optimizerMaxIterations]] `optimizerMaxIterations`
| link:spark-sql-SQLConf.adoc#spark.sql.optimizer.maxIterations[spark.sql.optimizer.maxIterations]
| Maximum number of iterations for link:spark-sql-Analyzer.adoc#fixedPoint[Analyzer] and  link:spark-sql-Optimizer.adoc#fixedPoint[Optimizer].

| [[sessionLocalTimeZone]] `sessionLocalTimeZone`
|
|
|===

=== [[resolver]] `resolver` Method

`resolver` gives case-sensitive or case-insensitive `Resolvers` per <<caseSensitiveAnalysis, caseSensitiveAnalysis>> setting.

NOTE: `Resolver` is a mere function of two `String` parameters that returns `true` if both refer to the same entity (i.e. for case insensitive equality).
