== [[JettyUtils]] JettyUtils

`JettyUtils` is a set of utility methods for:

* Launching a web server using Jetty's HTTP Server

* FIXME

=== [[createServletHandler]] Creating HTTP Request Handler for Path -- `createServletHandler` Method

[source, scala]
----
createServletHandler[T <: AnyRef](
  path: String,
  servletParams: ServletParams[T],
  securityMgr: SecurityManager,
  conf: SparkConf,
  basePath: String = ""): ServletContextHandler
----

`createServletHandler`...FIXME

[NOTE]
====
`createServletHandler` is used when:

* `WebUI` is requested to link:spark-webui-WebUI.adoc#attachPage[attachPage]

* `MetricsServlet` is requested to `getHandlers`

* Spark Standalone's `WorkerWebUI` is requested to `initialize`
====

=== [[createServlet]] Creating HttpServlet -- `createServlet` Method

[source, scala]
----
createServlet[T <: AnyRef](
  servletParams: ServletParams[T],
  securityMgr: SecurityManager,
  conf: SparkConf): HttpServlet
----

`createServlet` creates the `X-Frame-Options` header that can be either `ALLOW-FROM` with the value of link:spark-webui-properties.adoc#spark.ui.allowFramingFrom[spark.ui.allowFramingFrom] configuration property if defined or `SAMEORIGIN`.

`createServlet` creates a Java Servlets `HttpServlet` with support for `GET` requests.

When handling `GET` requests, the `HttpServlet` first checks view permissions of the remote user (by requesting the `SecurityManager` to `checkUIViewPermissions` of the remote user).

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.SecurityManager` logger to see what happens when `SecurityManager` does the security check.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.SecurityManager=DEBUG
```

You should see the following DEBUG message in the logs:

```
DEBUG SecurityManager: user=[user] aclsEnabled=[aclsEnabled] viewAcls=[viewAcls] viewAclsGroups=[viewAclsGroups]
```
====

With view permissions check passed, the `HttpServlet` sends a response with the following:

* FIXME

In case the view permissions didn't allow to view the page, the `HttpServlet` sends an error response with the following:

* Status `403`

* `Cache-Control` header with "no-cache, no-store, must-revalidate"

* Error message: "User is not authorized to access this page."

NOTE: `createServlet` is used exclusively when `JettyUtils` is requested to <<createServletHandler, createServletHandler>>.
