== [[BaseSessionStateBuilder]] BaseSessionStateBuilder -- Base for Builders of SessionState

NOTE: `BaseSessionStateBuilder` is an experimental and unstable API. _You've been warned!_.

`BaseSessionStateBuilder` is <<creating-instance, created>> when `SparkSession` link:spark-sql-SparkSession.adoc#instantiateSessionState[is requested for a `SessionState`] (and also when <<newBuilder, newBuilder>> is called).

[source, scala]
----
val spark: SparkSession = ...
scala> spark.sessionState
res0: org.apache.spark.sql.internal.SessionState = org.apache.spark.sql.internal.SessionState@5feb8e9a
----

NOTE: `SessionStateBuilder` and `HiveSessionStateBuilder` are concrete `BaseSessionStateBuilder`.

[[properties]]
.BaseSessionStateBuilder's Properties (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| analyzer
|

| catalog
|

| conf
|

| createClone
|

| createQueryExecution
|

| experimentalMethods
|

| [[functionRegistry]] functionRegistry
| link:spark-sql-FunctionRegistry.adoc[FunctionRegistry]

CAUTION: FIXME Where is this used?

| listenerManager
|

| optimizer
|

| planner
|

| resourceLoader
|

| sqlParser
|

| streamingQueryManager
|

| udfRegistration
|
|===

[NOTE]
====
`BaseSessionStateBuilder` defines a type alias https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala#L57[NewBuilder] for a function to create a `BaseSessionStateBuilder`.

[source, scala]
----
type NewBuilder = (SparkSession, Option[SessionState]) => BaseSessionStateBuilder
----
====

=== [[contract]] BaseSessionStateBuilder Contract

[source, scala]
----
abstract class BaseSessionStateBuilder {
  def newBuilder: NewBuilder
}
----

.BaseSessionStateBuilder Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[newBuilder]] `newBuilder`
| Function to create a `BaseSessionStateBuilder`
|===

=== [[creating-instance]] Creating BaseSessionStateBuilder Instance

`BaseSessionStateBuilder` takes the following when created:

* [[session]] link:spark-sql-SparkSession.adoc[SparkSession]
* [[parentState]] Optional link:spark-sql-SessionState.adoc[SessionState]

=== [[build]] Building SessionState -- `build` Method

[source, scala]
----
build(): SessionState
----

`build` creates a link:spark-sql-SessionState.adoc[SessionState] (based on the link:spark-sql-SparkSession.adoc#sharedState[SharedState] of the input <<session, SparkSession>> and <<properties, properties>>).
