== SaveAs Operators

There are two *saveAs operators* in link:spark-streaming-operators.adoc[DStream]:

* `saveAsObjectFiles`
* `saveAsTextFiles`

They are link:spark-streaming-operators.adoc[output operators] that return nothing as they save each RDD in a batch to a storage.

Their full signature is as follows:

[source, scala]
----
saveAsObjectFiles(prefix: String, suffix: String = ""): Unit
saveAsTextFiles(prefix: String, suffix: String = ""): Unit
----

NOTE: SaveAs operators use link:spark-streaming-operators.adoc#foreachRDD[foreachRDD] output operator.

`saveAsObjectFiles` uses link:spark-io.adoc#saving-rdds-to-files[RDD.saveAsObjectFile] while `saveAsTextFiles` uses link:spark-io.adoc#saving-rdds-to-files[RDD.saveAsTextFile].

The file name is based on mandatory `prefix` and batch `time` with optional `suffix`. It is in the format of `[prefix]-[time in milliseconds].[suffix]`.

=== [[example]] Example

[source, scala]
----
val clicks: InputDStream[(String, String)] = messages
clicks.saveAsTextFiles("clicks", "txt")
----
