== CrossValidator

CAUTION: FIXME Needs more love to be finished.

`CrossValidator` is an link:spark-mllib-estimators.adoc[Estimator] for link:spark-mllib-models.adoc[CrossValidatorModel], i.e. it can fit a `CrossValidatorModel` for a given input dataset.

It belongs to `org.apache.spark.ml.tuning` package.

[source, scala]
----
import org.apache.spark.ml.tuning.CrossValidator
----

`CrossValidator` accepts `numFolds` parameter (amongst the others).

NOTE: What makes `CrossValidator` a very useful tool for _model selection_ is its ability to work with any link:spark-mllib-estimators.adoc[Estimator] instance, link:spark-mllib-pipelines.adoc[Pipelines] including, that can preprocess datasets before passing them on. This gives you a way to work with any dataset and preprocess it before a new (possibly better) model could be fit to it.

[source, scala]
----
import org.apache.spark.ml.tuning.CrossValidator
val cv = new CrossValidator

scala> println(cv.explainParams)
estimator: estimator for selection (undefined)
estimatorParamMaps: param maps for the estimator (undefined)
evaluator: evaluator used to select hyper-parameters that maximize the validated metric (undefined)
numFolds: number of folds for cross validation (>= 2) (default: 3)
seed: random seed (default: -1191137437)
----

=== [[example]] Example (with Pipeline)

[source, scala]
----
// Let's create a pipeline with transformers and estimator
import org.apache.spark.ml.feature.Tokenizer
val tok = new Tokenizer().setInputCol("text")

import org.apache.spark.ml.feature.HashingTF
val hashTF = new HashingTF()
  .setInputCol(tok.getOutputCol)
  .setOutputCol("features")
  .setNumFeatures(10)

import org.apache.spark.ml.clustering.KMeans
val kmeans = new KMeans

import org.apache.spark.ml.Pipeline
val pipeline = new Pipeline().setStages(Array(tok, hashTF, kmeans))

// 0 = scientific text
// 1 = non-scientific text
val trainDS = Seq(
  (0L, "[science] hello world", 0),
  (1L, "long text", 1),
  (2L, "[science] hello all people", 0),
  (3L, "[science] hello hello", 0)).toDF("id", "text", "label").cache

// Check out the train dataset
// Values in label and prediction columns should be alike
val sampleModel = pipeline.fit(trainDS)
scala> sampleModel.transform(trainDS).select("text", "label", "features", "prediction").show(false)
+--------------------------+-----+--------------------------------+----------+
|text                      |label|features                        |prediction|
+--------------------------+-----+--------------------------------+----------+
|[science] hello world     |0    |(10,[0,2],[1.0,2.0])            |0         |
|long text                 |1    |(10,[2,3],[1.0,1.0])            |1         |
|[science] hello all people|0    |(10,[0,2,3,9],[1.0,1.0,1.0,1.0])|1         |
|[science] hello hello     |0    |(10,[0,2],[1.0,2.0])            |0         |
+--------------------------+-----+--------------------------------+----------+

val input = Seq("Hello ScienCE").toDF("text")
scala> sampleModel.transform(input).show(false)
+-------------+------------------------+--------------------+----------+
|text         |tok_4174a05fbc07__output|features            |prediction|
+-------------+------------------------+--------------------+----------+
|Hello ScienCE|[hello, science]        |(10,[2,6],[1.0,1.0])|1         |
+-------------+------------------------+--------------------+----------+

import org.apache.spark.ml.tuning.ParamGridBuilder
val paramGrid = new ParamGridBuilder().build()

import org.apache.spark.ml.evaluation.RegressionEvaluator
val regEval = new RegressionEvaluator

import org.apache.spark.ml.tuning.CrossValidator
val cv = new CrossValidator()
  .setEstimator(pipeline) // <-- pipeline is the estimator
  .setEvaluator(regEval)
  .setEstimatorParamMaps(paramGrid)

val cvModel = cv.fit(trainDS)
----

=== [[example-without-pipeline]] Example (no Pipeline)

[source, scala]
----
import org.apache.spark.mllib.linalg.Vectors
val features = Vectors.sparse(3, Array(1), Array(1d))
val df = Seq(
  (0, "hello world", 0.0, features),
  (1, "just hello",  1.0, features)).toDF("id", "text", "label", "features")

import org.apache.spark.ml.classification.LogisticRegression
val lr = new LogisticRegression

import org.apache.spark.ml.evaluation.RegressionEvaluator
val regEval = new RegressionEvaluator

import org.apache.spark.ml.tuning.ParamGridBuilder
// Parameterize the only estimator used, i.e. LogisticRegression
// Use println(lr.explainParams) to learn about the supported parameters
val paramGrid = new ParamGridBuilder()
  .addGrid(lr.regParam, Array(0.1, 0.01))
  .build()

import org.apache.spark.ml.tuning.CrossValidator
val cv = new CrossValidator()
  .setEstimator(lr) // just LogisticRegression not Pipeline
  .setEvaluator(regEval)
  .setEstimatorParamMaps(paramGrid)

// FIXME

scala> val cvModel = cv.fit(df)
java.lang.IllegalArgumentException: requirement failed: Nothing has been added to this summarizer.
  at scala.Predef$.require(Predef.scala:219)
  at org.apache.spark.mllib.stat.MultivariateOnlineSummarizer.normL2(MultivariateOnlineSummarizer.scala:270)
  at org.apache.spark.mllib.evaluation.RegressionMetrics.SSerr$lzycompute(RegressionMetrics.scala:65)
  at org.apache.spark.mllib.evaluation.RegressionMetrics.SSerr(RegressionMetrics.scala:65)
  at org.apache.spark.mllib.evaluation.RegressionMetrics.meanSquaredError(RegressionMetrics.scala:99)
  at org.apache.spark.mllib.evaluation.RegressionMetrics.rootMeanSquaredError(RegressionMetrics.scala:108)
  at org.apache.spark.ml.evaluation.RegressionEvaluator.evaluate(RegressionEvaluator.scala:94)
  at org.apache.spark.ml.tuning.CrossValidator$$anonfun$fit$1.apply(CrossValidator.scala:115)
  at org.apache.spark.ml.tuning.CrossValidator$$anonfun$fit$1.apply(CrossValidator.scala:105)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.apache.spark.ml.tuning.CrossValidator.fit(CrossValidator.scala:105)
  ... 61 elided
----
