== Metrics System

Spark uses http://metrics.dropwizard.io/[Metrics] - a Java library to measure the behavior of the components.

`org.apache.spark.metrics.source.Source` is the top-level class for the metric registries in Spark. They expose their internal status.

Spark uses http://metrics.dropwizard.io/3.1.0/[Metrics 3.1.0].

[CAUTION]
====
FIXME Review

* How to use the metrics to monitor Spark using jconsole?
* ApplicationSource
* WorkerSource
* ExecutorSource
* JvmSource
* MesosClusterSchedulerSource
* StreamingSource
====

* Review `MetricsServlet`
* Review `org.apache.spark.metrics` package, esp. `MetricsSystem` class.
* Default properties
** `"*.sink.servlet.class", "org.apache.spark.metrics.sink.MetricsServlet"`
** `"*.sink.servlet.path", "/metrics/json"`
** `"master.sink.servlet.path", "/metrics/master/json"`
** `"applications.sink.servlet.path", "/metrics/applications/json"`
* `spark.metrics.conf` (default: `metrics.properties` on `CLASSPATH`)
* `spark.metrics.conf.` prefix in SparkConf

=== Executors

A non-local executor registers executor source.

FIXME See `Executor` class.

=== Master

```
$ http http://192.168.1.4:8080/metrics/master/json/path
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 207
Content-Type: text/json;charset=UTF-8
Server: Jetty(8.y.z-SNAPSHOT)
X-Frame-Options: SAMEORIGIN

{
    "counters": {},
    "gauges": {
        "master.aliveWorkers": {
            "value": 0
        },
        "master.apps": {
            "value": 0
        },
        "master.waitingApps": {
            "value": 0
        },
        "master.workers": {
            "value": 0
        }
    },
    "histograms": {},
    "meters": {},
    "timers": {},
    "version": "3.0.0"
}
```
