== [[FairSchedulableBuilder]] FairSchedulableBuilder -- SchedulableBuilder for FAIR Scheduling Mode

`FairSchedulableBuilder` is a <<spark-scheduler-SchedulableBuilder.adoc#, SchedulableBuilder>> that is <<creating-instance, created>> exclusively for <<spark-TaskSchedulerImpl.adoc#, TaskSchedulerImpl>> for *FAIR scheduling mode* (when <<spark-configuration-properties.adoc#spark.scheduler.mode, spark.scheduler.mode>> configuration property is `FAIR`).

[[creating-instance]]
`FairSchedulableBuilder` takes the following to be created:

* [[rootPool]] <<spark-Schedulable-Pool.adoc#, Root pool of schedulables>>
* [[conf]] <<spark-SparkConf.adoc#, SparkConf>>

Once <<creating-instance, created>>, `TaskSchedulerImpl` requests the `FairSchedulableBuilder` to <<buildPools, build the pools>>.

[[DEFAULT_SCHEDULER_FILE]]
`FairSchedulableBuilder` uses the pools defined in an <<allocations-file, allocation pools configuration file>> that is assumed to be the value of the <<spark-configuration-properties.adoc#spark.scheduler.allocation.file, spark.scheduler.allocation.file>> configuration property or the default *fairscheduler.xml* (that is <<buildPools, expected to be available on a Spark application's class path>>).

TIP: Use *conf/fairscheduler.xml.template* as a template for the <<allocations-file, allocation pools configuration file>>.

[[DEFAULT_POOL_NAME]]
`FairSchedulableBuilder` always has the *default* pool defined (and <<buildDefaultPool, registers it>> unless done in the <<allocations-file, allocation pools configuration file>>).

[[logging]]
[TIP]
====
Enable `ALL` logging level for `org.apache.spark.scheduler.FairSchedulableBuilder` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.scheduler.FairSchedulableBuilder=ALL
```

Refer to <<spark-logging.adoc#, Logging>>.
====

=== [[allocations-file]] Allocation Pools Configuration File

The *allocation pools configuration file* is an XML file.

The default `conf/fairscheduler.xml.template` is as follows:

[source, xml]
----
<?xml version="1.0"?>
<allocations>
  <pool name="production">
    <schedulingMode>FAIR</schedulingMode>
    <weight>1</weight>
    <minShare>2</minShare>
  </pool>
  <pool name="test">
    <schedulingMode>FIFO</schedulingMode>
    <weight>2</weight>
    <minShare>3</minShare>
  </pool>
</allocations>
----

TIP: The top-level element's name `allocations` can be anything. Spark does not insist on `allocations` and accepts any name.

=== [[buildPools]] Building (Tree of) Pools of Schedulables -- `buildPools` Method

[source, scala]
----
buildPools(): Unit
----

NOTE: `buildPools` is part of the <<spark-scheduler-SchedulableBuilder.adoc#buildPools, SchedulableBuilder Contract>> to build a tree of <<spark-Schedulable-Pool.adoc#, pools (of Schedulables)>>.

`buildPools` <<buildFairSchedulerPool, creates Fair Scheduler pools from a configuration file>> if available and then <<buildDefaultPool, builds the default pool>>.

`buildPools` prints out the following INFO message to the logs when the configuration file (per the <<spark-configuration-properties.adoc#spark.scheduler.allocation.file, spark.scheduler.allocation.file>> configuration property) could be read:

```
Creating Fair Scheduler pools from [file]
```

`buildPools` prints out the following INFO message to the logs when the <<spark-configuration-properties.adoc#spark.scheduler.allocation.file, spark.scheduler.allocation.file>> configuration property was not used to define the configuration file and the <<DEFAULT_SCHEDULER_FILE, default configuration file>> is used instead:

```
Creating Fair Scheduler pools from default file: [DEFAULT_SCHEDULER_FILE]
```

When neither <<spark-configuration-properties.adoc#spark.scheduler.allocation.file, spark.scheduler.allocation.file>> configuration property nor the <<DEFAULT_SCHEDULER_FILE, default configuration file>> could be used, `buildPools` prints out the following WARN message to the logs:

```
Fair Scheduler configuration file not found so jobs will be scheduled in FIFO order. To use fair scheduling, configure pools in [DEFAULT_SCHEDULER_FILE] or set spark.scheduler.allocation.file to a file that contains the configuration.
```

=== [[addTaskSetManager]] addTaskSetManager

`addTaskSetManager` link:spark-taskscheduler-Schedulable.adoc#contract[looks up the default pool (using Pool.getSchedulableByName)].

NOTE: `addTaskSetManager` is part of the <<contract, SchedulableBuilder Contract>>.

NOTE: Although the `Pool.getSchedulableByName` method may return no Schedulable for a name, the default root pool does exist as <<buildDefaultPool, it is assumed it was registered before>>.

If `properties` for the `Schedulable` were given, `spark.scheduler.pool` property is looked up and becomes the current pool name (or defaults to `default`).

NOTE: `spark.scheduler.pool` is the only property supported. Refer to <<spark.scheduler.pool, spark.scheduler.pool>> later in this document.

If the pool name is not available, it is registered with the pool name, `FIFO` scheduling mode, minimum share `0`, and weight `1`.

After the new pool was registered, you should see the following INFO message in the logs:

```
INFO FairSchedulableBuilder: Created pool [poolName], schedulingMode: FIFO, minShare: 0, weight: 1
```

The `manager` schedulable is registered to the pool (either the one that already existed or was created just now).

You should see the following INFO message in the logs:

```
INFO FairSchedulableBuilder: Added task set [manager.name] to pool [poolName]
```

=== [[spark.scheduler.pool]] spark.scheduler.pool Property

link:spark-sparkcontext-local-properties.adoc#setLocalProperty[SparkContext.setLocalProperty] allows for setting properties per thread to group jobs in logical groups. This mechanism is used by `FairSchedulableBuilder` to watch for `spark.scheduler.pool` property to group jobs from threads and submit them to a non-default pool.

[source, scala]
----
val sc: SparkContext = ???
sc.setLocalProperty("spark.scheduler.pool", "myPool")
----

TIP: See <<addTaskSetManager, addTaskSetManager>> for how this setting is used.

=== [[buildDefaultPool]] Registering Default Pool -- `buildDefaultPool` Method

[source, scala]
----
buildDefaultPool(): Unit
----

`buildDefaultPool` requests the <<rootPool, root pool>> to <<getSchedulableByName, find the default pool>> (one with the <<DEFAULT_POOL_NAME, default>> name).

Unless already available, `buildDefaultPool` creates a <<spark-Schedulable-Pool.adoc#, schedulable pool>> with the following:

* <<DEFAULT_POOL_NAME, default>> pool name

* `FIFO` scheduling mode

* `0` for the initial minimum share

* `1` for the initial weight

In the end, `buildDefaultPool` requests the <<rootPool, Pool>> to <<spark-Schedulable-Pool.adoc#addSchedulable, register the pool>> followed by the INFO message in the logs:

```
Created default pool: [name], schedulingMode: [mode], minShare: [minShare], weight: [weight]
```

NOTE: `buildDefaultPool` is used exclusively when `FairSchedulableBuilder` is requested to <<buildPools, build the pools>>.

=== [[buildFairSchedulerPool]] Building Pools from XML Allocations File -- `buildFairSchedulerPool` Internal Method

[source, scala]
----
buildFairSchedulerPool(
  is: InputStream,
  fileName: String): Unit
----

`buildFairSchedulerPool` starts by loading the XML file from the given `InputStream`.

For every *pool* element, `buildFairSchedulerPool` creates a <<spark-Schedulable-Pool.adoc#, schedulable pool>> with the following:

* Pool name per *name* attribute

* Scheduling mode per *schedulingMode* element (case-insensitive with `FIFO` as the default)

* Initial minimum share per *minShare* element (default: `0`)

* Initial weight per *weight* element (default: `1`)

In the end, `buildFairSchedulerPool` requests the <<rootPool, Pool>> to <<spark-Schedulable-Pool.adoc#addSchedulable, register the pool>> followed by the INFO message in the logs:

```
Created pool: [name], schedulingMode: [mode], minShare: [minShare], weight: [weight]
```

NOTE: `buildFairSchedulerPool` is used exclusively when `FairSchedulableBuilder` is requested to <<buildPools, build the pools>>.
