== [[UserDefinedAggregateFunction]] UserDefinedAggregateFunction -- User-Defined Aggregate Functions (UDAFs)

`UserDefinedAggregateFunction` is a <<contract, contract>> to define *user-defined aggregate functions* (UDAFs).

`UserDefinedAggregateFunction` is created using <<apply, apply>> or <<distinct, distinct>> factory methods (and wrapped in a link:spark-sql-Expression-ImperativeAggregate-ScalaUDAF.adoc[ScalaUDAF] expression container).

[NOTE]
====
Use link:spark-sql-UDFRegistration.adoc[UDFRegistration] to register a (temporary) `UserDefinedAggregateFunction` and use it in link:spark-sql-SparkSession.adoc#sql[SQL mode].

[source, scala]
----
import org.apache.spark.sql.expressions.UserDefinedAggregateFunction
val mySum: UserDefinedAggregateFunction = ...
spark.udf.register("mySum", mySum)

spark.sql("SELECT mySum(*) FROM range(5)")
----
====

=== [[contract]] UserDefinedAggregateFunction Contract

[source, scala]
----
package org.apache.spark.sql.expressions

abstract class UserDefinedAggregateFunction {
  // only required methods that have no implementation
  def bufferSchema: StructType
  def dataType: DataType
  def deterministic: Boolean
  def evaluate(buffer: Row): Any
  def initialize(buffer: MutableAggregationBuffer): Unit
  def inputSchema: StructType
  def merge(buffer1: MutableAggregationBuffer, buffer2: Row): Unit
  def update(buffer: MutableAggregationBuffer, input: Row): Unit
}
----

.(Subset of) UserDefinedAggregateFunction Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[bufferSchema]] bufferSchema
|

| [[dataType]] dataType
|

| [[deterministic]] deterministic
|

| [[evaluate]] evaluate
|

| [[initialize]] initialize
|

| [[inputSchema]] inputSchema
|

| [[merge]] merge
|

| [[update]] update
|
|===

=== [[apply]] Creating Column for UDAF -- `apply` Method

CAUTION: FIXME

=== [[distinct]] Creating Column for UDAF with Distinct Values -- `distinct` Method

CAUTION: FIXME
