== [[QueryPlanner]] `QueryPlanner` -- From Logical to Physical Plans

`QueryPlanner` transforms a link:spark-sql-LogicalPlan.adoc[logical query] through a chain of `GenericStrategy` objects to produce a  physical execution plan, i.e. link:spark-sql-SparkPlan.adoc[SparkPlan] for link:spark-sql-SparkPlanner.adoc[SparkPlanner] or the <<HiveSessionState, Hive-Specific SparkPlanner>>.

=== [[contract]] `QueryPlanner` Contract

`QueryPlanner` contract defines the following operations:

* Abstract <<strategies, strategies>>
* Concrete <<plan, plan>>
* Protected <<collectPlaceholders, collectPlaceholders>>
* Protected <<prunePlans, prunePlans>>

NOTE: Protected `collectPlaceholders` and `prunePlans` are supposed to be defined by subclasses and are used in the concrete `plan` method.

==== [[strategies]] `strategies` Method

[source, scala]
----
strategies: Seq[GenericStrategy[PhysicalPlan]]
----

`strategies` abstract method returns a collection of `GenericStrategy` objects (that are used in <<plan, plan>> method).

==== [[plan]] `plan` Method

[source, scala]
----
plan(plan: LogicalPlan): Iterator[PhysicalPlan]
----

`plan` returns an `Iterator[PhysicalPlan]` with elements being the result of applying each `GenericStrategy` object from <<strategies, strategies>> collection to `plan` input parameter.

==== [[collectPlaceholders]] `collectPlaceholders` Method

[source, scala]
----
collectPlaceholders(plan: PhysicalPlan): Seq[(PhysicalPlan, LogicalPlan)]
----

`collectPlaceholders` returns a collection of pairs of a given physical and a corresponding link:spark-sql-LogicalPlan.adoc[logical] plans.

==== [[prunePlans]] `prunePlans` Method

[source, scala]
----
prunePlans(plans: Iterator[PhysicalPlan]): Iterator[PhysicalPlan]
----

`prunePlans` prunes bad physical plans.

=== [[SparkStrategies]] `SparkStrategies` -- Container of `SparkStrategy` Strategies

`SparkStrategies` is an abstract base <<contract, QueryPlanner>> (of link:spark-sql-SparkPlan.adoc[SparkPlan]) that serves as a "container" (or a namespace) of the concrete `SparkStrategy` objects:

1. `SpecialLimits`
2. link:spark-sql-JoinSelection.adoc[JoinSelection]
3. `StatefulAggregationStrategy`
4. `Aggregation`
5. `InMemoryScans`
6. `StreamingRelationStrategy`
7. link:spark-sql-BasicOperators.adoc[BasicOperators]
8. link:spark-sql-DDLStrategy.adoc[DDLStrategy]

NOTE: `Strategy` is a type alias of `SparkStrategy` that is defined in https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/package.scala#L44[`org.apache.spark.sql` package object].

NOTE: link:spark-sql-SparkPlanner.adoc[SparkPlanner] is the one and only concrete implementation of `SparkStrategies`.

CAUTION: FIXME What is `singleRowRdd` for?

=== [[HiveSessionState]] Hive-Specific SparkPlanner for HiveSessionState

`HiveSessionState` class uses an custom anonymous  link:spark-sql-SparkPlanner.adoc[SparkPlanner] for `planner` method (part of the link:spark-sql-sessionstate.adoc[SessionState] contract).

The custom anonymous `SparkPlanner` uses `Strategy` objects defined in `HiveStrategies`.
