== [[ObjectHashAggregateExec]] ObjectHashAggregateExec Aggregate Physical Operator

`ObjectHashAggregateExec` is a link:spark-sql-SparkPlan.adoc#UnaryExecNode[unary physical operator] that is <<creating-instance, created>> (indirectly through link:spark-sql-SparkStrategy-Aggregation.adoc#AggUtils-createAggregate[AggUtils.createAggregate]) when:

* ...

CAUTION: FIXME

[[metrics]]
.ObjectHashAggregateExec's SQLMetrics
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `numOutputRows`
| number of output rows
|===

=== [[doExecute]] `doExecute` Method

CAUTION: FIXME

=== [[supportsAggregate]] `supportsAggregate` Method

[source, scala]
----
supportsAggregate(aggregateExpressions: Seq[AggregateExpression]): Boolean
----

`supportsAggregate` is enabled (i.e. returns `true`) if there is at least one `TypedImperativeAggregate` aggregate function in the input `aggregateExpressions` link:spark-sql-Expression-AggregateExpression.adoc[aggregate expressions].

NOTE: `supportsAggregate` is used exclusively when `AggUtils.createAggregate` link:spark-sql-SparkStrategy-Aggregation.adoc#AggUtils-createAggregate[selects an aggregate physical operator given aggregate expressions].

=== [[creating-instance]] Creating ObjectHashAggregateExec Instance

`ObjectHashAggregateExec` takes the following when created:

* [[requiredChildDistributionExpressions]] Required child distribution link:spark-sql-Expression.adoc[expressions]
* [[groupingExpressions]] Grouping link:spark-sql-Expression.adoc#NamedExpression[named expressions]
* [[aggregateExpressions]] link:spark-sql-Expression-AggregateExpression.adoc[Aggregate expressions]
* [[aggregateAttributes]] Aggregate link:spark-sql-Expression-Attribute.adoc[attributes]
* [[initialInputBufferOffset]] Initial input buffer offset
* [[resultExpressions]] Output link:spark-sql-Expression.adoc#NamedExpression[named expressions]
* [[child]] Child link:spark-sql-SparkPlan.adoc[physical operator]
