== [[WebUI]] WebUI -- Framework For Web UIs

`WebUI` is the <<contract, base>> of <<implementations, web UIs>> in Apache Spark:

* Active Spark applications

* Spark History Server

* Spark Standalone cluster manager

* Spark on Mesos cluster manager

NOTE: Spark on YARN uses a different web framework for the web UI.

[[contract]]
[source, scala]
----
package org.apache.spark.ui

abstract class WebUI {
  // only required methods that have no implementation
  // the others follow
  def initialize(): Unit
}
----

NOTE: `WebUI` is a `private[spark]` contract.

.(Subset of) WebUI Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `initialize`
a| [[initialize]] Used in <<implementations, implementations>> only to let them initialize their web components

NOTE: `initialize` does not add anything special to the Scala type hierarchy but a common name to use across `WebUIs` (that could also be possible without it). In other words, `initialize` does not participate in any design pattern or a type hierarchy.
|===

[[implementations]]
.WebUIs
[cols="1,2",options="header",width="100%"]
|===
| WebUI
| Description

| `HistoryServer`
| [[HistoryServer]] Used in Spark History Server

| `MasterWebUI`
| [[MasterWebUI]] Used in Spark Standalone cluster manager

| `MesosClusterUI`
| [[MesosClusterUI]] Used in Spark on Mesos cluster manager

| link:spark-webui-SparkUI.adoc[SparkUI]
| [[SparkUI]] `WebUI` of a Spark application

| `WorkerWebUI`
| [[WorkerWebUI]] Used in Spark Standalone cluster manager
|===

[[internal-registries]]
.WebUI's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `tabs`
| [[tabs]] link:spark-webui-WebUITab.adoc[WebUITabs]

Used when...FIXME

| `handlers`
| [[handlers]] `ServletContextHandlers`

Used when...FIXME

| `pageToHandlers`
| [[pageToHandlers]] `ServletContextHandlers` per link:spark-webui-WebUIPage.adoc[WebUIPage]

Used when...FIXME

| `serverInfo`
| [[serverInfo]] Optional `ServerInfo` (default: `None`)

Used when...FIXME

| `publicHostName`
| [[publicHostName]] Optional `ServerInfo` (default: `None`)

Used when...FIXME

| `className`
| [[className]]

Used when...FIXME
|===

=== [[creating-instance]] Creating WebUI Instance

`WebUI` takes the following when created:

* [[securityManager]] `SecurityManager`
* [[sslOptions]] `SSLOptions`
* [[port]] Port number
* [[conf]] link:spark-SparkConf.adoc[SparkConf]
* [[basePath]] `basePath` (default: empty)
* [[name]] Name (default: empty)

`WebUI` initializes the <<internal-registries, internal registries and counters>>.

NOTE: `WebUI` is a Scala abstract class and cannot be created directly, but only through <<implementations, implementations>>.

=== [[detachPage]] Detaching Page from UI -- `detachPage` Method

[source, scala]
----
detachPage(page: WebUIPage): Unit
----

`detachPage`...FIXME

NOTE: `detachPage` is used when...FIXME

=== [[detachTab]] Detaching Tab from UI -- `detachTab` Method

[source, scala]
----
detachTab(tab: WebUITab): Unit
----

`detachTab`...FIXME

NOTE: `detachTab` is used when...FIXME

=== [[attachPage]] Attaching WebUIPage -- `attachPage` Method

[source, scala]
----
attachPage(page: WebUIPage): Unit
----

Internally, `attachPage` creates the path of the link:spark-webui-WebUIPage.adoc[WebUIPage] that is `/` (forward slash) followed by the link:spark-webui-WebUIPage.adoc#prefix[prefix] of the page.

`attachPage` link:spark-webui-JettyUtils.adoc#createServletHandler[creates a HTTP request handler]...FIXME

[NOTE]
====
`attachPage` is used when:

* `WebUI` is requested to <<attachTab, attach a WebUITab>> (the link:spark-webui-WebUITab.adoc#pages[WebUIPages] actually)

* Spark `HistoryServer` is requested to `initialize`

* Spark Standalone's `MasterWebUI` and `WorkerWebUI` are requested to `initialize`

* Spark on Mesos' `MesosClusterUI` is requested to `initialize`
====

=== [[attachTab]] Attaching WebUITab and WebUIPages -- `attachTab` Method

[source, scala]
----
attachTab(tab: WebUITab): Unit
----

`attachTab` <<attachPage, attaches>> every `WebUIPage` of the input link:spark-webui-WebUITab.adoc#pages[WebUITab].

In the end, `attachTab` adds the input `WebUITab` to <<tabs, WebUITab tabs>>.

NOTE: `attachTab` is used when...FIXME

=== [[attachHandler]] Attaching ServletContextHandler -- `attachHandler` Method

[source, scala]
----
attachHandler(handler: ServletContextHandler): Unit
----

`attachHandler`...FIXME

NOTE: `attachHandler` is used when...FIXME
