== [[SchedulableBuilder]] Schedulable Builders

`SchedulableBuilder` is a <<contract, contract>> of <<implementations, schedulable builders>> that operate on a link:spark-taskscheduler-pool.adoc[Pool] (<<rootPool, rootPool>>) from link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl].

Schedulable builders can <<buildPools, build pools>> and <<addTaskSetManager, add new Schedulable entities to the pool>>.

A `SchedulableBuilder` is configured when <<initialize, TaskSchedulerImpl is being initialized>>.

NOTE: `SchedulableBuilder` is a `private[spark]` Scala trait. You can find the sources in https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/SchedulableBuilder.scala[org.apache.spark.scheduler.SchedulableBuilder].

=== [[contract]] SchedulableBuilder Contract

Every `SchedulableBuilder` provides the following services:

* It manages a <<rootPool, root pool>>.

* It can <<buildPools, build pools>>.

* It can <<addTaskSetManager, add a Schedulable with properties>>.

=== [[rootPool]] Root Pool (rootPool method)

[source, scala]
----
rootPool: Pool
----

`rootPool` link:spark-taskscheduler-pool.adoc[Pool] (of link:spark-taskscheduler-schedulable.adoc[Schedulables])

=== [[buildPools]] Build Pools (buildPools method)

[source, scala]
----
buildPools(): Unit
----

=== [[addTaskSetManager]] Add Schedulable (addTaskSetManager method)

[source, scala]
----
addTaskSetManager(manager: Schedulable, properties: Properties): Unit
----

`addTaskSetManager` registers the `manager` link:spark-taskscheduler-schedulable.adoc[Schedulable] with additional `properties`.

NOTE: `addTaskSetManager` is used by link:spark-taskschedulerimpl.adoc#submitTasks[TaskSchedulerImpl to submit a task set for a stage for execution].

=== [[implementations]] Schedulable Builders

There are currently two types of `Schedulable` entities:

There are currently two implementations of the <<contract, SchedulableBuilder Contract>>:

* <<FIFOSchedulableBuilder, FIFOSchedulableBuilder>> - the default `SchedulableBuilder`
* <<FairSchedulableBuilder, FairSchedulableBuilder>>

=== [[FIFOSchedulableBuilder]] FIFOSchedulableBuilder

`FIFOSchedulableBuilder` is a `SchedulableBuilder` that is a _mere_ wrapper around a single link:spark-taskscheduler-pool.adoc[Pool] (the only constructor parameter).

NOTE: `FIFOSchedulableBuilder` is the default `SchedulableBuilder` for `TaskSchedulerImpl` (see link:spark-taskschedulerimpl.adoc#creating-instance[Creating TaskSchedulerImpl]).

NOTE: When `FIFOSchedulableBuilder` is created, the `TaskSchedulerImpl` passes its own `rootPool` (that belongs to the link:spark-taskscheduler.adoc#contract[TaskScheduler Contract] that `TaskSchedulerImpl` follows).

`FIFOSchedulableBuilder` obeys the <<contract, SchedulableBuilder Contract>> as follows:

* <<buildPools, buildPools>> does nothing.

* `addTaskSetManager` merely link:spark-taskscheduler-pool.adoc#addSchedulable[passes the input `Schedulable` to rootPool (using `addSchedulable`)].

=== [[FairSchedulableBuilder]] FairSchedulableBuilder

CAUTION: FIXME
