== [[ParserInterface]] ParserInterface -- SQL Parser Contract

`ParserInterface` is the <<contract, parser contract>> for creating `Expression` (to create link:spark-sql-Column.adoc[Columns] from), link:spark-sql-LogicalPlan.adoc[LogicalPlan], `TableIdentifier`, and link:spark-sql-StructType.adoc[StructType] for a given SQL textual representation.

NOTE: The one and only `ParserInterface` in Spark SQL is link:spark-sql-AbstractSqlParser.adoc[AbstractSqlParser].

`ParserInterface` is available as `sqlParser` in link:spark-sql-SessionState.adoc#sqlParser[SessionState].

[source, scala]
----
val spark: org.apache.spark.sql.SparkSession = ...
spark.sessionState.sqlParser
----

=== [[contract]] ParserInterface Contract

[source, scala]
----
package org.apache.spark.sql.catalyst.parser

trait ParserInterface {
  def parseExpression(sqlText: String): Expression
  def parsePlan(sqlText: String): LogicalPlan
  def parseTableIdentifier(sqlText: String): TableIdentifier
  def parseTableSchema(sqlText: String): StructType
}
----

.ParserInterface Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[parseExpression]] `parseExpression`
| Used when...

| [[parsePlan]] `parsePlan`
a| Used mainly when `SparkSession` is requested to link:spark-sql-SparkSession.adoc#sql[execute a SQL query] using `sql` method.

```
scala> :type spark
org.apache.spark.sql.SparkSession

scala> spark.sql("show databases").show
+------------+
\|databaseName\|
+------------+
\|     default\|
+------------+
```

| [[parseTableIdentifier]] `parseTableIdentifier`
| Used when...

| [[parseTableSchema]] `parseTableSchema`
| Used when...
|===

It has the only single abstract subclass link:spark-sql-AbstractSqlParser.adoc[AbstractSqlParser].
