== Joins

CAUTION: FIXME

=== [[broadcast-join]] Broadcast Join (aka Map-Side Join)

CAUTION: FIXME: Review `BroadcastNestedLoop`.

You can use link:spark-sql-functions.adoc#broadcast[broadcast] function to mark a link:spark-sql-dataset.adoc[Dataset] to be broadcast when used in a `join` operator.

NOTE: According to the article http://dmtolpeko.com/2015/02/20/map-side-join-in-spark/[Map-Side Join in Spark], *broadcast join* is also called a *replicated join* (in the distributed system community) or a *map-side join* (in the Hadoop community).

NOTE: At long last! I have always been wondering what a map-side join is and it appears I am close to uncover the truth!

And later in the article http://dmtolpeko.com/2015/02/20/map-side-join-in-spark/[Map-Side Join in Spark], you can find that with the broadcast join, you can very effectively join a large table (fact) with relatively small tables (dimensions), i.e. to perform a *star-schema join* you can avoid sending all data of the large table over the network.

`CanBroadcast` object matches a link:spark-sql-catalyst-LogicalPlan.adoc[LogicalPlan] with output small enough for broadcast join.

NOTE: Currently statistics are only supported for Hive Metastore tables where the command `ANALYZE TABLE [tableName] COMPUTE STATISTICS noscan` has been run.

It uses link:spark-sql-settings.adoc#autoBroadcastJoinThreshold[spark.sql.autoBroadcastJoinThreshold] setting to control the size of a table that will be broadcast to all worker nodes when performing a join.
