== [[GenerateUnsafeProjection]] GenerateUnsafeProjection

`GenerateUnsafeProjection` is a link:spark-sql-CodeGenerator.adoc[CodeGenerator] for converting link:spark-sql-Expression.adoc[Catalyst expressions] to link:spark-sql-UnsafeProjection.adoc[UnsafeProjection].

[source, scala]
----
GenerateUnsafeProjection: Seq[Expression] => UnsafeProjection
----

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.GenerateUnsafeProjection=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[createCode]] Creating ExprCode for Catalyst Expressions -- `createCode` Method

CAUTION: FIXME

=== [[generate]] `generate` Method

[source, scala]
----
generate(
  expressions: Seq[Expression],
  subexpressionEliminationEnabled: Boolean): UnsafeProjection
----

`generate` <<create, creates>> a link:spark-sql-UnsafeProjection.adoc[UnsafeProjection] with `expressions` <<canonicalize, canonicalized>>.

NOTE: `generate` is used when `UnsafeProjection` factory object link:spark-sql-UnsafeProjection.adoc#create[creates a `UnsafeProjection`].

=== [[canonicalize]] `canonicalize` Method

[source, scala]
----
canonicalize(in: Seq[Expression]): Seq[Expression]
----

`canonicalize` removes unnecessary `Alias` expressions.

Internally, `canonicalize` uses `ExpressionCanonicalizer` rule executor (that in turn uses just one `CleanExpressions` expression rule).

=== [[create]] `create` Method

[source, scala]
----
create(
  expressions: Seq[Expression],
  subexpressionEliminationEnabled: Boolean): UnsafeProjection
create(references: Seq[Expression]): UnsafeProjection // <1>
----
<1> Calls the former `create` with `subexpressionEliminationEnabled` disabled

`create` first creates a link:spark-sql-CodeGenerator.adoc#newCodeGenContext[CodegenContext] and an <<createCode, ExprCode>> for the input `expressions` that is converted to a Java source code (as `CodeAndComment`).

You should see the following DEBUG message in the logs:

```
DEBUG GenerateUnsafeProjection: code for [expressions]:
[code]
```

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator` logger to see the message above.

```
log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator=DEBUG
```

See link:spark-sql-CodeGenerator.adoc#logging[CodeGenerator].
====

`create` requests `CodeGenerator` to link:spark-sql-CodeGenerator.adoc#compile[compile the Java source code into a GeneratedClass].

You should see the following INFO message in the logs:

```
INFO CodeGenerator: Code generated in [time] ms
```

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator` logger to see the message above.

```
log4j.logger.org.apache.spark.sql.catalyst.expressions.codegen.CodeGenerator=INFO
```

See link:spark-sql-CodeGenerator.adoc#logging[CodeGenerator].
====

`create` passes references into the `GeneratedClass` that eventually becomes the final link:spark-sql-UnsafeProjection.adoc[UnsafeProjection].

NOTE: (Single-argument) `create` is a part of link:spark-sql-CodeGenerator.adoc#create[CodeGenerator Contract].
