== [[GenerateUnsafeProjection]] GenerateUnsafeProjection

`GenerateUnsafeProjection` is a link:spark-sql-CodeGenerator.adoc[CodeGenerator] function object that converts a link:spark-sql-Expression.adoc[Expression] collection to link:spark-sql-UnsafeProjection.adoc[UnsafeProjection].

[source, scala]
----
GenerateUnsafeProjection: Seq[Expression] => UnsafeProjection
----

=== [[create]] `create` Internal Method

[source, scala]
----
create(
  expressions: Seq[Expression],
  subexpressionEliminationEnabled: Boolean): UnsafeProjection
----

CAUTION: FIXME

=== [[generate]] `generate` Method

[source, scala]
----
generate(
  expressions: Seq[Expression],
  subexpressionEliminationEnabled: Boolean): UnsafeProjection
----

`generate` <<create, creates>> a link:spark-sql-UnsafeProjection.adoc[UnsafeProjection] with `expressions` <<canonicalize, canonicalized>>.

NOTE: `generate` is used when `UnsafeProjection` factory object link:spark-sql-UnsafeProjection.adoc#create[creates a `UnsafeProjection`].

=== [[canonicalize]] `canonicalize` Method

[source, scala]
----
canonicalize(in: Seq[Expression]): Seq[Expression]
----

`canonicalize` removes unnecessary `Alias` expressions.

Internally, `canonicalize` uses `ExpressionCanonicalizer` rule executor (that in turn uses just one `CleanExpressions` expression rule).
