== [[QueryPlanner]] QueryPlanner -- Transforming Trees

`QueryPlanner` transforms a link:spark-sql-LogicalPlan.adoc[logical query] through a chain of link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] transformations to produce a link:spark-sql-SparkPlan.adoc[physical plan] for link:spark-sql-SparkPlanner.adoc[SparkPlanner] or the link:spark-sql-HiveSessionState.adoc[Hive-specific SparkPlanner].

=== [[contract]] QueryPlanner Contract

`QueryPlanner` contract defines the following operations:

* Abstract <<strategies, strategies>>
* Concrete <<plan, plan>>
* Protected <<collectPlaceholders, collectPlaceholders>>
* Protected <<prunePlans, prunePlans>>

NOTE: Protected `collectPlaceholders` and `prunePlans` are supposed to be defined by subclasses and are used in the concrete `plan` method.

==== [[strategies]] `strategies` Method

[source, scala]
----
strategies: Seq[GenericStrategy[PhysicalPlan]]
----

`strategies` abstract method returns a collection of link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] transformations (that are used in <<plan, plan>> method).

==== [[plan]] `plan` Method

[source, scala]
----
plan(plan: LogicalPlan): Iterator[PhysicalPlan]
----

`plan` returns an `Iterator[PhysicalPlan]` with elements being the result of applying each link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] transformation from <<strategies, strategies>> collection to `plan` input parameter.

==== [[collectPlaceholders]] `collectPlaceholders` Method

[source, scala]
----
collectPlaceholders(plan: PhysicalPlan): Seq[(PhysicalPlan, LogicalPlan)]
----

`collectPlaceholders` returns a collection of pairs of a given physical and a corresponding link:spark-sql-LogicalPlan.adoc[logical] plans.

==== [[prunePlans]] `prunePlans` Method

[source, scala]
----
prunePlans(plans: Iterator[PhysicalPlan]): Iterator[PhysicalPlan]
----

`prunePlans` prunes bad physical plans.

=== [[SparkStrategies]] SparkStrategies -- Container of SparkStrategy Strategies

`SparkStrategies` is an abstract base <<contract, QueryPlanner>> (of link:spark-sql-SparkPlan.adoc[SparkPlan]) that serves as a "container" (or a namespace) of the concrete link:spark-sql-SparkStrategy.adoc[SparkStrategies]:

. `SpecialLimits`
. link:spark-sql-SparkStrategy-JoinSelection.adoc[JoinSelection]
. `StatefulAggregationStrategy`
. link:spark-sql-SparkStrategy-Aggregation.adoc[Aggregation]
. `InMemoryScans`
. `StreamingRelationStrategy`
. link:spark-sql-SparkStrategy-BasicOperators.adoc[BasicOperators]
. link:spark-sql-SparkStrategy-DDLStrategy.adoc[DDLStrategy]

NOTE: link:spark-sql-SparkPlanner.adoc[SparkPlanner] is the one and only concrete implementation of `SparkStrategies`.

CAUTION: FIXME What is `singleRowRdd` for?
