== [[QueryPlanner]] QueryPlanner -- Transforming Trees

`QueryPlanner` converts a link:spark-sql-LogicalPlan.adoc[logical plan] to a link:spark-sql-SparkPlan.adoc[physical plan] using link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] transformations.

=== [[contract]] QueryPlanner Contract

[source, scala]
----
abstract class QueryPlanner[PhysicalPlan <: TreeNode[PhysicalPlan]] {
  def collectPlaceholders(plan: PhysicalPlan): Seq[(PhysicalPlan, LogicalPlan)]
  def prunePlans(plans: Iterator[PhysicalPlan]): Iterator[PhysicalPlan]
}
----

.QueryPlanner Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| <<strategies, strategies>>
|

| <<plan, plan>>
|

| [[collectPlaceholders]] `collectPlaceholders`
| Collection of "placeholder" physical plans and the corresponding link:spark-sql-LogicalPlan.adoc[logical plans].

Used exclusively in <<plan, plan>>.

Overriden in link:spark-sql-SparkPlanner.adoc#collectPlaceholders[SparkPlanner]

| [[prunePlans]] `prunePlans`
| Prunes physical plans (e.g. bad or somehow incorrect plans).

Used exclusively in <<plan, plan>>.
|===

==== [[strategies]] `strategies` Method

[source, scala]
----
strategies: Seq[GenericStrategy[PhysicalPlan]]
----

`strategies` abstract method returns a collection of link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] transformations (that are used in <<plan, plan>> method).

==== [[plan]] `plan` Method

[source, scala]
----
plan(plan: LogicalPlan): Iterator[PhysicalPlan]
----

`plan` returns an `Iterator[PhysicalPlan]` with elements being the result of applying each link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] transformation from <<strategies, strategies>> collection to `plan` input parameter.

=== [[SparkStrategies]] SparkStrategies -- Container of SparkStrategy Strategies

`SparkStrategies` is an abstract base <<contract, QueryPlanner>> (of link:spark-sql-SparkPlan.adoc[SparkPlan]) that serves as a "container" (or a namespace) of the concrete link:spark-sql-SparkStrategy.adoc[SparkStrategies]:

. `SpecialLimits`
. link:spark-sql-SparkStrategy-JoinSelection.adoc[JoinSelection]
. `StatefulAggregationStrategy`
. link:spark-sql-SparkStrategy-Aggregation.adoc[Aggregation]
. `InMemoryScans`
. `StreamingRelationStrategy`
. link:spark-sql-SparkStrategy-BasicOperators.adoc[BasicOperators]

NOTE: link:spark-sql-SparkPlanner.adoc[SparkPlanner] is the one and only concrete implementation of `SparkStrategies`.

CAUTION: FIXME What is `singleRowRdd` for?
