== [[Aggregation]] Aggregation Execution Planning Strategy

`Aggregation` is an link:spark-sql-SparkStrategy.adoc[execution planning strategy] (of link:spark-sql-SparkPlanner.adoc[SparkPlanner]) that...FIXME

=== [[apply]] Executing Strategy -- `apply` Method

[source, scala]
----
apply(plan: LogicalPlan): Seq[SparkPlan]
----

`apply`

NOTE: `apply` is a part of link:spark-sql-catalyst-GenericStrategy.adoc#apply[GenericStrategy Contract].

=== [[PhysicalAggregation]][[PhysicalAggregation-unapply]] `PhysicalAggregation.unapply` Method

[source, scala]
----
unapply(a: Any): Option[ReturnType]
----

`unapply` destructures a link:spark-sql-LogicalPlan.adoc[logical plan], i.e. breaks a `LogicalPlan` into pieces.

[NOTE]
====

`ReturnType` is a type alias (aka _type synonym_) for a 4-element tuple with grouping, aggregate and result link:spark-sql-catalyst-Expression.adoc[expressions], and child link:spark-sql-LogicalPlan.adoc[logical operator].

[source, scala]
----
type ReturnType =
  (Seq[NamedExpression], Seq[AggregateExpression], Seq[NamedExpression], LogicalPlan)
----
====

NOTE: `PhysicalAggregation` is a Scala http://docs.scala-lang.org/tutorials/tour/extractor-objects.html[extractor object] with a single <<PhysicalAggregation-unapply, unapply>> method.

=== [[AggUtils]][[AggUtils-planAggregateWithoutDistinct]] `AggUtils.planAggregateWithoutDistinct` Method

=== [[AggUtils-planAggregateWithOneDistinct]] `AggUtils.planAggregateWithOneDistinct` Method

=== [[AggUtils-createAggregate]] Creating Physical Operator Given Aggregate Expressions -- `AggUtils.createAggregate` Internal Method

[source, scala]
----
createAggregate(
  requiredChildDistributionExpressions: Option[Seq[Expression]] = None,
  groupingExpressions: Seq[NamedExpression] = Nil,
  aggregateExpressions: Seq[AggregateExpression] = Nil,
  aggregateAttributes: Seq[Attribute] = Nil,
  initialInputBufferOffset: Int = 0,
  resultExpressions: Seq[NamedExpression] = Nil,
  child: SparkPlan): SparkPlan
----

`createAggregate` creates a link:spark-sql-SparkPlan.adoc[physical operator] given the input `aggregateExpressions`.

.createAggregate and Selecting Physical Operator (in execution order)
[cols="1,2",options="header",width="100%"]
|===
| Operator
| Conditions (for selection)

| link:spark-sql-SparkPlan-HashAggregateExec.adoc[HashAggregateExec]
a| Builds a schema from link:spark-sql-Expression-AggregateFunction.adoc#aggBufferAttributes[aggBufferAttributes] (of every `AggregateFunction`) of every link:spark-sql-Expression-AggregateExpression.adoc[AggregateExpression] (in the input `aggregateExpressions`) and checks for any non-mutable fields (that _cannot_ be updated in place in `UnsafeRows`). When not found, `HashAggregateExec` is selected.

Mutable field types include:

* `NullType`
* `BooleanType`
* `ByteType`
* `ShortType`
* `IntegerType`
* `LongType`
* `FloatType`
* `DoubleType`
* `DateType`
* `TimestampType`
* `DecimalType`

| `ObjectHashAggregateExec`
| When link:spark-sql-SQLConf.adoc#spark.sql.execution.useObjectHashAggregateExec[spark.sql.execution.useObjectHashAggregateExec] intenal flag enabled (it is by default) and `aggregateExpressions` contains at least one `TypedImperativeAggregate`.

| `SortAggregateExec`
| When all the above conditions fail.
|===

NOTE: `createAggregate` is used in <<AggUtils-planAggregateWithoutDistinct, AggUtils.planAggregateWithoutDistinct>>, <<AggUtils-planAggregateWithOneDistinct, AggUtils.planAggregateWithOneDistinct>> and `planStreamingAggregation` (for Structured Streaming's `StatefulAggregationStrategy`).
