== [[BlockManagerSource]] BlockManagerSource -- Metrics Source for BlockManager

`BlockManagerSource` is the metrics link:spark-metrics-Source.adoc[Source] for link:spark-blockmanager.adoc[BlockManager].

`BlockManagerSource` is registered under the name *BlockManager* (when link:spark-sparkcontext-creating-instance-internals.adoc#registerSource[`SparkContext` is created]).

[[metrics]]
.BlockManagerSource's Metrics
[width="100%",cols="1,1,2",options="header"]
|===
| Name
| Type
| Description

| `memory.maxMem_MB`
| long
| Requests `BlockManagerMaster` for link:spark-BlockManagerMaster.adoc#getStorageStatus[storage status] (for every link:spark-blockmanager.adoc[BlockManager]) and sums up their maximum memory limit.

| `memory.remainingMem_MB`
| long
| Requests `BlockManagerMaster` for link:spark-BlockManagerMaster.adoc#getStorageStatus[storage status] (for every link:spark-blockmanager.adoc[BlockManager]) and sums up their memory remaining.

| `memory.memUsed_MB`
| long
| Requests `BlockManagerMaster` for link:spark-BlockManagerMaster.adoc#getStorageStatus[storage status] (for every link:spark-blockmanager.adoc[BlockManager]) and sums up their memory used.

| `disk.diskSpaceUsed_MB`
| long
| Requests `BlockManagerMaster` for link:spark-BlockManagerMaster.adoc#getStorageStatus[storage status] (for every link:spark-blockmanager.adoc[BlockManager]) and sums up their disk space used.
|===

You can access the `BlockManagerSource` <<metrics, metrics>> using the web UI's port (as link:spark-webui.adoc#spark.ui.port[spark.ui.port] property).

```
$ http --follow http://localhost:4040/metrics/json \
  | jq '.gauges | keys | .[] | select(test(".driver.BlockManager"; "g"))'
"local-1488272192549.driver.BlockManager.disk.diskSpaceUsed_MB"
"local-1488272192549.driver.BlockManager.memory.maxMem_MB"
"local-1488272192549.driver.BlockManager.memory.memUsed_MB"
"local-1488272192549.driver.BlockManager.memory.remainingMem_MB"
```
