== [[Expression]] Expression -- Executable Node in Catalyst Tree

`Expression` is a link:spark-sql-catalyst-TreeNode.adoc[node] (in a Catalyst tree) that represents a computation that can be <<eval, evaluated>> to a value given input values, i.e. can produce JVM objects for every `InternalRow` (in a link:spark-sql-Dataset.adoc[Dataset]).

[[specialized-expressions]]
.Specialized Expressions
[cols="1,2,2,1",options="header",width="100%"]
|===
| Name
| Scala Kind
| Behaviour
| Examples

| [[BinaryExpression]] `BinaryExpression`
| abstract class
|
|

| [[CodegenFallback]] `CodegenFallback`
| trait
|
|

| [[ExpectsInputTypes]] `ExpectsInputTypes`
| trait
|
|

| [[LeafExpression]] `LeafExpression`
| abstract class
|  Has no children, i.e. `children` method returns always an empty collection.
|

| [[NamedExpression]] `NamedExpression`
|
| Can later be referenced in a dataflow graph.
|

| <<Nondeterministic, Nondeterministic>>
| trait
|
|

| [[NonSQLExpression]] `NonSQLExpression`
| trait
| Expression with no SQL representation

Gives the only custom <<sql, sql>> method that is non-overridable (i.e. `final`).

When requested <<sql, SQL representation>>, `NonSQLExpression` transforms link:spark-sql-Expression-Attribute.adoc[Attributes] to be ``PrettyAttribute``s to build text representation.
| link:spark-sql-Expression-ImperativeAggregate-ScalaUDAF.adoc[ScalaUDAF]

| [[TernaryExpression]] `TernaryExpression`
| abstract class
|
|

| [[TimeZoneAwareExpression]] `TimeZoneAwareExpression`
| trait
| Timezone-aware expressions
| link:spark-sql-Expression-UnixTimestamp.adoc[UnixTimestamp]

| [[UnaryExpression]] `UnaryExpression`
| abstract class
|
|

| [[Unevaluable]] `Unevaluable`
| trait
| Cannot be evaluated, i.e. `eval` and `doGenCode` are not supported and immediately report an `UnsupportedOperationException`.

Expressions that are replaced by some other expressions during analysis or optimization.

a|

* `CurrentDatabase`
* link:spark-sql-Expression-WindowExpression.adoc[WindowExpression]
|===

=== [[contract]] Expression Contract

[source, scala]
----
abstract class Expression extends TreeNode[Expression] {
  // only required methods with no implementation
  def nullable: Boolean
  def eval(input: InternalRow = null): Any
  def doGenCode(ctx: CodegenContext, ev: ExprCode): ExprCode
  def dataType: DataType
}
----

.(Subset of) Expression Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[foldable]] `foldable`
|

| [[deterministic]] `deterministic`
|

| [[nullable]] `nullable`
|

| [[references]] `references`
|

| [[eval]] `eval`
| Evaluates an expression to a JVM object for a link:spark-sql-InternalRow.adoc[InternalRow]

| [[genCode]] `genCode`
|

| [[doGenCode]] `doGenCode`
|

| [[resolved]] `resolved`
|

| [[dataType]] `dataType`
|

| [[childrenResolved]] `childrenResolved`
|

| [[canonicalized]] `canonicalized`
|

| [[semanticEquals]] `semanticEquals`
|

| [[semanticHash]] `semanticHash`
|

| [[checkInputDataTypes]] `checkInputDataTypes`
|

| [[prettyName]] `prettyName`
|

| [[sql]] `sql`
a| SQL representation

<<prettyName, prettyName>> followed by `sql` of <<children, children>> in the round brackets and concatenated using the comma (`,`), e.g.

```
import org.apache.spark.sql.catalyst.dsl.expressions._
import org.apache.spark.sql.catalyst.expressions.Sentences
val sentences = Sentences("Hi there! Good morning.", "en", "US")

import org.apache.spark.sql.catalyst.expressions.Expression
val expr: Expression = count("*") === 5 && count(sentences) === 5
scala> expr.sql
res0: String = ((count('*') = 5) AND (count(sentences('Hi there! Good morning.', 'en', 'US')) = 5))
```

|===

=== [[Nondeterministic]] `Nondeterministic` Expression

`Nondeterministic` expressions are non-deterministic and non-<<foldable, foldable>>, i.e. `deterministic` and `foldable` properties are disabled (i.e. `false`). They require explicit initialization before evaluation.

`Nondeterministic` expressions have two additional methods:

1. `initInternal` for internal initialization (called before `eval`)
2. `evalInternal` to ``eval``uate a link:spark-sql-InternalRow.adoc[InternalRow] into a JVM object.

NOTE: `Nondeterministic` is a Scala trait.

`Nondeterministic` expressions have the additional `initialized` flag that is enabled (i.e. `true`) after the other additional `initInternal` method has been called.

Examples of `Nondeterministic` expressions are `InputFileName`, `MonotonicallyIncreasingID`, `SparkPartitionID` functions and the abstract `RDG` (that is the base for `Rand` and `Randn` functions).

NOTE: `Nondeterministic` expressions are the target of `PullOutNondeterministic` logical plan rule.
