== [[NettyBlockTransferService]] `NettyBlockTransferService` -- Netty-Based BlockTransferService

`NettyBlockTransferService` is a link:spark-blocktransferservice.adoc[BlockTransferService] that uses Netty for block transport (when <<uploadBlock, uploading>> or <<fetchBlocks, fetching blocks>>).

NOTE: `NettyBlockTransferService` is created when link:spark-sparkenv.adoc#NettyBlockTransferService[`SparkEnv` is created] (and later passed on to create a link:spark-blockmanager.adoc#creating-instance[BlockManager] per driver and executors).

[TIP]
====
Enable `INFO` or `TRACE` logging level for `org.apache.spark.network.netty.NettyBlockTransferService` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.network.netty.NettyBlockTransferService=TRACE
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[creating-instance]] Creating `NettyBlockTransferService` Instance

=== [[uploadBlock]] `uploadBlock` Method

[source, scala]
----
uploadBlock(
  hostname: String,
  port: Int,
  execId: String,
  blockId: BlockId,
  blockData: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Future[Unit]
----

`uploadBlock` creates a `TransportClient` client to send a `UploadBlock` message. The message contains the <<appId, application id>>, `execId`, and `blockId` with `blockData`, `level` and `classTag` serialized.

CAUTION: FIXME Describe `TransportClient` and `UploadBlock`.

When `blockId` block was successfully uploaded, you should see the following TRACE message in the logs:

```
TRACE NettyBlockTransferService: Successfully uploaded block [blockId]
```

When an upload failed, you should see the following ERROR message in the logs:

```
ERROR Error while uploading block [blockId]
```

NOTE: `uploadBlock` is executed when link:spark-blocktransferservice.adoc#uploadBlockSync[`BlockTransferService` does block upload in blocking way] (which simply allows for custom block upload in a link:spark-blocktransferservice.adoc[BlockTransferService]).

=== [[fetchBlocks]] `fetchBlocks` Method

=== [[appId]] Application Id -- `appId` Property
