== [[BlockDataManager]] BlockDataManager -- Block Storage Management API

`BlockDataManager` is a pluggable <<contract, interface>> to manage storage for blocks of data (aka _block storage management API_). Blocks are identified by `BlockId` that has a globally unique identifier (`name`) and stored as <<ManagedBuffer, ManagedBuffer>>.

[[BlockId]]
.Types of BlockIds
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| [[RDDBlockId]] RDDBlockId
| Described by `rddId` and `splitIndex`

Created when a `RDD` is requested to link:spark-rdd.adoc#getOrCompute[`getOrCompute` a partition] (identified by `splitIndex`).

| [[ShuffleBlockId]] `ShuffleBlockId`
| Described by `shuffleId`, `mapId` and `reduceId`

| [[ShuffleDataBlockId]] ShuffleDataBlockId
| Described by `shuffleId`, `mapId` and `reduceId`

| [[ShuffleIndexBlockId]] ShuffleIndexBlockId
| Described by `shuffleId`, `mapId` and `reduceId`

| [[BroadcastBlockId]] `BroadcastBlockId`
| Described by `broadcastId` identifier and optional `field`

| [[TaskResultBlockId]] TaskResultBlockId
| Described by `taskId`

| [[StreamBlockId]] StreamBlockId
| Described by `streamId` and `uniqueId`
|===

NOTE: link:spark-blockmanager.adoc[BlockManager] is currently the only available implementation of `BlockDataManager`.

NOTE: `org.apache.spark.network.BlockDataManager` is a `private[spark]` Scala trait in Spark.

=== [[contract]][[getBlockData]][[putBlockData]] `BlockDataManager` Contract

Every `BlockDataManager` offers the following services:

* `getBlockData` to fetch a local block data by `blockId`.
+
[source, scala]
----
getBlockData(blockId: BlockId): ManagedBuffer
----

* `putBlockData` to upload a block data locally by `blockId`. The return value says whether the operation has succeeded (`true`) or failed (`false`).
+
[source, scala]
----
putBlockData(
  blockId: BlockId,
  data: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Boolean
----

* `releaseLock` is a release lock for `getBlockData` and `putBlockData` operations.
+
[source, scala]
----
releaseLock(blockId: BlockId): Unit
----

=== [[ManagedBuffer]] ManagedBuffer
