== [[CallMethodViaReflection]] CallMethodViaReflection Expression

`CallMethodViaReflection` is an link:spark-sql-Expression.adoc[expression] that represents a static method call in Scala or Java using `reflect` and `java_method` functions.

NOTE: `reflect` and `java_method` functions are only supported in link:spark-sql-SparkSession.adoc#sql[SQL] and link:spark-sql-dataset-operators.adoc#selectExpr[expression] modes.

[[properties]]
.CallMethodViaReflection's Properties (in alphabetical order)
[width="100%",cols="1,2",options="header"]
|===
| Property
| Description

| [[dataType]] `dataType`
| `StringType`

| [[deterministic]] `deterministic`
| Disabled (i.e. `false`)

| [[nullable]] `nullable`
| Enabled (i.e. `true`)

| [[prettyName]] `prettyName`
| `reflect`
|===

[source, scala]
----
val q = """
  select reflect("java.time.LocalDateTime", "now") as now
  """
val plan = spark.sql(q).queryExecution.logical
// CallMethodViaReflection shows itself under "reflect" name
scala> println(plan.numberedTreeString)
00 Project [reflect(java.time.LocalDateTime, now) AS now#39]
01 +- OneRowRelation$

import org.apache.spark.sql.catalyst.expressions.CallMethodViaReflection
val className = "java.time.LocalDateTime"
val methodName = "now"
import org.apache.spark.sql.catalyst.expressions.Literal
scala> val expr = CallMethodViaReflection(
     |   Literal(className) ::
     |   Literal(methodName) :: Nil)
expr: org.apache.spark.sql.catalyst.expressions.CallMethodViaReflection = reflect(java.time.LocalDateTime, now)
----

`CallMethodViaReflection` supports a link:spark-sql-Expression.adoc#CodegenFallback[fallback mode for expression code generation].

NOTE: `CallMethodViaReflection` is very similar to link:spark-sql-Expression-StaticInvoke.adoc[StaticInvoke] expression.
