== [[SchedulableBuilder]] SchedulableBuilders

CAUTION: FIXME

`SchedulableBuilder` offers the following methods:

* `rootPool` to return a link:spark-taskscheduler-pool.adoc[Pool].
* <<buildPools, buildPools>>
* `addTaskSetManager(manager: Schedulable, properties: Properties)`

NOTE: `SchedulableBuilder.addTaskSetManager` is called by <<submitTasks, TaskSchedulerImpl.submitTasks>> when a TaskSet is submitted for execution.

There are two implementations available (click the links to go to their sections):

* <<FIFOSchedulableBuilder, FIFOSchedulableBuilder>>
* <<FairSchedulableBuilder, FairSchedulableBuilder>>

=== [[buildPools]] buildPools

CAUTION: FIXME

=== [[FIFOSchedulableBuilder]] FIFOSchedulableBuilder

`FIFOSchedulableBuilder` is a _very basic_ `SchedulableBuilder`.

* `rootPool` is given as a mandatory input parameter to the constructor.

* <<buildPools, buildPools>> does nothing.

* `addTaskSetManager(manager: Schedulable, properties: Properties)` adds the `manager` Schedulable to `rootPool` (using `Pool.addSchedulable`).

=== [[FairSchedulableBuilder]] FairSchedulableBuilder

CAUTION: FIXME
