== RowEncoder -- DataFrame Encoder

`RowEncoder` is a part of the link:spark-sql-Encoder.adoc[Encoder framework] and is the encoder for link:spark-sql-dataframe.adoc[DataFrames] that are link:spark-sql-dataset.adoc[Datasets] of link:spark-sql-dataframe-row.adoc[Rows].

TIP: `RowEncoder` is an `object` in Scala with <<apply, apply>> and other factory methods.

`RowEncoder` object can create link:spark-sql-Encoder.adoc#ExpressionEncoder[ExpressionEncoder] of link:spark-sql-dataframe-row.adoc[Row], i.e. `ExpressionEncoder[Row]`, from a link:spark-sql-schema.adoc#StructType[schema] (using <<apply, apply method>>).

[source, scala]
----
import org.apache.spark.sql.types._
val schema = StructType(
  StructField("id", LongType, nullable = false) ::
  StructField("name", StringType, nullable = false) :: Nil)

import org.apache.spark.sql.catalyst.encoders.RowEncoder
scala> val encoder = RowEncoder(schema)
encoder: org.apache.spark.sql.catalyst.encoders.ExpressionEncoder[org.apache.spark.sql.Row] = class[id[0]: bigint, name[0]: string]
----

`RowEncoder` belongs to `org.apache.spark.sql.catalyst.encoders` package.

=== [[apply]] Creating ExpressionEncoder of Rows -- `apply` method

[source, scala]
----
apply(schema: StructType): ExpressionEncoder[Row]
----

`apply` builds `ExpressionEncoder[Row]` from the input link:spark-sql-schema.adoc[StructType] (as `schema`).

Internally, `apply` creates a `BoundReference` for the link:spark-sql-dataframe-row.adoc[Row] type and returns a `ExpressionEncoder[Row]` for the input `schema`, a `CreateNamedStruct` serializer, a deserializer for the schema, and the `Row` type.
