== [[ExecutorsListener]] ExecutorsListener Spark Listener

=== [[onTaskEnd]] `onTaskEnd` Method

[source, scala]
----
onTaskEnd(taskEnd: SparkListenerTaskEnd): Unit
----

`onTaskEnd` works with the `TaskInfo` from the input `taskEnd` if available.

NOTE: `onTaskEnd` is a part of link:spark-SparkListener.adoc[SparkListener] API.

`onTaskEnd` manages executor summaries in the internal `executorToTaskSummary` collection of executor ids and their executor summaries.

If the `TaskMetrics` (in the input `taskEnd`) is available, the metrics are added to the `taskSummary` for the task's executor.

.Task Metrics and Task Summary
[frame="topbot",cols="1,2",options="header",width="100%"]
|======================
| Task Summary | Task Metric
| `inputBytes` | `inputMetrics.bytesRead`
| `inputRecords` | `inputMetrics.recordsRead`
| `outputBytes` | `outputMetrics.bytesWritten`
| `outputRecords` | `outputMetrics.recordsWritten`
| `shuffleRead` | `shuffleReadMetrics.remoteBytesRead`
| `shuffleWrite` | `shuffleWriteMetrics.bytesWritten`
| `jvmGCTime` | `metrics.jvmGCTime`
|======================
