== [[ShuffleManager]] ShuffleManager -- Shuffle System Manager

`ShuffleManager` is the <<contract, pluggable mechanism>> for *shuffle systems* that track link:spark-dagscheduler-ShuffleMapStage.adoc[shuffle dependencies for `ShuffleMapStage`].

NOTE: link:spark-SortShuffleManager.adoc[SortShuffleManager] (short name: `sort` or `tungsten-sort`) is the only available `ShuffleManager`.

The driver and executors register their own ``ShuffleManager``s.

The setting <<spark.shuffle.manager, spark.shuffle.manager>> sets up the default shuffle manager.

The driver and executor access the current `ShuffleManager` using link:spark-sparkenv.adoc#shuffleManager[SparkEnv].

[source, scala]
----
val shuffleManager = SparkEnv.get.shuffleManager
----

The driver registers shuffles with a shuffle manager, and executors (or tasks running locally in the driver) can ask to read and write data.

It is network-addressable, i.e. it is available on a host and port.

There can be many shuffle services running simultaneously and a driver registers with all of them when link:spark-scheduler-backends.adoc[CoarseGrainedSchedulerBackend] is used.

When link:spark-rdd-shuffledrdd.adoc[ShuffledRDD] is computed it reads partitions from it.

The name appears https://github.com/apache/spark/commit/2da3a9e98e5d129d4507b5db01bba5ee9558d28e[here], twice in link:varia/spark-building-from-sources.adoc[the build's output] and others.

Review the code in `network/shuffle` module.

* When is data eligible for shuffling?
* Get the gist of _"The shuffle files are not currently cleaned up when using Spark on Mesos with the external shuffle service"_

=== [[contract]] ShuffleManager Contract

[source, scala]
----
trait ShuffleManager {
  def registerShuffle[K, V, C](
      shuffleId: Int,
      numMaps: Int,
      dependency: ShuffleDependency[K, V, C]): ShuffleHandle
  def getWriter[K, V](
    handle: ShuffleHandle,
    mapId: Int,
    context: TaskContext): ShuffleWriter[K, V]
  def getReader[K, C](
    handle: ShuffleHandle,
    startPartition: Int,
    endPartition: Int,
    context: TaskContext): ShuffleReader[K, C]
  def unregisterShuffle(shuffleId: Int): Boolean
  def shuffleBlockResolver: ShuffleBlockResolver
  def stop(): Unit
}
----

NOTE: `ShuffleManager` is a `private[spark]` contract.

.ShuffleManager Contract
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Method
| Description

|[[registerShuffle]] `registerShuffle`
| Executed when ??? registers a shuffle and passes the `ShuffleHandle` to tasks.

|[[getWriter]] `getWriter`
| Executed when ??? requests a `ShuffleWriter` to write records for a partition.

|[[getReader]] `getReader`
| Executed when ??? requests a `ShuffleReader` for a range of partitions.

|[[unregisterShuffle]] `unregisterShuffle`
| Executed when ??? removes the metadata of a shuffle.

|[[shuffleBlockResolver]] `shuffleBlockResolver`
| Executed when ??? requests a `ShuffleBlockResolver` capable of retrieving shuffle block data.

|[[stop]] `stop`
| Executed when ??? stops a `ShuffleManager`.
|===

TIP: Review https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/shuffle/ShuffleManager.scala[`ShuffleManager` sources].

=== [[settings]] Settings

.Spark Properties
[frame="topbot",cols="1,1,2",options="header",width="100%"]
|===
| Spark Property
| Default Value
| Description

| [[spark.shuffle.manager]] `spark.shuffle.manager`
| `sort`
| The default shuffle manager.

You can use a short name or the fully-qualified class name of a custom implementation.

1. `sort` or `org.apache.spark.shuffle.sort.SortShuffleManager`

2. `tungsten-sort` or `org.apache.spark.shuffle.sort.SortShuffleManager`

| [[spark.shuffle.spill]] `spark.shuffle.spill`
| `true`
| Not used. When `false` the following WARNING shows in the logs:

`WARN SortShuffleManager: spark.shuffle.spill was set to false, but this configuration is ignored as of Spark 1.6+. Shuffle will continue to spill to disk when necessary.`

|===

=== [[i-want-more]] Further Reading or Watching

1. (slides) http://www.slideshare.net/colorant/spark-shuffle-introduction[Spark shuffle introduction] by http://blog.csdn.net/colorant/[Raymond Liu] (aka _colorant_).
