== [[CreatableRelationProvider]] CreatableRelationProvider -- Data Sources That Save Rows Per Save Mode

`CreatableRelationProvider` is a <<contract, contract>> for link:spark-sql-DataSource.adoc#providers[data source providers] that <<createRelation, save the result of a structured query per save mode and return the schema>>.

NOTE: A structured query is a link:spark-sql-DataFrame.adoc[DataFrame] while the result are link:spark-sql-Row.adoc[Rows].

`CreatableRelationProvider` is used when:

* `DataSource` is requested to link:spark-sql-DataSource.adoc#write[write the result of a structured query to data source per save mode] (after `DataFrameWriter` is requested to link:spark-sql-DataFrameWriter.adoc#save[save])

* `DataSource` is requested to link:spark-sql-DataSource.adoc#writeAndRead[write the result of a structured query to data source per save mode followed by reading rows back] (after `DataFrameWriter` is requested to link:spark-sql-DataFrameWriter.adoc#saveAsTable[save to a non-Hive table] or for link:spark-sql-SparkSqlAstBuilder.adoc#visitCreateTable[Create Table As Select] SQL statements)

[[known-implementations]]
.CreatableRelationProvider's Known Implementations
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| link:spark-sql-JdbcRelationProvider.adoc[JdbcRelationProvider]
|

| link:spark-sql-DataSourceRegister-KafkaSourceProvider.adoc[KafkaSourceProvider]
|
|===

=== [[contract]] CreatableRelationProvider Contract

[source, scala]
----
package org.apache.spark.sql.sources

trait CreatableRelationProvider {
  def createRelation(
    sqlContext: SQLContext,
    mode: SaveMode,
    parameters: Map[String, String],
    data: DataFrame): BaseRelation
}
----

.CreatableRelationProvider Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[createRelation]] `createRelation`
a| Saves the result of a link:spark-sql-DataFrame.adoc[structured query] to a target relation per save mode and parameters. Creates a link:spark-sql-BaseRelation.adoc[BaseRelation] to describe the scheme.

The save mode specifies what happens when the destination already exists:

* Append
* ErrorIfExists
* Ignore
* Overwrite
|===
