== [[MetricsConfig]] MetricsConfig -- Metrics System Configuration

`MetricsConfig` is...FIXME

The default configuration file is *metrics.properties* (that is first loaded from CLASSPATH before using the path) that can be changed using <<spark.metrics.conf, spark.metrics.conf>> property.

You can also configure the metrics system using ``spark.metrics.conf.``-prefixed Spark properties.

`MetricsConfig` is created when `MetricsSystem` link:spark-MetricsSystem.adoc#creating-instance[is created].

[[internal-registries]]
.MetricsConfig's Internal Registries and Counters
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[properties]] `properties`
| https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html[java.util.Properties]

Used when...FIXME

| [[perInstanceSubProperties]] `perInstanceSubProperties`
| FIXME

Used when...FIXME
|===

=== [[setDefaultProperties]] `setDefaultProperties` Internal Method

CAUTION: FIXME

=== [[subProperties]] `subProperties` Method

CAUTION: FIXME

=== [[creating-instance]] Creating MetricsConfig Instance

`MetricsConfig` takes the following when created:

* [[conf]] link:spark-SparkConf.adoc[SparkConf]

`MetricsConfig` initializes the <<internal-registries, internal registries and counters>>.

=== [[initialize]] Initializing MetricsConfig -- `initialize` Method

[source, scala]
----
initialize(): Unit
----

`initialize` <<setDefaultProperties, sets the default properties>> and <<loadPropertiesFromFile, loads the properties from the configuration file>> (that is defined using <<spark.metrics.conf, spark.metrics.conf>> Spark property).

`initialize` takes all the properties that start with *spark.metrics.conf.* prefix from <<conf, SparkConf>> and registers them in <<properties, properties>> (without the prefix).

In the end, `initialize` splits <<perInstanceSubProperties, configuration for different Spark subsystems>> with the default configuration (denoted as `*`) assigned to the configured subsystems afterwards.

NOTE: `initialize` accepts `*` (star) for the default configuration or any combination of lower- and upper-case letters for Spark subsystem names.

NOTE: `initialize` is used exclusively when `MetricsSystem` link:spark-MetricsSystem.adoc#creating-instance[is created].

=== [[settings]] Settings

.Spark Properties
[cols="1,1,2",options="header",width="100%"]
|===
| Spark Property
| Default Value
| Description

| [[spark.metrics.conf]] `spark.metrics.conf`
| `metrics.properties`
| The metrics configuration file.
|===
