== Attribute Expression

`Attribute` is a link:spark-sql-catalyst-Expression.adoc#LeafExpression[leaf] (i.e. no children) link:spark-sql-catalyst-Expression.adoc#NamedExpression[named] expression.

NOTE: A link:spark-sql-catalyst-QueryPlan.adoc#output[`QueryPlan` uses `Attributes`] to build the link:spark-sql-StructType.adoc[schema] of the query (it represents).

.`Attribute` Properties and Their Behaviour (Inherited from Expression)
[cols="1,2",options="header",width="100%"]
|===
| Property | Behaviour
| `references` | A one-element collection with itself.
| `toAttribute` | Self-reference
|===

`Attribute` abstract class defines three additional "builder" methods.

.`Attribute` Expression Builder Methods
[cols="1,2",options="header",width="100%"]
|===
| Name | Description
| `withNullability` | Sets
| `withQualifier` | Sets
| `withName` | Sets
|===

NOTE: `Attribute` is the base link:spark-sql-catalyst-Expression.adoc[expression] for `AttributeReference`, `UnresolvedAttribute`, and `PrettyAttribute`.

As an optimization, `Attribute` is marked as to not tolerate `nulls`, and when given a `null` input produces a `null` output.
