== CatalystSerde

`CatalystSerde` object consists of three methods:

1. <<deserialize, deserialize>> to create a <<DeserializeToObject, `DeserializeToObject` logical plan>> for a logical plan.
2. <<serialize, serialize>>
3. <<generateObjAttr, generateObjAttr>>

`CatalystSerde` is a Scala object and belongs to `org.apache.spark.sql.catalyst.plans.logical` package.

=== [[deserialize]] Creating `DeserializeToObject` Logical Plan for Child Logical Plan -- `deserialize` method

[source, scala]
----
deserialize[T : Encoder](child: LogicalPlan): DeserializeToObject
----

`deserialize` creates a <<DeserializeToObject, `DeserializeToObject` logical plan>> for the input `child` link:spark-sql-catalyst-LogicalPlan.adoc[logical plan].

Internally, `deserialize` creates a `UnresolvedDeserializer` for the deserializer for the type `T` first and passes it on to a `DeserializeToObject` with a `AttributeReference` (being the result of <<generateObjAttr, generateObjAttr>>).

=== [[serialize]] `serialize` method

[source, scala]
----
serialize[T : Encoder](child: LogicalPlan): SerializeFromObject
----

=== [[generateObjAttr]] `generateObjAttr` method

[source, scala]
----
generateObjAttr[T : Encoder]: Attribute
----

=== [[DeserializeToObject]] DeserializeToObject Unary Logical Plan

[source, scala]
----
case class DeserializeToObject(
  deserializer: Expression,
  outputObjAttr: Attribute,
  child: LogicalPlan) extends UnaryNode with ObjectProducer
----

`DeserializeToObject` is a link:spark-sql-catalyst-LogicalPlan.adoc#UnaryNode[unary logical plan] that takes the input row from the input `child` link:spark-sql-catalyst-LogicalPlan.adoc[logical plan] and turns it into the input `outputObjAttr` attribute using the given `deserializer` expression.
