== [[UserDefinedFunction]] UserDefinedFunction

`UserDefinedFunction` represents a *user-defined function*.

`UserDefinedFunction` is <<creating-instance, created>> when:

1. link:spark-sql-functions.adoc#udf[udf] function is executed
1. `UDFRegistration` is requested to link:spark-sql-UDFRegistration.adoc#register[register a Scala function as a user-defined function] (in `FunctionRegistry`)

[source, scala]
----
import org.apache.spark.sql.functions.udf
scala> val lengthUDF = udf { s: String => s.length }
lengthUDF: org.apache.spark.sql.expressions.UserDefinedFunction = UserDefinedFunction(<function1>,IntegerType,Some(List(StringType)))

scala> lengthUDF($"name")
res1: org.apache.spark.sql.Column = UDF(name)
----

(new in *2.3.0*) `UserDefinedFunction` can also have a <<withName, name>>.

[source, scala]
----
// New in 2.3.0
val namedLengthUDF = lengthUDF.withName("lengthUDF")
scala> namedLengthUDF($"name")
res2: org.apache.spark.sql.Column = UDF:lengthUDF(name)
----

(new in *2.3.0*) `UserDefinedFunction` is *nullable* by default, but can be changed as <<asNonNullable, non-nullable>>.

[source, scala]
----
// New in 2.3.0
val nonNullableLengthUDF = lengthUDF.asNonNullable
scala> nonNullableLengthUDF.nullable
res1: Boolean = false
----

=== [[apply]] Executing UserDefinedFunction (Creating Column with ScalaUDF Expression) -- `apply` Method

[source, scala]
----
apply(exprs: Column*): Column
----

`apply` creates a link:spark-sql-Column.adoc#creating-instance[Column] with link:spark-sql-Expression-ScalaUDF.adoc#creating-instance[ScalaUDF] expression.

[source, scala]
----
import org.apache.spark.sql.functions.udf
scala> val lengthUDF = udf { s: String => s.length }
lengthUDF: org.apache.spark.sql.expressions.UserDefinedFunction = UserDefinedFunction(<function1>,IntegerType,Some(List(StringType)))

scala> lengthUDF($"name")
res1: org.apache.spark.sql.Column = UDF(name)
----

NOTE: `apply` is used when...FIXME

=== [[asNonNullable]] Marking UserDefinedFunction as NonNullable -- `asNonNullable` Method

[source, scala]
----
asNonNullable(): UserDefinedFunction
----

`asNonNullable`...FIXME

NOTE: `asNonNullable` is used when...FIXME

=== [[withName]] Naming UserDefinedFunction -- `withName` Method

[source, scala]
----
withName(name: String): UserDefinedFunction
----

`withName`...FIXME

NOTE: `withName` is used when...FIXME

=== [[creating-instance]] Creating UserDefinedFunction Instance

`UserDefinedFunction` takes the following when created:

* [[f]] A Scala function (as Scala's `AnyRef`)
* [[dataType]] Output link:spark-sql-DataType.adoc[data type]
* [[inputTypes]] Input link:spark-sql-DataType.adoc[data types] (if available)

`UserDefinedFunction` initializes the <<internal-registries, internal registries and counters>>.
