== [[ExecutedCommandExec]] ExecutedCommandExec Physical Operator for Command Execution

`ExecutedCommandExec` is a link:spark-sql-SparkPlan.adoc[SparkPlan] for executing link:spark-sql-LogicalPlan-RunnableCommand.adoc[logical commands with side effects].

`ExecutedCommandExec` runs a command and caches the result in <<sideEffectResult, sideEffectResult>> internal attribute.

[[methods]]
.ExecutedCommandExec's Methods (in alphabetical order)
[width="100%",cols="1,2",options="header"]
|===
| Method
| Description

| [[doExecute]] `doExecute`
| Executes `ExecutedCommandExec` physical operator (and produces a result as an RDD of link:spark-sql-InternalRow.adoc[internal binary rows]

| [[executeCollect]] `executeCollect`
|

| [[executeTake]] `executeTake`
|

| [[executeToIterator]] `executeToIterator`
|
|===

=== [[sideEffectResult]] Executing Logical RunnableCommand and Caching Result As InternalRows -- `sideEffectResult` Internal Lazy Attribute

[source, scala]
----
sideEffectResult: Seq[InternalRow]
----

`sideEffectResult` link:link:spark-sql-LogicalPlan-RunnableCommand.adoc#run[runs the `RunnableCommand`] (that produces a `Seq[Row]`) and converts the result to a `Seq[InternalRow]` using a Catalyst converter function for a given link:spark-sql-catalyst-QueryPlan.adoc#schema[schema].

CAUTION: FIXME `CatalystTypeConverters.createToCatalystConverter`?

NOTE: `sideEffectResult` is used when `ExecutedCommandExec` is requested for <<executeCollect, executeCollect>>, <<executeToIterator, executeToIterator>>, <<executeTake, executeTake>>, <<doExecute, doExecute>>.
