== [[JoinSelection]] JoinSelection

`JoinSelection` is a `Strategy` of link:spark-sql-SparkPlanner.adoc[SparkPlanner] and link:spark-sql-HiveSessionState.adoc[Hive-specific `QueryPlanner`].

When applied to a link:spark-sql-LogicalPlan.adoc[LogicalPlan], its processing varies per join type.

.JoinSelection's Cases
[cols="1,3",options="header",width="100%"]
|===
| Name | Behaviour
| `ExtractEquiJoinKeys` | Used to destructure a `Join`
| `Join` |
|===

=== [[canBuildLocalHashMap]] `canBuildLocalHashMap` Internal Method

CAUTION: FIXME

=== [[ExtractEquiJoinKeys]] ExtractEquiJoinKeys

`ExtractEquiJoinKeys` is a pattern used to destructure a link:spark-sql-LogicalPlan-Join.adoc[Join] into a tuple of `(JoinType, Seq[Expression], Seq[Expression], Option[Expression], LogicalPlan, LogicalPlan)`.

=== [[canBuildLeft]] `canBuildLeft` Internal Method

CAUTION: FIXME

=== [[canBuildRight]] `canBuildRight` Internal Method

[source, scala]
----
canBuildRight(joinType: JoinType): Boolean
----

`canBuildRight` is a predicate that is positive (i.e. `true`) for link:spark-sql-joins.adoc[joins] that are:

* CROSS, INNER, LEFT ANTI, LEFT OUTER, LEFT SEMI or Existence

Otherwise, `canBuildRight` is negative (i.e. `false`).

=== [[canBroadcast]] Checking If Logical Plan Can Be Broadcast -- `canBroadcast` Internal Method

[source, scala]
----
canBroadcast(plan: LogicalPlan): Boolean
----

`canBroadcast` is a predicate that is positive (i.e. `true`) for link:spark-sql-LogicalPlan.adoc[logical operators] with statistics that can be broadcast and of non-negative size that is however less than link:spark-sql-settings.adoc#spark.sql.autoBroadcastJoinThreshold[spark.sql.autoBroadcastJoinThreshold].
