== [[Analyzer]] Logical Query Plan Analyzer

CAUTION: FIXME Work in progress

`Analyzer` is a link:spark-sql-logical-plan.adoc[logical query plan] analyzer. It is available through link:spark-sql-sessionstate.adoc#analyzer[analyzer attribute] of the current `SparkSession`.

[source, scala]
----
sparkSession.sessionState.analyzer
----

NOTE: link:spark-sql-sparksession.adoc#sessionState[`sessionState` attribute in `SparkSession`] is `private[sql] lazy val` so the code should be inside `org.apache.spark.sql` package.

`Analyzer` is a `RuleExecutor` with `CheckAnalysis` and defines `Substitution`, `Resolution`, `Nondeterministic`, `UDF`, `FixNullability`, and `Cleanup` batches.

`Analyzer` uses a link:spark-sql-sessionstate.adoc#SessionCatalog[SessionCatalog], a `CatalystConf`, and a configurable number of iterations (as `maxIterations`).

`Analyzer` defines `extendedResolutionRules` attribute being a collection of `Rule[LogicalPlan]` as an extension point which a custom `Analyzer` can use to extend the `Resolution` batch. The collection is then added at the end of the `Resolution` batch.

You can access the result of executing `Analyzer` against the link:spark-sql-logical-plan.adoc[logical plan] of a link:spark-sql-dataset.adoc[Dataset] using link:spark-sql-dataset.adoc#explain[explain] method or link:spark-sql-query-execution.adoc[QueryExecution]:

[source, scala]
----
val dataset = spark.range(5).withColumn("new_column", 'id + 5 as "plus5")

scala> dataset.explain(true)
== Parsed Logical Plan ==
'Project [*, ('id + 5) AS plus5#296 AS new_column#297]
+- Range (0, 5, splits=8)

== Analyzed Logical Plan ==
id: bigint, new_column: bigint
Project [id#293L, (id#293L + cast(5 as bigint)) AS new_column#297L]
+- Range (0, 5, splits=8)

== Optimized Logical Plan ==
Project [id#293L, (id#293L + 5) AS new_column#297L]
+- Range (0, 5, splits=8)

== Physical Plan ==
*Project [id#293L, (id#293L + 5) AS new_column#297L]
+- *Range (0, 5, splits=8)

scala> dataset.queryExecution.analyzed
res34: org.apache.spark.sql.catalyst.plans.logical.LogicalPlan =
Project [id#293L, (id#293L + cast(5 as bigint)) AS new_column#297L]
+- Range (0, 5, splits=8)
----
