== [[BroadcastNestedLoopJoinExec]] BroadcastNestedLoopJoinExec Physical Operator

`BroadcastNestedLoopJoinExec` is a link:spark-sql-SparkPlan.adoc#BinaryExecNode[binary physical operator].

`BroadcastNestedLoopJoinExec` <<requiredChildDistribution, requires that partition requirements>> for the two children physical operators match `BroadcastDistribution` (with `IdentityBroadcastMode`) and `UnspecifiedDistribution` (for <<left, left>> and <<right, right>> sides of a join or vice versa).

[[metrics]]
.BroadcastNestedLoopJoinExec SQLMetrics (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[numOutputRows]] `numOutputRows`
| Number of output rows
|===

=== [[requiredChildDistribution]] `requiredChildDistribution` Method

[source, scala]
----
requiredChildDistribution: Seq[Distribution]
----

`requiredChildDistribution` gives a two-element collection for two-child partition requirements with the following:

* `BroadcastDistribution` and `UnspecifiedDistribution` for <<buildSide, BuildLeft build side>>

* `UnspecifiedDistribution` and `BroadcastDistribution` for <<buildSide, BuildRight build side>>

NOTE: `BroadcastDistribution` uses `IdentityBroadcastMode` broadcast mode.

NOTE: `requiredChildDistribution` is a part of link:spark-sql-SparkPlan.adoc#requiredChildDistribution[SparkPlan Contract] to specify partition requirements on the input data.
