== RDD Caching / Persistence

* An RDD can be cached (using `cache` operation) or persisted (using `persist(newLevel: StorageLevel)` operation).
* `cache()` is a synonym of `persist()` that uses the default storage level `MEMORY_ONLY`.
* `StorageLevel` describes how an RDD is persisted:
** Uses disk?
** Uses memory?
** Uses off-heap?
** Should an RDD be serialized?
** Replication (default: `1`) can only be less than `40`.

* There are the following `StorageLevel` (number `_2` in the name denotes 2 replications):
** `NONE` (default)
** `DISK_ONLY`
** `DISK_ONLY_2`
** `MEMORY_ONLY`
** `MEMORY_ONLY_2`
** `MEMORY_ONLY_SER`
** `MEMORY_ONLY_SER_2`
** `MEMORY_AND_DISK`
** `MEMORY_AND_DISK_2`
** `MEMORY_AND_DISK_SER`
** `MEMORY_AND_DISK_SER_2`
** `OFF_HEAP`

* You can ask for storage level using `getStorageLevel: StorageLevel` operation.
+
```
scala> val lines = sc.textFile("README.md")
lines: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[3] at textFile at <console>:24

scala> lines.getStorageLevel
res2: org.apache.spark.storage.StorageLevel = StorageLevel(false, false, false, false, 1)
```

* An RDD can be unpersisted (using `unpersist(blocking: Boolean = true)` operation) that removes it from link:spark-blockmanager.adoc[Block Manager], posts link:spark-listeners.adoc[an unpersist notification], and finally marks it to have persistence level `NONE`.
