== FIFOSchedulableBuilder - SchedulableBuilder for FIFO Scheduling Mode

`FIFOSchedulableBuilder` is a <<SchedulableBuilder,SchedulableBuilder>> that is a _mere_ wrapper around a single link:spark-taskscheduler-pool.adoc[Pool] (the only constructor parameter).

NOTE: `FIFOSchedulableBuilder` is the default `SchedulableBuilder` for `TaskSchedulerImpl` (see link:spark-taskschedulerimpl.adoc#creating-instance[Creating TaskSchedulerImpl]).

NOTE: When `FIFOSchedulableBuilder` is created, the `TaskSchedulerImpl` passes its own `rootPool` (that belongs to the link:spark-taskscheduler.adoc#contract[TaskScheduler Contract] that `TaskSchedulerImpl` follows).

`FIFOSchedulableBuilder` obeys the <<contract, SchedulableBuilder Contract>> as follows:

* <<buildPools, buildPools>> does nothing.
* `addTaskSetManager` link:spark-taskscheduler-pool.adoc#addSchedulable[passes the input `Schedulable` to the one and only rootPool Pool (using `addSchedulable`)] and completely disregards the properties of the Schedulable.
