== FsHistoryProvider

`FsHistoryProvider` is the default <<ApplicationHistoryProvider, application history provider>> for link:spark-history-server.adoc[HistoryServer]. It uses link:spark-SparkConf.adoc[SparkConf] and `Clock` objects for its operation.

[TIP]
====
Enable `INFO` or `DEBUG` logging levels for `org.apache.spark.deploy.history.FsHistoryProvider` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.deploy.history.FsHistoryProvider=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[getAppUI]] `getAppUI` Method

[source, scala]
----
getAppUI(appId: String, attemptId: Option[String]): Option[LoadedAppUI]
----

NOTE: `getAppUI` is part of <<ApplicationHistoryProvider, ApplicationHistoryProvider Contract>> to...FIXME.

`getAppUI`...FIXME

=== [[ApplicationHistoryProvider]] ApplicationHistoryProvider

`ApplicationHistoryProvider` tracks the history of <<ApplicationHistoryProvider-getListing, Spark applications>> with their <<ApplicationHistoryProvider-getAppUI, Spark UIs>>. It can be <<ApplicationHistoryProvider-stop, stopped>> and <<ApplicationHistoryProvider-writeEventLogs, write events to a stream>>.

It is an abstract class.

==== [[ApplicationHistoryProvider-contract]] ApplicationHistoryProvider Contract

Every `ApplicationHistoryProvider` offers the following:

[[ApplicationHistoryProvider-getListing]]
* `getListing` to return a list of all known applications.
+
[source, scala]
----
getListing(): Iterable[ApplicationHistoryInfo]
----

[[ApplicationHistoryProvider-getAppUI]]
* `getAppUI` to return link:spark-webui.adoc[Spark UI] for an application.
+
[source, scala]
----
getAppUI(appId: String, attemptId: Option[String]): Option[LoadedAppUI]
----

[[ApplicationHistoryProvider-stop]]
* `stop` to stop the instance.
+
[source, scala]
----
stop(): Unit
----

* `getConfig` to return configuration of...FIXME
+
[source, scala]
----
getConfig(): Map[String, String] = Map()
----

[[ApplicationHistoryProvider-writeEventLogs]]
* `writeEventLogs` to write events to a stream.
+
[source, scala]
----
writeEventLogs(appId: String, attemptId: Option[String], zipStream: ZipOutputStream): Unit
----
