== [[Expression]] Expression -- Executable Node in Catalyst Tree

`Expression` is a executable link:spark-sql-catalyst-TreeNode.adoc[node] (in a Catalyst tree) that can be <<eval, evaluated>> to a value given input values, i.e. can produce a JVM object per `InternalRow`.

NOTE: `Expression` is often called a *Catalyst expression* even though it is _merely_ built using (not be part of) the link:spark-sql-catalyst.adoc[Catalyst -- Tree Manipulation Framework].

[source, scala]
----
// evaluating an expression
// Use Literal expression to create an expression from a Scala object
import org.apache.spark.sql.catalyst.expressions.Expression
import org.apache.spark.sql.catalyst.expressions.Literal
val e: Expression = Literal("hello")

import org.apache.spark.sql.catalyst.expressions.EmptyRow
val v: Any = e.eval(EmptyRow)

// Convert to Scala's String
import org.apache.spark.unsafe.types.UTF8String
scala> val s = v.asInstanceOf[UTF8String].toString
s: String = hello
----

`Expression` can <<genCode, generate a Java source code>> that is then used in evaluation.

[[specialized-expressions]]
.Specialized Expressions
[cols="1,2,2,1",options="header",width="100%"]
|===
| Name
| Scala Kind
| Behaviour
| Examples

| [[BinaryExpression]] `BinaryExpression`
| abstract class
|
a|

* link:spark-sql-Expression-UnixTimestamp.adoc[UnixTimestamp]

| [[CodegenFallback]] `CodegenFallback`
| trait
| Does not support code generation and falls back to interpreted mode
a|

* link:spark-sql-Expression-CallMethodViaReflection.adoc[CallMethodViaReflection]

| [[ExpectsInputTypes]] `ExpectsInputTypes`
| trait
|
|

| [[LeafExpression]] `LeafExpression`
| abstract class
| Has no link:spark-sql-catalyst-TreeNode.adoc#children[child expressions] (and hence "terminates" the expression tree).
a|

* link:spark-sql-Expression-Attribute.adoc[Attribute]
* link:spark-sql-Expression-Literal.adoc[Literal]

| [[NamedExpression]] `NamedExpression`
|
| Can later be referenced in a dataflow graph.
|

| <<Nondeterministic, Nondeterministic>>
| trait
|
|

| [[NonSQLExpression]] `NonSQLExpression`
| trait
| Expression with no SQL representation

Gives the only custom <<sql, sql>> method that is non-overridable (i.e. `final`).

When requested <<sql, SQL representation>>, `NonSQLExpression` transforms link:spark-sql-Expression-Attribute.adoc[Attributes] to be ``PrettyAttribute``s to build text representation.
a|

* link:spark-sql-Expression-ScalaUDAF.adoc[ScalaUDAF]
* link:spark-sql-Expression-StaticInvoke.adoc[StaticInvoke]
* link:spark-sql-Expression-TimeWindow.adoc[TimeWindow]

| [[TernaryExpression]] `TernaryExpression`
| abstract class
|
|

| [[TimeZoneAwareExpression]] `TimeZoneAwareExpression`
| trait
| Timezone-aware expressions
a|

* link:spark-sql-Expression-UnixTimestamp.adoc[UnixTimestamp]
* link:spark-sql-Expression-JsonToStructs.adoc[JsonToStructs]

| [[UnaryExpression]] `UnaryExpression`
| abstract class
|
a|

* link:spark-sql-Expression-Generator.adoc#ExplodeBase[ExplodeBase]
* link:spark-sql-Expression-JsonToStructs.adoc[JsonToStructs]

| [[Unevaluable]] `Unevaluable`
| trait
| Cannot be evaluated, i.e. <<eval, eval>> and <<doGenCode, doGenCode>> are not supported and report an `UnsupportedOperationException`.

`Unevaluable` expressions are supposed to be replaced by some other expressions during link:spark-sql-Analyzer.adoc[analysis] or link:spark-sql-Optimizer.adoc[optimization].

a|

* link:spark-sql-Expression-AggregateExpression.adoc[AggregateExpression]
* `CurrentDatabase`
* link:spark-sql-Expression-TimeWindow.adoc[TimeWindow]
* link:spark-sql-Expression-WindowExpression.adoc[WindowExpression]
* link:spark-sql-Expression-WindowSpecDefinition.adoc[WindowSpecDefinition]
|===

=== [[contract]] Expression Contract

[source, scala]
----
package org.apache.spark.sql.catalyst.expressions

abstract class Expression extends TreeNode[Expression] {
  // only required methods that have no implementation
  def dataType: DataType
  def doGenCode(ctx: CodegenContext, ev: ExprCode): ExprCode
  def eval(input: InternalRow = EmptyRow): Any
  def nullable: Boolean
}
----

.(Subset of) Expression Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[canonicalized]] `canonicalized`
|

| [[checkInputDataTypes]] `checkInputDataTypes`
|

| [[childrenResolved]] `childrenResolved`
|

| [[dataType]] `dataType`
|

| [[deterministic]] `deterministic`
|

| [[doGenCode]] `doGenCode`
| *Code-generated evaluation* that generates a Java source code (that is used to evaluate the expression in a more optimized way not directly using <<eval, eval>>).

Used as part of <<genCode, genCode>>.

| [[eval]] `eval`
a| *No-code-generated evaluation* that evaluates the expression to a JVM object for a given link:spark-sql-InternalRow.adoc[InternalRow] (without <<genCode, generating a corresponding Java code>>.)

NOTE: By default accepts `EmptyRow`, i.e. `null`.

| [[foldable]] `foldable`
|

| [[genCode]] `genCode`
| *Code-generated evaluation* that generates a Java source code (that is used to evaluate the expression in a more optimized way not directly using <<eval, eval>>).

Similar to <<doGenCode, doGenCode>> but supports expression reuse (aka _subexpression elimination_).

| [[nullable]] `nullable`
|

| [[prettyName]] `prettyName`
|

| [[references]] `references`
|

| [[resolved]] `resolved`
|

| [[semanticEquals]] `semanticEquals`
|

| [[semanticHash]] `semanticHash`
|

| [[sql]] `sql`
a| SQL representation

<<prettyName, prettyName>> followed by `sql` of link:spark-sql-catalyst-TreeNode.adoc#children[children] in the round brackets and concatenated using the comma (`,`), e.g.

```
import org.apache.spark.sql.catalyst.dsl.expressions._
import org.apache.spark.sql.catalyst.expressions.Sentences
val sentences = Sentences("Hi there! Good morning.", "en", "US")

import org.apache.spark.sql.catalyst.expressions.Expression
val expr: Expression = count("*") === 5 && count(sentences) === 5
scala> expr.sql
res0: String = ((count('*') = 5) AND (count(sentences('Hi there! Good morning.', 'en', 'US')) = 5))
```
|===

=== [[Nondeterministic]] `Nondeterministic` Expression

`Nondeterministic` expressions are non-deterministic and non-<<foldable, foldable>>, i.e. `deterministic` and `foldable` properties are disabled (i.e. `false`). They require explicit initialization before evaluation.

`Nondeterministic` expressions have two additional methods:

1. `initInternal` for internal initialization (called before `eval`)
2. `evalInternal` to ``eval``uate a link:spark-sql-InternalRow.adoc[InternalRow] into a JVM object.

NOTE: `Nondeterministic` is a Scala trait.

`Nondeterministic` expressions have the additional `initialized` flag that is enabled (i.e. `true`) after the other additional `initInternal` method has been called.

Examples of `Nondeterministic` expressions are `InputFileName`, `MonotonicallyIncreasingID`, `SparkPartitionID` functions and the abstract `RDG` (that is the base for `Rand` and `Randn` functions).

NOTE: `Nondeterministic` expressions are the target of `PullOutNondeterministic` logical plan rule.
