== ShuffledRDD

*ShuffledRDD* is the result RDD of a link:spark-rdd-shuffle.adoc[shuffle], i.e. the result of `coalesce` transformation with `shuffle` input parameter being `true` (defaults to `false`).

It's also known as *a shuffle step* (see https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rdd/RDD.scala#L403[this line in org/apache/spark/rdd/RDD.scala]).

A parent RDD is a pair RDD which means ShuffleRDD works with RDDs of pairs.

It is also the result of RDD transformations using Scala implicits:

* `repartitionAndSortWithinPartitions`
* `sortByKey` (be very careful due to https://issues.apache.org/jira/browse/SPARK-1021[[SPARK-1021\]
sortByKey() launches a cluster job when it shouldn't])
* `combineByKeyWithClassTag` (only when the input partitioner is different from the current one in an RDD)
* `partitionBy` (only when the input partitioner is different from the current one in an RDD)

It uses link:spark-rdd-partitions.adoc#partitioner[Partitioner].

ShuffledRDD's RDD Dependencies are always a single-element link:spark-rdd-dependencies.adoc#ShuffleDependency[ShuffleDependency]. Partitions are of type `ShuffledRDDPartition`.

It uses link:spark-service-mapoutputtracker.adoc#MapOutputTrackerMaster[MapOutputTrackerMaster] to get preferred locations for a shuffle, i.e. a ShuffleDependency.

[CAUTION]
====
FIXME

* Where's `mapSideCombine` flag used?
====
