== [[RetryingBlockFetcher]] RetryingBlockFetcher

`RetryingBlockFetcher` is...FIXME

`RetryingBlockFetcher` is <<creating-instance, created>> and immediately <<start, started>> when:

* `NettyBlockTransferService` is requested to link:spark-NettyBlockTransferService.adoc#fetchBlocks[fetchBlocks] (when link:spark-TransportConf.adoc#io.maxRetries[maxIORetries] is greater than `0` which it is by default)

* `ExternalShuffleClient` is requested to link:spark-ShuffleClient-ExternalShuffleClient.adoc#fetchBlocks[fetchBlocks] (when link:spark-TransportConf.adoc#io.maxRetries[maxIORetries] is greater than `0` which it is by default)

[[outstandingBlocksIds]]
`RetryingBlockFetcher` uses `outstandingBlocksIds` internal registry of outstanding block IDs to fetch that is initially the <<blockIds, block IDs to fetch>> when <<creating-instance, created>>.

At <<initiateRetry, initiateRetry>>, `RetryingBlockFetcher` prints out the following INFO message to the logs (with the number of <<outstandingBlocksIds, outstandingBlocksIds>>):

```
Retrying fetch ([retryCount]/[maxRetries]) for [size] outstanding blocks after [retryWaitTime] ms
```

On <<RetryingBlockFetchListener-onBlockFetchSuccess, onBlockFetchSuccess>> and <<RetryingBlockFetchListener-onBlockFetchFailure, onBlockFetchFailure>>, <<currentListener, RetryingBlockFetchListener>> removes the block ID from <<outstandingBlocksIds, outstandingBlocksIds>>.

[[currentListener]]
`RetryingBlockFetcher` uses a <<RetryingBlockFetchListener, RetryingBlockFetchListener>> to remove block IDs from the <<outstandingBlocksIds, outstandingBlocksIds>> internal registry.

=== [[creating-instance]] Creating RetryingBlockFetcher Instance

`RetryingBlockFetcher` takes the following when created:

* [[conf]] link:spark-TransportConf.adoc[TransportConf]
* [[fetchStarter]] `BlockFetchStarter`
* [[blockIds]] Block IDs
* [[listener]] link:spark-BlockFetchingListener.adoc[BlockFetchingListener]

`RetryingBlockFetcher` initializes the <<internal-registries, internal registries and counters>>.

=== [[start]] Starting RetryingBlockFetcher -- `start` Method

[source, java]
----
void start()
----

`start` simply <<fetchAllOutstanding, fetchAllOutstanding>>.

[NOTE]
====
`start` is used when:

* `NettyBlockTransferService` is requested to link:spark-NettyBlockTransferService.adoc#fetchBlocks[fetchBlocks] (when link:spark-TransportConf.adoc#io.maxRetries[maxIORetries] is greater than `0` which it is by default)

* `ExternalShuffleClient` is requested to link:spark-ShuffleClient-ExternalShuffleClient.adoc#fetchBlocks[fetchBlocks] (when link:spark-TransportConf.adoc#io.maxRetries[maxIORetries] is greater than `0` which it is by default)
====

=== [[initiateRetry]] `initiateRetry` Internal Method

[source, java]
----
synchronized void initiateRetry()
----

`initiateRetry`...FIXME

[NOTE]
====
`initiateRetry` is used when:

* `RetryingBlockFetcher` is requested to <<fetchAllOutstanding, fetchAllOutstanding>>

* `RetryingBlockFetchListener` is requested to <<RetryingBlockFetchListener-onBlockFetchFailure, onBlockFetchFailure>>
====

=== [[fetchAllOutstanding]] `fetchAllOutstanding` Internal Method

[source, java]
----
void fetchAllOutstanding()
----

`fetchAllOutstanding` requests <<fetchStarter, BlockFetchStarter>> to `createAndStart` for the <<outstandingBlocksIds, outstandingBlocksIds>>.

NOTE: `fetchAllOutstanding` is used when `RetryingBlockFetcher` is requested to <<start, start>> and <<initiateRetry, initiateRetry>>.

=== [[RetryingBlockFetchListener]] RetryingBlockFetchListener

`RetryingBlockFetchListener` is a link:spark-BlockFetchingListener.adoc[BlockFetchingListener] that <<currentListener, RetryingBlockFetcher>> uses to remove block IDs from the <<outstandingBlocksIds, outstandingBlocksIds>> internal registry.

==== [[RetryingBlockFetchListener-onBlockFetchSuccess]] `onBlockFetchSuccess` Method

[source, scala]
----
void onBlockFetchSuccess(String blockId, ManagedBuffer data)
----

NOTE: `onBlockFetchSuccess` is part of link:spark-BlockFetchingListener.adoc#onBlockFetchSuccess[BlockFetchingListener Contract] to...FIXME.

`onBlockFetchSuccess`...FIXME

==== [[RetryingBlockFetchListener-onBlockFetchFailure]] `onBlockFetchFailure` Method

[source, scala]
----
void onBlockFetchFailure(String blockId, Throwable exception)
----

NOTE: `onBlockFetchFailure` is part of link:spark-BlockFetchingListener.adoc#onBlockFetchFailure[BlockFetchingListener Contract] to...FIXME.

`onBlockFetchFailure`...FIXME
