== [[TreeNode]] TreeNode -- Node in Catalyst Tree

`TreeNode` is a node in link:spark-sql-catalyst.adoc[Catalyst] tree with zero or more <<children, children>> (and can build link:spark-sql-Expression.adoc[expression] or link:spark-sql-catalyst-QueryPlan.adoc[structured query plan] trees).

`TreeNode` offers not only functions that you may have used from Scala Collection API, e.g. `map`, `flatMap`, `collect`, `collectFirst`, `foreach`, but also `mapChildren`, `transform`, `transformDown`, `transformUp`, `foreachUp`, `numberedTreeString`, `p`, `asCode`, `prettyJson`, etc. that are particularly useful for tree manipulation or debugging.

NOTE: Scala-specific, `TreeNode` is an abstract class that is the base class of link:spark-sql-Expression.adoc[Expression] and Catalyst's link:spark-sql-catalyst-QueryPlan.adoc[QueryPlan] abstract classes.

[TIP]
====
`TreeNode` abstract type is a quite advanced Scala type definition (at least comparing to the other Scala types in Spark) so understanding its behaviour even outside Spark might be worthwhile by itself.

[source, scala]
----
abstract class TreeNode[BaseType <: TreeNode[BaseType]] extends Product {
  self: BaseType =>

  // ...
}
----
====

=== [[contract]] TreeNode Contract

[source, scala]
----
package org.apache.spark.sql.catalyst.trees

abstract class TreeNode[BaseType <: TreeNode[BaseType]] extends Product {
  self: BaseType =>

  // only required methods that have no implementation
  def children: Seq[BaseType]
  def verboseString: String
}
----

.(Subset of) TreeNode Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[children]] `children`
|

| [[verboseString]] `verboseString`
|
|===

=== [[treeString]] Text Representation of All Nodes in Tree -- `treeString` Method

[source, scala]
----
treeString: String  // <1>
treeString(verbose: Boolean, addSuffix: Boolean = false): String
----
<1> Turns verbose flag on

`treeString` gives the string representation of all the nodes in a `TreeNode`.

NOTE: `treeString` is used mainly when `TreeNode` is requested for the <<numberedTreeString, numbered text representation>> for display purposes (and also for the string representation of a `TreeNode` object).

=== [[generateTreeString]] `generateTreeString` Method

[source, scala]
----
generateTreeString(
  depth: Int,
  lastChildren: Seq[Boolean],
  builder: StringBuilder,
  verbose: Boolean,
  prefix: String = "",
  addSuffix: Boolean = false): StringBuilder
----

`generateTreeString`...FIXME

NOTE: `generateTreeString` is used when...FIXME

=== [[withNewChildren]] `withNewChildren` Method

CAUTION: FIXME

=== [[simpleString]] Simple One-Line Node Description -- `simpleString` Method

[source, scala]
----
simpleString: String
----

`simpleString` gives a simple one-line description of a `TreeNode`.

Internally, `simpleString` is the <<nodeName, nodeName>> followed by <<argString, argString>> separated by a single white space.

NOTE: `simpleString` is used when `TreeNode` is requested for <<argString, argString>> (of child nodes) and <<generateTreeString, tree text representation>> (with `verbose` flag off).

=== [[numberedTreeString]] Building Numbered Text Representation -- `numberedTreeString` Method

[source, scala]
----
numberedTreeString: String
----

`numberedTreeString` adds numbers to the <<treeString, text representation of all the nodes>>.

NOTE: `numberedTreeString` is used primarily for interactive debugging using <<apply, apply>> and <<p, p>> methods.

=== [[apply]] Getting n-th TreeNode in Tree (for Interactive Debugging) -- `apply` Method

[source, scala]
----
apply(number: Int): TreeNode[_]
----

`apply` gives `number`-th tree node in a tree.

NOTE: `apply` can be used for interactive debugging.

Internally, `apply` <<getNodeNumbered, gets the node>> at `number` position or `null`.

=== [[p]] Getting n-th BaseType in Tree (for Interactive Debugging) -- `p` Method

[source, scala]
----
p(number: Int): BaseType
----

`p` gives `number`-th tree node in a tree as `BaseType` for interactive debugging.

NOTE: `p` can be used for interactive debugging.

[NOTE]
====
`BaseType` is the base type of a tree and in Spark SQL can be:

* link:spark-sql-LogicalPlan.adoc[LogicalPlan] for logical plan trees

* link:spark-sql-SparkPlan.adoc[SparkPlan] for physical plan trees

* link:spark-sql-Expression.adoc[Expression] for expression trees
====
