== Dataset

*Dataset* is an experimental feature of Spark SQL first introduced in Apache Spark 1.6.0. It aims at offering simplicity of link:spark-sql-dataframe.adoc[DataFrames] with strong type-safety (of Scala the programming language).

A `Dataset` object requires a link:spark-sql-sqlcontext.adoc[SQLContext], a <<QueryExecution, QueryExecution>>, and an <<Encoder, Encoder>>.

NOTE: `SQLContext` and `QueryExecution` are transient and do not participate in serialization process. The only _firmly-tied_ feature of a Dataset is the Encoder.

A `Dataset` is <<Queryable, Queryable>> and `Serializable`, i.e. can be saved to a persistent storage.

A Dataset has a <<schema, schema>>.

You can convert a Dataset to a DataFrame (using `toDF()` method) or an RDD (using `rdd` method).

=== [[schema]] Schema

A Dataset has a *schema* that is available as `schema`.

You may also use the following methods to learn about the schema:

* `printSchema(): Unit`
* `explain(): Unit`
* `explain(extended: Boolean): Unit`

=== [[plans]] Logical and Physical Plans

CAUTION: FIXME

=== [[Encoder]] Encoder

CAUTION: FIXME

It works with the type of the accompanying Dataset.

=== [[QueryExecution]] QueryExecution

CAUTION: FIXME

NOTE: It is a transient feature of a Dataset, i.e. it is not preserved across serializations.

=== [[Queryable]] Queryable

CAUTION: FIXME
