== [[ExecutorAllocationClient]] ExecutorAllocationClient

`ExecutorAllocationClient` is a <<contract, contract>> for clients to communicate with a cluster manager to request or kill executors.

=== [[contract]] ExecutorAllocationClient Contract

[source, scala]
----
trait ExecutorAllocationClient {
  def getExecutorIds(): Seq[String]
  def requestTotalExecutors(numExecutors: Int, localityAwareTasks: Int, hostToLocalTaskCount: Map[String, Int]): Boolean
  def requestExecutors(numAdditionalExecutors: Int): Boolean
  def killExecutor(executorId: String): Boolean
  def killExecutors(executorIds: Seq[String]): Seq[String]
  def killExecutorsOnHost(host: String): Boolean
}
----

NOTE: `ExecutorAllocationClient` is a `private[spark]` contract.

.ExecutorAllocationClient Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[getExecutorIds]] `getExecutorIds`
| Finds identifiers of the executors in use.

Used when link:spark-sparkcontext.adoc#getExecutorIds[`SparkContext` calculates the executors in use] and also when link:spark-streaming/spark-streaming-dynamic-allocation.adoc[Spark Streaming manages executors].

| [[requestTotalExecutors]] `requestTotalExecutors`
a| Updates the cluster manager with the exact number of executors desired. It returns whether the request has been acknowledged by the cluster manager (`true`) or not (`false`).

Used when:

* link:spark-sparkcontext.adoc#requestTotalExecutors[`SparkContext` requests executors] (for coarse-grained scheduler backends only).

* `ExecutorAllocationManager` link:spark-ExecutorAllocationManager.adoc#start[starts], does link:spark-ExecutorAllocationManager.adoc#updateAndSyncNumExecutorsTarget[updateAndSyncNumExecutorsTarget], and link:spark-ExecutorAllocationManager.adoc#addExecutors[addExecutors].

* Streaming `ExecutorAllocationManager` link:spark-streaming/spark-streaming-ExecutorAllocationManager.adoc#requestExecutors[requests executors].

* link:yarn/spark-yarn-yarnschedulerbackend.adoc#stop[`YarnSchedulerBackend` stops].

| [[requestExecutors]] `requestExecutors`
| Requests additional executors from a cluster manager and returns whether the request has been acknowledged by the cluster manager (`true`) or not (`false`).

Used when link:spark-sparkcontext.adoc#requestExecutors[`SparkContext` requests additional executors] (for coarse-grained scheduler backends only).

| [[killExecutor]] `killExecutor`
a| Requests a cluster manager to kill a single executor that is no longer in use and returns whether the request has been acknowledged by the cluster manager (`true`) or not (`false`).

The default implementation simply calls <<killExecutors, killExecutors>> (with a single-element collection of executors to kill).

Used when:

* `ExecutorAllocationManager` link:spark-ExecutorAllocationManager.adoc#removeExecutor[removes an executor].

* `SparkContext` link:spark-sparkcontext.adoc#killExecutors[is requested to kill executors].

* Streaming `ExecutorAllocationManager` link:spark-streaming/spark-streaming-ExecutorAllocationManager.adoc#killExecutor[is requested to kill executors].

| [[killExecutors]] `killExecutors`
| Requests that a cluster manager to kill one or many executors that are no longer in use and returns whether the request has been acknowledged by the cluster manager (`true`) or not (`false`).

_Interestingly_, it is only used for <<killExecutor, killExecutor>>.

| [[killExecutorsOnHost]] `killExecutorsOnHost`
| Used exclusively when `BlacklistTracker` kills blacklisted executors.

|===
