=== TaskSets

A *TaskSet* is a set of tasks submitted together (to link:spark-taskscheduler.adoc[Task Scheduler]) that belong to a single link:spark-dagscheduler-stages.adoc[stage] and an attempt.

A TaskSet represents the missing partitions of a stage.

The pair of a stage and an attempt uniquely describes a TaskSet and that is what you can see in the logs:

```
TaskSet [stageId].[stageAttemptId]
```

TaskSet has *priority* and *properties*. Priority is used in FIFO scheduling mode. Properties are the properties of the first job in a stage.

CAUTION: FIXME Where are `properties` of a TaskSet used?

A TaskSet contains a fully-independent sequence of tasks that can run right away based on the data that is already on the cluster, e.g. map output files from previous stages, though it may fail if this data becomes unavailable.

TaskSet can be submitted (consult link:spark-taskscheduler.adoc#contract[TaskScheduler Contract]).

=== Priority Field and FIFO Scheduling

A TaskSet has `priority` field that turns into the *priority* field's value of link:spark-tasksetmanager.adoc[TaskSetManager] (which is a Schedulable).

The `priority` field is used in `FIFOSchedulingAlgorithm` in which equal priorities give stages an advantage (not to say _priority_).

`FIFOSchedulingAlgorithm` is only used for `FIFO` scheduling mode in a `Pool` which is a Schedulable collection of `Schedulable`'s.

Effectively, the `priority` field is the job's id of the first job this stage was part of (for FIFO scheduling).
