== ContinuousQueryManager

NOTE: `ContinuousQueryManager` is an experimental feature of Spark 2.0.0.

A `ContinuousQueryManager` is the Management API for Continuous Queries to manage link:spark-sql-continuousquery.adoc[ContinuousQuery] instances per single `SQLContext`.

You can access `ContinuousQueryManager` for the current session using link:spark-sql-sqlcontext.adoc#accessing-ContinuousQueryManager[SQLContext.streams] method. It is lazily created when a `SQLContext` instance starts.

[source, scala]
----
scala> val queries = sqlContext.streams
queries: org.apache.spark.sql.ContinuousQueryManager = org.apache.spark.sql.ContinuousQueryManager@3b22bcad
----

NOTE: There is a single `ContinuousQueryManager` instance per `SQLContext` session.

=== [[startQuery]] startQuery

[source, scala]
----
startQuery(
  name: String,
  checkpointLocation: String,
  df: DataFrame,
  sink: Sink,
  trigger: Trigger = ProcessingTime(0)): ContinuousQuery
----

`startQuery` is a `private[sql]` method to start a link:spark-sql-continuousquery.adoc[ContinuousQuery].

=== [[ContinuousQueryManager-active]] Return All Active Continuous Queries per SQLContext

[source, scala]
----
active: Array[ContinuousQuery]
----

`active` method returns a collection of link:spark-sql-continuousquery.adoc[ContinuousQuery] instances for the current `SQLContext`.

=== [[ContinuousQueryManager-get]] Getting Active Continuous Query By Name

[source, scala]
----
get(name: String): ContinuousQuery
----

`get` method returns a link:spark-sql-continuousquery.adoc[ContinuousQuery] by `name`.

It may throw an `IllegalArgumentException` when no ContinuousQuery exists for the `name`.

```
java.lang.IllegalArgumentException: There is no active query with name hello
  at org.apache.spark.sql.ContinuousQueryManager$$anonfun$get$1.apply(ContinuousQueryManager.scala:59)
  at org.apache.spark.sql.ContinuousQueryManager$$anonfun$get$1.apply(ContinuousQueryManager.scala:59)
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
  at scala.collection.AbstractMap.getOrElse(Map.scala:59)
  at org.apache.spark.sql.ContinuousQueryManager.get(ContinuousQueryManager.scala:58)
  ... 49 elided
```

=== [[ContinuousQueryListener]] ContinuousQueryListener

CAUTION: FIXME

`ContinuousQueryListener` is an interface for listening to query life cycle events, i.e. a query start, progress and termination events.
