== [[StorageStatusListener]] StorageStatusListener -- Spark Listener To Track BlockManagers

`StorageStatusListener` is a link:spark-SparkListener.adoc[SparkListener] that link:spark-webui-SparkUI.adoc[web UI] uses to track status of every link:spark-blockmanager.adoc[BlockManager] in a Spark application.

NOTE: `StorageStatusListener` is created and registered when `SparkUI` link:spark-webui-SparkUI.adoc#create[is created]. It is later used to create link:spark-webui-executors-ExecutorsListener.adoc[ExecutorsListener] and link:spark-webui-StorageListener.adoc[StorageListener] Spark listeners.

.StorageStatusListener Event Handlers
[cols="1,2",options="header",width="100%"]
|===
| Event Handler
| Description

| [[onBlockManagerAdded]] `onBlockManagerAdded`
| Adds an executor id with link:spark-blockmanager-StorageStatus.adoc[StorageStatus] (with link:spark-blockmanager.adoc[BlockManager] and maximum memory on the executor) to <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry.

Removes any other `BlockManager` that may have been registered for the executor earlier in <<deadExecutorStorageStatus, deadExecutorStorageStatus>> internal registry.

| `onBlockManagerRemoved`
| Removes an executor from <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry and adds the removed link:spark-blockmanager-StorageStatus.adoc[StorageStatus] to <<deadExecutorStorageStatus, deadExecutorStorageStatus>> internal registry.

Removes the oldest link:spark-blockmanager-StorageStatus.adoc[StorageStatus] when the number of entries in <<deadExecutorStorageStatus, deadExecutorStorageStatus>> is bigger than link:spark-webui.adoc#spark.ui.retainedDeadExecutors[spark.ui.retainedDeadExecutors].

| `onBlockUpdated`
| Updates link:spark-blockmanager-StorageStatus.adoc[StorageStatus] for an executor in <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry, i.e. removes a block for link:spark-rdd-StorageLevel.adoc[`NONE` storage level] and updates otherwise.

| `onUnpersistRDD`
| Removes the RDD blocks for the unpersisted `rddId` from every link:spark-blockmanager-StorageStatus.adoc[StorageStatus] in <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry.
|===

[[internal-registries]]
.StorageStatusListener's Internal Registries and Counters
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[deadExecutorStorageStatus]] `deadExecutorStorageStatus`
| Collection of link:spark-blockmanager-StorageStatus.adoc[StorageStatus] of removed/inactive `BlockManagers`.

Accessible using <<deadStorageStatusList, deadStorageStatusList>> method.

Adds an element when `StorageStatusListener` <<onBlockManagerRemoved, handles a BlockManager being removed>> (possibly removing one element from the head when the number of elements are above link:spark-webui.adoc#spark.ui.retainedDeadExecutors[spark.ui.retainedDeadExecutors] property).

Removes an element when `StorageStatusListener` <<onBlockManagerAdded, handles a new BlockManager>> (per executor) so the executor is not longer dead.

| [[executorIdToStorageStatus]] `executorIdToStorageStatus`
| Lookup table of link:spark-blockmanager-StorageStatus.adoc[StorageStatus] per executor (including the driver).

Adds an entry when `StorageStatusListener` <<onBlockManagerAdded, handles a new BlockManager>>.

Removes an entry when `StorageStatusListener` <<onBlockManagerRemoved, handles a BlockManager being removed>>.

Updates `StorageStatus` of an executor when `StorageStatusListener` <<updateStorageStatus, handles StorageStatus updates>>.
|===

=== [[updateStorageStatus]] `updateStorageStatus` Internal Method

[source, scala]
----
updateStorageStatus(unpersistedRDDId: Int)
----

`updateStorageStatus` updates...FIXME

NOTE: `storageStatusList` is used when...FIXME

=== [[storageStatusList]] `storageStatusList` Method

[source, scala]
----
storageStatusList: Seq[StorageStatus]
----

`storageStatusList` gives a collection of link:spark-blockmanager-StorageStatus.adoc[StorageStatus] (from <<executorIdToStorageStatus, executorIdToStorageStatus>> internal registry).

[NOTE]
====
`storageStatusList` is used when:

* `StorageStatusListener` does <<updateStorageStatus, updateStorageStatus>>
* `ExecutorsListener` does link:spark-webui-executors-ExecutorsListener.adoc#activeStorageStatusList[activeStorageStatusList]
* `StorageListener` does link:spark-webui-StorageListener.adoc#activeStorageStatusList[activeStorageStatusList]
====

=== [[deadStorageStatusList]] `deadStorageStatusList` Method

[source, scala]
----
deadStorageStatusList: Seq[StorageStatus]
----

`deadStorageStatusList` gives <<deadExecutorStorageStatus, deadExecutorStorageStatus>> internal registry.

NOTE: `deadStorageStatusList` is used when `ExecutorsListener` link:spark-webui-executors-ExecutorsListener.adoc#deadStorageStatusList[is requested for inactive/dead BlockManagers].
