== QueryPlanner

`QueryPlanner` transforms a link:spark-sql-logical-plan.adoc[LogicalPlan] through a chain of `GenericStrategy` objects to produce a `PhysicalPlan`, e.g. link:spark-sql-spark-plan.adoc[SparkPlan] for <<SparkPlanner, SparkPlanner>> or the <<HiveSessionState, custom SparkPlanner for HiveSessionState>>.

`QueryPlanner` contract defines three operations:

* `strategies` that returns a collection of `GenericStrategy` objects.

* `planLater(plan: LogicalPlan): PhysicalPlan` that skips the current plan.

* `plan(plan: LogicalPlan)` that returns an `Iterator[PhysicalPlan]` with elements being the result of applying each `GenericStrategy` object from `strategies` collection to `plan` input parameter.

=== [[SparkStrategies]] SparkStrategies

`SparkStrategies` is an abstract `QueryPlanner` for link:spark-sql-spark-plan.adoc[SparkPlan].

It serves as a source of concrete `Strategy` objects.

Among available `SparkStrategies` is <<SparkPlanner, SparkPlanner>>.

=== [[SparkPlanner]] SparkPlanner

`SparkPlanner` is a concrete `QueryPlanner` (extending <<SparkStrategies, SparkStrategies>>) that uses a link:spark-sparkcontext.adoc[SparkContext], a link:spark-sql-SQLConf.adoc[SQLConf], and a collection of `Strategy` objects (as `extraStrategies`).

It defines `numPartitions` method that is the value of link:spark-sql-settings.adoc#spark.sql.shuffle.partitions[spark.sql.shuffle.partitions] for the number of partitions to use for joins and aggregations.

`strategies` collection uses predefined `Strategy` objects as well as the constructor's `extraStrategies`.

Among the `Strategy` objects is `JoinSelection`.

=== [[HiveSessionState]] Custom SparkPlanner for HiveSessionState

`HiveSessionState` class uses an custom anonymous  <<SparkPlanner, SparkPlanner>> for `planner` method (part of `SessionState` contract).

The custom anonymous `SparkPlanner` uses `Strategy` objects defined in `HiveStrategies`.
