== [[SchedulableBuilder]] SchedulableBuilder Contract -- Builders of Schedulable Pools

`SchedulableBuilder` is the <<contract, abstraction>> of <<implementations, schedulable builders>> that manage a <<rootPool, root pool (of Schedulables)>>, which is to <<buildPools, build a pool>> and <<addTaskSetManager, register a new Schedulable (with the pool)>>.

`SchedulableBuilder` is a `private[spark]` Scala trait that is used exclusively by <<spark-scheduler-TaskSchedulerImpl.adoc#, TaskSchedulerImpl>> (the default Spark scheduler). When requested to <<spark-scheduler-TaskSchedulerImpl.adoc#initialize, initialize>>, `TaskSchedulerImpl` uses the <<spark-configuration-properties.adoc#spark.scheduler.mode, spark.scheduler.mode>> configuration property (default: `FIFO`) to select one of the <<implementations, available schedulable builders>>.

[[contract]]
.SchedulableBuilder Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| addTaskSetManager
a| [[addTaskSetManager]]

[source, scala]
----
addTaskSetManager(manager: Schedulable, properties: Properties): Unit
----

Registers a new <<spark-scheduler-Schedulable.adoc#, Schedulable>> with the <<rootPool, rootPool>>

Used exclusively when `TaskSchedulerImpl` is requested to <<spark-scheduler-TaskSchedulerImpl.adoc#submitTasks, submit tasks (of TaskSet) for execution>> (and registers a new <<spark-scheduler-TaskSetManager.adoc#, TaskSetManager>> for the `TaskSet`)

| buildPools
a| [[buildPools]]

[source, scala]
----
buildPools(): Unit
----

Builds a tree of <<spark-scheduler-Pool.adoc#, pools (of Schedulables)>>

Used exclusively when `TaskSchedulerImpl` is requested to <<spark-scheduler-TaskSchedulerImpl.adoc#initialize, initialize>> (and creates a <<spark-scheduler-TaskSchedulerImpl.adoc#schedulableBuilder, SchedulableBuilder>> per <<spark-configuration-properties.adoc#spark.scheduler.mode, spark.scheduler.mode>> configuration property)

| rootPool
a| [[rootPool]]

[source, scala]
----
rootPool: Pool
----

Root (top-level) <<spark-scheduler-Pool.adoc#, pool (of Schedulables)>>

Used when:

* `FIFOSchedulableBuilder` is requested to <<spark-scheduler-FIFOSchedulableBuilder.adoc#addTaskSetManager, addTaskSetManager>>

* `FairSchedulableBuilder` is requested to <<spark-scheduler-FairSchedulableBuilder.adoc#buildDefaultPool, buildDefaultPool>>, <<spark-scheduler-FairSchedulableBuilder.adoc#buildFairSchedulerPool, buildFairSchedulerPool>>, and <<spark-scheduler-FairSchedulableBuilder.adoc#addTaskSetManager, addTaskSetManager>>

|===

[[implementations]]
.SchedulableBuilders
[cols="1,3",options="header",width="100%"]
|===
| SchedulableBuilder
| Description

| <<spark-scheduler-FairSchedulableBuilder.adoc#, FairSchedulableBuilder>>
| [[FairSchedulableBuilder]] Used when the <<spark-configuration-properties.adoc#spark.scheduler.mode, spark.scheduler.mode>> configuration property is `FAIR`

| <<spark-scheduler-FIFOSchedulableBuilder.adoc#, FIFOSchedulableBuilder>>
| [[FIFOSchedulableBuilder]] Default `SchedulableBuilder` that is used when the <<spark-configuration-properties.adoc#spark.scheduler.mode, spark.scheduler.mode>> configuration property is `FIFO` (default)

|===
