== [[SparkUI]] SparkUI

`SparkUI` represents the web UI for a <<createLiveUI, Spark application>> and <<createHistoryUI, Spark History Server>>. It is <<creating-instance, created>> and bound when link:spark-sparkcontext-creating-instance-internals.adoc#ui[`SparkContext` is created] (with link:spark-webui.adoc#spark_ui_enabled[spark.ui.enabled] enabled).

NOTE: The only difference between `SparkUI` for a <<createLiveUI, Spark application>> and <<createHistoryUI, Spark History Server>> is that...**FIXME**

=== [[creating-instance]] Creating SparkUI Instance

[source, scala]
----
class SparkUI (
  val sc: Option[SparkContext],
  val conf: SparkConf,
  securityManager: SecurityManager,
  val environmentListener: EnvironmentListener,
  val storageStatusListener: StorageStatusListener,
  val executorsListener: ExecutorsListener,
  val jobProgressListener: JobProgressListener,
  val storageListener: StorageListener,
  val operationGraphListener: RDDOperationGraphListener,
  var appName: String,
  val basePath: String,
  val startTime: Long)
extends WebUI(securityManager,
  securityManager.getSSLOptions("ui"), SparkUI.getUIPort(conf),
  conf, basePath, "SparkUI")
----

When executed, `SparkUI` creates a link:spark-webui-stages.adoc[StagesTab] and does <<initialize, initialization>>.

NOTE: `SparkUI` is created when link:spark-sparkcontext-creating-instance-internals.adoc#ui[`SparkContext` is created] (with link:spark-webui.adoc#spark_ui_enabled[spark.ui.enabled] enabled). `SparkUI` gets the reference to the owning `SparkContext` and the other properties, i.e. link:spark-configuration.adoc[SparkConf], link:spark-sparkcontext.adoc#listenerBus[`LiveListenerBus` Event Bus], link:spark-webui-JobProgressListener.adoc[JobProgressListener], `SecurityManager`, `appName`, and `startTime`.

=== [[stop]] `stop` Method

=== [[initialize]] `initialize` Method

=== [[getSparkUser]] `getSparkUser` Method

=== [[createLiveUI]] `createLiveUI` Method

CAUTION: FIXME

=== [[createHistoryUI]] `createHistoryUI` Method

CAUTION: FIXME

=== [[appUIAddress]] `appUIAddress`

CAUTION: FIXME

=== [[createHistoryUI]] `createHistoryUI` Method

=== [[create]] `create` Factory Method

[source, scala]
----
create(
  sc: Option[SparkContext],
  conf: SparkConf,
  listenerBus: SparkListenerBus,
  securityManager: SecurityManager,
  appName: String,
  basePath: String = "",
  jobProgressListener: Option[JobProgressListener] = None,
  startTime: Long): SparkUI
----

`create` creates a `SparkUI`. It is an internal helper method to create a web UI for <<createLiveUI, a Spark application>> and <<createHistoryUI, Spark History Server>>.

CAUTION: FIXME
