== [[Schedulable]] Schedulable

`Schedulable` is a <<contract, contract of schedulable entities>>.

NOTE: `Schedulable` is a `private[spark]` Scala trait. You can find the sources in https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/Schedulable.scala[org.apache.spark.scheduler.Schedulable].

There are currently two types of `Schedulable` entities in Spark:

* link:spark-taskscheduler-pool.adoc[Pool]
* link:spark-TaskSetManager.adoc[TaskSetManager]

=== [[contract]] Schedulable Contract

Every `Schedulable` follows the following contract:

* It has a `name`.
+
[source, scala]
----
name: String
----

* It has a `parent` link:spark-taskscheduler-pool.adoc[Pool] (of other `Schedulables`).
+
[source, scala]
----
parent: Pool
----
+
With the `parent` property you could build a tree of `Schedulables`

* It has a `schedulingMode`, `weight`, `minShare`, `runningTasks`, `priority`, `stageId`.
+
[source, scala]
----
schedulingMode: SchedulingMode
weight: Int
minShare: Int
runningTasks: Int
priority: Int
stageId: Int
----

* It manages a <<schedulableQueue, collection of Schedulables>> and can add or remove one.
+
[source, scala]
----
schedulableQueue: ConcurrentLinkedQueue[Schedulable]
addSchedulable(schedulable: Schedulable): Unit
removeSchedulable(schedulable: Schedulable): Unit
----
+
NOTE: `schedulableQueue` is https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html[java.util.concurrent.ConcurrentLinkedQueue].

* It can query for a `Schedulable` by name.
+
[source, scala]
----
getSchedulableByName(name: String): Schedulable
----

* It can <<getSortedTaskSetQueue, return a sorted collection of TaskSetManagers>>.

[[executorLost]]
* It can be informed about lost link:spark-Executor.adoc[executors].
+
[source, scala]
----
executorLost(executorId: String, host: String, reason: ExecutorLossReason): Unit
----
+
It is called by link:spark-TaskSchedulerImpl.adoc#removeExecutor[TaskSchedulerImpl] to inform link:spark-TaskSetManager.adoc[TaskSetManagers] about executors being lost.

* It checks for *speculatable tasks*.
+
[source, scala]
----
checkSpeculatableTasks(): Boolean
----
+
CAUTION: FIXME What are speculatable tasks?

==== [[getSortedTaskSetQueue]] getSortedTaskSetQueue

[source, scala]
----
getSortedTaskSetQueue: ArrayBuffer[TaskSetManager]
----

`getSortedTaskSetQueue` is used in link:spark-TaskSchedulerImpl.adoc#resourceOffers[`TaskSchedulerImpl` to handle resource offers] (to link:spark-TaskSetManager.adoc#executorAdded[let every TaskSetManager know about a new executor ready to execute tasks]).

==== [[schedulableQueue]] schedulableQueue

[source, scala]
----
schedulableQueue: ConcurrentLinkedQueue[Schedulable]
----

`schedulableQueue` is used in link:spark-SparkContext.adoc#getAllPools[SparkContext.getAllPools].
