== [[SQLMetric]] SQLMetric -- Physical Operator Metric

`SQLMetric` is a link:spark-accumulators.adoc[accumulator] metric used to monitor performance of link:spark-sql-SparkPlan.adoc[physical operators].

NOTE: Use *Details for Query* page in link:spark-webui-sql.adoc#ExecutionPage[SQL tab] in web UI to see the metrics of a structured query.

[[metricType]][[initValue]]
`SQLMetric` takes a metric type and an initial value when created.

[[metrics-types]]
.Metric Types and Corresponding Create Methods (in alphabetical order)
[cols="1,1,1,2",options="header",width="100%"]
|===
| Metric Type
| Create Method
| Failed Values Counted?
| Description

| [[size]] `size`
| [[createSizeMetric]] `createSizeMetric`
| no
| Used when...

| [[sum]] `sum`
| [[createMetric]] `createMetric`
| no
| Used when...

| [[timing]] `timing`
| [[createTimingMetric]] `createTimingMetric`
| no
| Used when...
|===

=== [[postDriverMetricUpdates]] Posting Driver-Side Updates to SQLMetrics -- `postDriverMetricUpdates` Method

[source, scala]
----
postDriverMetricUpdates(
  sc: SparkContext,
  executionId: String,
  metrics: Seq[SQLMetric]): Unit
----

`postDriverMetricUpdates` posts a link:spark-webui-SQLListener.adoc#SparkListenerDriverAccumUpdates[SparkListenerDriverAccumUpdates] to a link:spark-SparkListenerBus.adoc[SparkListenerBus] when `executionId` is specified.

NOTE: `postDriverMetricUpdates` used in link:spark-sql-SparkPlan-BroadcastExchangeExec.adoc#relationFuture[BroadcastExchangeExec], `FileSourceScanExec` and  `SubqueryExec` physical operators.
