== [[ShuffleMetricsSource]] ShuffleMetricsSource -- Metrics Source of BlockManager for Shuffle-Related Metrics

`ShuffleMetricsSource` is the link:spark-metrics-Source.adoc[metrics source] of link:spark-BlockManager.adoc[BlockManagers] for <<metrics, shuffle-related metrics>> that is registered when a Spark application runs in a non-local / cluster mode.

`ShuffleMetricsSource` is <<creating-instance, created>> exclusively when `BlockManager` is requested for the link:spark-BlockManager.adoc#shuffleMetricsSource[shuffleMetricsSource].

When <<creating-instance, created>>, `ShuffleMetricsSource` gets a <<metricSet, MetricSet>> that `BlockManager` requests from the link:spark-ShuffleClient.adoc#shuffleMetrics[ShuffleClient] (only link:spark-Executor.adoc#creating-instance-BlockManager-shuffleMetricsSource[when in a non-local / cluster mode]).

CAUTION: FIXME Figure of the interaction between `ShuffleMetricsSource`, `BlockManager` and `ShuffleClient`, `Executor`.

[[sourceName]]
`ShuffleMetricsSource` is registered under the following name per the type of a `BlockManager`:

* *NettyBlockTransfer* when link:spark-ExternalShuffleService.adoc#spark.shuffle.service.enabled[spark.shuffle.service.enabled] configuration property is off (`false`)

* *ExternalShuffle* when link:spark-ExternalShuffleService.adoc#spark.shuffle.service.enabled[spark.shuffle.service.enabled] configuration property is on (`true`)

NOTE: link:spark-ExternalShuffleService.adoc#spark.shuffle.service.enabled[spark.shuffle.service.enabled] configuration property is off (`false`) by default.

[[metrics]]
.ShuffleMetricsSource's Gauge Metrics (in alphabetical order)
[width="100%",cols="1,1,2",options="header"]
|===
| Name
| Type
| Description
|===

You can access the `ShuffleMetricsSource` <<metrics, metrics>> using the FIXME port.

```
// Make sure that a cluster mode is used
// e.g. Spark Standalone cluster
// FIXME Port of the executor
$ http --follow http://localhost:FIXME/metrics/json
```

=== [[creating-instance]] Creating ShuffleMetricsSource Instance

`ShuffleMetricsSource` takes the following when created:

* [[sourceName]] Source name
* [[metricSet]] Dropwizard Metrics' https://metrics.dropwizard.io/3.1.0/apidocs/com/codahale/metrics/MetricSet.html[MetricSet]
