== MemoryConsumer

`MemoryConsumer` is the <<contract, contract for memory consumers of `TaskMemoryManager`>> with support for <<spill, spilling>>.

A `MemoryConsumer` basically tracks <<used, how much memory is allocated>>.

Creating a `MemoryConsumer` requires a link:spark-taskscheduler-taskmemorymanager.adoc[TaskMemoryManager] with optional `pageSize` and a `MemoryMode`.

NOTE: If not specified, `pageSize` defaults to link:spark-taskscheduler-taskmemorymanager.adoc#pageSizeBytes[TaskMemoryManager.pageSizeBytes] and `ON_HEAP` memory mode.

=== [[contract]] MemoryConsumer Contract

CAUTION: FIXME the contract

==== [[used]] Memory Allocated (used Registry)

`used` is the amount of memory in use (i.e. allocated) by the `MemoryConsumer`.

==== [[spill]] spill method

[source, java]
----
abstract long spill(long size, MemoryConsumer trigger) throws IOException
----

==== [[allocateArray]] Deallocate LongArray (freeArray method)

[source, java]
----
void freeArray(LongArray array)
----

`freeArray` <<freePage, deallocates the `LongArray`>>.

==== [[freePage]] Deallocate MemoryBlock (freePage method)

[source, java]
----
protected void freePage(MemoryBlock page)
----

`freePage` is a protected method to deallocate the `MemoryBlock`.

Internally, it decrements <<used, used>> registry by the size of `page` and link:spark-taskscheduler-taskmemorymanager.adoc#freePage[frees the page].

==== [[allocateArray]] Allocate LongArray (allocateArray method)

[source, java]
----
LongArray allocateArray(long size)
----

`allocateArray` allocates `LongArray` of `size` length.

Internally, it link:spark-taskscheduler-taskmemorymanager.adoc#allocatePage[allocates a page] for the requested `size`. The size is recorded in the internal <<used, used>> counter.

However, if it was not possible to allocate the `size` memory, it link:spark-taskscheduler-taskmemorymanager.adoc#showMemoryUsage[shows the current memory usage] and a `OutOfMemoryError` is thrown.

```
Unable to acquire [required] bytes of memory, got [got]
```

==== [[acquireMemory]] Acquiring Memory (acquireMemory method)

[source, java]
----
long acquireMemory(long size)
----

`acquireMemory` link:spark-taskscheduler-taskmemorymanager.adoc#acquireExecutionMemory[acquires execution memory of `size` size]. The memory is recorded in <<used, used>> registry.
