== [[BroadcastManager]] BroadcastManager

*Broadcast Manager* (`BroadcastManager`) is a Spark service to manage link:spark-broadcast.adoc[broadcast values] in Spark jobs. It is created for a Spark application as part of link:spark-sparkcontext.adoc#creating-instance[SparkContext's initialization] and is a simple wrapper around <<BroadcastFactory, BroadcastFactory>>.

Broadcast Manager tracks the number of broadcast values (using the internal field `nextBroadcastId`).

The idea is to transfer values used in transformations from a driver to executors in a most effective way so they are copied once and used many times by tasks (rather than being copied every time a task is launched).

When `BroadcastManager` is initialized an instance of <<BroadcastFactory, BroadcastFactory>> is created based on <<spark_broadcast_factory, spark.broadcast.factory>> setting.

=== [[newBroadcast]] `newBroadcast` Method

[source, scala]
----
newBroadcast[T](value_ : T, isLocal: Boolean): Broadcast[T]
----

`newBroadcast` simply requests the <<BroadcastFactory-newBroadcast, pluggable `BroadcastFactory` to create a new broadcast variable>>.

NOTE: `newBroadcast` is executed for link:spark-sparkcontext.adoc#broadcast[`SparkContext.broadcast` method] and when link:spark-service-mapoutputtracker.adoc#serializeMapStatuses[`MapOutputTracker` serializes ``MapStatus``es].

=== [[BroadcastFactory]] `BroadcastFactory` -- Pluggable Interface for Broadcast Variable Factories

`BroadcastFactory` is a pluggable interface for broadcast implementations in Spark. It is exclusively used and instantiated inside of `BroadcastManager` to manage broadcast variables.

.`BroadcastFactory` Methods
[frame="topbot",cols="1,2",options="header",width="100%"]
|======================
| Method | Description
| [[initialize]] `initialize` |
| [[BroadcastFactory-newBroadcast]] `newBroadcast` |
| [[unbroadcast]] `unbroadcast` |
| [[stop]] `stop` |
|======================

NOTE: link:spark-TorrentBroadcastFactory.adoc[TorrentBroadcastFactory] is the only one implementation of `BroadcastFactory`.

=== [[settings]] Settings

.Settings
[width="100%",cols="1,1,3",frame="topbot",options="header,footer"]
|======================
|Name | Default value |Description

| [[spark_broadcast_blockSize]] `spark.broadcast.blockSize` | `4m` | The size of a block

Used when link:spark-TorrentBroadcast.adoc#writeBlocks[`TorrentBroadcast` stores brodcast blocks to `BlockManager`].

| [[spark_broadcast_compress]] `spark.broadcast.compress` | `true` | The flag to enable compression.

Refer to link:spark-CompressionCodec.adoc[CompressionCodec].

Used when link:spark-TorrentBroadcast.adoc#creating-instance[`TorrentBroadcast` is created] and later when link:spark-TorrentBroadcast.adoc#writeBlocks[it stores broadcast blocks to `BlockManager`]. Also in link:spark-SerializerManager.adoc#settings[SerializerManager].

| [[spark_broadcast_factory]] `spark.broadcast.factory` | link:spark-TorrentBroadcastFactory.adoc[org.apache.spark.broadcast.TorrentBroadcastFactory] | The fully-qualified class name for the implementation of `BroadcastFactory` interface.
|======================
