== [[AbstractApplicationResource]] AbstractApplicationResource

`AbstractApplicationResource` is...FIXME

[[paths]]
.AbstractApplicationResource's Paths
[cols="1,1,2",options="header",width="100%"]
|===
| Path
| HTTP Method
| Description

| `storage/rdd`
| GET
| <<rddList, rddList>>

| `jobs`
| GET
| <<jobsList, jobsList>>

| `jobs/{jobId: \d+}`
| GET
| <<oneJob, oneJob>>

| `executors`
| GET
| <<executorList, executorList>>

| `allexecutors`
| GET
| <<allExecutorList, allExecutorList>>

| `storage/rdd/{rddId: \d+}`
| GET
| <<rddData, rddData>>

| `environment`
| GET
| <<environmentInfo, environmentInfo>>

| _others_
|
|
|===

=== [[rddList]] `rddList` Method

[source, scala]
----
rddList(): Seq[RDDStorageInfo]
----

`rddList`...FIXME

NOTE: `rddList` is used when...FIXME

=== [[environmentInfo]] `environmentInfo` Method

[source, scala]
----
environmentInfo(): ApplicationEnvironmentInfo
----

`environmentInfo`...FIXME

NOTE: `environmentInfo` is used when...FIXME

=== [[rddData]] `rddData` Method

[source, scala]
----
rddData(@PathParam("rddId") rddId: Int): RDDStorageInfo
----

`rddData`...FIXME

NOTE: `rddData` is used when...FIXME

=== [[allExecutorList]] `allExecutorList` Method

[source, scala]
----
allExecutorList(): Seq[ExecutorSummary]
----

`allExecutorList`...FIXME

NOTE: `allExecutorList` is used when...FIXME

=== [[executorList]] `executorList` Method

[source, scala]
----
executorList(): Seq[ExecutorSummary]
----

`executorList`...FIXME

NOTE: `executorList` is used when...FIXME

=== [[oneJob]] `oneJob` Method

[source, scala]
----
oneJob(@PathParam("jobId") jobId: Int): JobData
----

`oneJob`...FIXME

NOTE: `oneJob` is used when...FIXME

=== [[jobsList]] `jobsList` Method

[source, scala]
----
jobsList(@QueryParam("status") statuses: JList[JobExecutionStatus]): Seq[JobData]
----

`jobsList`...FIXME

NOTE: `jobsList` is used when...FIXME
