== [[AppStatusListener]] AppStatusListener

`AppStatusListener` is a link:spark-SparkListener.adoc[SparkListener] that...FIXME

[[AppStatusListener-handlers]]
.AppStatusListener's Event Handlers
[width="100%",cols="1,1",options="header"]
|===
| Event
| Handler

| `SparkListenerBlockUpdated`
| <<onBlockUpdated, onBlockUpdated>>

| `SparkListenerStageSubmitted`
| <<onStageSubmitted, onStageSubmitted>>
|===

[[internal-registries]]
.AppStatusListener's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `liveRDDs`
| [[liveRDDs]] link:spark-core-LiveRDD.adoc[LiveRDDs] by RDD ID
|===

=== [[onStageSubmitted]] `onStageSubmitted` Method

[source, scala]
----
onStageSubmitted(event: SparkListenerStageSubmitted): Unit
----

NOTE: `onStageSubmitted` is part of link:spark-SparkListener.adoc#onStageSubmitted[SparkListener Contract] to...FIXME.

`onStageSubmitted`...FIXME

=== [[update]] `update` Internal Method

[source, scala]
----
update(entity: LiveEntity, now: Long, last: Boolean = false): Unit
----

`update` simply requests the `LiveEntity` to link:spark-core-LiveEntity.adoc#write[write] (with the <<kvstore, ElementTrackingStore>> as the store and the `last` flag as `checkTriggers` flag).

NOTE: `update` is used in event handlers (i.e. `onApplicationStart`, `onExecutorRemoved`, `onJobEnd`, `onStageSubmitted`, `onTaskEnd`, `onStageCompleted`), <<liveUpdate, liveUpdate>>, <<maybeUpdate, maybeUpdate>>, <<flush, flush>> and <<updateRDDBlock, updateRDDBlock>>.

=== [[flush]] `flush` Internal Method

[source, scala]
----
flush(): Unit
----

`flush`...FIXME

NOTE: `flush` is used when...FIXME

=== [[maybeUpdate]] `maybeUpdate` Internal Method

[source, scala]
----
maybeUpdate(entity: LiveEntity, now: Long): Unit
----

`maybeUpdate`...FIXME

NOTE: `maybeUpdate` is used when...FIXME

=== [[liveUpdate]] `liveUpdate` Internal Method

[source, scala]
----
liveUpdate(entity: LiveEntity, now: Long): Unit
----

`liveUpdate`...FIXME

NOTE: `liveUpdate` is used when...FIXME

=== [[updateRDDBlock]] `updateRDDBlock` Internal Method

[source, scala]
----
updateRDDBlock(event: SparkListenerBlockUpdated, block: RDDBlockId): Unit
----

`updateRDDBlock`...FIXME

NOTE: `updateRDDBlock` is used exclusively when `AppStatusListener` is requested to <<onBlockUpdated, handle a SparkListenerBlockUpdated event>> (for a link:spark-blockdatamanager.adoc#RDDBlockId[RDDBlockId]).

=== [[updateStreamBlock]] `updateStreamBlock` Internal Method

[source, scala]
----
updateStreamBlock(event: SparkListenerBlockUpdated, stream: StreamBlockId): Unit
----

`updateStreamBlock`...FIXME

NOTE: `updateStreamBlock` is used exclusively when `AppStatusListener` is requested to <<onBlockUpdated, handle a SparkListenerBlockUpdated event>> (for a link:spark-blockdatamanager.adoc#StreamBlockId[StreamBlockId]).

=== [[onBlockUpdated]] Intercepting SparkListenerBlockUpdated Events -- `onBlockUpdated` Handler Method

[source, scala]
----
onBlockUpdated(event: SparkListenerBlockUpdated): Unit
----

NOTE: `onBlockUpdated` is part of link:spark-SparkListener.adoc#onBlockUpdated[SparkListener Contract] to...FIXME.

`onBlockUpdated` simply dispatches to the following event-specific handlers (per link:spark-blockdatamanager.adoc#BlockId[BlockId] type):

* <<updateRDDBlock, updateRDDBlock>> for link:spark-blockdatamanager.adoc#RDDBlockId[RDDBlockIds]

* <<updateStreamBlock, updateStreamBlock>> for link:spark-blockdatamanager.adoc#StreamBlockId[StreamBlockIds]

* Ignores (_swallows_) the `SparkListenerBlockUpdated` event for the other types
