== Settings

=== [[spark.yarn.cache.types]] spark.yarn.cache.types

`spark.yarn.cache.types` is an internal setting...

=== [[spark.yarn.cache.visibilities]] spark.yarn.cache.visibilities

`spark.yarn.cache.visibilities` is an internal setting...

=== [[spark.yarn.cache.timestamps]] spark.yarn.cache.timestamps

`spark.yarn.cache.timestamps` is an internal setting...

=== [[spark.yarn.cache.filenames]] spark.yarn.cache.filenames

`spark.yarn.cache.filenames` is an internal setting...

=== [[spark.yarn.cache.sizes]] spark.yarn.cache.sizes

`spark.yarn.cache.sizes` is an internal setting...

=== [[spark.yarn.cache.confArchive]] spark.yarn.cache.confArchive

`spark.yarn.cache.confArchive` is an internal setting...

=== [[spark.yarn.secondary.jars]] spark.yarn.secondary.jars

`spark.yarn.secondary.jars` is...

=== [[spark.yarn.executor.nodeLabelExpression]] spark.yarn.executor.nodeLabelExpression

`spark.yarn.executor.nodeLabelExpression` is a node label expression for executors.

=== [[spark.yarn.launchContainers]] spark.yarn.launchContainers

`spark.yarn.launchContainers` (default: `true`)...FIXME

=== [[spark.yarn.containerLauncherMaxThreads]] spark.yarn.containerLauncherMaxThreads

`spark.yarn.containerLauncherMaxThreads` (default: `25`)...FIXME

=== [[spark.yarn.executor.failuresValidityInterval]] spark.yarn.executor.failuresValidityInterval

`spark.yarn.executor.failuresValidityInterval` (default: `-1L`) is an interval (in milliseconds) after which Executor failures will be considered independent and not accumulate towards the attempt count.

=== [[spark.yarn.submit.waitAppCompletion]] spark.yarn.submit.waitAppCompletion

`spark.yarn.submit.waitAppCompletion` (default: `true`) is a flag to control whether to wait for the application to finish before exiting the launcher process in cluster mode.

=== [[spark.yarn.executor.memoryOverhead]] spark.yarn.executor.memoryOverhead

`spark.yarn.executor.memoryOverhead` (in MiBs)

=== [[spark.yarn.am.cores]] spark.yarn.am.cores

`spark.yarn.am.cores` (default: `1`) sets the number of CPU cores for ApplicationMaster's JVM.

=== [[spark.yarn.driver.memoryOverhead]] spark.yarn.driver.memoryOverhead

`spark.yarn.driver.memoryOverhead` (in MiBs)

=== [[spark.yarn.am.memoryOverhead]] spark.yarn.am.memoryOverhead

`spark.yarn.am.memoryOverhead` (in MiBs)

=== [[spark.yarn.am.memory]] spark.yarn.am.memory

`spark.yarn.am.memory` (default: `512m`) sets the memory size of ApplicationMaster's JVM (in MiBs)

=== [[spark.yarn.stagingDir]] spark.yarn.stagingDir

`spark.yarn.stagingDir` is a staging directory used while submitting applications.

=== [[spark.yarn.preserve.staging.files]] spark.yarn.preserve.staging.files

`spark.yarn.preserve.staging.files` (default: `false`) controls whether to preserve temporary files in a staging directory (as pointed by <<spark.yarn.stagingDir, spark.yarn.stagingDir>>).

=== [[spark.yarn.credentials.file]] spark.yarn.credentials.file

`spark.yarn.credentials.file` ...
