== [[LogicalRelation]] LogicalRelation Logical Operator -- Adapter for BaseRelation

`LogicalRelation` is a link:spark-sql-LogicalPlan.adoc#LeafNode[leaf logical operator] that acts as an adapter for link:spark-sql-BaseRelation.adoc[BaseRelation] in a link:spark-sql-LogicalPlan.adoc[logical query plan].

[source, scala]
----
val q1 = spark.read.option("header", true).csv("../datasets/people.csv")
scala> println(q1.queryExecution.logical.numberedTreeString)
00 Relation[id#72,name#73,age#74] csv

val q2 = sql("select * from `csv`.`../datasets/people.csv`")
scala> println(q2.queryExecution.optimizedPlan.numberedTreeString)
00 Relation[_c0#175,_c1#176,_c2#177] csv
----

`LogicalRelation` is <<creating-instance, created>> when:

* `DataFrameReader` link:spark-sql-DataFrameReader.adoc#load[loads data from a data source that supports multiple paths] (through link:spark-sql-SparkSession.adoc#baseRelationToDataFrame[SparkSession.baseRelationToDataFrame])
* `DataFrameReader` link:spark-sql-DataFrameReader.adoc#jdbc[loads data from an external table using JDBC] (through link:spark-sql-SparkSession.adoc#baseRelationToDataFrame[SparkSession.baseRelationToDataFrame])
* `TextInputCSVDataSource` and `TextInputJsonDataSource` are requested to infer schema
* `ResolveSQLOnFile` converts a logical plan
* `FindDataSourceTable` converts a logical plan
* `RelationConversions` converts a logical plan
* `CreateTempViewUsing` runnable command is executed
* Structured Streaming's `FileStreamSource` creates batches of records

[[apply]]
[NOTE]
====
`LogicalRelation` is created using `apply` factory methods that accept <<relation, BaseRelation>> with optional <<catalogTable, CatalogTable>>.

[source, scala]
----
apply(relation: BaseRelation): LogicalRelation
apply(relation: BaseRelation, table: CatalogTable): LogicalRelation
----
====

=== [[creating-instance]] Creating LogicalRelation Instance

`LogicalRelation` takes the following when created:

* [[relation]] link:spark-sql-BaseRelation.adoc[BaseRelation]
* [[output]] Output schema `AttributeReferences`
* [[catalogTable]] Optional `CatalogTable`
