== [[HashAggregateExec]] HashAggregateExec Aggregate Physical Operator

`HashAggregateExec` is a link:spark-sql-SparkPlan.adoc#UnaryExecNode[unary physical operator] that link:spark-sql-whole-stage-codegen.adoc#CodegenSupport[supports code generation] (aka _codegen_).

`HashAggregateExec` is created when:

* link:spark-sql-SparkStrategy-Aggregation.adoc[Aggregation] strategy creates link:spark-sql-SparkPlan.adoc[execution plans] for an aggregate logical operator (with or no distinct)
* `StatefulAggregationStrategy` strategy creates plan for streaming `EventTimeWatermark` or `Aggregate` logical operators.

NOTE: `HashAggregateExec` is created exclusively in `AggUtils.createAggregate`.

=== [[creating-instance]] Creating HashAggregateExec Instance

`HashAggregateExec` takes the following when created:

* [[requiredChildDistributionExpressions]] Optional link:spark-sql-catalyst-Expression.adoc[expressions]
* [[groupingExpressions]] Collection of grouping `NamedExpressions`
* [[aggregateExpressions]] Collection of link:spark-sql-Expression-AggregateExpression.adoc[AggregateExpressions]
* [[aggregateAttributes]] Collection of link:spark-sql-catalyst-Attribute.adoc[Attributes]
* [[initialInputBufferOffset]] Initial offset
* [[resultExpressions]] Collection of output `NamedExpressions`
* [[child]] child link:spark-sql-SparkPlan.adoc[SparkPlan]

=== [[doProduce]] `doProduce` Method

[source, scala]
----
doProduce(ctx: CodegenContext): String
----

`doProduce` executes <<doProduceWithoutKeys, doProduceWithoutKeys>> when no <<groupingExpressions, groupingExpressions>> were specified for the `HashAggregateExec` or <<doProduceWithKeys, doProduceWithKeys>> otherwise.

NOTE: `doProduce` is a part of link:spark-sql-whole-stage-codegen.adoc#CodegenSupport[CodegenSupport Contract].

=== [[doExecute]] `doExecute` Method

=== [[allAttributes]] `allAttributes` Property

=== [[metrics]] `metrics` Property

=== [[output]] `output` Property
