== [[BroadcastManager]] BroadcastManager

*Broadcast Manager* (`BroadcastManager`) is a Spark service to manage link:spark-broadcast.adoc[broadcast variables] in Spark. It is created for a Spark application when link:spark-sparkcontext.adoc#creating-instance[SparkContext is initialized] and is a simple wrapper around link:spark-BroadcastFactory.adoc[BroadcastFactory].

`BroadcastManager` tracks the number of broadcast variables in a Spark application (using the internal field `nextBroadcastId`).

The idea is to transfer values used in transformations from a driver to executors in a most effective way so they are copied once and used many times by tasks (rather than being copied every time a task is launched).

When <<initialize, initialized>>, `BroadcastManager` creates an instance of link:spark-TorrentBroadcastFactory.adoc[TorrentBroadcastFactory].

=== [[stop]] `stop` Method

CAUTION: FIXME

=== [[creating-instance]] Creating `BroadcastManager` Instance

CAUTION: FIXME

=== [[initialize]] Initializing BroadcastManager -- `initialize` Internal Method

[source, scala]
----
initialize(): Unit
----

`initialize` link:spark-TorrentBroadcastFactory.adoc#initialize[creates and initializes a `TorrentBroadcastFactory`].

NOTE: `initialize` is executed only once (when <<creating-instance, `BroadcastManager` is created>>) and controlled by the internal `initialized` flag.

=== [[newBroadcast]] `newBroadcast` Method

[source, scala]
----
newBroadcast[T](value_ : T, isLocal: Boolean): Broadcast[T]
----

`newBroadcast` simply requests the link:spark-BroadcastFactory.adoc[current `BroadcastFactory` for a new broadcast variable].

NOTE: The `BroadcastFactory` is created when <<initialize, `BroadcastManager` is initialized>>.

NOTE: `newBroadcast` is executed for link:spark-sparkcontext.adoc#broadcast[`SparkContext.broadcast` method] and when link:spark-service-mapoutputtracker.adoc#serializeMapStatuses[`MapOutputTracker` serializes `MapStatuses`].

=== [[settings]] Settings

.Settings
[width="100%",cols="1,1,3",options="header"]
|===
|Name | Default value |Description

| [[spark_broadcast_blockSize]] `spark.broadcast.blockSize` | `4m` | The size of a block (in kB when unit not specified).

Used when link:spark-TorrentBroadcast.adoc#writeBlocks[`TorrentBroadcast` stores brodcast blocks to `BlockManager`].

| [[spark_broadcast_compress]] `spark.broadcast.compress` | `true` | The flag to enable compression.

Refer to link:spark-CompressionCodec.adoc[CompressionCodec].

Used when link:spark-TorrentBroadcast.adoc#creating-instance[`TorrentBroadcast` is created] and later when link:spark-TorrentBroadcast.adoc#writeBlocks[it stores broadcast blocks to `BlockManager`]. Also in link:spark-SerializerManager.adoc#settings[SerializerManager].
|===
