== ExecutorAllocationManager

`ExecutorAllocationManager` is responsible for dynamically allocating and removing link:spark-executor.adoc[executors] based on the workload.

It uses link:spark-service-ExecutorAllocationClient.adoc[ExecutorAllocationClient], link:spark-LiveListenerBus.adoc[LiveListenerBus], and link:spark-configuration.adoc[SparkConf] (that are all passed in when `ExecutorAllocationManager` is created).

=== [[start]] Starting ExecutorAllocationManager (start method)

[source, scala]
----
start(): Unit
----

`start` registers link:spark-service-ExecutorAllocationListener.adoc[ExecutorAllocationListener] (with link:spark-LiveListenerBus.adoc[LiveListenerBus]) to monitor scheduler events and make decisions when to add and remove executors. It then immediately starts a separate thread that is responsible for the <<schedule, scheduling>> every `100` milliseconds.

NOTE: `100` milliseconds for the period between successive <<schedule, scheduling>> is fixed, i.e. not configurable.

It link:spark-service-ExecutorAllocationClient.adoc#requestTotalExecutors[requests executors] using the input link:spark-service-ExecutorAllocationClient.adoc[ExecutorAllocationClient]. It requests link:spark-dynamic-allocation.adoc#spark.dynamicAllocation.initialExecutors[spark.dynamicAllocation.initialExecutors].

NOTE: `start` is called while link:spark-sparkcontext-creating-instance-internals.adoc#ExecutorAllocationManager[SparkContext is being created] (with link:spark-dynamic-allocation.adoc#isDynamicAllocationEnabled[dynamic allocation enabled]).

=== [[schedule]] Scheduling Executors (schedule method)

CAUTION: FIXME
