== Input Streams

*Input Streams* in Spark Streaming are the way to ingest data from external data sources. They are represented as `InputDStream` abstract class.

`InputDStream` is the abstract base class for all input link:spark-streaming-dstreams.adoc[DStreams]. It provides two abstract methods `start()` and `stop()` to start and stop ingesting data, respectively.

When instantiated, an `InputDStream` registers itself as an input stream (using link:spark-streaming-dstreams.adoc#DStreamGraph[DStreamGraph.addInputStream]) and, while doing so, is told about its owning link:spark-streaming-dstreams.adoc[DStreamGraph].

It asks for its own unique identifier using `StreamingContext.getNewInputStreamId()`.

NOTE: It is StreamingContext to maintain the identifiers and how many input streams have already been created.

`InputDStream` has a human-readable `name` that is made up from a nicely-formatted part based on the class name and the unique identifier.

TIP: Name your custom `InputDStream` using the CamelCase notation with the suffix *InputDStream*, e.g. MyCustomInputDStream.

* `slideDuration` calls link:spark-streaming-dstreams.adoc#DStreamGraph[DStreamGraph.batchDuration].

* `dependencies` method returns an empty collection.

NOTE: `compute(validTime: Time): Option[RDD[T]]` abstract method from link:spark-streaming-dstreams.adoc[DStream] abstract class is not defined.

Custom implementations of `InputDStream` can override (and actually provide!) the optional link:spark-streaming.adoc#RateController[RateController]. It is undefined by default.
