== BlockDataManager - Block Storage Management API

`BlockDataManager` is a pluggable <<contract, interface>> to manage storage for blocks (aka _block storage management API_). Blocks are identified by <<BlockId, BlockId>> and stored as <<ManagedBuffer, ManagedBuffer>>.

NOTE: link:spark-blockmanager.adoc[BlockManager] is currently the only available implementation of `BlockDataManager`.

NOTE: `org.apache.spark.network.BlockDataManager` is a `private[spark]` Scala trait in Spark.

=== [[contract]] BlockDataManager Contract

Every `BlockDataManager` offers the following services:

* `getBlockData` to fetch a local block data by `blockId`.
+
[source, scala]
----
getBlockData(blockId: BlockId): ManagedBuffer
----

* `putBlockData` to upload a block data locally by `blockId`. The return value says whether the operation has succeeded (`true`) or failed (`false`).
+
[source, scala]
----
putBlockData(
  blockId: BlockId,
  data: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Boolean
----

* `releaseLock` is a release lock for `getBlockData` and `putBlockData` operations.
+
[source, scala]
----
releaseLock(blockId: BlockId): Unit
----

=== [[BlockId]] BlockId

`BlockId` identifies a block of data. It has a globally unique identifier (`name`)

There are the following types of `BlockId`:

* *RDDBlockId* - described by `rddId` and `splitIndex`
* *ShuffleBlockId* - described by `shuffleId`, `mapId` and `reduceId`
* *ShuffleDataBlockId* - described by `shuffleId`, `mapId` and `reduceId`
* *ShuffleIndexBlockId* - described by `shuffleId`, `mapId` and `reduceId`
* <<BroadcastBlockId, BroadcastBlockId>> - described by `broadcastId` and optional `field` - a piece of broadcast value
* *TaskResultBlockId* - described by `taskId`
* *StreamBlockId* - described by `streamId` and `uniqueId`

=== [[BroadcastBlockId]] BroadcastBlockId

`BroadcastBlockId` is an <<BlockId, BlockId>> with a `long` identifier and an optional `field`.

=== [[ManagedBuffer]] ManagedBuffer
