== DStreamGraph

`DStreamGraph` (is a final helper class that) manages link:spark-streaming-dstreams.adoc[input and output streams].

It maintains the collections of link:spark-streaming-inputdstreams.adoc[InputDStream] instances (as `inputStreams`) and output link:spark-streaming-dstreams.adoc[DStream] instances (as `outputStreams`), but, more importantly, <<DStreamGraph-generateJobs, it generates streaming jobs for output streams for a batch>>.

[NOTE]
====
`DStreamGraph` holds `batchDuration` (using `setBatchDuration(duration: Duration)`) for other parts of the Streaming application.

It appears that it is _the_ place for the value since it must be set before link:spark-streaming-jobgenerator.adoc[JobGenerator] can be instantiated.

It _is_ set while link:spark-streaming-streamingcontext.adoc[StreamingContext] is being instantiated and is validated (using `validate()` method of `StreamingContext` and `DStreamGraph`) before `StreamingContext` is started.
====

When `DStreamGraph` is started (using `start(time: Time)` method), it saves `time` as `startTime`, and calls `initialize()` and `remember()` methods on every output stream (one by one). It then starts the input streams (in parallel).

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.streaming.DStreamGraph` logger to see what happens in `DStreamGraph`.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.streaming.DStreamGraph=DEBUG
```
====

=== [[DStreamGraph-generateJobs]] Generating Streaming Jobs for Output Streams for Batch

`DStreamGraph` is responsible for generating streaming jobs for output streams for a batch (given `Time`). When requested, it uses `DStreamGraph.generateJobs(time: Time)` to walk over each registered output stream and generates a streaming job (using `DStream.generateJob`).

NOTE: Who's calling it and when?

When the method runs, you should see the following DEBUG message in the logs before the jobs are generated for a batch:

```
DEBUG DStreamGraph: Generating jobs for time [time] ms
```

Right before the method finishes, you should see the following DEBUG message with the number of streaming jobs generated (as `jobs.length`):

```
DEBUG DStreamGraph: Generated [jobs.length] jobs for time [time] ms
```

=== [[dstreamgraph-validation]] Validation Check (using validate method)

`validate()` method checks whether batch duration and at least one output stream have been set. It will throw `java.lang.IllegalArgumentException` when either is not.

NOTE: It is called when link:spark-streaming-streamingcontext.adoc#start[StreamingContext starts].
