== [[SparkPlan]] SparkPlan -- Physical Execution Plan

`SparkPlan` is the base link:spark-sql-query-plan.adoc[QueryPlan] for physical operators that, when executed, produce link:spark-rdd.adoc[RDDs] of link:spark-sql-InternalRow.adoc[InternalRow], i.e. ``RDD[InternalRow]``s.

CAUTION: FIXME `SparkPlan` is `Serializable`. Why?

NOTE: The naming convention for physical operators in Spark's source code is to have their names end with the _Exec_ prefix, e.g. `DebugExec` or link:spark-sql-spark-plan-LocalTableScanExec.adoc[LocalTableScanExec].

TIP: Read link:spark-sql-InternalRow.adoc[InternalRow] about the internal binary row format.

`SparkPlan` has the following attributes:

* `metadata`
* <<metrics, metrics>>
* `outputPartitioning`
* `outputOrdering`

`SparkPlan` has the following `final` methods that prepare environment and pass calls on to corresponding methods that constitute <<contract, SparkPlan Contract>>:

* `execute` calls `doExecute`
* `prepare` calls `doPrepare`
* `executeBroadcast` calls `doExecuteBroadcast`

=== [[contract]] SparkPlan Contract

The contract of `SparkPlan` requires that concrete implementations define the following method:

* `doExecute(): RDD[InternalRow]`

They may also define their own custom overrides:

* `doPrepare`
* `doExecuteBroadcast`

CAUTION: FIXME Why are there two executes?

=== [[UnaryExecNode]][[specialized-spark-plans]] Specialized SparkPlans

* `UnaryExecNode`

CAUTION: FIXME

=== [[executeCollect]] executeCollect

CAUTION: FIXME

=== [[SQLMetric]] SQLMetric

`SQLMetric` is an link:spark-accumulators.adoc[accumulator] that accumulate and produce long values.

There are three known `SQLMetrics`:

* `sum`
* `size`
* `timing`

=== [[metrics]] metrics Lookup Table

[source, scala]
----
metrics: Map[String, SQLMetric] = Map.empty
----

`metrics` is a `private[sql]` lookup table of supported <<SQLMetric, SQLMetrics>> by their names.
