== [[BaseRelation]] BaseRelation -- Collection of Tuples with Schema

`BaseRelation` is a <<contract, contract>> to represent a collection of tuples with a known <<schema, schema>> (in a <<sqlContext, SQLContext>>).

[[sizeInBytes]]
`BaseRelation` knows its estimated size in bytes (as `sizeInBytes`) that defaults to link:spark-sql-SQLConf.adoc#spark.sql.defaultSizeInBytes[spark.sql.defaultSizeInBytes] internal property (i.e. infinite).

[[needConversion]]
`BaseRelation` whether it needs a conversion.

[[unhandledFilters]]
`BaseRelation` computes the list of `Filter` that this data source may not be able to handle.

[[available-implementations]]
.BaseRelation's Available Implementations (in alphabetical order)
[width="100%",cols="1,2",options="header"]
|===
| BaseRelation
| Description

| link:spark-sql-BaseRelation-HadoopFsRelation.adoc[HadoopFsRelation]
|

| link:spark-sql-BaseRelation-JDBCRelation.adoc[JDBCRelation]
|

| `KafkaRelation`
| Structured Streaming's `BaseRelation` for datasets from Apache Kafka
|===

NOTE: A "data source" and "relation" appear as synonyms.

=== [[contract]] BaseRelation Contract

[source, scala]
----
package org.apache.spark.sql.sources

abstract class BaseRelation {
  // only required methods that have no implementation
  def schema: StructType
  def sqlContext: SQLContext
}
----

.(Subset of) BaseRelation Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[schema]] `schema`
| link:spark-sql-StructType.adoc[StructType]

| [[sqlContext]] `sqlContext`
| link:spark-sql-SQLContext.adoc[SQLContext]
|===
