== [[ExternalClusterManager]] ExternalClusterManager -- Pluggable Cluster Managers

`ExternalClusterManager` is a <<contract, contract for pluggable cluster managers>>. It returns a link:spark-TaskScheduler.adoc[task scheduler] and a link:spark-SchedulerBackend.adoc[backend scheduler] that will be used by link:spark-sparkcontext.adoc[SparkContext] to schedule tasks.

NOTE: The support for pluggable cluster managers was introduced in https://issues.apache.org/jira/browse/SPARK-13904[SPARK-13904 Add support for pluggable cluster manager].

External cluster managers are link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[registered using the `java.util.ServiceLoader` mechanism] (with service markers under `META-INF/services` directory). This allows auto-loading implementations of `ExternalClusterManager` interface.

NOTE: `ExternalClusterManager` is a `private[spark]` trait in `org.apache.spark.scheduler` package.

NOTE: The two implementations of the <<contract, ExternalClusterManager contract>> in Spark 2.0 are link:yarn/spark-yarn-YarnClusterManager.adoc[YarnClusterManager] and `MesosClusterManager`.

=== [[contract]] ExternalClusterManager Contract

==== [[canCreate]] `canCreate` Method

[source, scala]
----
canCreate(masterURL: String): Boolean
----

`canCreate` is a mechanism to match a `ExternalClusterManager` implementation to a given master URL.

NOTE: `canCreate` is used when link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[`SparkContext` loads the external cluster manager for a master URL].

==== [[createTaskScheduler]] `createTaskScheduler` Method

[source, scala]
----
createTaskScheduler(sc: SparkContext, masterURL: String): TaskScheduler
----

`createTaskScheduler` creates a link:spark-TaskScheduler.adoc[TaskScheduler] given a link:spark-sparkcontext.adoc[SparkContext] and the input `masterURL`.

==== [[createSchedulerBackend]] `createSchedulerBackend` Method

[source, scala]
----
createSchedulerBackend(sc: SparkContext,
  masterURL: String,
  scheduler: TaskScheduler): SchedulerBackend
----

`createSchedulerBackend` creates a link:spark-SchedulerBackend.adoc[SchedulerBackend] given a link:spark-sparkcontext.adoc[SparkContext], the input `masterURL`, and link:spark-TaskScheduler.adoc[TaskScheduler].

==== [[initialize]] Initializing Scheduling Components -- `initialize` Method

[source, scala]
----
initialize(scheduler: TaskScheduler, backend: SchedulerBackend): Unit
----

`initialize` is called after the link:spark-TaskScheduler.adoc[task scheduler] and the link:spark-SchedulerBackend.adoc[backend scheduler] were created and initialized separately.

NOTE: There is a cyclic dependency between a task scheduler and a backend scheduler that begs for this additional initialization step.

NOTE: link:spark-TaskScheduler.adoc[TaskScheduler] and link:spark-SchedulerBackend.adoc[SchedulerBackend] (with link:spark-dagscheduler.adoc[DAGScheduler]) are commonly referred to as *scheduling components*.
