== [[DataSourceScanExec]] DataSourceScanExec -- Contract for Leaf Physical Operators with Code Generation

`DataSourceScanExec` is a <<contract, contract>> for link:spark-sql-SparkPlan.adoc#LeafExecNode[leaf physical operators] with link:spark-sql-CodegenSupport.adoc[support for code generation] that...FIXME

NOTE: The prefix for variable names for `DataSourceScanExec` operators in link:spark-sql-CodegenSupport.adoc[CodegenSupport]-generated code is *scan*.

[[known-implementations]]
.DataSourceScanExec's Known Implementations
[width="100%",cols="1,2",options="header"]
|===
| DataSourceScanExec
| Description

| link:spark-sql-SparkPlan-DataSourceScanExec-FileSourceScanExec.adoc[FileSourceScanExec]
|

| link:spark-sql-SparkPlan-DataSourceScanExec-RowDataSourceScanExec.adoc[RowDataSourceScanExec]
|
|===

=== [[contract]] DataSourceScanExec Contract

[source, scala]
----
package org.apache.spark.sql.execution

trait DataSourceScanExec extends LeafExecNode with CodegenSupport {
  // only required vals and methods that have no implementation
  val metastoreTableIdentifier: Option[TableIdentifier]
  val relation: BaseRelation
}
----

.(Subset of) DataSourceScanExec Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[metastoreTableIdentifier]] `metastoreTableIdentifier`
| `TableIdentifier` that...FIXME

| [[relation]] `relation`
| link:spark-sql-BaseRelation.adoc[BaseRelation] that...FIXME
|===
