== [[ApiRootResource]] ApiRootResource

`ApiRootResource` is the main link:spark-api-ApiRequestContext.adoc[ApiRequestContext] that <<getServletHandler, registers>> the `/api/*` context handler (with the REST resources and providers in `org.apache.spark.status.api.v1` package).

`ApiRootResource` gives the metrics of a Spark application in JSON format (using JAX-RS API).

`ApiRootResource` serves HTTP requests for <<paths, paths>> under the `/v1` path for link:spark-webui-SparkUI.adoc#initialize[SparkUI] and link:spark-history-server-HistoryServer.adoc#initialize[HistoryServer].

```
// start spark-shell
$ http http://localhost:4040/api/v1/applications
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 257
Content-Type: application/json
Date: Tue, 05 Jun 2018 18:36:16 GMT
Server: Jetty(9.3.z-SNAPSHOT)
Vary: Accept-Encoding, User-Agent

[
    {
        "attempts": [
            {
                "appSparkVersion": "2.3.1-SNAPSHOT",
                "completed": false,
                "duration": 0,
                "endTime": "1969-12-31T23:59:59.999GMT",
                "endTimeEpoch": -1,
                "lastUpdated": "2018-06-05T15:04:48.328GMT",
                "lastUpdatedEpoch": 1528211088328,
                "sparkUser": "jacek",
                "startTime": "2018-06-05T15:04:48.328GMT",
                "startTimeEpoch": 1528211088328
            }
        ],
        "id": "local-1528211089216",
        "name": "Spark shell"
    }
]

// FIXME Why does the following not work?
$ http http://localhost:4040/api/v1/version
```

[[paths]]
.ApiRootResource's Paths
[cols="1,1,2",options="header",width="100%"]
|===
| Path
| HTTP Method
| Description

| `applications`
|
| Uses link:spark-api-ApplicationListResource.adoc[ApplicationListResource] resource class

| `applications/{appId}`
|
| Uses link:spark-api-OneApplicationResource.adoc[OneApplicationResource] resource class

| `version`
|
| Creates a `VersionInfo` with the current version of Spark.
|===

=== [[getServletHandler]] Registering /api/* Context Handler -- `getServletHandler` Method

[source, scala]
----
getServletHandler(uiRoot: UIRoot): ServletContextHandler
----

`getServletHandler` creates a Jetty `ServletContextHandler` for `/api` context path.

NOTE: The Jetty `ServletContextHandler` created does not support HTTP sessions as REST API is stateless.

`getServletHandler` creates a Jetty `ServletHolder` with the resources and providers in `org.apache.spark.status.api.v1` package. It then registers the `ServletHolder` to serve `/*` context path (under the `ServletContextHandler` for `/api`).

`getServletHandler` requests `UIRootFromServletContext` to link:spark-api-UIRootFromServletContext.adoc#setUiRoot[setUiRoot] with the `ServletContextHandler` and the input link:spark-api-UIRoot.adoc[UIRoot].

NOTE: `getServletHandler` is used when link:spark-webui-SparkUI.adoc#initialize[SparkUI] and link:spark-history-server-HistoryServer.adoc#initialize[HistoryServer] are requested to initialize.
