== Spark and Hadoop

From https://hadoop.apache.org/[Apache Hadoop]'s web site:

> The Apache Hadoop software library is a framework that allows for the distributed processing of large data sets across clusters of computers using simple programming models. It is designed to scale up from single servers to thousands of machines, each offering local computation and storage. Rather than rely on hardware to deliver high-availability, the library itself is designed to detect and handle failures at the application layer, so delivering a highly-available service on top of a cluster of computers, each of which may be prone to failures.

* _Originally_, *Hadoop* is an umbrella term for the following (core) *modules*:
** http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsDesign.html[HDFS (Hadoop Distributed File System)] is a distributed file system designed to run on commodity hardware.
** *MapReduce* - the compute engine for batch processing
** *YARN* (Yet Another Resource Negotiator) - the resource manager
* _Currently_, it's more about the ecosystem of solutions that all use Hadoop infrastructure for their work.

People reported to do wonders with the software with http://yahoohadoop.tumblr.com/post/129872361846/large-scale-distributed-deep-learning-on-hadoop[Yahoo! saying]:

> Yahoo has progressively invested in building and scaling Apache Hadoop clusters with a current footprint of more than 40,000 servers and 600 petabytes of storage spread across 19 clusters.

Beside numbers http://yahoohadoop.tumblr.com/post/129872361846/large-scale-distributed-deep-learning-on-hadoop[Yahoo! reported] that:

> Deep learning can be defined as first-class steps in http://oozie.apache.org/[Apache Oozie] workflows with Hadoop for data processing and Spark pipelines for machine learning.

You can find some _preliminary_ information about *Spark pipelines for machine learning* in this book's chapter link:spark-mllib-pipelines.adoc[ML Pipelines].

HDFS provides fast analytics – scanning over large amounts of data very quickly, but it was not built to handle updates. If data changed, it would need to be appended in bulk after a certain volume or time interval, preventing real-time visibility into this data.

* HBase complements HDFS’ capabilities by providing fast and random reads and writes and supporting updating data, i.e. serving small queries extremely quickly, and allowing data to be updated in place.

=== Hadoop YARN

From https://hadoop.apache.org/[Apache Hadoop]'s web site:

> Hadoop YARN: A framework for job scheduling and cluster resource management.

* YARN could be considered a cornerstone of Hadoop OS (operating system) for big distributed data with HDFS as the storage along with YARN as a process scheduler.
* YARN is essentially a container system and scheduler designed primarily for use with a Hadoop-based cluster.
* The containers in YARN are capable of running various types of tasks.
* Resource manager, node manager, container, application master, jobs
* focused on data storage and offline batch analysis
* Hadoop is storage and compute platform:
** MapReduce is the computing part.
** HDFS is the storage.
* Hadoop is a resource and cluster manager (YARN)
* Spark runs on YARN clusters, and can read from and save data to HDFS.
** leverages link:spark-data-locality.adoc[data locality]
* Spark needs distributed file system and HDFS (or Amazon S3, but slower) is a great choice.
* HDFS allows for link:spark-data-locality.adoc[data locality].
* Excellent throughput when Spark and Hadoop are both distributed and co-located on the same (YARN or Mesos) cluster nodes.
* HDFS offers (important for initial loading of data):
** high data locality
** high throughput when co-located with Spark
** low latency because of data locality
** very reliable because of replication
* When reading data from HDFS, each `InputSplit` maps to exactly one Spark partition.
* HDFS is distributing files on data-nodes and storing a file on the filesystem, it will be split into partitions.
* From http://stackoverflow.com/q/29011574/1305344[How does partitioning work for data from files on HDFS?]:
+
> When Spark reads a file from HDFS, it creates a single partition for a single input split. Input split is set by the Hadoop `InputFormat` used to read this file. For instance, if you use `textFile()` it would be `TextInputFormat` in Hadoop, which would return you a single partition for a single block of HDFS (but the split between partitions would be done on line split, not the exact block split), unless you have a compressed text file. In case of compressed file you would get a single partition for a single file (as compressed text files are not splittable).
+
> If you have a 30GB uncompressed text file stored on HDFS, then with the default HDFS block size setting (128MB) it would be stored in 235 blocks, which means that the RDD you read from this file would have 235 partitions. When you call repartition(1000) your RDD would be marked as to be repartitioned, but in fact it would be shuffled to 1000 partitions only when you will execute an action on top of this RDD (lazy execution concept)

When using `textFile` to read an HDFS folder with multiple files inside, the number of partitions are equal to the number of HDFS blocks. The read operation is lazy.

=== Further reading

* http://vision.cloudera.com/introducing-kudu-the-new-hadoop-storage-engine-for-fast-analytics-on-fast-data/[Introducing Kudu: The New Hadoop Storage Engine for Fast Analytics on Fast Data]
