== [[Project]] Project Unary Logical Operator

`Project` is a link:spark-sql-LogicalPlan.adoc#UnaryNode[unary logical operator] that is <<creating-instance, created>> to represent the following:

1. Dataset operators, i.e.  link:spark-sql-joins.adoc#joinWith[joinWith], link:spark-sql-dataset-operators.adoc#select[select] (incl. `selectUntyped`), `unionByName`
1. `KeyValueGroupedDataset` operators, i.e. `keys`, `mapValues`
1. `CreateViewCommand.aliasPlan`
1. SQL's link:spark-sql-AstBuilder.adoc#withQuerySpecification[SELECT] queries with named expressions

`Project` can also appear in a logical plan after link:spark-sql-Analyzer.adoc[analysis] or link:spark-sql-Optimizer.adoc[optimization] phases.

[source, scala]
----
CAUTION: FIXME Examples with their plans

// 1. Show the SQL with Project logical operator
// 1. joinWith
// 1. select
// select[U1](c1: TypedColumn[T, U1])
// Dataset.unionByName
// KeyValueGroupedDataset.mapValues
// KeyValueGroupedDataset.keys
// CreateViewCommand.aliasPlan

// Examples with Project after analysis
// Examples with Project after optimization
----

NOTE: link:spark-sql-Expression.adoc#deterministic[Nondeterministic expressions] are allowed in `Project` logical operator and enforced by link:spark-sql-Analyzer-CheckAnalysis.adoc#deterministic[CheckAnalysis].

[[output]]
`output`...FIXME

[[maxRows]]
`maxRows`...FIXME

[[resolved]]
`resolved`...FIXME

[[validConstraints]]
`validConstraints`...FIXME

[NOTE]
====
You can use Spark SQL's *Catalyst DSL* (in `org.apache.spark.sql.catalyst.dsl` package object) for constructing Catalyst data structures using Scala implicit conversions if you are into Spark testing.

[source, scala]
----
scala> spark.version
res0: String = 2.3.0-SNAPSHOT

import org.apache.spark.sql.catalyst.dsl.plans._  // <-- gives table and select
import org.apache.spark.sql.catalyst.dsl.expressions.star
val plan = table("a").select(star())
scala> println(plan.numberedTreeString)
00 'Project [*]
01 +- 'UnresolvedRelation `a`
----
====

=== [[creating-instance]] Creating Project Instance

`Project` takes the following when created:

* [[projectList]] link:spark-sql-Expression.adoc#NamedExpression[Named expressions]
* [[child]] Child link:spark-sql-LogicalPlan.adoc[logical plan]

`Project` initializes the <<internal-registries, internal registries and counters>>.
