== BlockManagerMaster - BlockManager for Driver

`BlockManagerMaster` link:spark-sparkenv.adoc#BlockManagerMaster[runs on the driver and executors]. It uses <<BlockManagerMasterEndpoint, BlockManagerMasterEndpoint>> registered under `BlockManagerMaster` RPC endpoint name on the driver with the `BlockManagerMaster` RPC endpoint's references on executors.

NOTE: An instance of `BlockManagerMaster` is created in link:spark-sparkenv.adoc#BlockManagerMaster[SparkEnv (for the driver and executors)], and immediately used to create their link:spark-blockmanager.adoc[BlockManagers].

[TIP]
====
Enable `INFO` or `DEBUG` logging level for `org.apache.spark.storage.BlockManagerMaster` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.storage.BlockManagerMaster=INFO
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[creating-instance]] Creating BlockManagerMaster Instance

An instance of `BlockManagerMaster` requires the RPC endpoint reference to `BlockManagerMaster` <<BlockManagerMasterEndpoint, BlockManagerMasterEndpoint>>, link:spark-configuration.adoc[SparkConf], and the `isDriver` flag to say whether it is created for the driver or executors.

NOTE: An instance of `BlockManagerMaster` is created as part of link:spark-sparkenv.adoc#BlockManagerMaster[creating an instance of SparkEnv for the driver and executors].

=== [[removeBlock]] Removing Block (removeBlock method)

[source, scala]
----
removeBlock(blockId: BlockId)
----

`removeBlock` removes `blockId` block ...FIXME

It posts a blocking `RemoveBlock` message to the input `driverEndpoint` RPC endpoint reference.

=== [[stop]] Stopping BlockManagerMaster (stop method)

[source, scala]
----
stop(): Unit
----

`stop` sends `StopBlockManagerMaster` to <<BlockManagerMasterEndpoint, BlockManagerMaster RPC endpoint>> and waits for a response.

If all goes fine, you should see the following INFO message in the logs:

```
INFO BlockManagerMaster: BlockManagerMaster stopped
```

Otherwise, a `SparkException` is thrown.

```
BlockManagerMasterEndpoint returned false, expected true.
```

=== [[registerBlockManager]] Registering BlockManager to Driver (registerBlockManager method)

[source, scala]
----
registerBlockManager(
  blockManagerId: BlockManagerId,
  maxMemSize: Long,
  slaveEndpoint: RpcEndpointRef): Unit
----

When `registerBlockManager` runs, you should see the following INFO message in the logs:

```
INFO BlockManagerMaster: Trying to register BlockManager
```

It then sends `RegisterBlockManager` to <<BlockManagerMasterEndpoint, BlockManagerMaster RPC endpoint>> and waits for a response.

If all goes fine, you should see the following INFO message in the logs:

```
INFO BlockManagerMaster: Registered BlockManager
```

Otherwise, a `SparkException` is thrown.

```
BlockManagerMasterEndpoint returned false, expected true.
```

NOTE: `registerBlockManager` is called while link:spark-blockmanager.adoc#initialize[BlockManager is being initialized] and possibly later while link:spark-blockmanager.adoc#reregister[re-registering blocks to the driver].

=== [[updateBlockInfo]] Sending UpdateBlockInfo to Driver (updateBlockInfo method)

[source, scala]
----
updateBlockInfo(
  blockManagerId: BlockManagerId,
  blockId: BlockId,
  storageLevel: StorageLevel,
  memSize: Long,
  diskSize: Long): Boolean
----

`updateBlockInfo` sends a `UpdateBlockInfo` message to <<BlockManagerMasterEndpoint, BlockManagerMaster RPC endpoint>> and waits for a response.

You should see the following DEBUG message in the logs:

```
DEBUG BlockManagerMaster: Updated info of block [blockId]
```

The response from the BlockManagerMaster RPC endpoint is returned.

=== [[BlockManagerMasterEndpoint]] BlockManagerMasterEndpoint - BlockManagerMaster RPC Endpoint

CAUTION: FIXME

*BlockManagerMasterEndpoint* is the RPC endpoint for <<BlockManagerMaster, BlockManagerMaster>> on the master node to track statuses of all slaves' block managers.

The following two-way events are handled:

* RegisterBlockManager
* UpdateBlockInfo
* GetLocations
* GetLocationsMultipleBlockIds
* GetPeers
* GetRpcHostPortForExecutor
* GetMemoryStatus
* GetStorageStatus
* GetBlockStatus
* GetMatchingBlockIds
* RemoveRdd
* RemoveShuffle
* RemoveBroadcast
* RemoveBlock
* RemoveExecutor
* StopBlockManagerMaster
* BlockManagerHeartbeat
* HasCachedBlocks
