== GraphX

Apache Spark comes with a library for executing distributed computation on graph data, http://spark.apache.org/graphx/[GraphX].

* Apache Spark graph analytics
* GraphX is a pure programming API
** missing a graphical UI to visually explore datasets
** Could TitanDB be a solution?

From the article http://www.ibmbigdatahub.com/blog/merging-datasets-using-graph-analytics[Merging datasets using graph analytics]:

> Such a situation, in which we need to find the best matching in a weighted bipartite graph, poses what is known as the https://en.wikipedia.org/wiki/Stable_marriage_problem[stable marriage problem]. It is a classical problem that has a well-known solution, the Gale–Shapley algorithm.

> A popular *model of distributed computation on graphs* known as Pregel was published by Google researchers in 2010. Pregel is based on passing messages along the graph edges in a series of iterations. Accordingly, it is a good fit for the Gale–Shapley algorithm, which starts with each “gentleman” (a vertex on one side of the bipartite graph) sending a marriage proposal to its most preferred single “lady” (a vertex on the other side of the bipartite graph). The “ladies” then marry their most preferred suitors, after which the process is repeated until there are no more proposals to be made.

> The Apache Spark distributed computation engine includes GraphX, a library specifically made for executing distributed computation on graph data. GraphX provides an elegant Pregel interface but also permits more general computation that is not restricted to the message-passing pattern.
