== [[DiskBlockObjectWriter]] DiskBlockObjectWriter

`DiskBlockObjectWriter` is a https://docs.oracle.com/javase/8/docs/api/java/io/OutputStream.html[java.io.OutputStream] that link:spark-blockmanager.adoc#getDiskWriter[`BlockManager` uses as a block writer].

NOTE: `DiskBlockObjectWriter` is a `private[spark]` class.

[[internal-registries]]
.DiskBlockObjectWriter's Internal Registries and Counters
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[streamOpen]] `streamOpen`
| Internal flag...FIXME

Used when...FIXME

| [[objOut]] `objOut`
| FIXME

Used when...FIXME
|===

=== [[open]] `open` Method

CAUTION: FIXME

=== [[recordWritten]] `recordWritten` Method

CAUTION: FIXME

=== [[commitAndGet]] `commitAndGet` Method

[source, scala]
----
commitAndGet(): FileSegment
----

NOTE: `commitAndGet` is used when...FIXME

=== [[close]] `close` Method

CAUTION: FIXME

=== [[creating-instance]] Creating DiskBlockObjectWriter Instance

`DiskBlockObjectWriter` takes the following when created:

1. `file`
2. `serializerManager` -- link:spark-SerializerManager.adoc[SerializerManager]
3. `serializerInstance` -- link:spark-SerializerInstance.adoc[SerializerInstance]
4. `bufferSize`
5. `syncWrites` flag
6. `writeMetrics` -- `ShuffleWriteMetrics`
7. `blockId` -- link:spark-blockdatamanager.adoc#BlockId[BlockId]

`DiskBlockObjectWriter` initializes the <<internal-registries, internal registries and counters>>.

=== [[write]] Writing Key-Value Pair -- `write` Method

[source, scala]
----
write(key: Any, value: Any): Unit
----

Before writing, `write` <<open, opens the stream>> unless already <<streamOpen, open>>.

`write` then link:spark-SerializationStream.adoc#writeKey[writes the `key`] first followed by link:spark-SerializationStream.adoc#writeValue[writing the `value`].

In the end, `write` <<recordWritten, recordWritten>>.

NOTE: `write` is used when link:spark-BypassMergeSortShuffleWriter.adoc#write[`BypassMergeSortShuffleWriter` writes records] and in `ExternalAppendOnlyMap`, `ExternalSorter` and `WritablePartitionedPairCollection`.
