== JobGenerator

When `JobGenerator` is created, it creates `timer` link:spark-streaming-jobscheduler.adoc#RecurringTimer[RecurringTimer] (with the name being `JobGenerator`) that later, when started, posts link:spark-streaming.adoc#GenerateJobs[GenerateJobs] events to <<eventLoop, JobGenerator eventLoop>> (it is only when `JobGenerator` is started when the JobGenerator eventLoop starts processing events).

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.streaming.scheduler.JobGenerator` logger to see what happens in JobGenerator.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.streaming.scheduler.JobGenerator=DEBUG
```
====

You should see the following INFO message in the logs when `JobGenerator` starts:

```
INFO JobGenerator: Started JobGenerator at [startTime] ms
```

Once started, `timer` RecurringTimer starts posting `GenerateJobs` every `ssc.graph.batchDuration.milliseconds`.

=== [[eventLoop]] JobGenerator eventLoop and JobGeneratorEvent Handler

JobGenerator uses `EventLoop` to process `JobGeneratorEvent` events asynchronously (one event at a time).

For every event, you should see the following DEBUG message in the logs:

```
DEBUG JobGenerator: Got event [event]
```

See below for the extensive coverage of supported event types.

==== [[GenerateJobs]] GenerateJobs and JobGenerator.generateJobs

When `GenerateJobs` is received `JobGenerator.generateJobs(time: Time)` is executed to process it.

NOTE: `GenerateJobs` events are posted by `JobGenerator` regularly every batch interval (using `timer` RecurringTimer).

It calls `JobScheduler.receiverTracker.allocateBlocksToBatch`, and then calls link:spark-streaming.adoc#DStreamGraph-generateJobs[DStreamGraph.generateJobs(time: Time)].

When the above two calls have finished successfully, the collection of jobs is passed to link:spark-streaming-jobscheduler.adoc#submitJobSet[JobScheduler.submitJobSet] as a link:spark-streaming-jobscheduler.adoc[JobSet].

Ultimately, it posts <<DoCheckpoint, DoCheckpoint>> event.

==== [[ClearMetadata]] ClearMetadata and clearMetadata

CAUTION: FIXME

==== [[DoCheckpoint]] DoCheckpoint and doCheckpoint

CAUTION: FIXME

==== [[ClearCheckpointData]] ClearCheckpointData and clearCheckpointData

CAUTION: FIXME

=== [[stop]] JobGenerator.stop

`JobGenerator.stop(processReceivedData: Boolean)` stops a JobGenerator.

CAUTION: FIXME
