== [[TreeNode]] TreeNode

`TreeNode` is the foundation of *Catalyst* -- an implementation-agnostic framework for manipulating trees of *relational operators* and *expressions*.

NOTE: `TreeNode` and the Catalyst framework were first introduced in https://issues.apache.org/jira/browse/SPARK-1251[SPARK-1251 Support for optimizing and executing structured queries] resolved on 20/Mar/14 19:12.

Scala-specific, `TreeNode` is an abstract class that is the base class of link:spark-sql-QueryPlan.adoc[QueryPlan] and link:spark-sql-catalyst-Expression.adoc[Expression] abstract classes.

TIP: `TreeNode` abstract type is a quite advanced Scala type definition (at least comparing to the other Scala types in Spark) so understanding its behaviour even outside Spark might be worthwhile by itself.

[source, scala]
----
abstract class TreeNode[BaseType <: TreeNode[BaseType]] extends Product {
  self: BaseType =>

  // ...
}
----

`TreeNode` can have `children` and offers not only functions that you may have used from Scala Collection API, e.g. `foreach`, `map`, `flatMap`, `collect`, `collectFirst`, but also `foreachUp`, `mapChildren`, `transform`, `transformDown`, `transformUp`, etc. that are particularly useful for tree manipulation.
