== [[SchedulingMode]] Scheduling Mode

*Scheduling Mode* (aka _order task policy_ or _scheduling policy_) defines a policy to sort tasks.

`schedulingMode` method is a part of the link:spark-taskscheduler.adoc#schedulingMode[TaskScheduler Contract] to set up the link:spark-taskscheduler.adoc#rootPool[rootPool] method (that returns proper link:spark-taskscheduler-pool.adoc[Pool] for the scheduling mode).

The scheduling mode for link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl] is configured by link:spark-taskschedulerimpl.adoc#spark.scheduler.mode[spark.scheduler.mode] setting (with `FIFO` being the default) while link:spark-taskschedulerimpl.adoc#initialize[it is being initialized].

There are three acceptable scheduling modes:

* *FIFO* with no pools; one root pool with instances of link:spark-tasksetmanager.adoc[TaskSetManager]; lower priority gets link:spark-taskscheduler-schedulable.adoc[Schedulable] sooner or earlier stage wins.
* <<FAIR, FAIR>>
* *NONE* (not used)

NOTE: However there are three possible `SchedulingMode` policies only two are supported by link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl].

TIP: Refer to link:spark-taskscheduler-schedulablebuilders.adoc[SchedulableBuilder].

=== [[FAIR]] FAIR Scheduling Mode

CAUTION: FIXME

=== [[fair-scheduling-sparkui]] Monitoring FAIR Scheduling Mode using Spark UI

CAUTION: FIXME
