== [[ShuffleBlockFetcherIterator]] ShuffleBlockFetcherIterator

`ShuffleBlockFetcherIterator` is a Scala http://www.scala-lang.org/api/current/scala/collection/Iterator.html[Iterator] to <<next, iterate over a sequence of `(BlockId, InputStream)` pairs>>.

=== [[initialize]] `initialize` Internal Method

CAUTION: FIXME

=== [[creating-instance]] Creating ShuffleBlockFetcherIterator Instance

When created, `ShuffleBlockFetcherIterator` takes the following:

1. link:spark-taskscheduler-taskcontext.adoc[TaskContext]
2. link:spark-shuffleclient.adoc[ShuffleClient]
3. link:spark-blockmanager.adoc[BlockManager]
4. `blocksByAddress` list of blocks to fetch per link:spark-blockmanager.adoc[BlockManager].
+
```
blocksByAddress: Seq[(BlockManagerId, Seq[(BlockId, Long)])]
```

5. `streamWrapper` function to wrap the returned input stream
+
```
streamWrapper: (BlockId, InputStream) => InputStream
```

6. Maximum size (in bytes) of map outputs to fetch simultaneously from each reduce task (`maxBytesInFlight` and controlled by link:spark-BlockStoreShuffleReader.adoc#spark_reducer_maxSizeInFlight[spark.reducer.maxSizeInFlight] Spark property)
7. The maximum number of remote requests to fetch blocks at any given point (`maxReqsInFlight` and controlled by link:spark-BlockStoreShuffleReader.adoc#spark_reducer_maxReqsInFlight[spark.reducer.maxReqsInFlight] Spark property)
8. `detectCorrupt` flag to detect any corruption in fetched blocks (controlled by link:spark-BlockStoreShuffleReader.adoc#spark_shuffle_detectCorrupt[spark.shuffle.detectCorrupt] Spark property)

CAUTION: FIXME

=== [[next]] `next` Method

CAUTION: FIXME

=== [[throwFetchFailedException]] Throwing FetchFailedException (for ShuffleBlockId) -- `throwFetchFailedException` Internal Method

[source, scala]
----
throwFetchFailedException(
  blockId: BlockId,
  address: BlockManagerId,
  e: Throwable): Nothing
----

`throwFetchFailedException` throws a link:spark-TaskRunner-FetchFailedException.adoc[FetchFailedException] when the input `blockId` is a `ShuffleBlockId`.

NOTE: `throwFetchFailedException` creates a `FetchFailedException` passing on the root cause of a failure, i.e. the input `e`.

Otherwise, `throwFetchFailedException` throws a `SparkException`:

```
Failed to get block [blockId], which is not a shuffle block
```

NOTE: `throwFetchFailedException` is used when <<next `ShuffleBlockFetcherIterator` is requested for the next element>>.
