== [[JoinSelection]] JoinSelection

`JoinSelection` is a `Strategy` of link:spark-sql-SparkPlanner.adoc[SparkPlanner] and link:spark-sql-queryplanner.adoc#HiveSessionState[Hive-specific `QueryPlanner`].

When applied to a link:spark-sql-LogicalPlan.adoc[LogicalPlan], its processing varies per join type.

.JoinSelection's Cases
[cols="1,3",options="header",width="100%"]
|===
| Name | Behaviour
| `ExtractEquiJoinKeys` | Used to destructure a `Join`
| `Join` |
|===

=== [[ExtractEquiJoinKeys]] ExtractEquiJoinKeys

`ExtractEquiJoinKeys` is a pattern used to destructure a link:spark-sql-Join.adoc[Join] into a tuple of `(JoinType, Seq[Expression], Seq[Expression], Option[Expression], LogicalPlan, LogicalPlan)`.

=== [[canBuildRight]] `canBuildRight` Internal Method

[source, scala]
----
canBuildRight(joinType: JoinType): Boolean
----

`canBuildRight` is a predicate that is positive (i.e. `true`) for link:spark-sql-joins.adoc[joins] that are:

* "INNER", "CROSS", "LEFT OUTER", "LEFT SEMI", "LEFT ANTI" and a helper `ExistenceJoin`.

Otherwise, `canBuildRight` is negative (i.e. `false`).

=== [[canBroadcast]] `canBroadcast` Internal Method

[source, scala]
----
canBroadcast(plan: LogicalPlan): Boolean
----

`canBroadcast` is a predicate that is positive (i.e. `true`) for link:spark-sql-LogicalPlan.adoc[logical operators] with statistics that can be broadcast and of size less than link:spark-sql-settings.adoc#spark.sql.autoBroadcastJoinThreshold[spark.sql.autoBroadcastJoinThreshold].
