== [[FunctionRegistry]] FunctionRegistry

`FunctionRegistry` is a base registry (aka _catalog_) of native and user-defined functions.

NOTE: The one and only `FunctionRegistry` available in Spark SQL is <<SimpleFunctionRegistry, SimpleFunctionRegistry>>.

You can access a session-specific `FunctionRegistry` through link:spark-sql-SessionState.adoc#functionRegistry[SessionState].

[source, scala]
----
val spark: SparkSession = ...
spark.sessionState.functionRegistry
----

NOTE: You can register a new user-defined function using link:spark-sql-UDFRegistration.adoc[UDFRegistration].

[[attributes]]
.FunctionRegistry's Attributes (in alphabetical order)
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| [[builtin]] `builtin`
| <<SimpleFunctionRegistry, SimpleFunctionRegistry>> with the <<expressions, built-in functions>> registered.

| [[expressions]] `expressions`
| Collection of link:spark-sql-Expression.adoc[expressions] that represent built-in/native functions.
|===

=== [[lookupFunction]] `lookupFunction` Method

CAUTION: FIXME

=== [[registerFunction]] `registerFunction` Methods

[source, scala]
----
registerFunction(name: String, builder: FunctionBuilder): Unit  // <1>
registerFunction(name: String, info: ExpressionInfo, builder: FunctionBuilder): Unit
----
<1> Relays calls to the other `registerFunction`

NOTE: `registerFunction` is used when...FIXME

=== [[SimpleFunctionRegistry]] SimpleFunctionRegistry

`SimpleFunctionRegistry` is the default <<FunctionRegistry, FunctionRegistry>> that is backed by a hash map (with optional case sensitivity).
