== [[SchedulingMode]] Scheduling Mode -- spark.scheduler.mode

*Scheduling Mode* (aka _order task policy_ or _scheduling policy_) defines a policy to sort tasks in order for execution.

`schedulingMode` method is a part of the link:spark-taskscheduler.adoc#schedulingMode[TaskScheduler Contract] to set up the link:spark-taskscheduler.adoc#rootPool[rootPool] method (that returns a link:spark-taskscheduler-pool.adoc[Pool] for a given scheduling mode).

The scheduling mode for link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl] is configured by link:spark-taskschedulerimpl.adoc#spark.scheduler.mode[spark.scheduler.mode] setting (with `FIFO` being the default) when link:spark-taskschedulerimpl.adoc#initialize[`TaskSchedulerImpl` is initialized].

There are three acceptable scheduling modes:

* <<FIFO, FIFO>> with no pools but a single one pool with instances of link:spark-tasksetmanager.adoc[TaskSetManager]; lower priority gets link:spark-taskscheduler-schedulable.adoc[Schedulable] sooner or earlier stage wins.
* <<FAIR, FAIR>>
* *NONE* (not used)

NOTE: Out of three possible `SchedulingMode` policies only `FIFO` and `FAIR` are supported by link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl].

TIP: Refer to link:spark-taskscheduler-schedulablebuilders.adoc[SchedulableBuilder] that is an entity that manages `Schedulable` pools.

=== [[FIFO]] FIFO Scheduling Mode

When link:spark-taskschedulerimpl.adoc#spark.scheduler.mode[spark.scheduler.mode] is `FIFO`, link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl] uses the unnamed link:spark-taskscheduler.adoc#rootPool[root pool] with `initMinShare` and `initWeight` being both `0`.

NOTE: The link:spark-taskscheduler.adoc#rootPool[root pool] is a `Schedulable`. Refer to link:spark-taskscheduler-schedulable.adoc[Schedulable].

When link:spark-taskschedulerimpl.adoc#initialize[`TaskSchedulerImpl` is initialized], a link:spark-taskscheduler-FIFOSchedulableBuilder.adoc#[`FIFOSchedulableBuilder` is used to set up the pool] that simply does nothing, i.e. returns the same pool it has been given.

NOTE: After the root pool is initialized, the scheduling mode is no longer relevant (since the link:spark-taskscheduler-schedulable.adoc[Schedulable] that represents the pool is fully set up). It is used to link:spark-taskschedulerimpl.adoc#submitTasks[submit tasks (as `TaskSets`)] afterwards.

=== [[FAIR]] FAIR Scheduling Mode

CAUTION: FIXME

=== [[fair-scheduling-sparkui]] Monitoring FAIR Scheduling Mode using Spark UI

CAUTION: FIXME
