== [[Optimizer]] Catalyst Query Optimizer

CAUTION: FIXME Review https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala[sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala].

Catalyst is an extensible *query plan optimizer* with link:spark-sql-catalyst-constant-folding.adoc[constant folding], link:spark-sql-predicate-pushdown.adoc[predicate pushdown], link:spark-sql-catalyst-nullability-propagation.adoc[nullability (NULL value) propagation], link:spark-sql-catalyst-vectorized-parquet-decoder.adoc[vectorized Parquet decoder] and link:spark-sql-whole-stage-codegen.adoc[whole-stage code generation] optimization techniques.

Catalyst supports both rule-based and cost-based optimization.

Among the rule-based optimizations is link:spark-sql-catalyst-nullability-propagation.adoc[nullability (NULL value) propagation].

=== [[SparkOptimizer]] SparkOptimizer

CAUTION: FIXME

=== RowEncoder

`RowEncoder` is a factory object that maps link:spark-sql-dataframe-structtype.adoc[StructType] to `ExpressionEncoder[Row]`

It belongs to `org.apache.spark.sql.catalyst.encoders` package.

=== [[i-want-more]] Further reading or watching

* https://databricks.com/blog/2015/04/13/deep-dive-into-spark-sqls-catalyst-optimizer.html[Deep Dive into Spark SQL’s Catalyst Optimizer]
