== [[HistoryServer]] HistoryServer

`HistoryServer` extends `WebUI` abstract class.

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.deploy.history.HistoryServer` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.deploy.history.HistoryServer=INFO
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[main]] Starting HistoryServer Standalone Application -- `main` Method

CAUTION: FIXME

=== [[creating-instance]] Creating HistoryServer Instance

CAUTION: FIXME

=== [[attachSparkUI]] `attachSparkUI` Method

[source, scala]
----
FIXME
----

NOTE: `attachSparkUI` is part of link:spark-history-server-ApplicationCacheOperations.adoc#attachSparkUI[ApplicationCacheOperations Contract] to...FIXME.

`attachSparkUI`...FIXME

=== [[initialize]] Initializing HistoryServer -- `initialize` Method

[source, scala]
----
initialize(): Unit
----

NOTE: `initialize` is part of link:spark-webui-WebUI.adoc#initialize[WebUI Contract] to initialize web components.

`initialize`...FIXME
