== [[UDFRegistration]] UDFRegistration

`UDFRegistration` is an interface to the session-scoped <<functionRegistry, FunctionRegistry>> to register user-defined functions (UDFs) and <<register, user-defined aggregate functions>> (UDAFs).

`UDFRegistration` is available using link:spark-sql-SparkSession.adoc#udf[SparkSession].

[source, scala]
----
import org.apache.spark.sql.SparkSession
val spark: SparkSession = ...
spark.udf
----

`UDFRegistration` is <<creating-instance, created>> exclusively for link:spark-sql-SessionState.adoc#creating-instance[SessionState].

=== [[creating-instance]] Creating UDFRegistration Instance

`UDFRegistration` takes the following when created:

* [[functionRegistry]] link:spark-sql-FunctionRegistry.adoc[FunctionRegistry]

=== [[register]] Registering UserDefinedAggregateFunction (with FunctionRegistry) -- `register` Method

[source, scala]
----
register(
  name: String,
  udaf: UserDefinedAggregateFunction): UserDefinedAggregateFunction
----

`register` link:spark-sql-FunctionRegistry.adoc#registerFunction[registers a UserDefinedAggregateFunction] under `name` with <<functionRegistry, FunctionRegistry>>.

`register` creates a link:spark-sql-Expression-ScalaUDAF.adoc[ScalaUDAF] internally to register a UDAF.

NOTE: `register` gives the input `udaf` aggregate function back after the function has been registered with <<functionRegistry, FunctionRegistry>>.
