== [[QueryExecution]] QueryExecution -- Query Execution of Dataset

`QueryExecution` represents the structured query execution of a link:spark-sql-Dataset.adoc[Dataset] (that, once an action is executed, will "produce" the records as `RDD[InternalRow]`).

NOTE: `QueryExecution` is a transient feature of a link:spark-sql-Dataset.adoc[Dataset], i.e. it is not preserved across serializations.

You can access the `QueryExecution` of a `Dataset` using link:spark-sql-Dataset.adoc#queryExecution[queryExecution] attribute.

[source, scala]
----
val ds: Dataset[Long] = ...
val queryExec = ds.queryExecution
----

`QueryExecution` is the result of link:spark-sql-SessionState.adoc#executePlan[executing a `LogicalPlan` in a `SparkSession`] (and so you could create a `Dataset` from a link:spark-sql-LogicalPlan.adoc[logical operator] or use the `QueryExecution` after executing a logical operator).

[[attributes]]
.QueryExecution's (Lazily-Initialized) Attributes (aka Plan Processing Pipeline)
[cols="1,3",options="header",width="100%"]
|===
| Attribute
| Description

| [[analyzed]] `analyzed`
a| Analyzed logical plan, i.e. <<logical, LogicalPlan>> after link:spark-sql-Analyzer.adoc#execute[going through] `Analyzer`.

TIP: Use Dataset's link:spark-sql-dataset-operators.adoc#explain[explain(extended = true)] or SQL's `EXPLAIN EXTENDED` to see the analyzed logical plan of a structured query.

| [[withCachedData]] `withCachedData`
| `LogicalPlan` that is the `analyzed` plan after being analyzed, checked (for unsupported operations) and replaced with cached segments.

| [[optimizedPlan]] `optimizedPlan`
| Optimized link:spark-sql-LogicalPlan.adoc[LogicalPlan] being the result of executing the session-owned link:spark-sql-SessionState.adoc#optimizer[Catalyst Query Optimizer] to <<withCachedData, withCachedData>>.

| [[sparkPlan]] `sparkPlan`
a| link:spark-sql-SparkPlan.adoc[SparkPlan] that is the result of requesting link:spark-sql-SparkPlanner.adoc[SparkPlanner] to plan a <<optimizedPlan, optimized logical query plan>>.

NOTE: In fact, the result `SparkPlan` is the first Spark query plan from the collection of possible query plans from link:spark-sql-SparkPlanner.adoc[SparkPlanner].

| [[executedPlan]] `executedPlan`
| link:spark-sql-SparkPlan.adoc[SparkPlan] ready for execution, i.e. <<sparkPlan, sparkPlan>> after <<prepareForExecution, all the preparation rules applied>>.

| [[toRdd]] `toRdd`
| `RDD` of link:spark-sql-InternalRow.adoc[InternalRow] records after link:spark-sql-SparkPlan.adoc#execute[executing] the <<executedPlan, SparkPlan>>.
|===

You can access the lazy attributes as follows:

[source, scala]
----
val dataset: Dataset[Long] = ...
dataset.queryExecution.executedPlan
----

`QueryExecution` uses the input `SparkSession` to access the current link:spark-sql-SparkPlanner.adoc[SparkPlanner] (through link:spark-sql-SessionState.adoc[SessionState] that could also return a link:spark-sql-HiveSessionState.adoc[HiveSessionState]) when <<creating-instance, it is created>>. It then computes a link:spark-sql-SparkPlan.adoc[SparkPlan] (a `PhysicalPlan` exactly) using the planner. It is available as the <<sparkPlan, `sparkPlan` attribute>>.

A streaming variant of `QueryExecution` is <<IncrementalExecution, IncrementalExecution>>.

TIP: Use link:spark-sql-dataset-operators.adoc#explain[`explain` operator] to know about the logical and physical plans of a `Dataset`.

[source, scala]
----
val ds = spark.range(5)
scala> ds.queryExecution
res17: org.apache.spark.sql.execution.QueryExecution =
== Parsed Logical Plan ==
Range 0, 5, 1, 8, [id#39L]

== Analyzed Logical Plan ==
id: bigint
Range 0, 5, 1, 8, [id#39L]

== Optimized Logical Plan ==
Range 0, 5, 1, 8, [id#39L]

== Physical Plan ==
WholeStageCodegen
:  +- Range 0, 1, 8, 5, [id#39L]
----

CAUTION: FIXME What's `planner`? Why do we need `assertSupported`?

NOTE: `QueryExecution` belongs to `org.apache.spark.sql.execution` package.

=== [[simpleString]] `simpleString` Method

CAUTION: FIXME

=== [[completeString]] Building Complete Text Representation -- `completeString` Internal Method

CAUTION: FIXME

=== [[creating-instance]] Creating QueryExecution Instance

`QueryExecution` takes the following when created:

* [[sparkSession]] link:spark-sql-sparksession.adoc[SparkSession]
* [[logical]] link:spark-sql-LogicalPlan.adoc[LogicalPlan]

=== [[planner]] Accessing `SparkPlanner` -- `planner` Method

[source, scala]
----
planner: SparkPlanner
----

`planner` returns the current link:spark-sql-SparkPlanner.adoc[SparkPlanner].

`planner` is merely to expose internal link:spark-sql-SessionState.adoc#planner[planner] (in the current link:spark-sql-SessionState.adoc[SessionState]).

=== [[preparations]] preparations -- SparkPlan Preparation Rules (to apply before Query Execution)

`preparations` is a sequence of link:spark-sql-SparkPlan.adoc[SparkPlan] optimization rules.

TIP: A `SparkPlan` optimization rule transforms a link:spark-sql-SparkPlan.adoc[SparkPlan physical operator] to another (possibly more efficient) `SparkPlan`.

`preparations` collection is an intermediate phase of query execution that developers can used to introduce further optimizations.

The current list of `SparkPlan` transformations in `preparations` is as follows:

1. `ExtractPythonUDFs`
2. `PlanSubqueries`
3. link:spark-sql-EnsureRequirements.adoc[EnsureRequirements]
4. `CollapseCodegenStages`
5. `ReuseExchange`
6. `ReuseSubquery`

NOTE: The transformation rules are applied sequentially in order to the physical plan before execution, i.e. they generate a `SparkPlan` when <<executedPlan, executedPlan>> lazy value is accessed.

=== [[prepareForExecution]] Applying preparations Transformation Rules to SparkPlan -- `prepareForExecution` Method

[source, scala]
----
prepareForExecution(plan: SparkPlan): SparkPlan
----

`prepareForExecution` takes <<preparations, preparations>> rules and applies them one by one to the input `plan`.

NOTE: `prepareForExecution` is used exclusively when `QueryExecution` <<executedPlan, calculates `SparkPlan` for execution>>.

=== [[IncrementalExecution]] IncrementalExecution

`IncrementalExecution` is a custom `QueryExecution` with `OutputMode`, `checkpointLocation`, and `currentBatchId`.

It lives in `org.apache.spark.sql.execution.streaming` package.

CAUTION: FIXME What is `stateStrategy`?

Stateful operators in the query plan are numbered using `operatorId` that starts with `0`.

`IncrementalExecution` adds one `Rule[SparkPlan]` called `state` to <<preparations, preparations>> sequence of rules as the first element.

CAUTION: FIXME What does `IncrementalExecution` do? Where is it used?

=== [[assertAnalyzed]] Creating Analyzed Logical Plan and Checking Correctness -- `assertAnalyzed` Method

[source, scala]
----
assertAnalyzed(): Unit
----

`assertAnalyzed` triggers initialization of <<analyzed, analyzed>> (which is almost like executing it).

NOTE: `assertAnalyzed` executes <<analyzed, analyzed>> by accessing it and throwing the result away. Since `analyzed` is a lazy value in Scala, it will then get initialized for the first time and stays so forever.

`assertAnalyzed` then requests `Analyzer` to link:spark-sql-Analyzer-CheckAnalysis.adoc#checkAnalysis[check the correctness of the analysis of the LogicalPlan] (i.e. `analyzed`).

[NOTE]
====
`assertAnalyzed` uses <<sparkSession, SparkSession>> to link:spark-sql-sparksession.adoc#sessionState[access the current `SessionState`] that it then uses to link:spark-sql-SessionState.adoc#analyzer[access the `Analyzer`].

In Scala the access path looks as follows.

[source, scala]
----
sparkSession.sessionState.analyzer
----
====

In case of any `AnalysisException`, `assertAnalyzed` creates a new `AnalysisException` to make sure that it holds <<analyzed, analyzed>> and reports it.

[NOTE]
====
`assertAnalyzed` is used when:

* `Dataset` link:spark-sql-Dataset.adoc#creating-instance[is created]
* `QueryExecution` <<withCachedData, is requested for `LogicalPlan` with cached data>>
* link:spark-sql-CreateViewCommand.adoc#run[CreateViewCommand] and link:spark-sql-AlterViewAsCommand.adoc#run[AlterViewAsCommand] are executed
====

=== [[toString]] Building Extended Text Representation with Logical and Physical Plans -- `toString` Method

[source, scala]
----
toString: String
----

`toString` is a mere alias for <<completeString, completeString>> with `appendStats` flag disabled.

NOTE: `toString` is on the "other" side of <<toStringWithStats, toStringWithStats>> which has `appendStats` flag enabled.

NOTE: `toString` is used when...FIXME

=== [[toStringWithStats]] Building Text Representation with Cost Stats -- `toStringWithStats` Method

[source, scala]
----
toStringWithStats: String
----

`toStringWithStats` is a mere alias for <<completeString, completeString>> with `appendStats` flag enabled.

NOTE: `toStringWithStats` is a custom <<toString, toString>> with cost statistics.

NOTE: `toStringWithStats` is used exclusively when `ExplainCommand` link:spark-sql-LogicalPlan-ExplainCommand.adoc#run[is executed] (only when `cost` attribute is enabled).

=== [[hiveResultString]] Transforming SparkPlan Execution Result to Hive-Compatible Output Format -- `hiveResultString` Method

[source, scala]
----
hiveResultString(): Seq[String]
----

`hiveResultString` returns the result as a Hive-compatible output format.

[source, scala]
----
scala> spark.range(5).queryExecution.hiveResultString
res0: Seq[String] = ArrayBuffer(0, 1, 2, 3, 4)

scala> spark.read.csv("people.csv").queryExecution.hiveResultString
res4: Seq[String] = ArrayBuffer(id	name	age, 0	Jacek	42)
----

Internally, `hiveResultString` <<hiveResultString-transformations, transformation>> the <<executedPlan, SparkPlan>>.

[[hiveResultString-transformations]]
.hiveResultString's SparkPlan Transformations (in execution order)
[width="100%",cols="1,2",options="header"]
|===
| SparkPlan
| Description

| link:spark-sql-SparkPlan-ExecutedCommandExec.adoc[ExecutedCommandExec] for `DescribeTableCommand`
| Executes `DescribeTableCommand` and transforms every link:spark-sql-Row.adoc[Row] to a Hive-compatible output format.

| link:spark-sql-SparkPlan-ExecutedCommandExec.adoc[ExecutedCommandExec] for `ShowTablesCommand`
| Executes `ExecutedCommandExec` and transforms the result to a collection of table names.

| Any other link:spark-sql-SparkPlan.adoc[SparkPlan]
| Executes `SparkPlan` and transforms the result to a Hive-compatible output format.
|===

NOTE: `hiveResultString` is used exclusively when `SparkSQLDriver` (of ThriftServer) runs a command.
