== [[CollectionGenerator]] CollectionGenerator Generator Expression Contract

`CollectionGenerator` is the <<contract, contract>> in Spark SQL for link:spark-sql-Expression-Generator.adoc[Generator expressions] that <<collectionType, generate a collection object>> (i.e. an array or map) and (at execution time) link:spark-sql-SparkPlan-GenerateExec.adoc#doConsume[use a different path for whole-stage Java code generation] (while executing `GenerateExec` physical operator with link:spark-sql-whole-stage-codegen.adoc[Whole-Stage Java Code Generation] enabled).

[[contract]]
[source, scala]
----
package org.apache.spark.sql.catalyst.expressions

trait CollectionGenerator extends Generator {
  def collectionType: DataType = dataType
  def inline: Boolean
  def position: Boolean
}
----

.CollectionGenerator Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[collectionType]] `collectionType`
| The type of the returned collection object.

Used when...

| [[inline]] `inline`
| Flag whether to inline rows during whole-stage Java code generation.

Used when...

| [[position]] `position`
| Flag whether to include the positions of elements within the result collection.

Used when...
|===

[[implementations]]
.CollectionGenerators
[cols="1,2",options="header",width="100%"]
|===
| CollectionGenerator
| Description

| link:spark-sql-Expression-Inline.adoc[Inline]
|

| link:spark-sql-Expression-ExplodeBase.adoc[ExplodeBase]
|

| link:spark-sql-Expression-ExplodeBase.adoc#Explode[Explode]
|

| link:spark-sql-Expression-ExplodeBase.adoc#PosExplode[PosExplode]
|
|===
