== [[WindowExpression]] WindowExpression

`WindowExpression` is an link:spark-sql-catalyst-Expression.adoc#Unevaluable[Unevaluable expression] (i.e. `eval` and `doGenCode` are not supported).

[source, scala]
----
import org.apache.spark.sql.catalyst.expressions.WindowExpression
scala> val windowExpr = spark.emptyDataset[Int]
  .selectExpr("count() OVER (PARTITION BY value) AS count")
  .queryExecution
  .logical
  .expressions
  .toList(0)
  .children(0)
  .asInstanceOf[WindowExpression]
windowExpr: org.apache.spark.sql.catalyst.expressions.WindowExpression = 'count() windowspecdefinition('value, UnspecifiedFrame)

scala> windowExpr.sql
res2: String = count() OVER (PARTITION BY `value` UnspecifiedFrame)
----

[[windowFunction]][[windowSpec]]
`WindowExpression` is created for `windowFunction` and `WindowSpecDefinition` link:spark-sql-catalyst-Expression.adoc[expressions].

NOTE: `WindowExpression` is used in `Analyzer` in link:spark-sql-Analyzer.adoc#ExtractWindowExpressions[ExtractWindowExpressions], link:spark-sql-Analyzer.adoc#ResolveWindowOrder[ResolveWindowOrder] link:spark-sql-Analyzer.adoc#ResolveWindowFrame[ResolveWindowFrame], link:spark-sql-Analyzer.adoc#WindowsSubstitution[WindowsSubstitution] rules.

NOTE: `WindowExpression` is also used in `Analyzer` for link:spark-sql-Analyzer-CheckAnalysis.adoc[analysis validation] for the following checks: FIXME...

NOTE: `WindowExpression` is used in link:spark-sql-Optimizer-NullPropagation.adoc[NullPropagation] optimization.

[[properties]]
.WindowExpression's Properties (in alphabetical order)
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| `children`
| Collection of two link:spark-sql-catalyst-Expression.adoc[expressions], i.e. <<windowFunction, windowFunction>> and <<windowSpec, WindowSpecDefinition>>, for which `WindowExpression` was created.

| `dataType`
| link:spark-sql-DataType.adoc[DataType] of <<windowFunction, windowFunction>>

| `foldable`
| Whether or not <<windowFunction, windowFunction>> is foldable.

| `nullable`
| Whether or not <<windowFunction, windowFunction>> is nullable.

| `sql`
| `"[windowFunction].sql OVER [windowSpec].sql"`

| `toString`
| `"[windowFunction] [windowSpec]"`
|===
