== [[event-logging]] Persisting Events using EventLoggingListener

Spark has a <<spark-listeners, SparkListener>> called `EventLoggingListener` that logs JSON-encoded events to persistent storage.

NOTE: It uses `JsonProtocol` class to log events.

When `EventLoggingListener` starts, it prints out the following INFO message to the logs:

```
INFO Logging events to [logPath]
```

=== [[settings]] Settings

`EventLoggingListener` uses the following properties:

* `spark.eventLog.enabled` (default: `false`) - whether to log Spark events that encode the information displayed in the UI to persisted storage. It is useful for reconstructing the Web UI after a Spark application has finished.
* `spark.eventLog.compress` (default: `false`) - whether to compress logged events.
* `spark.eventLog.overwrite` (default: `false`) - whether to overwrite any existing files.
* `spark.eventLog.dir` (default: `/tmp/spark-events`) - path to the directory in which events are logged, e.g. `hdfs://namenode:8021/directory`. The directory must exist before Spark starts up.
* `spark.eventLog.buffer.kb` (default: `100`) - buffer size to use when writing to output streams.
* `spark.eventLog.testing` (default: `false`)
