== [[HiveSessionState]] HiveSessionState -- Hive-Specific SessionState

`HiveSessionState` class uses an custom anonymous link:spark-sql-SparkPlanner.adoc[SparkPlanner] for `planner` method (part of the link:spark-sql-SessionState.adoc[SessionState] contract).

The custom anonymous `SparkPlanner` uses `Strategy` objects defined in `HiveStrategies`.

[[attributes]]
.HiveSessionState's (Lazily-Initialized) Attributes (in alphabetical order)
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Type
| Description

| [[sqlParser]] `sqlParser`
| link:spark-sql-ParserInterface.adoc[ParserInterface]
| FIXME

Used when...FIXME
|===

=== [[apply]] `apply` Factory Methods

CAUTION: FIXME

[source, scala]
----
apply(sparkSession: SparkSession): HiveSessionState // <1>
apply(sparkSession: SparkSession, conf: SQLConf): HiveSessionState
----
<1> Passes `sparkSession` to the other `apply` with a new `SQLConf`

NOTE: `apply` is used exclusively when `SparkSession` link:spark-sql-sparksession.adoc#instantiateSessionState[is requested for the current `SessionState`].

=== [[clone]] `clone` Method

CAUTION: FIXME

NOTE: `clone` is used when...

=== [[createAnalyzer]] `createAnalyzer` Internal Method

[source, scala]
----
createAnalyzer(
  sparkSession: SparkSession,
  catalog: HiveSessionCatalog,
  sqlConf: SQLConf): Analyzer
----

`createAnalyzer` creates a logical query plan link:spark-sql-Analyzer.adoc[Analyzer] with rules specific to the Hive-specific link:spark-sql-SessionState.adoc[SessionState], i.e. <<HiveSessionState, HiveSessionState>>.

[[batches]]
.Analyzer's Evaluation Rules for HiveSessionState (in the order of execution)
[cols="2,1,3",options="header",width="100%"]
|===
^.^| Method
| Rules
| Description

.3+^.^| extendedResolutionRules
| ResolveHiveSerdeTable
|

| FindDataSourceTable
| Replaces `InsertIntoTable` (with `CatalogRelation`) and `CatalogRelation` logical plans with `LogicalRelation`.

| ResolveSQLOnFile
|

.7+^.^| postHocResolutionRules
| DetermineTableStats
|

| ParquetConversions
|

| OrcConversions
|

| PreprocessTableCreation
|

| PreprocessTableInsertion
|

| DataSourceAnalysis
|

| HiveAnalysis
|

^.^| extendedCheckRules
| PreWriteCheck
|
|===

NOTE: `createAnalyzer` is used when `HiveSessionState` is <<apply, created>> or <<clone, cloned>>.

=== [[planner]] `planner` Method

CAUTION: FIXME
