== Building Spark

You can download pre-packaged versions of Apache Spark from http://spark.apache.org/downloads.html[the project's web site]. The packages are built for a different Hadoop versions, but only for Scala 2.10.

NOTE: Since https://github.com/apache/spark/commit/289373b28cd2546165187de2e6a9185a1257b1e7[[SPARK-6363\][BUILD\] Make Scala 2.11 the default Scala version] the default version of Scala is *2.11*.

If you want a *Scala 2.11* version of Apache Spark _"users should download the Spark source package and build with Scala 2.11 support"_ (quoted from the Note at http://spark.apache.org/downloads.html[Download Spark]).

The build process for Scala 2.11 takes around 15 mins (on a decent machine) and is so simple that it's unlikely to refuse the urge to do it yourself.

You can use <<sbt, sbt>> or <<maven, Maven>> as the build command.

=== [[sbt]] Using sbt as the build tool

The build command with sbt as the build tool is as follows:

```
./build/sbt -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.1 -Phive -Phive-thriftserver -DskipTests clean assembly
```

Using Java 8 to build Spark using sbt takes ca 10 minutes.

```
➜  spark git:(master) ✗ ./build/sbt -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.1 -Phive -Phive-thriftserver -DskipTests clean assembly
...
[success] Total time: 496 s, completed Dec 7, 2015 8:24:41 PM
```

=== [[maven]] Using Apache Maven as the build tool

The build command with Apache Maven is as follows:

```
$ ./build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.1 -Phive -Phive-thriftserver -DskipTests clean install
```

After a couple of minutes your freshly baked distro is ready to fly!

I'm using Oracle Java 8 to build Spark.

```
➜  spark git:(master) ✗ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

➜  spark git:(master) ✗ ./build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.1 -Phive -Phive-thriftserver -DskipTests clean install
Using `mvn` from path: /usr/local/bin/mvn
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Spark Project Parent POM
[INFO] Spark Project Launcher
[INFO] Spark Project Networking
[INFO] Spark Project Shuffle Streaming Service
[INFO] Spark Project Unsafe
[INFO] Spark Project Core
[INFO] Spark Project Bagel
[INFO] Spark Project GraphX
[INFO] Spark Project Streaming
[INFO] Spark Project Catalyst
[INFO] Spark Project SQL
[INFO] Spark Project ML Library
[INFO] Spark Project Tools
[INFO] Spark Project Hive
[INFO] Spark Project REPL
[INFO] Spark Project YARN Shuffle Service
[INFO] Spark Project YARN
[INFO] Spark Project Hive Thrift Server
[INFO] Spark Project Assembly
[INFO] Spark Project External Twitter
[INFO] Spark Project External Flume Sink
[INFO] Spark Project External Flume
[INFO] Spark Project External Flume Assembly
[INFO] Spark Project External MQTT
[INFO] Spark Project External MQTT Assembly
[INFO] Spark Project External ZeroMQ
[INFO] Spark Project External Kafka
[INFO] Spark Project Examples
[INFO] Spark Project External Kafka Assembly
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spark Project Parent POM 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ spark-parent_2.11 ---
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spark Project Parent POM ........................... SUCCESS [  3.731 s]
[INFO] Spark Project Test Tags ............................ SUCCESS [  3.611 s]
[INFO] Spark Project Sketch ............................... SUCCESS [  5.722 s]
[INFO] Spark Project Launcher ............................. SUCCESS [  9.695 s]
[INFO] Spark Project Networking ........................... SUCCESS [ 11.342 s]
[INFO] Spark Project Shuffle Streaming Service ............ SUCCESS [  7.307 s]
[INFO] Spark Project Unsafe ............................... SUCCESS [  7.882 s]
[INFO] Spark Project Core ................................. SUCCESS [01:58 min]
[INFO] Spark Project GraphX ............................... SUCCESS [ 16.775 s]
[INFO] Spark Project Streaming ............................ SUCCESS [ 38.474 s]
[INFO] Spark Project Catalyst ............................. SUCCESS [01:33 min]
[INFO] Spark Project SQL .................................. SUCCESS [01:17 min]
[INFO] Spark Project ML Library ........................... SUCCESS [01:20 min]
[INFO] Spark Project Tools ................................ SUCCESS [  5.239 s]
[INFO] Spark Project Hive ................................. SUCCESS [ 44.372 s]
[INFO] Spark Project Docker Integration Tests ............. SUCCESS [  2.009 s]
[INFO] Spark Project REPL ................................. SUCCESS [  6.495 s]
[INFO] Spark Project YARN Shuffle Service ................. SUCCESS [  6.818 s]
[INFO] Spark Project YARN ................................. SUCCESS [ 13.716 s]
[INFO] Spark Project Hive Thrift Server ................... SUCCESS [  9.813 s]
[INFO] Spark Project Assembly ............................. SUCCESS [ 40.605 s]
[INFO] Spark Project External Twitter ..................... SUCCESS [  7.439 s]
[INFO] Spark Project External Flume Sink .................. SUCCESS [  6.325 s]
[INFO] Spark Project External Flume ....................... SUCCESS [  9.567 s]
[INFO] Spark Project External Flume Assembly .............. SUCCESS [  1.655 s]
[INFO] Spark Project External Akka ........................ SUCCESS [  6.172 s]
[INFO] Spark Project External MQTT ........................ SUCCESS [ 14.146 s]
[INFO] Spark Project External MQTT Assembly ............... SUCCESS [  2.126 s]
[INFO] Spark Project External ZeroMQ ...................... SUCCESS [  7.035 s]
[INFO] Spark Project External Kafka ....................... SUCCESS [ 12.157 s]
[INFO] Spark Project Examples ............................. SUCCESS [01:00 min]
[INFO] Spark Project External Kafka Assembly .............. SUCCESS [  3.033 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:15 min
[INFO] Finished at: 2016-01-30T22:29:53+01:00
[INFO] Final Memory: 119M/1526M
[INFO] ------------------------------------------------------------------------
```

Please note the messages that say the version of Spark (_Building Spark Project Parent POM 2.0.0-SNAPSHOT_), Scala version (_maven-clean-plugin:2.6.1:clean (default-clean) @ spark-parent_2.11_) and the Spark modules built.

The above command gives you the latest version of *Apache Spark 2.0.0-SNAPSHOT* built for *Scala 2.11.7* (see https://github.com/apache/spark/blob/master/pom.xml#L2488-L2497[the configuration of scala-2.11 profile]).

TIP: You can also know the version of Spark using `./bin/spark-shell --version`.

=== [[make-distribution]] Making Distribution

`./make-distribution.sh` is the shell script to make a distribution. It uses the same profiles as for sbt and Maven.

Use `--tgz` option to have a tar gz version of the Spark distribution.

```
➜  spark git:(master) ✗ ./make-distribution.sh --tgz -Pyarn -Phadoop-2.6 -Dhadoop.version=2.7.1 -Phive -Phive-thriftserver -DskipTests
```

Once finished, you will have the distribution in the current directory, i.e. `spark-2.0.0-SNAPSHOT-bin-2.7.1.tgz`.
