== [[StoragePage]] StoragePage

[[prefix]]
`StoragePage` is a link:spark-webui-WebUIPage.adoc[WebUIPage] with an empty link:spark-webui-WebUIPage.adoc#prefix[prefix].

`StoragePage` is <<creating-instance, created>> exclusively when `StorageTab` is link:spark-webui-StorageTab.adoc#creating-instance[created].

[[creating-instance]]
`StoragePage` takes the following when created:

* [[parent]] Parent link:spark-webui-SparkUITab.adoc[SparkUITab]
* [[store]] link:spark-core-AppStatusStore.adoc[AppStatusStore]

=== [[rddRow]] Rendering HTML Table Row for RDD Details -- `rddRow` Internal Method

[source, scala]
----
rddRow(rdd: v1.RDDStorageInfo): Seq[Node]
----

`rddRow`...FIXME

NOTE: `rddRow` is used when...FIXME

=== [[rddTable]] Rendering HTML Table for RDD Details -- `rddTable` Method

[source, scala]
----
rddTable(rdds: Seq[v1.RDDStorageInfo]): Seq[Node]
----

`rddTable`...FIXME

NOTE: `rddTable` is used when...FIXME

=== [[render]] `render` Method

[source, scala]
----
render(request: HttpServletRequest): Seq[Node]
----

NOTE: `render` is part of link:spark-webui-WebUIPage.adoc#render[WebUIPage Contract] to...FIXME.

`render`...FIXME
