== [[ExpressionEncoder]] ExpressionEncoder

`ExpressionEncoder` is a generic link:spark-sql-Encoder.adoc[Encoder] for the JVM type `T` that uses link:spark-sql-Expression.adoc[expressions] to <<serializer, serialize>> to and <<deserializer, deserialize>> from the link:spark-sql-InternalRow.adoc[internal binary row format].

NOTE: `ExpressionEncoder` is the only supported implementation of `Encoder` which is explicitly enforced when `Dataset` link:spark-sql-Dataset.adoc#exprEnc[is created] (even though `Dataset` can be created with a bare `Encoder[T]`).

`ExpressionEncoder` uses <<serializer, serializer expressions>> to encode (aka _serialize_) a JVM object of type `T` to an link:spark-sql-InternalRow.adoc[internal binary row format]. It is assumed that all serializer expressions contain at least one and the same `BoundReference`.

CAUTION: FIXME What's `BoundReference`?

`ExpressionEncoder` uses a <<deserializer, deserializer expression>> to decode a JVM object of type `T` from link:spark-sql-InternalRow.adoc[internal binary row format].

`ExpressionEncoder` is <<flat, flat>> when there is only one expression for the <<serializer, serializer>>.

Internally, a `ExpressionEncoder` creates a `UnsafeProjection` (for the input serializer), a link:spark-sql-InternalRow.adoc[InternalRow] (of size `1`), and a safe `Projection` (for the input deserializer). They are all internal lazy attributes of the encoder.

NOTE: `Encoders` object contains the default `ExpressionEncoders` for Scala and Java primitive types, e.g. `boolean`, `long`, `String`, `java.sql.Date`, `java.sql.Timestamp`, `Array[Byte]`.

=== [[resolveAndBind]] `resolveAndBind` Method

CAUTION: FIXME

=== [[creating-instance]] Creating ExpressionEncoder Instance

`ExpressionEncoder` takes the following when created:

* [[schema]] link:spark-sql-StructType.adoc[Schema]
* [[flat]] Flag whether `ExpressionEncoder` is flat or not
* [[serializer]] Serializer link:spark-sql-Expression.adoc[expressions]
* [[deserializer]] Deserializer link:spark-sql-Expression.adoc[expression]
* [[clsTag]] Scala's http://www.scala-lang.org/api/current/scala/reflect/ClassTag.html[ClassTag] for the JVM type `T`

=== [[deserializerFor]][[ScalaReflection-deserializerFor]] Creating Deserialize Expression -- `ScalaReflection.deserializerFor` Method

[source, scala]
----
deserializerFor[T: TypeTag]: Expression
----

`deserializerFor` creates an link:spark-sql-Expression.adoc[expression] to deserialize from link:spark-sql-InternalRow.adoc[internal binary row format] to a Scala type `T`.

[source, scala]
----
import org.apache.spark.sql.catalyst.ScalaReflection.deserializerFor
val timestampDeExpr = deserializerFor[java.sql.Timestamp]
scala> println(timestampDeExpr.numberedTreeString)
00 staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, ObjectType(class java.sql.Timestamp), toJavaTimestamp, upcast(getcolumnbyordinal(0, TimestampType), TimestampType, - root class: "java.sql.Timestamp"), true)
01 +- upcast(getcolumnbyordinal(0, TimestampType), TimestampType, - root class: "java.sql.Timestamp")
02    +- getcolumnbyordinal(0, TimestampType)

val tuple2DeExpr = deserializerFor[(java.sql.Timestamp, Double)]
scala> println(tuple2DeExpr.numberedTreeString)
00 newInstance(class scala.Tuple2)
01 :- staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, ObjectType(class java.sql.Timestamp), toJavaTimestamp, upcast(getcolumnbyordinal(0, TimestampType), TimestampType, - field (class: "java.sql.Timestamp", name: "_1"), - root class: "scala.Tuple2"), true)
02 :  +- upcast(getcolumnbyordinal(0, TimestampType), TimestampType, - field (class: "java.sql.Timestamp", name: "_1"), - root class: "scala.Tuple2")
03 :     +- getcolumnbyordinal(0, TimestampType)
04 +- upcast(getcolumnbyordinal(1, DoubleType), DoubleType, - field (class: "scala.Double", name: "_2"), - root class: "scala.Tuple2")
05    +- getcolumnbyordinal(1, DoubleType)
----

Internally, `deserializerFor` uses a single-element walked type path with `- root class: "[clsName]"` and the recursive internal variant of <<deserializerFor-recursive, deserializerFor>>.

TIP: Read up on Scala's `TypeTags` in http://docs.scala-lang.org/overviews/reflection/typetags-manifests.html[TypeTags and Manifests].

NOTE: `deserializerFor` is used exclusively when `ExpressionEncoder` <<creating-instance, is created>> for a Scala type `T`.

==== [[deserializerFor-recursive]] Recursive Internal `deserializerFor` Method

[source, scala]
----
deserializerFor(
  tpe: `Type`,
  path: Option[Expression],
  walkedTypePath: Seq[String]): Expression
----

.JVM Types and Deserialize Expressions (in evaluation order)
[cols="1,1",options="header",width="100%"]
|===
| JVM Type (Scala or Java)
| Deserialize Expressions

| `Option[T]`
|

| `java.lang.Integer`
|

| `java.lang.Long`
|

| `java.lang.Double`
|

| `java.lang.Float`
|

| `java.lang.Short`
|

| `java.lang.Byte`
|

| `java.lang.Boolean`
|

| `java.sql.Date`
|

| `java.sql.Timestamp`
|

| `java.lang.String`
|

| `java.math.BigDecimal`
|

| `scala.BigDecimal`
|

| `java.math.BigInteger`
|

| `scala.math.BigInt`
|

| `Array[T]`
|

| `Seq[T]`
|

| `Map[K, V]`
|

| `SQLUserDefinedType`
|

| User Defined Types (UDTs)
|

| `Product` (including `Tuple`) or `DefinedByConstructorParams`
|
|===
