== [[ApplicationHistoryProvider]] ApplicationHistoryProvider

`ApplicationHistoryProvider` is the <<contract, base>> of the <<implementations, history providers>> of <<getListing, Spark applications>>.

[[contract]]
[source, scala]
----
package org.apache.spark.deploy.history

abstract class ApplicationHistoryProvider {
  // only required methods that have no implementation
  // the others follow
  def getListing(): Iterator[ApplicationInfo]
  def getAppUI(appId: String, attemptId: Option[String]): Option[LoadedAppUI]
  def writeEventLogs(appId: String, attemptId: Option[String], zipStream: ZipOutputStream): Unit
  def getApplicationInfo(appId: String): Option[ApplicationInfo]
}
----

NOTE: `ApplicationHistoryProvider` is a `private[history]` contract.

.(Subset of) ApplicationHistoryProvider Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `getListing`
| [[getListing]]

| `getAppUI`
| [[getAppUI]] link:spark-webui-SparkUI.adoc[Spark UI] (the UI of a Spark application)

Used exclusively when `HistoryServer` is requested for the link:spark-history-server-HistoryServer.adoc#getAppUI[UI of a Spark application]

| `writeEventLogs`
| [[writeEventLogs]] Writes events to a stream

| `getApplicationInfo`
| [[getApplicationInfo]]
|===

`ApplicationHistoryProvider` is a Scala abstract class and cannot be created directly, but only as one of the <<implementations, implementations>>.

[[implementations]]
NOTE: link:spark-history-server-FsHistoryProvider.adoc[FsHistoryProvider] is the one and only known implementation of <<contract, ApplicationHistoryProvider contract>> in Apache Spark.
