== Streaming Listeners

*Streaming listeners* are listeners interested in streaming events.

Streaming listeners implement `org.apache.spark.streaming.scheduler.StreamingListener` listener interface and process `StreamingListenerEvent` events.

The following streaming listeners are available in Spark Streaming:

* <<StreamingJobProgressListener, StreamingJobProgressListener>>

=== [[StreamingListenerEvent]] StreamingListenerEvent Events

* `StreamingListenerBatchStarted` triggers `StreamingListener.onBatchStarted`

* `StreamingListenerBatchSubmitted` is posted when <<submitJobSet, streaming jobs are submitted for execution>> and triggers `StreamingListener.onBatchSubmitted`

=== [[StreamingJobProgressListener]] StreamingJobProgressListener

`StreamingJobProgressListener` is a streaming listener.

NOTE: It is created while link:spark-streaming-streamingcontext.adoc#creating-instance[StreamingContext is created] and later registered as a `StreamingListener` and `SparkListener` when link:spark-streaming-webui.adoc[Streaming tab] is created.

==== onBatchSubmitted

For `StreamingListenerBatchSubmitted(batchInfo: BatchInfo)` events, it stores `batchInfo` batch information in the internal `waitingBatchUIData` registry per batch time.

The number of entries in `waitingBatchUIData` registry contributes to `numUnprocessedBatches` (together with `runningBatchUIData`), `waitingBatches`, and `retainedBatches`. It is also used to look up the batch data for a batch time (in `getBatchUIData`).

`numUnprocessedBatches`, `waitingBatches` are used in link:spark-streaming.adoc#StreamingSource[StreamingSource].

NOTE: `waitingBatches` and `runningBatches` are displayed together in link:spark-streaming-webui.adoc#active-batches[Active Batches in Streaming tab in web UI].

==== onBatchStarted

CAUTION: FIXME

==== onBatchCompleted

CAUTION: FIXME

==== [[retainedBatches]] Retained Batches

CAUTION: FIXME

`retainedBatches` = waiting, running, and completed batches.
