== JobGenerator

CAUTION: FIXME

When `JobGenerator` is created, it creates link:spark-streaming-jobscheduler.adoc#RecurringTimer[RecurringTimer] (as `timer` with name being `JobGenerator`) to post link:spark-streaming.adoc#GenerateJobs[GenerateJobs] events to <<eventLoop, JobGenerator eventLoop>> (it is only when `JobGenerator` is started when the JobGenerator eventLoop starts processing events).

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.streaming.scheduler.JobGenerator` logger to see what happens in JobGenerator.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.streaming.scheduler.JobGenerator=DEBUG
```
====

For every `JobGeneratorEvent` event, you should see the following DEBUG message in the logs:

```
DEBUG Got event [event]
```

You should see the following INFO message in the logs when it starts:

```
INFO JobGenerator: Started JobGenerator at [startTime] ms
```

=== [[eventLoop]] JobGenerator eventLoop and JobGeneratorEvent Handler

JobGenerator uses `EventLoop` for JobGeneratorEvent events.

See below for extensive coverage of event types it handles.

==== [[GenerateJobs]] GenerateJobs and JobGenerator.generateJobs

CAUTION: FIXME

When `GenerateJobs` is received (FIXME when?) `JobGenerator.generateJobs(time: Time)` is executed to process it.

It calls `JobScheduler.receiverTracker.allocateBlocksToBatch`, and then calls link:spark-streaming.adoc#DStreamGraph-generateJobs[DStreamGraph.generateJobs(time: Time)].

When it finishes successfully, a collection of jobs is given that are passed to link:spark-streaming-jobscheduler.adoc#submitJobSet[JobScheduler.submitJobSet] as a `JobSet`.

Ultimately, it posts <<DoCheckpoint, DoCheckpoint>> event.

==== [[ClearMetadata]] ClearMetadata and clearMetadata

CAUTION: FIXME

==== [[DoCheckpoint]] DoCheckpoint and doCheckpoint

CAUTION: FIXME

==== [[ClearCheckpointData]] ClearCheckpointData and clearCheckpointData

CAUTION: FIXME
