== [[SortShuffleManager]] SortShuffleManager -- The Default Shuffle System

CAUTION: FIXME

`SortShuffleManager` is a shuffle manager with the short name being `sort` or `tungsten-sort`.

<<creating-instance, `SortShuffleManager` is created>> for the driver and executors.

`SortShuffleManager` uses `IndexShuffleBlockResolver` (as <<shuffleBlockResolver, `shuffleBlockResolver` internal registry>>).

[[internal-registries]]
.`SortShuffleManager` Internal Registries and Counters
[frame="topbot",cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| [[numMapsForShuffle]] `numMapsForShuffle`
|

| [[shuffleBlockResolver]] `shuffleBlockResolver`
|

Used when ???
|===

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.shuffle.sort.SortShuffleManager$` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.shuffle.sort.SortShuffleManager$=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[creating-instance]] Creating SortShuffleManager Instance

`SortShuffleManager` takes a link:spark-configuration.adoc[SparkConf].

`SortShuffleManager` makes sure that `spark.shuffle.spill` Spark property is enabled. If not you should see the following WARN message in the logs:

```
WARN SortShuffleManager: spark.shuffle.spill was set to false, but this configuration is ignored as of Spark 1.6+. Shuffle will continue to spill to disk when necessary.
```

`SortShuffleManager` <<internal-registries, initializes the internal registries and counters>>.

NOTE: `SortShuffleManager` is created when link:spark-sparkenv.adoc#ShuffleManager[`SparkEnv` is created] (per the driver and executors).

=== [[registerShuffle]] `registerShuffle` Method

[source, scala]
----
registerShuffle[K, V, C](
  shuffleId: Int,
  numMaps: Int,
  dependency: ShuffleDependency[K, V, C]): ShuffleHandle
----

NOTE: `registerShuffle` is a part of link:spark-shuffle-manager.adoc#contract[ShuffleManager contract].

`registerShuffle` returns a `ShuffleHandle`
