== [[Aggregation]] Aggregation Execution Planning Strategy

CAUTION: FIXME

[NOTE]
====
`Strategy` is a mere https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/package.scala#L44[type alias] (aka _type synonym_) for `SparkStrategy` type in `sql` package object, i.e.

[source, scala]
----
type Strategy = SparkStrategy
----
====

=== [[apply]] Executing Strategy -- `apply` Method

[source, scala]
----
apply(plan: LogicalPlan): Seq[SparkPlan]
----

`apply`

NOTE: `apply` is a part of link:spark-sql-catalyst-GenericStrategy.adoc#apply[GenericStrategy Contract].

=== [[PhysicalAggregation]][[PhysicalAggregation-unapply]] `PhysicalAggregation.unapply` Method

[source, scala]
----
unapply(a: Any): Option[ReturnType]
----

`unapply` destructures a link:spark-sql-LogicalPlan.adoc[logical plan], i.e. breaks a `LogicalPlan` into pieces.

[NOTE]
====

`ReturnType` is a type alias (aka _type synonym_) for a 4-element tuple with grouping, aggregate and result link:spark-sql-catalyst-Expression.adoc[expressions], and child link:spark-sql-LogicalPlan.adoc[logical operator].

[source, scala]
----
type ReturnType =
  (Seq[NamedExpression], Seq[AggregateExpression], Seq[NamedExpression], LogicalPlan)
----
====

NOTE: `PhysicalAggregation` is a Scala http://docs.scala-lang.org/tutorials/tour/extractor-objects.html[extractor object] with a single <<PhysicalAggregation-unapply, unapply>> method.

=== [[AggUtils]][[AggUtils-planAggregateWithoutDistinct]] `AggUtils.planAggregateWithoutDistinct` Method

=== [[AggUtils-planAggregateWithOneDistinct]] `AggUtils.planAggregateWithOneDistinct` Method
