== [[AppStatusListener]] AppStatusListener

`AppStatusListener` is a link:spark-SparkListener.adoc[SparkListener] that...FIXME

[[internal-registries]]
.AppStatusListener's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `liveRDDs`
| [[liveRDDs]] link:spark-core-LiveRDD.adoc[LiveRDDs] by RDD ID
|===

=== [[onStageSubmitted]] `onStageSubmitted` Method

[source, scala]
----
onStageSubmitted(event: SparkListenerStageSubmitted): Unit
----

NOTE: `onStageSubmitted` is part of link:spark-SparkListener.adoc#onStageSubmitted[SparkListener Contract] to...FIXME.

`onStageSubmitted`...FIXME

=== [[update]] `update` Internal Method

[source, scala]
----
update(entity: LiveEntity, now: Long, last: Boolean = false): Unit
----

`update` simply requests the `LiveEntity` to link:spark-core-LiveEntity.adoc#write[write] (with the <<kvstore, ElementTrackingStore>> as the store and the `last` flag as `checkTriggers` flag).

NOTE: `update` is used in event handlers (i.e. `onApplicationStart`, `onExecutorRemoved`, `onJobEnd`, `onStageSubmitted`, `onTaskEnd`, `onStageCompleted`), <<liveUpdate, liveUpdate>>, <<maybeUpdate, maybeUpdate>>, <<flush, flush>> and <<updateRDDBlock, updateRDDBlock>>.

=== [[flush]] `flush` Internal Method

[source, scala]
----
flush(): Unit
----

`flush`...FIXME

NOTE: `flush` is used when...FIXME

=== [[maybeUpdate]] `maybeUpdate` Internal Method

[source, scala]
----
maybeUpdate(entity: LiveEntity, now: Long): Unit
----

`maybeUpdate`...FIXME

NOTE: `maybeUpdate` is used when...FIXME

=== [[liveUpdate]] `liveUpdate` Internal Method

[source, scala]
----
liveUpdate(entity: LiveEntity, now: Long): Unit
----

`liveUpdate`...FIXME

NOTE: `liveUpdate` is used when...FIXME

=== [[updateRDDBlock]] `updateRDDBlock` Internal Method

[source, scala]
----
updateRDDBlock(event: SparkListenerBlockUpdated, block: RDDBlockId): Unit
----

`updateRDDBlock`...FIXME

NOTE: `updateRDDBlock` is used when...FIXME
