== [[ShuffleManager]] ShuffleManager Contract -- Pluggable Shuffle Systems

`ShuffleManager` is the <<contract, contract>> of <<implementations, shuffle systems>> that manage shuffle metadata on the driver (using shuffle IDs or `ShuffleHandle`) and allows running tasks on executors to access the metadata.

[[contract]]
.ShuffleManager Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| getReader
a| [[getReader]]

[source, scala]
----
getReader[K, C](
  handle: ShuffleHandle,
  startPartition: Int,
  endPartition: Int,
  context: TaskContext): ShuffleReader[K, C]
----

Used when the following RDDs are requested to <<spark-rdd-RDD.adoc#compute, compute a partition>>:

* <<spark-rdd-CoGroupedRDD.adoc#, CoGroupedRDD>>

* <<spark-rdd-ShuffledRDD.adoc#, ShuffledRDD>>

* <<spark-rdd-SubtractedRDD.adoc#, SubtractedRDD>>

* `ShuffledRowRDD` (Spark SQL)

| getWriter
a| [[getWriter]]

[source, scala]
----
getWriter[K, V](
  handle: ShuffleHandle,
  mapId: Int,
  context: TaskContext): ShuffleWriter[K, V]
----

<<spark-shuffle-ShuffleWriter.adoc#, ShuffleWriter>> for the `ShuffleHandle` and `mapId`

Used exclusively when `ShuffleMapTask` is requested to <<spark-scheduler-ShuffleMapTask.adoc#runTask, run>> (and requests the <<spark-shuffle-ShuffleWriter.adoc#, ShuffleWriter>> to write records for a partition)

| registerShuffle
a| [[registerShuffle]]

[source, scala]
----
registerShuffle[K, V, C](
  shuffleId: Int,
  numMaps: Int,
  dependency: ShuffleDependency[K, V, C]): ShuffleHandle
----

Registers a shuffle (by the given `shuffleId` and <<spark-rdd-ShuffleDependency.adoc#, ShuffleDependency>>) and returns a `ShuffleHandle`

Used exclusively when `ShuffleDependency` is <<spark-rdd-ShuffleDependency.adoc#shuffleHandle, created>> (and registers itself with the shuffle system)

| shuffleBlockResolver
a| [[shuffleBlockResolver]]

[source, scala]
----
shuffleBlockResolver: ShuffleBlockResolver
----

<<spark-shuffle-ShuffleBlockResolver.adoc#, ShuffleBlockResolver>> of the shuffle system

Used when...FIXME

| stop
a| [[stop]]

[source, scala]
----
stop(): Unit
----

Stops the shuffle system

Used exclusively when `SparkEnv` is requested to <<spark-SparkEnv.adoc#stop, stop>>

| unregisterShuffle
a| [[unregisterShuffle]]

[source, scala]
----
unregisterShuffle(shuffleId: Int): Boolean
----

Unregisters a shuffle (given `shuffleId`)

Used exclusively when `BlockManagerSlaveEndpoint` is requested to <<spark-blockmanager-BlockManagerSlaveEndpoint.adoc#RemoveShuffle, receives a RemoveShuffle message>>

|===

The driver and executor access the `ShuffleManager` instance using link:spark-SparkEnv.adoc#shuffleManager[SparkEnv.shuffleManager].

[source, scala]
----
val shuffleManager = SparkEnv.get.shuffleManager
----

The driver registers shuffles with a shuffle manager, and executors (or tasks running locally in the driver) can ask to read and write data.

`ShuffleManager` is network-addressable, i.e. it is available on a host and port.

There can be many shuffle services running simultaneously and a driver registers with all of them when link:spark-SchedulerBackend.adoc[CoarseGrainedSchedulerBackend] is used.

[[implementations]]
NOTE: <<spark-SortShuffleManager.adoc#, SortShuffleManager>> (short name: `sort` or `tungsten-sort`) is the default implementation of the <<contract, ShuffleManager Contract>> in Apache Spark.

<<spark-configuration-properties.adoc#spark.shuffle.manager, spark.shuffle.manager>> Spark property sets up the default shuffle manager.

=== [[i-want-more]] Further Reading or Watching

1. (slides) http://www.slideshare.net/colorant/spark-shuffle-introduction[Spark shuffle introduction] by http://blog.csdn.net/colorant/[Raymond Liu] (aka _colorant_).
