== Receivers

*Receivers* run on link:spark-workers.adoc[workers] to receive external data. Receivers belong to their link:spark-streaming-receiverinputdstreams.adoc[ReceiverInputDStreams].

NOTE: link:spark-streaming-receivertracker.adoc[ReceiverTracker] launches a receiver on a worker.

It is represented by https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/receiver/Receiver.scala[abstract class Receiver] that is parameterized by link:spark-rdd-caching.adoc#storage-levels[StorageLevel].

The abstract `Receiver` class requires the following methods to be implemented:

* `onStart()` that starts the receiver when the application starts.
* `onStop()` that stops the receiver.

A receiver is identified by the unique identifier `Receiver.streamId` (that corresponds to the unique identifier of the receiver input stream it is associated with).

NOTE: link:spark-rdd-caching.adoc#storage-levels[StorageLevel] of a receiver is used to instantiate link:spark-streaming-receivedblockhandlers.adoc[ReceivedBlockHandler] in link:spark-streaming-receiversupervisors.adoc#ReceiverSupervisorImpl[ReceiverSupervisorImpl].

A receiver uses `store` methods to store received data as data blocks into Spark's memory.

NOTE: Receivers must have link:spark-streaming-receiversupervisors.adoc[ReceiverSupervisors] attached before they can be started since `store` and management methods simply pass calls on to the respective methods in the ReceiverSupervisor.

A receiver can be in one of the three states: `Initialized`, `Started`, and `Stopped`.
