== [[MapOutputTrackerMasterEndpoint]] MapOutputTrackerMasterEndpoint

`MapOutputTrackerMasterEndpoint` is a link:spark-rpc.adoc#RpcEndpoint[RpcEndpoint] for link:spark-service-MapOutputTrackerMaster.adoc[MapOutputTrackerMaster].

`MapOutputTrackerMasterEndpoint` handles the following messages:

* <<GetMapOutputStatuses, GetMapOutputStatuses>>
* <<StopMapOutputTracker, StopMapOutputTracker>>

[TIP]
====
Enable `INFO` or `DEBUG` logging levels for `org.apache.spark.MapOutputTrackerMasterEndpoint` logger to see what happens in `MapOutputTrackerMasterEndpoint`.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.MapOutputTrackerMasterEndpoint=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[GetMapOutputStatuses]] `GetMapOutputStatuses` Message

CAUTION: FIXME

=== [[StopMapOutputTracker]] `StopMapOutputTracker` Message

CAUTION: FIXME

=== [[creating-instance]] Creating MapOutputTrackerMasterEndpoint Instance

`MapOutputTrackerMasterEndpoint` takes the following when created:

1. `rpcEnv` -- link:spark-rpc.adoc[RpcEnv]
2. `tracker` -- link:spark-service-MapOutputTrackerMaster.adoc[MapOutputTrackerMaster]
3. `conf` -- link:spark-configuration.adoc[SparkConf]

When created, you should see the following DEBUG message in the logs:

```
DEBUG init
```

NOTE: `MapOutputTrackerMasterEndpoint` is created when link:spark-sparkenv.adoc#MapOutputTrackerMasterEndpoint[`SparkEnv` is created] for the driver and executors.
