== ExternalClusterManager

`ExternalClusterManager` is a <<contract, contract for pluggable cluster managers>>.

NOTE: `ExternalClusterManager` is a `private[spark]` trait in `org.apache.spark.scheduler` package.

NOTE: The only known implementation of the <<contract, ExternalClusterManager contract>> in Spark is `YarnClusterManager`.

NOTE: SparkContext finds a `ExternalClusterManager` for a master URL using an internal link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[getClusterManager].

=== [[contract]] ExternalClusterManager Contract

==== [[initialize]] initialize

[source, scala]
----
initialize(scheduler: TaskScheduler, backend: SchedulerBackend): Unit
----

==== [[canCreate]] canCreate

[source, scala]
----
canCreate(masterURL: String): Boolean
----

NOTE: It is used when link:spark-sparkcontext-creating-instance-internals.adoc#getClusterManager[finding the external cluster manager for a master URL (in `SparkContext`)].

==== [[createTaskScheduler]] createTaskScheduler

[source, scala]
----
createTaskScheduler(sc: SparkContext, masterURL: String): TaskScheduler
----

==== [[createSchedulerBackend]] createSchedulerBackend

[source, scala]
----
createSchedulerBackend(sc: SparkContext,
  masterURL: String,
  scheduler: TaskScheduler): SchedulerBackend
----
