== [[SharedState]] SharedState -- Shared State Across SparkSessions

`SharedState` is an internal class that holds the <<attributes, shared state>> across active link:spark-sql-SparkSession.adoc[SparkSessions].

[[attributes]]
.SessionState's Attributes (Shared State)
[cols="1,1,2",options="header",width="100%"]
|===
| Name
| Type
| Description

| [[cacheManager]] `cacheManager`
| link:spark-sql-CacheManager.adoc[CacheManager]
|

| [[externalCatalog]] `externalCatalog`
| link:spark-sql-ExternalCatalog.adoc[ExternalCatalog]
|

| [[globalTempViewManager]] `globalTempViewManager`
| `GlobalTempViewManager`
|

| [[jarClassLoader]] `jarClassLoader`
| `NonClosableMutableURLClassLoader`
|

| [[listener]] `listener`
| link:spark-webui-SQLListener.adoc[SQLListener]
|

| [[sparkContext]] `sparkContext`
| link:spark-SparkContext.adoc[SparkContext]
|

| [[warehousePath]] `warehousePath`
|
|
|===

`SharedState` takes a link:spark-SparkContext.adoc[SparkContext] when created. It also adds `hive-site.xml` to link:spark-SparkContext.adoc#hadoopConfiguration[Hadoop's `Configuration` in the current SparkContext] if found on CLASSPATH.

NOTE: `hive-site.xml` is an optional Hive configuration file when working with Hive in Spark.

`SharedState` is created lazily, i.e. when first accessed after `SparkSession` <<creating-instance, is created>>. It can happen when a <<newSession, new session is created>> or when the shared services are accessed.

When created, `SharedState` sets `hive.metastore.warehouse.dir` to link:spark-sql-settings.adoc#spark_sql_warehouse_dir[spark.sql.warehouse.dir] if `hive.metastore.warehouse.dir` is not set or `spark.sql.warehouse.dir` is set. Otherwise, when `hive.metastore.warehouse.dir` is set and `spark.sql.warehouse.dir` is not, `spark.sql.warehouse.dir` gets set to `hive.metastore.warehouse.dir`.

You should see the following INFO message in the logs:

```
INFO spark.sql.warehouse.dir is not set, but hive.metastore.warehouse.dir is set. Setting spark.sql.warehouse.dir to the value of hive.metastore.warehouse.dir ('[hiveWarehouseDir]').
```

You should see the following INFO message in the logs:

```
INFO SharedState: Warehouse path is '[warehousePath]'.
```

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.sql.internal.SharedState` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.sql.internal.SharedState=INFO
```

Refer to link:spark-logging.adoc[Logging].
====
