== Physical Plan Preparations Rules

[NOTE]
====
For the time being, this page *Physical Plan Preparations Rules* serves mainly as a placeholder for the menu layout so the physical plan preparation rules show up nicely in the menu.

The page is _merely_ a compilation of what you may have found on link:spark-sql-QueryExecution.adoc[QueryExecution] page.
====

---

`QueryExecution` has multiple link:spark-sql-QueryExecution.adoc#execution-pipeline[phases of query execution] in a so-called *Structured Query Execution Pipeline*.

Among the phases is the link:spark-sql-QueryExecution.adoc#executedPlan[executedPlan] phase that is one of the last stages which is the result of link:spark-sql-QueryExecution.adoc#prepareForExecution[executing physical preparation rules] to a structured query.

The physical preparation rules are applied sequentially to a physical plan and link:spark-sql-QueryExecution.adoc#preparations[include the following]:

1. `ExtractPythonUDFs`
1. `PlanSubqueries`
1. link:spark-sql-EnsureRequirements.adoc[EnsureRequirements]
1. link:spark-sql-CollapseCodegenStages.adoc[CollapseCodegenStages]
1. `ReuseExchange`
1. `ReuseSubquery`
