== [[SessionCatalog]] SessionCatalog

`SessionCatalog` is a proxy between link:spark-sql-sparksession.adoc[SparkSession] and the underlying metastore, e.g. `HiveSessionCatalog`.

You can access the `SessionCatalog` for a link:spark-sql-sparksession.adoc[SparkSession] through link:spark-sql-sessionstate.adoc[SessionState].

[source, scala]
----
sparkSession.sessionState.catalog
----

=== [[alterTempViewDefinition]] `alterTempViewDefinition` Method

[source, scala]
----
alterTempViewDefinition(name: TableIdentifier, viewDefinition: LogicalPlan): Boolean
----

`alterTempViewDefinition` alters the temporary view by <<createTempView, updating an in-memory temporary table>> (when a database is not specified and the table has already been registered) or a global temporary table (when a database is specified and it is for global temporary tables).

NOTE: "Temporary table" and "temporary view" are synonyms.

`alterTempViewDefinition` returns `true` when an update could be executed and finished successfully.

=== [[createTempView]] `createTempView` Method

CAUTION: FIXME

=== [[createGlobalTempView]] `createGlobalTempView` Method

CAUTION: FIXME

=== [[createTable]] `createTable` Method

CAUTION: FIXME

=== [[alterTable]] `alterTable` Method

CAUTION: FIXME
