== [[LocalSparkCluster]] LocalSparkCluster -- Single-JVM Spark Standalone Cluster

`LocalSparkCluster` is responsible for *local-cluster* master URL.

NOTE: `local-cluster` master URL matches `local-cluster[numWorkers,coresPerWorker,memoryPerWorker]` pattern where <<numWorkers, numWorkers>>, <<coresPerWorker, coresPerWorker>> and <<memoryPerWorker, memoryPerWorker>> are all numbers separated by the comma.

`LocalSparkCluster` can be particularly useful to test distributed operation and fault recovery without spinning up a lot of processes.

`LocalSparkCluster` is <<creating-instance, created>> when `SparkContext` is created for *local-cluster* master URL (and so requested to link:spark-SparkContext.adoc#createTaskScheduler[create the SchedulerBackend and the TaskScheduler]).

[[internal-registries]]
.LocalSparkCluster's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `localHostname`
| [[localHostname]] FIXME

Used when...FIXME

| `masterRpcEnvs`
| [[masterRpcEnvs]] FIXME

Used when...FIXME

| `workerRpcEnvs`
| [[workerRpcEnvs]] FIXME

Used when...FIXME
|===

[[logging]]
[TIP]
====
Enable `INFO` logging level for `org.apache.spark.deploy.LocalSparkCluster` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.deploy.LocalSparkCluster=INFO
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[creating-instance]] Creating LocalSparkCluster Instance

`LocalSparkCluster` takes the following when created:

* [[numWorkers]] Number of workers
* [[coresPerWorker]] CPU cores per worker
* [[memoryPerWorker]] Memory per worker
* [[conf]] link:spark-SparkConf.adoc[SparkConf]

`LocalSparkCluster` initializes the <<internal-registries, internal registries and counters>>.

=== [[start]] `start` Method

[source, scala]
----
start(): Array[String]
----

`start`...FIXME

NOTE: `start` is used when...FIXME

=== [[stop]] `stop` Method

[source, scala]
----
stop(): Unit
----

`stop`...FIXME

NOTE: `stop` is used when...FIXME
