== MemoryStore

`MemoryStore` manages entries in `entries`. It is Java's `LinkedHashMap` with the initial capacity of `32`, the load factor of `0.75` and _access-order_ ordering mode (i.e. iteration is in the order in which its entries were last accessed, from least-recently accessed to most-recently).

TIP: `entries` is Java's https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html[java.util.LinkedHashMap].

`MemoryStore` requires link:spark-configuration.adoc[SparkConf], link:spark-BlockInfoManager.adoc[BlockInfoManager], `SerializerManager`, link:spark-MemoryManager.adoc[MemoryManager] and `BlockEvictionHandler` to be created.

CAUTION: FIXME Where are these dependencies used?

NOTE: `MemoryStore` is a `private[spark]` class.

=== [[evictBlocksToFreeSpace]] Evicting Blocks to Free Space

CAUTION: FIXME

=== [[remove]] Removing Block

CAUTION: FIXME

=== [[settings]] Settings

==== [[spark.storage.unrollMemoryThreshold]] spark.storage.unrollMemoryThreshold

`spark.storage.unrollMemoryThreshold` (default: `1024 * 1024`) controls...
