== ContinuousQuery

A `ContinuousQuery` has a name. It belongs to a single `SQLContext`.

NOTE: `ContinuousQuery` is a Scala trait with the only implementation being <<StreamExecution, StreamExecution>>

It can be in two states: active (started) or inactive (stopped). If inactive, it may have transitioned into the state due to an `ContinuousQueryException` (that is available under `exception`).

It tracks current state of all the sources, i.e. `SourceStatus`, as `sourceStatuses`.

There could only be a single Sink for a `ContinuousQuery` with many `Source`'s.

`ContinuousQuery` can be stopped by `stop` or an exception.

=== [[StreamExecution]] StreamExecution

`StreamExecution` manages execution of a streaming query for a `SQLContext` and a `Sink`. It requires a `LogicalPlan` to know the `Source` objects from which records are periodically pulled down.

It starts an internal thread (`microBatchThread`) to periodically (every 10 milliseconds) poll for new records in the sources and create a batch.

NOTE: The time between batches - 10 milliseconds - is fixed (i.e. not configurable).

`StreamExecution` can be in three states:

* `INITIALIZED` when the instance was created.
* `ACTIVE` when batches are pulled from the sources.
* `TERMINATED` when batches were successfully processed or the query stopped.
