== [[SchedulableBuilder]] Schedulable Builders

`SchedulableBuilder` is a <<contract, contract of schedulable builders>> that operate on a <<rootPool, pool of TaskSetManagers>> (from an owning link:spark-taskschedulerimpl.adoc[TaskSchedulerImpl]).

Schedulable builders can <<buildPools, build pools>> and <<addTaskSetManager, add new Schedulable entities to the pool>>.

A `SchedulableBuilder` is configured when <<initialize, TaskSchedulerImpl is being initialized>>.

NOTE: `SchedulableBuilder` is a `private[spark]` Scala trait. You can find the sources in https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/SchedulableBuilder.scala[org.apache.spark.scheduler.SchedulableBuilder].

Spark comes with two implementations of the <<contract, SchedulableBuilder Contract>>:

* link:spark-taskscheduler-FIFOSchedulableBuilder.adoc[FIFOSchedulableBuilder] - the default `SchedulableBuilder`
* link:spark-taskscheduler-FairSchedulableBuilder.adoc[FairSchedulableBuilder]

=== [[contract]] SchedulableBuilder Contract

Every `SchedulableBuilder` provides the following services:

* It manages a <<rootPool, root pool>>.

* It can <<buildPools, build pools>>.

* It can <<addTaskSetManager, add a Schedulable with properties>>.

=== [[rootPool]] Root Pool (rootPool method)

[source, scala]
----
rootPool: Pool
----

`rootPool` method returns a link:spark-taskscheduler-pool.adoc[Pool] (of link:spark-taskscheduler-schedulable.adoc[Schedulables]).

This is the data structure managed (_aka_ wrapped) by `SchedulableBuilders`.

=== [[buildPools]] Build Pools (buildPools method)

[source, scala]
----
buildPools(): Unit
----

NOTE: It is exclusively called by link:spark-taskschedulerimpl.adoc#initialize[TaskSchedulerImpl.initialize].

=== [[addTaskSetManager]] Add Schedulable (addTaskSetManager method)

[source, scala]
----
addTaskSetManager(manager: Schedulable, properties: Properties): Unit
----

`addTaskSetManager` registers the `manager` link:spark-taskscheduler-schedulable.adoc[Schedulable] (with additional `properties`) to the <<rootPool, rootPool>>.

NOTE: `addTaskSetManager` is currently exclusively used by link:spark-taskschedulerimpl.adoc#submitTasks[TaskSchedulerImpl to submit a task set for a stage for execution].
