== [[CollapseCodegenStages]] CollapseCodegenStages Physical Preparation Rule -- Collapsing Physical Operators with Whole-Stage CodeGen Support

`CollapseCodegenStages` is a link:spark-sql-QueryExecution-SparkPlan-Preparations.adoc[physical preparation rule] that <<apply, collapses physical operators with whole-stage codegen support into a WholeStageCodegenExec physical operator>>.

[NOTE]
====
`CollapseCodegenStages` does nothing (i.e. passes a physical plan through unchanged) when link:spark-sql-SQLConf.adoc#spark.sql.codegen.wholeStage[spark.sql.codegen.wholeStage] internal property is disabled.

`spark.sql.codegen.wholeStage` property is enabled by default.

[source, scala]
----
scala> spark.conf.get("spark.sql.codegen.wholeStage")
res0: String = true
----

Use link:spark-sql-SQLConf.adoc#wholeStageEnabled[SQLConf.wholeStageEnabled] method to access the current value.

[source, scala]
----
scala> spark.sessionState.conf.wholeStageEnabled
res1: Boolean = true
----
====

NOTE: Only link:spark-sql-CodegenSupport.adoc[CodegenSupport] physical plans that have `supportCodegen` enabled support codegen.

NOTE: All link:spark-sql-Expression.adoc[Catalyst expressions] (but link:spark-sql-Expression.adoc#CodegenFallback[CodegenFallback]) support codegen.

`CollapseCodegenStages` is a part of link:spark-sql-QueryExecution.adoc#preparations[preparations] batch of physical plan rules and is executed in link:spark-sql-QueryExecution.adoc#executedPlan[executedPlan] phase of a link:spark-sql-QueryExecution.adoc[query execution].

[[conf]]
`CollapseCodegenStages` takes a link:spark-sql-SQLConf.adoc[SQLConf] when created.

`CollapseCodegenStages` uses the internal setting `spark.sql.codegen.maxFields` (default: `200`) to control the number of fields in input and output schemas before deactivating whole-stage codegen. It counts the fields included in complex types, i.e. link:spark-sql-StructType.adoc[StructType], `MapType`, `ArrayType`, `UserDefinedType`, and their combinations, recursively. See https://issues.apache.org/jira/browse/SPARK-14554[SPARK-14554].

`CollapseCodegenStages` inserts `InputAdapter` leaf nodes in a physical plan recursively that is then used to generate code that consumes an RDD iterator of link:spark-sql-InternalRow.adoc[InternalRow].

[TIP]
====
Import `CollapseCodegenStages` and apply the rule directly to a physical plan to learn how the rule works.

[source, scala]
----
// FIXME
// See spark-sql-Optimizer-ReorderJoin.adoc
----
====

=== [[supportCodegen]] `supportCodegen` Internal Method

CAUTION: FIXME

=== [[apply]] Inserting WholeStageCodegenExec to Physical Plan for Operators that Support CodeGen -- `apply` Method

[source, scala]
----
apply(plan: SparkPlan): SparkPlan
----

`apply` finds link:spark-sql-CodegenSupport.adoc[physical operators with optional Java code generation] that <<supportCodegen, do support codegen>> and inserts a link:spark-sql-SparkPlan-WholeStageCodegenExec.adoc[WholeStageCodegenExec] operator into the link:spark-sql-SparkPlan.adoc[physical plan] (wrapping the operators).

Internally, `apply`...FIXME

`apply` does nothing (i.e. passes a physical plan through unchanged) when link:spark-sql-SQLConf.adoc#spark.sql.codegen.wholeStage[spark.sql.codegen.wholeStage] internal property is disabled.

[NOTE]
====
link:spark-sql-SQLConf.adoc#spark.sql.codegen.wholeStage[spark.sql.codegen.wholeStage] property is enabled by default.

[source, scala]
----
scala> spark.conf.get("spark.sql.codegen.wholeStage")
res0: String = true
----

Use link:spark-sql-SQLConf.adoc#wholeStageEnabled[SQLConf.wholeStageEnabled] method to access the current value.

[source, scala]
----
scala> spark.sessionState.conf.wholeStageEnabled
res1: Boolean = true
----
====
