== BlockManagerMaster - BlockManager for Driver

`BlockManagerMaster` is the link:spark-blockmanager.adoc[BlockManager] that runs on the link:spark-driver.adoc[driver].

It is available as <<BlockManagerMasterEndpoint, BlockManagerMaster RPC endpoint>>.

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.storage.BlockManagerMaster` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.storage.BlockManagerMaster=INFO
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[stop]] Stopping BlockManagerMaster (stop method)

[source, scala]
----
stop(): Unit
----

`stop` sends `StopBlockManagerMaster` to <<BlockManagerMasterEndpoint, BlockManagerMaster RPC endpoint>> and waits for a response.

If all goes fine, you should see the following INFO message in the logs:

```
INFO BlockManagerMaster: BlockManagerMaster stopped
```

Otherwise, a `SparkException` is thrown.

```
BlockManagerMasterEndpoint returned false, expected true.
```

=== [[registerBlockManager]] Registering BlockManager to Driver (registerBlockManager method)

[source, scala]
----
registerBlockManager(
  blockManagerId: BlockManagerId,
  maxMemSize: Long,
  slaveEndpoint: RpcEndpointRef): Unit
----

When `registerBlockManager` runs, you should see the following INFO message in the logs:

```
INFO BlockManagerMaster: Trying to register BlockManager
```

It then sends `RegisterBlockManager` to <<BlockManagerMasterEndpoint, BlockManagerMaster RPC endpoint>> and waits for a response.

If all goes fine, you should see the following INFO message in the logs:

```
INFO BlockManagerMaster: Registered BlockManager
```

Otherwise, a `SparkException` is thrown.

```
BlockManagerMasterEndpoint returned false, expected true.
```

NOTE: `registerBlockManager` is called while link:spark-blockmanager.adoc#initialize[BlockManager is being initialized] and possibly later while link:spark-blockmanager.adoc#reregister[re-registering blocks to the driver].

=== [[BlockManagerMasterEndpoint]] BlockManagerMasterEndpoint - BlockManagerMaster RPC Endpoint

CAUTION: FIXME

*BlockManagerMasterEndpoint* is the RPC endpoint for <<BlockManagerMaster, BlockManagerMaster>> on the master node to track statuses of all slaves' block managers.

The following two-way events are handled:

* RegisterBlockManager
* UpdateBlockInfo
* GetLocations
* GetLocationsMultipleBlockIds
* GetPeers
* GetRpcHostPortForExecutor
* GetMemoryStatus
* GetStorageStatus
* GetBlockStatus
* GetMatchingBlockIds
* RemoveRdd
* RemoveShuffle
* RemoveBroadcast
* RemoveBlock
* RemoveExecutor
* StopBlockManagerMaster
* BlockManagerHeartbeat
* HasCachedBlocks
