== [[AppStatusStore]] AppStatusStore

`AppStatusStore` is...FIXME

`AppStatusStore` is <<creating-instance, created>> when:

1. `SparkContext` is link:spark-sparkcontext-creating-instance-internals.adoc#_statusStore[created] (that triggers <<createLiveStore, createLiveStore>>)

1. `FsHistoryProvider` is requested to link:spark-history-server-FsHistoryProvider.adoc#getAppUI[create a LoadedAppUI]

=== [[rddList]] `rddList` Method

[source, scala]
----
rddList(cachedOnly: Boolean = true): Seq[v1.RDDStorageInfo]
----

`rddList`...FIXME

NOTE: `rddList` is used when...FIXME

=== [[creating-instance]] Creating AppStatusStore Instance

`AppStatusStore` takes the following when created:

* [[store]] link:spark-core-KVStore.adoc[KVStore]
* [[listener]] Optional link:spark-core-AppStatusListener.adoc[AppStatusListener] (default: `None`)

=== [[createLiveStore]] `createLiveStore` Method

[source, scala]
----
createLiveStore(conf: SparkConf): AppStatusStore
----

`createLiveStore`...FIXME

NOTE: `createLiveStore` is used exclusively when `SparkContext` is link:spark-sparkcontext-creating-instance-internals.adoc#_statusStore[created].
