== HistoryServer

`HistoryServer` is a web interface for completed and running (aka _incomplete_) Spark applications.

You can start a `HistoryServer` instance by executing `$SPARK_HOME/sbin/start-history-server.sh` script. See <<starting, Starting HistoryServer>>.

TIP: Use link:spark-scheduler-listeners-eventlogginglistener.adoc[EventLoggingListener] to collect events.

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.deploy.history.HistoryServer` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.deploy.history.HistoryServer=INFO
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[starting]][[main]] Starting HistoryServer

You can start a `HistoryServer` instance by executing `$SPARK_HOME/sbin/start-history-server.sh` script.

```
$ ./sbin/start-history-server.sh
starting org.apache.spark.deploy.history.HistoryServer, logging to .../spark/logs/spark-jacek-org.apache.spark.deploy.history.HistoryServer-1-japila.out
```

NOTE: To stop the server execute `stop-history-server.sh` or `kill` it.

When started, it prints out the following INFO message to the logs:

```
INFO HistoryServer: Started daemon with process name: [processName]
```

It registers signal handlers (using `SignalUtils`) for `TERM`, `HUP`, `INT` to log their execution:

```
ERROR HistoryServer: RECEIVED SIGNAL [signal]
```

It inits security if enabled (using `spark.history.kerberos.enabled` setting).

CAUTION: FIXME Describe `initSecurity`

It creates a `SecurityManager`.

It creates a link:spark-FsHistoryProvider.adoc#ApplicationHistoryProvider[ApplicationHistoryProvider] (by reading <<spark.history.provider, spark.history.provider>>).

It reads <<spark.history.ui.port, spark.history.ui.port>>.

It <<creating-instance, creates a HistoryServer>> and requests to bind.

It registers a shutdown hook to call `stop` on the `HistoryServer` instance.

=== [[creating-instance]] Creating HistoryServer Instance

CAUTION: FIXME

=== [[settings]] Settings

[[spark.history.provider]]
* `spark.history.provider` (default: link:spark-FsHistoryProvider.adoc[FsHistoryProvider]) is a fully-qualified class name for a link:spark-FsHistoryProvider.adoc#ApplicationHistoryProvider[ApplicationHistoryProvider] that comes with a single-arg constructor accepting `SparkConf`.

[[spark.history.ui.port]]
* `spark.history.ui.port` (default: `18080`) -- the port of the History Server's UI.
