== [[PrunedFilteredScan]] PrunedFilteredScan -- Contract for Relations to Prune Columns for Scans

`PrunedFilteredScan` is the <<contract, contract>> in Spark SQL for link:spark-sql-BaseRelation.adoc[relations] that can eliminate (aka _prune_) unneeded columns and filter using selected predicates (before producing an RDD containing all matching tuples as `Row` objects).

[[contract]]
[[buildScan]]
[source, scala]
----
package org.apache.spark.sql.sources

trait PrunedFilteredScan {
  def buildScan(requiredColumns: Array[String], filters: Array[Filter]): RDD[Row]
}
----

`PrunedFilteredScan` is used exclusively when `DataSourceStrategy` execution planning strategy link:spark-sql-SparkStrategy-DataSourceStrategy.adoc#PrunedFilteredScan[plans scans] over `LogicalRelations` with support for `PrunedFilteredScans`.

NOTE: The only known implementation of `PrunedFilteredScan` contract in Spark SQL is link:spark-sql-BaseRelation-JDBCRelation.adoc[JDBCRelation].

NOTE: `PrunedFilteredScan` is a "lighter" and stable version of `CatalystScan` contract.
