== UnifiedMemoryManager

CAUTION: FIXME

`UnifiedMemoryManager` is the default link:spark-MemoryManager.adoc[MemoryManager] since Spark 1.6 with `onHeapStorageMemory` being ??? and `onHeapExecutionMemory` being ???

NOTE: The other now legacy (before Spark 1.6) `MemoryManager` is `StaticMemoryManager`.

=== [[acquireStorageMemory]] acquireStorageMemory method

NOTE: `acquireStorageMemory` is a part of the link:spark-MemoryManager.adoc#acquireStorageMemory[MemoryManager Contract].

CAUTION: FIXME

=== [[acquireUnrollMemory]] acquireUnrollMemory method

NOTE: `acquireUnrollMemory` is a part of the link:spark-MemoryManager.adoc#contract[MemoryManager Contract].

`acquireUnrollMemory` simply passes calls to <<acquireStorageMemory, acquireStorageMemory>>.

=== [[maxOnHeapStorageMemory]] maxOnHeapStorageMemory method

NOTE: `maxOnHeapStorageMemory` is a part of the link:spark-MemoryManager.adoc#contract[MemoryManager Contract].

=== [[creating-instance]] Creating UnifiedMemoryManager Instance

[source, scala]
----
private[spark] class UnifiedMemoryManager private[memory] (
  conf: SparkConf,
  val maxHeapMemory: Long,
  onHeapStorageRegionSize: Long,
  numCores: Int)
----

When an instance of `UnifiedMemoryManager` is created, it requires a link:spark-configuration.adoc[SparkConf] with the following numbers:

* `maxHeapMemory`
* `onHeapStorageRegionSize`
* `numCores`

It makes sure that the sum of `onHeapExecutionMemoryPool` and `onHeapStorageMemoryPool` pool sizes is exactly the constructor's `maxHeapMemory`.

It also makes sure that the sum of `offHeapExecutionMemoryPool` and `offHeapStorageMemoryPool` pool sizes is exactly `maxOffHeapMemory`.

CAUTION: FIXME Describe the pools
