== [[UDFRegistration]] UDFRegistration

`UDFRegistration` is an interface to the session-scoped <<functionRegistry, FunctionRegistry>> to register user-defined functions.

`UDFRegistration` is available using link:spark-sql-sparksession.adoc#udf[SparkSession].

[source, scala]
----
spark.udf
----

`UDFRegistration` is created exclusively when `SessionState` link:spark-sql-SessionState.adoc#creating-instance[is created].

=== [[creating-instance]] Creating UDFRegistration Instance

`UDFRegistration` takes the following when created:

* [[functionRegistry]] link:spark-sql-FunctionRegistry.adoc[FunctionRegistry]

=== [[register]] Registering UserDefinedAggregateFunction (with FunctionRegistry) -- `register` Method

[source, scala]
----
register(
  name: String,
  udaf: UserDefinedAggregateFunction): UserDefinedAggregateFunction
----

`register` link:spark-sql-FunctionRegistry.adoc#registerFunction[registers a `UserDefinedAggregateFunction`] under `name` (as `ScalaUDAF`) with <<functionRegistry, FunctionRegistry>>.

NOTE: `register` gives `udaf` back after the function is registered with <<functionRegistry, FunctionRegistry>>.
