== [[KeyValueGroupedDataset]] KeyValueGroupedDataset -- Typed Grouping

`KeyValueGroupedDataset` is an experimental interface to <<operators, calculate aggregates over groups of objects>> in a typed link:spark-sql-Dataset.adoc[Dataset].

NOTE: link:spark-sql-RelationalGroupedDataset.adoc[RelationalGroupedDataset] is used for untyped Row-based aggregates.

`KeyValueGroupedDataset` is a result of executing link:spark-sql-basic-aggregation.adoc#groupByKey[groupByKey] strongly-typed grouping operator.

[source, scala]
----
val dataset: Dataset[Token] = ...
scala> val tokensByName = dataset.groupByKey(_.name)
tokensByName: org.apache.spark.sql.KeyValueGroupedDataset[String,Token] = org.apache.spark.sql.KeyValueGroupedDataset@1e3aad46
----

[[operators]]
.KeyValueGroupedDataset's Aggregate Operators (in alphabetical order)
[cols="1,3",options="header",width="100%"]
|===
| Operator
| Description

| `agg`
|

| `cogroup`
|

| `count`
|

| `flatMapGroups`
|

| `flatMapGroupsWithState`
|

| `keys`
|

| `keyAs`
|

| `mapGroups`
|

| `mapGroupsWithState`
|

| `mapValues`
|

| `reduceGroups`
|
|===

`KeyValueGroupedDataset` holds `keys` that were used for the object.

[source, scala]
----
scala> tokensByName.keys.show
+-----+
|value|
+-----+
|  aaa|
|  bbb|
+-----+
----
