== [[QueryPlanner]] QueryPlanner -- Converting Logical Plan to Physical Trees

`QueryPlanner` <<plan, plans a logical plan for execution>>, i.e. converts a link:spark-sql-LogicalPlan.adoc[logical plan] to one or more link:spark-sql-SparkPlan.adoc[physical plans] using <<strategies, strategies>>.

NOTE: `QueryPlanner` <<plan, generates>> at least one physical plan.

``QueryPlanner``'s main method is <<plan, plan>> that defines the extension points, i.e. <<strategies, strategies>>, <<collectPlaceholders, collectPlaceholders>> and <<prunePlans, prunePlans>>.

`QueryPlanner` is a part of link:spark-sql-catalyst.adoc[Catalyst Framework].

=== [[contract]] QueryPlanner Contract

[source, scala]
----
abstract class QueryPlanner[PhysicalPlan <: TreeNode[PhysicalPlan]] {
  def collectPlaceholders(plan: PhysicalPlan): Seq[(PhysicalPlan, LogicalPlan)]
  def prunePlans(plans: Iterator[PhysicalPlan]): Iterator[PhysicalPlan]
  def strategies: Seq[GenericStrategy[PhysicalPlan]]
}
----

.QueryPlanner Contract (in alphabetical order)
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[strategies]] `strategies`
| Collection of link:spark-sql-catalyst-GenericStrategy.adoc[GenericStrategy] planning strategies.

Used exclusively as an extension point in <<plan, plan>>.

| [[collectPlaceholders]] `collectPlaceholders`
| Collection of "placeholder" physical plans and the corresponding link:spark-sql-LogicalPlan.adoc[logical plans].

Used exclusively as an extension point in <<plan, plan>>.

Overriden in link:spark-sql-SparkPlanner.adoc#collectPlaceholders[SparkPlanner]

| [[prunePlans]] `prunePlans`
| Prunes physical plans (e.g. bad or somehow incorrect plans).

Used exclusively as an extension point in <<plan, plan>>.
|===

=== [[plan]] Planning Logical Plan -- `plan` Method

[source, scala]
----
plan(plan: LogicalPlan): Iterator[PhysicalPlan]
----

`plan` converts the input `plan` link:spark-sql-LogicalPlan.adoc[logical plan] to zero or more `PhysicalPlan` plans.

Internally, `plan` applies <<strategies, planning strategies>> to the input `plan` (one by one collecting all as the plan candidates).

`plan` then walks over the plan candidates to <<collectPlaceholders, collect placeholders>>.

If a plan does not contain a placeholder, the plan is returned as is. Otherwise, `plan` walks over placeholders (as pairs of `PhysicalPlan` and unplanned link:spark-sql-LogicalPlan.adoc[logical plan]) and (recursively) <<plan, plans>> the child logical plan. `plan` then replaces the placeholders with the planned child logical plan.

In the end, `plan` <<prunePlans, prunes "bad" physical plans>>.

NOTE: `plan` is used exclusively (through the concrete link:spark-sql-SparkPlanner.adoc[SparkPlanner]) when a `QueryExecution` link:spark-sql-QueryExecution.adoc#sparkPlan[is requested for a physical plan].
