== [[InputAdapter]] InputAdapter Unary Physical Operator

`InputAdapter` is a link:spark-sql-SparkPlan.adoc#UnaryExecNode[unary physical operator] (with link:spark-sql-CodegenSupport.adoc[CodegenSupport]) that is an adapter to generate code for the single child operator that does not support link:spark-sql-whole-stage-codegen.adoc[whole-stage code generation] but participates in such code generation for a structured query.

`InputAdapter` is created exclusively when `CollapseCodegenStages` link:spark-sql-CollapseCodegenStages.adoc#insertInputAdapter[inserts a WholeStageCodegenExec operator] into a physical plan.

[[generateTreeString]]
`InputAdapter` removes the star from a stringified tree representation of a physical plan (that link:spark-sql-SparkPlan-WholeStageCodegenExec.adoc[WholeStageCodegenExec] adds), e.g. for link:spark-sql-dataset-operators.adoc#explain[explain] operator.

[source, scala]
----
// explode (that uses Generate operator) does not support codegen
val ids = Seq(Seq(0,1,2,3)).toDF("ids").select(explode($"ids") as "id")
val query = spark.range(1).join(ids, "id")
scala> query.explain
== Physical Plan ==
*Project [id#150L]
+- *BroadcastHashJoin [id#150L], [cast(id#147 as bigint)], Inner, BuildRight
   :- *Range (0, 1, step=1, splits=8)
   +- BroadcastExchange HashedRelationBroadcastMode(List(cast(input[0, int, false] as bigint)))
      +- Generate explode(ids#143), false, false, [id#147]
         +- LocalTableScan [ids#143]
----

=== [[doProduce]] `doProduce` Method

[source, scala]
----
doProduce(ctx: CodegenContext): String
----

`doProduce` generates a Java source code that consumes link:spark-sql-InternalRow.adoc[internal row] of a single input `RDD` one at a time (in a `while` loop).

NOTE: `doProduce` supports one input RDD only (that the single child generates when link:spark-sql-SparkPlan.adoc#execute[executed]).

Internally, `doProduce` generates two terms `input` and `row` and uses the code from link:spark-sql-CodegenSupport.adoc#consume[consume] code generator.

NOTE: `doProduce` is a part of link:spark-sql-CodegenSupport.adoc#doProduce[CodegenSupport Contract] to generate a Java source code.
