== [[MapOutputTrackerWorker]] MapOutputTrackerWorker -- MapOutputTracker for Executors

A *MapOutputTrackerWorker* is the `MapOutputTracker` for executors.

`MapOutputTrackerWorker` uses Java's thread-safe https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html[java.util.concurrent.ConcurrentHashMap] for link:spark-service-mapoutputtracker.adoc#mapStatuses[`mapStatuses` internal cache] and any lookup cache miss triggers a fetch from the driver's link:spark-service-MapOutputTrackerMaster.adoc[MapOutputTrackerMaster].

NOTE: The only difference between `MapOutputTrackerWorker` and the base abstract class `MapOutputTracker` is that the link:spark-service-mapoutputtracker.adoc#mapStatuses[`mapStatuses` internal registry] is an instance of the thread-safe https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html[java.util.concurrent.ConcurrentHashMap].

[TIP]
====
Enable `INFO` or `DEBUG` logging level for `org.apache.spark.MapOutputTrackerWorker` logger to see what happens in `MapOutputTrackerWorker`.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.MapOutputTrackerWorker=DEBUG
```

Refer to link:spark-logging.adoc[Logging].
====
