== [[SpillListener]] SpillListener -- Detecting Spills in Jobs (for Testing)

`SpillListener` is a <<spark-SparkListener.adoc#, SparkListener>> that intercepts (_listens to_) the following events:

* <<onTaskEnd, onTaskEnd>>

* <<onStageCompleted, onStageCompleted>>

`SpillListener` is <<creating-instance, created>> exclusively for `TestUtils` when requested for `assertSpilled` and `assertNotSpilled`.

[[creating-instance]]
`SpillListener` takes no input arguments to be created.

NOTE: `SpillListener` is a Scala `private class`.

[[internal-registries]]
.SpillListener's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1m,3",options="header",width="100%"]
|===
| Name
| Description

| spilledStageIds
a| [[spilledStageIds]] (`mutable.HashMap[Int, ArrayBuffer[TaskMetrics]]`)

Used when...FIXME

| stageIdToTaskMetrics
a| [[stageIdToTaskMetrics]] (`mutable.HashSet[Int]`)

Used when...FIXME

|===

=== [[onTaskEnd]] `onTaskEnd` Callback

[source, scala]
----
onTaskEnd(taskEnd: SparkListenerTaskEnd): Unit
----

NOTE: `onTaskEnd` is part of the <<spark-SparkListener.adoc#onTaskEnd, SparkListener Contract>> to...FIXME.

`onTaskEnd`...FIXME

=== [[onStageCompleted]] `onStageCompleted` Callback

[source, scala]
----
onStageCompleted(stageComplete: SparkListenerStageCompleted): Unit
----

NOTE: `onStageCompleted` is part of the <<spark-SparkListener.adoc#onStageCompleted, SparkListener Contract>> to...FIXME.

`onStageCompleted`...FIXME
