== YarnRMClient

`YarnRMClient` is responsible for registering and unregistering a Spark application with the *YARN ResourceManager* (aka _RM_).

NOTE: YARN ResourceManager http://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/index.html[manages the global assignment of compute resources to applications], e.g. memory, cpu, disk, network, etc.

=== [[allocateResources]] allocateResources

CAUTION: FIXME

=== [[registering-applicationmaster]] Registering ApplicationMaster

`spark.yarn.maxAppAttempts` is the maximum number of attempts to register *ApplicationMaster* (aka _AM_).

It is used unless `yarn.resourcemanager.am.max-attempts` is set and smaller than `spark.yarn.maxAppAttempts`. When no setting is available it is assumed `YarnConfiguration.DEFAULT_RM_AM_MAX_ATTEMPTS` which is `2`.

NOTE: It is used by Spark's own link:spark-yarn-applicationmaster.adoc[ApplicationMaster].

=== [[register]] register method

[source, scala]
----
register(
  driverUrl: String,
  driverRef: RpcEndpointRef,
  conf: YarnConfiguration,
  sparkConf: SparkConf,
  uiAddress: String,
  uiHistoryAddress: String,
  securityMgr: SecurityManager,
  localResources: Map[String, LocalResource]): YarnAllocator
----

`register` registers the application master with the YARN ResourceManager. It creates a link:spark-yarn-YarnAllocator.adoc[YarnAllocator] that...FIXME

=== [[unregister]] unregister method

=== [[getAttemptId]] getAttemptId method
