== [[LocalEndpoint]] LocalEndpoint

`LocalEndpoint` is the communication channel between link:spark-TaskScheduler.adoc[Task Scheduler] and link:spark-LocalSchedulerBackend.adoc[LocalSchedulerBackend]. It is a (thread-safe) link:spark-rpc-RpcEndpoint.adoc[RpcEndpoint] that hosts an link:spark-Executor.adoc[executor] (with id `driver` and hostname `localhost`) for Spark local mode.

When a `LocalEndpoint` starts up (as part of Spark local's initialization) it prints out the following INFO messages to the logs:

```
INFO Executor: Starting executor ID driver on host localhost
INFO Executor: Using REPL class URI: http://192.168.1.4:56131
```

=== [[reviveOffers]] `reviveOffers` Method

CAUTION: FIXME

=== [[creating-instance]] Creating LocalEndpoint Instance

CAUTION: FIXME

=== [[messages]] RPC Messages

LocalEndpoint accepts the following RPC message types:

* `ReviveOffers` (receive-only, non-blocking) - read <<task-submission, Task Submission a.k.a. reviveOffers>>.

* [[StatusUpdate]] `StatusUpdate` (receive-only, non-blocking) that passes the message to TaskScheduler (using `statusUpdate`) and if link:spark-taskscheduler-tasks.adoc[the task's status is finished], it revives offers (see `ReviveOffers`).

* `KillTask` (receive-only, non-blocking) that kills the task that is currently running on the executor.

* [[StopExecutor]] `StopExecutor` (receive-reply, blocking) that stops the executor.
