== CatalystSerde

`CatalystSerde` object consists of three methods:

1. <<deserialize, deserialize>> to create a link:spark-sql-logical-plan-DeserializeToObject.adoc[`DeserializeToObject` logical operator] for a logical plan.
2. <<serialize, serialize>>
3. <<generateObjAttr, generateObjAttr>>

`CatalystSerde` is a Scala object and belongs to `org.apache.spark.sql.catalyst.plans.logical` package.

=== [[deserialize]] Creating `DeserializeToObject` Logical Operator for Child Logical Plan -- `deserialize` Method

[source, scala]
----
deserialize[T : Encoder](child: LogicalPlan): DeserializeToObject
----

`deserialize` creates a link:spark-sql-logical-plan-DeserializeToObject.adoc[`DeserializeToObject` logical operator] for the input `child` link:spark-sql-LogicalPlan.adoc[logical plan].

Internally, `deserialize` creates a `UnresolvedDeserializer` for the deserializer for the type `T` first and passes it on to a `DeserializeToObject` with a `AttributeReference` (being the result of <<generateObjAttr, generateObjAttr>>).

=== [[serialize]] `serialize` Method

[source, scala]
----
serialize[T : Encoder](child: LogicalPlan): SerializeFromObject
----

=== [[generateObjAttr]] `generateObjAttr` Method

[source, scala]
----
generateObjAttr[T : Encoder]: Attribute
----
