== Structured Streaming (aka Streaming DataFrames)

*Streaming DataFrames* are _infinite dataframes_ and the foundation of *Structured Streaming* for a high-level streaming API over Spark SQL engine. It offers primitives like *event time*, *windowing*, *sessions*, *sources* and *sinks*.

NOTE: It is slated for Spark 2.0 at the end of April or beginning of May, 2016.

Structured Streaming is to unify streaming, interactive, and batch queries.

Every *trigger* (time) a computation on DataFrames should be performed.

NOTE: The feature has also been called *Streaming Spark SQL Query* or *Streaming DataFrames* or *Continuous DataFrames* or *Continuous Queries*.

TIP: Watch https://issues.apache.org/jira/browse/SPARK-8360[SPARK-8360 Streaming DataFrames] to track progress of the feature.

=== [[i-want-more]] Further reading or watching

* (video) https://youtu.be/oXkxXDG0gNk[The Future of Real Time in Spark] from Spark Summit East 2016 in which Reynold Xin presents the concept of *Streaming DataFrames* to the public.
* (video) https://youtu.be/i7l3JQRx7Qw?t=19m15s[Structuring Spark: DataFrames, Datasets, and Streaming]
