== [[CreateViewCommand]] CreateViewCommand Logical Command

`CreateViewCommand` is a link:spark-sql-LogicalPlan-RunnableCommand.adoc[logical command] for creating a view or a table.

`CreateViewCommand` is a result of parsing `CREATE VIEW` (and variants) in SQL and executing `Dataset` operators: link:spark-sql-dataset-operators.adoc#createTempView[createTempView], link:spark-sql-dataset-operators.adoc#createOrReplaceTempView[createOrReplaceTempView], and link:spark-sql-dataset-operators.adoc#createGlobalTempView[createGlobalTempView].

TIP: `CreateViewCommand` is described by `createView` labeled alternative in `statement` expression in `SqlBase.g4` and parsed using link:spark-sql-SparkSqlParser.adoc[SparkSqlParser].

CAUTION: FIXME What's the difference between `CreateTempViewUsing`?

`CreateViewCommand` works with different view types (aka `ViewType`).

.CreateViewCommand's View Types
[options="header",cols="1,2",width="100%"]
|===
| View Type
| Description / Side Effect

| `LocalTempView`
| A session-scoped local temporary view. Available until the session that has created it stops.

When executed, `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#createTempView[current `SessionCatalog` to create a temporary view].

| `GlobalTempView`
| A cross-session global temporary view. Available until a Spark application stops.

When executed, `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#createGlobalTempView[current `SessionCatalog` to create a global view].

| `PersistedView`
| A cross-session persisted view. Available until you it is dropped.

When executed, `CreateViewCommand` checks if the table exists. If it does and replace is enabled `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#alterTable[current `SessionCatalog` to alter a table]. Otherwise, when the table does not exist, `CreateViewCommand` requests the link:spark-sql-SessionCatalog.adoc#createTable[current `SessionCatalog` to create it].
|===

=== [[run]] `run` Method

CAUTION: FIXME
