= BroadcastFactory

`BroadcastFactory` is the <<contract, contract>> for <<implementations, factories>> of link:spark-broadcast.adoc[broadcast variables] in Apache Spark.

NOTE: https://issues.apache.org/jira/browse/SPARK-12588[As of Spark 2.0], it is no longer possible to plug a custom `BroadcastFactory` in, and xref:core:TorrentBroadcastFactory.adoc[TorrentBroadcastFactory] is the one and only known implementation.

`BroadcastFactory` is exclusively used and instantiated inside of xref:core:BroadcastManager.adoc[BroadcastManager].

[[contract]]
[source, scala]
----
package org.apache.spark.broadcast

trait BroadcastFactory {
  def initialize(isDriver: Boolean, conf: SparkConf, securityMgr: SecurityManager): Unit
  def newBroadcast[T: ClassTag](value: T, isLocal: Boolean, id: Long): Broadcast[T]
  def unbroadcast(id: Long, removeFromDriver: Boolean, blocking: Boolean): Unit
  def stop(): Unit
}
----

NOTE: `BroadcastFactory` is a `private[spark]` contract.

.BroadcastFactory Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| `initialize`
| [[initialize]] Used when...FIXME

| `newBroadcast`
| [[newBroadcast]] Used when...FIXME

| `unbroadcast`
| [[unbroadcast]] Used when...FIXME

| `stop`
| [[stop]] Used when...FIXME
|===

[[implementations]]
NOTE: xref:core:TorrentBroadcastFactory.adoc[TorrentBroadcastFactory] is the one and only known implementation of <<contract, BroadcastFactory contract>> in Apache Spark.
