= TorrentBroadcastFactory

`TorrentBroadcastFactory` is a xref:core:BroadcastFactory.adoc[BroadcastFactory] of xref:core:TorrentBroadcast.adoc[TorrentBroadcast]s, i.e. BitTorrent-like link:spark-broadcast.adoc[broadcast variables].

NOTE: https://issues.apache.org/jira/browse/SPARK-12588[As of Spark 2.0] `TorrentBroadcastFactory` is the only implementation of xref:core:BroadcastFactory.adoc[BroadcastFactory].

[[initialize]][[stop]]
`initialize` and `stop` do nothing.

`unbroadcast` xref:core:TorrentBroadcast.adoc#unpersist[removes all the persisted state associated with a `TorrentBroadcast` of a given ID].

== [[newBroadcast]] Creating TorrentBroadcast -- `newBroadcast` Method

[source, scala]
----
newBroadcast[T: ClassTag](value_ : T, isLocal: Boolean, id: Long): Broadcast[T]
----

NOTE: `newBroadcast` is part of xref:core:BroadcastFactory.adoc#newBroadcast[BroadcastFactory Contract] to...FIXME.

`newBroadcast` creates a xref:core:TorrentBroadcast.adoc#creating-instance[TorrentBroadcast] (for the input `value_` and `id` and ignoring the `isLocal` parameter).
