== [[HistoryServer]] HistoryServer -- WebUI For Active And Completed Spark Applications

`HistoryServer` is the link:spark-webui-WebUI.adoc[web UI] for running (active) and completed Spark applications.

`HistoryServer` is <<creating-instance, created>> when...FIXME

`HistoryServer` uses the <<loaderServlet, HttpServlet>> to handle requests to `/*` URI that <<doGet, FIXME>>.

[[internal-registries]]
.HistoryServer's Internal Properties (e.g. Registries, Counters and Flags)
[cols="1,2",options="header",width="100%"]
|===
| Name
| Description

| `appCache`
| [[appCache]] xref:ApplicationCache.adoc[ApplicationCache]

Used when...FIXME

| `loaderServlet`
| [[loaderServlet]] Java Servlets' https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServlet.html[HttpServlet]

Used exclusively when `HistoryServer` is requested to <<initialize, initialize>> (and link:spark-webui-WebUI.adoc#attachHandler[attaches the servlet to the web UI] to handle `/*` URI)
|===

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.deploy.history.HistoryServer` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.deploy.history.HistoryServer=INFO
```

Refer to link:spark-logging.adoc[Logging].
====

=== [[attachSparkUI]] `attachSparkUI` Method

[source, scala]
----
attachSparkUI(
  appId: String,
  attemptId: Option[String],
  ui: SparkUI,
  completed: Boolean): Unit
----

NOTE: `attachSparkUI` is part of xref:ApplicationCacheOperations.adoc#attachSparkUI[ApplicationCacheOperations Contract] to...FIXME.

`attachSparkUI`...FIXME

=== [[initialize]] Initializing HistoryServer -- `initialize` Method

[source, scala]
----
initialize(): Unit
----

NOTE: `initialize` is part of link:spark-webui-WebUI.adoc#initialize[WebUI Contract] to initialize web components.

`initialize`...FIXME

=== [[main]] Launching HistoryServer Standalone Application -- `main` Method

[source, scala]
----
main(argStrings: Array[String]): Unit
----

`main`...FIXME

=== [[creating-instance]] Creating HistoryServer Instance

`HistoryServer` takes the following when created:

* [[conf]] link:spark-SparkConf.adoc[SparkConf]
* [[provider]] xref:ApplicationHistoryProvider.adoc[ApplicationHistoryProvider]
* [[securityManager]] `SecurityManager`
* [[port]] Port number

`HistoryServer` initializes the <<internal-registries, internal registries and counters>>.

=== [[getAppUI]] Requesting Spark Application UI -- `getAppUI` Method

[source, scala]
----
getAppUI(appId: String, attemptId: Option[String]): Option[LoadedAppUI]
----

NOTE: `getAppUI` is part of xref:ApplicationCacheOperations.adoc#getAppUI[ApplicationCacheOperations Contract] to...FIXME.

`getAppUI`...FIXME

=== [[withSparkUI]] `withSparkUI` Method

[source, scala]
----
withSparkUI[T](appId: String, attemptId: Option[String])(fn: SparkUI => T): T
----

NOTE: `withSparkUI` is part of link:spark-api-UIRoot.adoc#withSparkUI[UIRoot Contract] to...FIXME.

`withSparkUI`...FIXME

=== [[loadAppUi]] `loadAppUi` Internal Method

[source, scala]
----
loadAppUi(appId: String, attemptId: Option[String]): Boolean
----

`loadAppUi`...FIXME

NOTE: `loadAppUi` is used exclusively when `HistoryServer` is <<loaderServlet, created>>.

=== [[doGet]] `doGet` Method

[source, scala]
----
doGet(req: HttpServletRequest, res: HttpServletResponse): Unit
----

NOTE: `doGet` is part of Java Servlet's link:https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServlet.html[HttpServlet] to handle HTTP GET requests.

`doGet`...FIXME

NOTE: `doGet` is used when...FIXME
