= [[SortShuffleWriter]] SortShuffleWriter

*SortShuffleWriter* is a concrete xref:shuffle:ShuffleWriter.adoc[ShuffleWriter] that is used when xref:shuffle:SortShuffleManager.adoc#getWriter[`SortShuffleManager` returns a `ShuffleWriter` for `ShuffleHandle`] (and the more specialized xref:shuffle:BypassMergeSortShuffleWriter.adoc[BypassMergeSortShuffleWriter] and xref:shuffle:spark-shuffle-UnsafeShuffleWriter.adoc[UnsafeShuffleWriter] could not be used).

SortShuffleWriter is created when xref:SortShuffleManager.adoc#getWriter[`SortShuffleManager` returns a `ShuffleWriter` for the fallback `BaseShuffleHandle`].

`SortShuffleWriter[K, V, C]` is a parameterized type with `K` keys, `V` values, and `C` combiner values.

== [[creating-instance]] Creating Instance

SortShuffleWriter takes the following to be created:

* [[shuffleBlockResolver]] xref:shuffle:IndexShuffleBlockResolver.adoc[IndexShuffleBlockResolver]
* [[handle]] xref:shuffle:spark-shuffle-BaseShuffleHandle.adoc[BaseShuffleHandle]
* [[mapId]] Map ID
* [[context]] xref:scheduler:spark-TaskContext.adoc[TaskContext]

== [[mapStatus]] MapStatus

SortShuffleWriter uses an internal variable for a xref:scheduler:MapStatus.adoc[MapStatus] after <<write, writing records>>.

<<write, Writing records>> itself does not return a value, SortShuffleWriter uses the variable when requested to <<stop, stop>> (which allows returning a MapStatus).

== [[write]] Writing Records (Into Shuffle Partitioned File In Disk Store)

[source, scala]
----
write(
  records: Iterator[Product2[K, V]]): Unit
----

write creates an xref:shuffle:ExternalSorter.adoc[ExternalSorter] based on the xref:shuffle:spark-shuffle-BaseShuffleHandle.adoc#dependency[ShuffleDependency] (of the <<handle, BaseShuffleHandle>>), namely the xref:rdd:ShuffleDependency.adoc#mapSideCombine[Map-Size Partial Aggregation] flag. The ExternalSorter uses the aggregator and keyOrdering when the flag is enabled.

write requests the ExternalSorter to xref:shuffle:ExternalSorter.adoc#insertAll[inserts all the records].

write requests the <<shuffleBlockResolver, IndexShuffleBlockResolver>> for a xref:shuffle:IndexShuffleBlockResolver.adoc#getDataFile[shuffle output file] (for the shuffle and the <<mapId, map>> IDs) and creates a temporary file alongside the shuffle output file (in the same directory).

write creates a xref:storage:spark-BlockDataManager.adoc#ShuffleBlockId[ShuffleBlockId] (for the shuffle and the <<mapId, map>> IDs).

write requests ExternalSorter to xref:shuffle:ExternalSorter.adoc#writePartitionedFile[write all the records (previously inserted in) into the temporary partitioned file in the disk store]. ExternalSorter returns the length of every partition.

write requests <<shuffleBlockResolver, IndexShuffleBlockResolver>> to xref:shuffle:IndexShuffleBlockResolver.adoc#writeIndexFileAndCommit[write an index file and commit] (with the shuffle and the <<mapId, map>> IDs, the temporary shuffle output file).

write creates a xref:scheduler:MapStatus.adoc[MapStatus] (with the xref:storage:BlockManager.adoc#shuffleServerId[location of the shuffle server] that serves the shuffle files and the sizes of the shuffle partitions). The `MapStatus` is later available as the <<mapStatus, mapStatus>> internal attribute.

write does not handle exceptions so when they occur, they will break the processing.

In the end, write deletes the temporary shuffle output file. write prints out the following ERROR message to the logs if the file count not be deleted:

```
Error while deleting temp file [path]
```

write is part of the xref:shuffle:ShuffleWriter.adoc#write[ShuffleWriter] abstraction.

== [[stop]] Closing SortShuffleWriter (and Calculating MapStatus)

[source, scala]
----
stop(
  success: Boolean): Option[MapStatus]
----

stop turns <<stopping, stopping>> flag on and returns the internal <<mapStatus, mapStatus>> if the input `success` is enabled.

Otherwise, when <<stopping, stopping>> flag is already enabled or the input `success` is disabled, stop returns no `MapStatus` (i.e. `None`).

In the end, stop requests the ExternalSorter to xref:shuffle:ExternalSorter.adoc#stop[stop] and increments the shuffle write time task metrics.

stop is part of the xref:shuffle:ShuffleWriter.adoc#contract[ShuffleWriter] abstraction.

== [[logging]] Logging

Enable `ALL` logging level for `org.apache.spark.shuffle.sort.SortShuffleWriter` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

[source]
----
log4j.logger.org.apache.spark.shuffle.sort.SortShuffleWriter=ALL
----

Refer to xref:ROOT:spark-logging.adoc[Logging].

== [[internal-properties]] Internal Properties

[cols="30m,70",options="header",width="100%"]
|===
| Name
| Description

| [[stopping]] `stopping`
| Internal flag to mark that <<stop, SortShuffleWriter is closed>>.

|===
