== [[SerializedShuffleHandle]] SerializedShuffleHandle -- Marker Interface for Serialized Shuffle Handles

*SerializedShuffleHandle* is a link:spark-shuffle-BaseShuffleHandle.adoc[BaseShuffleHandle] to identify the choice of a *serialized shuffle*.

Like xref:spark-shuffle-BaseShuffleHandle.adoc[BaseShuffleHandle], SerializedShuffleHandle takes the following to be created:

* [[shuffleId]] Shuffle ID
* [[numMaps]] Number of mappers
* [[dependency]] xref:rdd:ShuffleDependency.adoc[ShuffleDependency] (`ShuffleDependency[K, V, V]`)

SerializedShuffleHandle is created when SortShuffleManager is requested for a xref:SortShuffleManager.adoc#registerShuffle[ShuffleHandle] (for a `ShuffleDependency`) and the link:SortShuffleManager.adoc#canUseSerializedShuffle[conditions hold] (but for link:SortShuffleManager.adoc#shouldBypassMergeSort[`BypassMergeSortShuffleHandle` do not] which are checked first).

SerializedShuffleHandle is used to create a xref:shuffle:UnsafeShuffleWriter.adoc#handle[UnsafeShuffleWriter].
