== [[MesosCoarseGrainedSchedulerBackend]] MesosCoarseGrainedSchedulerBackend -- Coarse-Grained Scheduler Backend for Mesos

CAUTION: FIXME

=== [[executorLimitOption]] `executorLimitOption` Property

`executorLimitOption` is an internal attribute to...FIXME

=== [[resourceOffers]] `resourceOffers` Method

CAUTION: FIXME

NOTE: `resourceOffers` is part of Mesos' http://mesos.apache.org/api/latest/java/org/apache/mesos/Scheduler.html[Scheduler] callback interface to be implemented by frameworks' schedulers.

=== [[handleMatchedOffers]] `handleMatchedOffers` Internal Method

CAUTION: FIXME

NOTE: `handleMatchedOffers` is used exclusively when `MesosCoarseGrainedSchedulerBackend` <<resourceOffers, resourceOffers>>.

=== [[buildMesosTasks]] `buildMesosTasks` Internal Method

CAUTION: FIXME

NOTE: `buildMesosTasks` is used exclusively when `MesosCoarseGrainedSchedulerBackend` <<handleMatchedOffers, launches Spark executors on accepted offers>>.

=== [[createCommand]] `createCommand` Method

CAUTION: FIXME

NOTE: `createCommand` is used exclusively when `MesosCoarseGrainedSchedulerBackend` <<buildMesosTasks, builds Mesos tasks for given offers>>.
