# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - Shuffle Handles:
    - BaseShuffleHandle.md
    - BypassMergeSortShuffleHandle.md
    - SerializedShuffleHandle.md
    - ShuffleHandle.md
  - Shuffle Readers:
    - BlockStoreShuffleReader.md
    - ShuffleReader.md
  - BypassMergeSortShuffleWriter: BypassMergeSortShuffleWriter.md
  - DownloadFileManager: DownloadFileManager.md
  - FetchFailedException: FetchFailedException.md
  - IndexShuffleBlockResolver: IndexShuffleBlockResolver.md
  - MigratableResolver: MigratableResolver.md
  - ShuffleBlockPusher: ShuffleBlockPusher.md
  - ShuffleBlockResolver: ShuffleBlockResolver.md
  - ShuffleExternalSorter: ShuffleExternalSorter.md
  - ShuffleInMemorySorter: ShuffleInMemorySorter.md
  - ShuffleManager: ShuffleManager.md
  - ShuffleReadMetricsReporter.md
  - ShuffleWriteMetricsReporter: ShuffleWriteMetricsReporter.md
  - ShuffleWriteProcessor: ShuffleWriteProcessor.md
  - ShuffleWriter: ShuffleWriter.md
  - SortShuffleManager: SortShuffleManager.md
  - SortShuffleWriter: SortShuffleWriter.md
  - UnsafeShuffleWriter: UnsafeShuffleWriter.md
  - Spillable Collections:
    - Spillable: Spillable.md
    - ExternalAppendOnlyMap: ExternalAppendOnlyMap.md
    - ExternalSorter: ExternalSorter.md
  - ShuffleDataIOs:
    - ShuffleDataIO: ShuffleDataIO.md
    - LocalDiskShuffleDataIO: LocalDiskShuffleDataIO.md
    - ShuffleDriverComponents: ShuffleDriverComponents.md
    - ShuffleExecutorComponents: ShuffleExecutorComponents.md
    - ShuffleMapOutputWriter: ShuffleMapOutputWriter.md
    - LocalDiskShuffleMapOutputWriter: LocalDiskShuffleMapOutputWriter.md
    - ExecutorDiskUtils: ExecutorDiskUtils.md
    - SingleSpillShuffleMapOutputWriter: SingleSpillShuffleMapOutputWriter.md
    - LocalDiskShuffleExecutorComponents: LocalDiskShuffleExecutorComponents.md
    - LocalDiskSingleSpillMapOutputWriter: LocalDiskSingleSpillMapOutputWriter.md
    - ShuffleDataIOUtils: ShuffleDataIOUtils.md
