# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - Configuration Properties: configuration-properties.md
  - WebUI: WebUI.md
  - WebUIPage: WebUIPage.md
  - WebUITab: WebUITab.md
  - Spark UI:
    - SparkUI: SparkUI.md
    - SparkUITab: SparkUITab.md
    - Environment:
      - EnvironmentTab: EnvironmentTab.md
      - EnvironmentPage: EnvironmentPage.md
    - Executors:
      - ExecutorsTab: ExecutorsTab.md
      - ExecutorsPage: ExecutorsPage.md
      - ExecutorThreadDumpPage: ExecutorThreadDumpPage.md
    - Jobs:
      - JobsTab: JobsTab.md
      - AllJobsPage: AllJobsPage.md
      - JobPage: JobPage.md
    - Stages:
      - StagesTab: StagesTab.md
      - AllStagesPage: AllStagesPage.md
      - StagePage: StagePage.md
      - PoolPage: PoolPage.md
    - Storage:
      - StorageTab: StorageTab.md
      - StoragePage: StoragePage.md
      - RDDPage: RDDPage.md
  - PrometheusResource: PrometheusResource.md
  - UIUtils: UIUtils.md
  - JettyUtils: JettyUtils.md
