# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - CoalescedRDD: CoalescedRDD.md
  - CheckpointRDD: CheckpointRDD.md
  - CoGroupedRDD: CoGroupedRDD.md
  - Dependency: Dependency.md
  - HadoopRDD: HadoopRDD.md
  - LocalCheckpointRDD: LocalCheckpointRDD.md
  - MapPartitionsRDD: MapPartitionsRDD.md
  - NarrowDependency: NarrowDependency.md
  - NewHadoopRDD: NewHadoopRDD.md
  - ParallelCollectionRDD: ParallelCollectionRDD.md
  - RDD: RDD.md
  - RDDOperationScope: RDDOperationScope.md
  - ReliableCheckpointRDD: ReliableCheckpointRDD.md
  - ShuffleDependency: ShuffleDependency.md
  - ShuffledRDD: ShuffledRDD.md
  - Operators:
    - Operators: spark-rdd-operations.md
    - Transformations: spark-rdd-transformations.md
    - OrderedRDDFunctions: OrderedRDDFunctions.md
    - PairRDDFunctions: PairRDDFunctions.md
    - AsyncRDDActions: AsyncRDDActions.md
    - Actions: spark-rdd-actions.md
  - Partitioners:
    - Partitioner: Partitioner.md
    - HashPartitioner: HashPartitioner.md
    - RangePartitioner: RangePartitioner.md
  - RDD Lineage: lineage.md
  - Caching and Persistence: spark-rdd-caching.md
  - Partitions and Partitioning: spark-rdd-partitions.md
  - Partition: Partition.md
  - RDD Checkpointing: checkpointing.md
  - RDDCheckpointData: RDDCheckpointData.md
  - LocalRDDCheckpointData: LocalRDDCheckpointData.md
  - MapPartitionsWithEvaluatorRDD: MapPartitionsWithEvaluatorRDD.md
  - ReliableRDDCheckpointData: ReliableRDDCheckpointData.md
  - ZippedPartitionsWithEvaluatorRDD: ZippedPartitionsWithEvaluatorRDD.md
  - Aggregator: Aggregator.md
