== [[PipelineStage]] PipelineStage -- ML Pipeline Component

The https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.PipelineStage[PipelineStage] abstract class represents a single stage in a link:spark-mllib-Pipeline.md[Pipeline].

`PipelineStage` has the following direct implementations (of which few are abstract classes, too):

* link:spark-mllib-estimators.md[Estimators]
* link:spark-mllib-models.md[Models]
* link:spark-mllib-Pipeline.md[Pipeline]
* link:spark-mllib-estimators.md#Predictor[Predictor]
* link:spark-mllib-transformers.md[Transformer]

[[transformSchema]]
Each `PipelineStage` transforms schema using `transformSchema` family of methods:

```
transformSchema(schema: StructType): StructType
transformSchema(schema: StructType, logging: Boolean): StructType
```

NOTE: link:spark-sql-StructType.md[StructType] describes a schema of a DataFrame.

[TIP]
====
Enable `DEBUG` logging level for the respective `PipelineStage` implementations to see what happens beneath.
====
