== [[Predictor]] Predictor

`Predictor` is an link:spark-mllib-Estimator.md[Estimator] for a link:spark-mllib-models.md#PredictionModel[PredictionModel] with its own abstract `train` method.

[source, scala]
----
train(dataset: DataFrame): M
----

The `train` method is supposed to ease dealing with schema validation and copying parameters to a trained `PredictionModel` model. It also sets the parent of the model to itself.

A `Predictor` is basically a function that maps a `DataFrame` onto a `PredictionModel`.

```
predictor: DataFrame =[train]=> PredictionModel
```

It implements the abstract `fit(dataset: DataFrame)` of the `Estimator` abstract class that validates and transforms the schema of a dataset (using a custom `transformSchema` of link:spark-mllib-PipelineStage.md[PipelineStage]), and then calls the abstract `train` method.

Validation and transformation of a schema (using `transformSchema`) makes sure that:

1. `features` column exists and is of correct type (defaults to link:spark-mllib-vector.md[Vector]).
2. `label` column exists and is of `Double` type.

As the last step, it adds the `prediction` column of `Double` type.
