== [[YarnClusterScheduler]] YarnClusterScheduler -- TaskScheduler for Cluster Deploy Mode

`YarnClusterScheduler` is the link:../spark-TaskScheduler.adoc[TaskScheduler] for link:README.adoc[Spark on YARN] in link:spark-submit.adoc#deploy-mode[cluster deploy mode].

It is a custom link:spark-yarn-yarnscheduler.adoc[YarnScheduler] that makes sure that appropriate initialization of link:spark-yarn-applicationmaster.adoc[ApplicationMaster] is performed, i.e. <<postStartHook, SparkContext is initialized>> and <<stop, stopped>>.

While being created, you should see the following INFO message in the logs:

```
INFO YarnClusterScheduler: Created YarnClusterScheduler
```

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.scheduler.cluster.YarnClusterScheduler` to see what happens inside `YarnClusterScheduler`.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.scheduler.cluster.YarnClusterScheduler=INFO
```

Refer to link:../spark-logging.adoc[Logging].
====

=== [[postStartHook]] `postStartHook` Callback

`postStartHook` calls link:spark-yarn-applicationmaster.adoc#sparkContextInitialized[ApplicationMaster.sparkContextInitialized] before the link:spark-TaskSchedulerImpl.adoc#postStartHook[parent's `postStartHook`].

You should see the following INFO message in the logs:

```
INFO YarnClusterScheduler: YarnClusterScheduler.postStartHook done
```

=== [[stop]] Stopping YarnClusterScheduler (stop method)

`stop` calls the link:spark-TaskSchedulerImpl.adoc#stop[parent's `stop`] followed by link:spark-yarn-applicationmaster.adoc#sparkContextStopped[ApplicationMaster.sparkContextStopped].
