== [[YarnClusterSchedulerBackend]] YarnClusterSchedulerBackend - SchedulerBackend for YARN in Cluster Deploy Mode

`YarnClusterSchedulerBackend` is a custom link:spark-yarn-yarnschedulerbackend.adoc[YarnSchedulerBackend] for Spark on YARN in <<cluster-mode, cluster deploy mode>>.

This is a scheduler backend that supports <<multiple-application-attempts, multiple application attempts>> and link:spark-SchedulerBackend.adoc#getDriverLogUrls[URLs for driver's logs] to display as links in the web UI in the Executors tab for the driver.

It uses `spark.yarn.app.attemptId` under the covers (that the YARN resource manager sets?).

NOTE: `YarnClusterSchedulerBackend` is a `private[spark]` Scala class. You can find the sources in https://github.com/apache/spark/blob/master/yarn/src/main/scala/org/apache/spark/scheduler/cluster/YarnClusterSchedulerBackend.scala[org.apache.spark.scheduler.cluster.YarnClusterSchedulerBackend].

[TIP]
====
Enable `DEBUG` logging level for `org.apache.spark.scheduler.cluster.YarnClusterSchedulerBackend` logger to see what happens inside.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.scheduler.cluster.YarnClusterSchedulerBackend=DEBUG
```

Refer to link:../spark-logging.adoc[Logging].
====

=== [[creating-instance]] Creating YarnClusterSchedulerBackend

Creating a `YarnClusterSchedulerBackend` object requires a link:spark-TaskSchedulerImpl.adoc[TaskSchedulerImpl] and link:spark-SparkContext.adoc[SparkContext] objects.

=== [[start]] Starting YarnClusterSchedulerBackend (start method)

`YarnClusterSchedulerBackend` comes with a custom `start` method.

NOTE: `start` is part of the link:spark-SchedulerBackend.adoc#contract[SchedulerBackend Contract].

Internally, it first link:spark-yarn-applicationmaster.adoc#getAttemptId[queries ApplicationMaster for attemptId] and link:spark-yarn-yarnschedulerbackend.adoc#bindToYarn[records the application and attempt ids].

[[totalExpectedExecutors]]
It then calls the link:spark-yarn-yarnschedulerbackend.adoc#start[parent's start] and sets the parent's link:spark-yarn-yarnschedulerbackend.adoc#totalExpectedExecutors[totalExpectedExecutors] to link:spark-yarn-YarnSparkHadoopUtil.adoc#getInitialTargetExecutorNumber[the initial number of executors].

=== [[getDriverLogUrls]] Calculating Driver Log URLs (getDriverLogUrls method)

`getDriverLogUrls` in `YarnClusterSchedulerBackend` calculates the URLs for the driver's logs - standard output (stdout) and standard error (stderr).

NOTE: `getDriverLogUrls` is part of the link:spark-SchedulerBackend.adoc#contract[SchedulerBackend Contract].

Internally, it retrieves the link:README.adoc#getContainerId[container id] and through environment variables computes the base URL.

You should see the following DEBUG in the logs:

```
DEBUG Base URL for logs: [baseUrl]
```
