== ClientDistributedCacheManager

`ClientDistributedCacheManager` is a mere _wrapper_ to hold the collection of cache-related resource entries `CacheEntry` (as `distCacheEntries`) to <<addResource, add resources to>> and later <<updateConfiguration, update Spark configuration with files to distribute>>.

CAUTION: FIXME What is a resource? Is this a file only?

=== [[addResource]] Adding Cache-Related Resource (addResource method)

[source, scala]
----
addResource(
  fs: FileSystem,
  conf: Configuration,
  destPath: Path,
  localResources: HashMap[String, LocalResource],
  resourceType: LocalResourceType,
  link: String,
  statCache: Map[URI, FileStatus],
  appMasterOnly: Boolean = false): Unit
----

=== [[updateConfiguration]] Updating Spark Configuration with Resources to Distribute (updateConfiguration method)

[source, scala]
----
updateConfiguration(conf: SparkConf): Unit
----

`updateConfiguration` sets the following internal Spark configuration settings in the input `conf` link:../spark-SparkConf.adoc[Spark configuration]:

* link:spark-yarn-settings.adoc#spark.yarn.cache.filenames[spark.yarn.cache.filenames]
* link:spark-yarn-settings.adoc#spark.yarn.cache.sizes[spark.yarn.cache.sizes]
* link:spark-yarn-settings.adoc#spark.yarn.cache.timestamps[spark.yarn.cache.timestamps]
* link:spark-yarn-settings.adoc#spark.yarn.cache.visibilities[spark.yarn.cache.visibilities]
* link:spark-yarn-settings.adoc#spark.yarn.cache.types[spark.yarn.cache.types]

It uses the internal `distCacheEntries` with <<addResource, resources to distribute>>.

NOTE: It is later used in link:spark-yarn-applicationmaster.adoc#localResources[`ApplicationMaster` when it prepares local resources].
