== [[YarnClusterManager]] YarnClusterManager -- ExternalClusterManager for YARN

`YarnClusterManager` is the only currently known link:spark-ExternalClusterManager.adoc[ExternalClusterManager] in Spark. It creates a `TaskScheduler` and a `SchedulerBackend` for YARN.

=== [[canCreate]] `canCreate` Method

`YarnClusterManager` can handle the `yarn` master URL only.

=== [[createTaskScheduler]] `createTaskScheduler` Method

`createTaskScheduler` creates a link:spark-yarn-yarnclusterscheduler.adoc[YarnClusterScheduler for `cluster` deploy mode] and a link:spark-yarn-yarnscheduler.adoc[YarnScheduler for `client` deploy mode].

It throws a `SparkException` for unknown deploy modes.

```
Unknown deploy mode '[deployMode]' for Yarn
```

=== [[createSchedulerBackend]] `createSchedulerBackend` Method

`createSchedulerBackend` creates a link:spark-yarn-cluster-yarnclusterschedulerbackend.adoc[`YarnClusterSchedulerBackend` for `cluster` deploy mode] and a link:spark-yarn-client-yarnclientschedulerbackend.adoc[`YarnClientSchedulerBackend` for `client` deploy mode].

It throws a `SparkException` for unknown deploy modes.

```
Unknown deploy mode '[deployMode]' for Yarn
```

=== [[initialize]] Initializing YarnClusterManager -- `initialize` Method

`initialize` simply link:spark-TaskSchedulerImpl.adoc#initialize[initializes the input `TaskSchedulerImpl`].
