== [[BinaryClassificationEvaluator]] BinaryClassificationEvaluator -- Evaluator for Binary Classification

`BinaryClassificationEvaluator` is an link:spark-mllib-Evaluator.adoc[Evaluator] of cross-validate models fitted by binary classifications (e.g. link:spark-mllib-LogisticRegression.adoc[LogisticRegression], link:spark-mllib-RandomForestClassifier.adoc[RandomForestClassifier], `NaiveBayes`, link:spark-mllib-DecisionTreeClassifier.adoc[DecisionTreeClassifier], `MultilayerPerceptronClassifier`, `GBTClassifier`, `LinearSVC`).

[[isLargerBetter]]
`BinaryClassificationEvaluator` finds the best model by maximizing the model evaluation metric (i.e. link:spark-mllib-Evaluator.adoc#isLargerBetter[isLargerBetter] is turned on for either <<metricName, metric>>)

[[parameters]]
.BinaryClassificationEvaluator' Parameters
[cols="1,1,2",options="header",width="100%"]
|===
| Parameter
| Default Value
| Description

| [[metricName]] `metricName`
| `areaUnderROC`
| Metric name in evaluation

Can be `areaUnderROC` (default) or `areaUnderPR`

| [[rawPredictionCol]] `rawPredictionCol`
| `rawPrediction`
| Column name with raw predictions (a.k.a. confidence)

| [[labelCol]] `labelCol`
| `label`
| Column name with labels
|===

=== [[evaluate]] Evaluating Model Output -- `evaluate` Method

[source, scala]
----
evaluate(dataset: Dataset[_]): Double
----

NOTE: `evaluate` is a part of link:spark-mllib-Evaluator.adoc#evaluate[Evaluator Contract].

`evaluate`...FIXME
