== [[ALSModel]] ALSModel

`ALSModel` is a link:spark-mllib-models.adoc[model] fitted by link:spark-mllib-ALS.adoc#fit[ALS] algorithm.

`ALSModel` is a link:spark-mllib-MLWritable.adoc[MLWritable].

=== [[transform]] `transform` Method

[source, scala]
----
transform(dataset: Dataset[_]): DataFrame
----

NOTE: `transform` is a part of link:spark-mllib-transformers.adoc#transform[Transformer Contract].

`transform`...FIXME

=== [[copy]] `copy` Method

[source, scala]
----
copy(extra: ParamMap): ALSModel
----

NOTE: `copy` is a part of link:spark-mllib-Model.adoc#copy[Model Contract].

`copy`...FIXME

=== [[predict]] `predict` Internal Property

[source, scala]
----
predict: UserDefinedFunction
----

`predict` is a link:../spark-sql-udfs.adoc[user-defined function (UDF)] that...FIXME

NOTE: `predict` is used exclusively when `ALSModel` is requested to <<transform, transform>>.

=== [[creating-instance]] Creating ALSModel Instance

`ALSModel` takes the following when created:

* [[uid]] Unique ID
* [[rank]] Rank
* [[userFactors]] `DataFrame` of user factors
* [[itemFactors]] `DataFrame` of item factors

`ALSModel` initializes the <<internal-registries, internal registries and counters>>.

`ALSModel` is <<creating-instance, created>> when...FIXME
