== [[Evaluator]] Evaluator

`Evaluator` is the <<contract, contract>> in Spark MLlib for evaluators that can <<evaluate, evaluate models>> (by computing metrics).

`Evaluator` link:spark-mllib-Params.adoc[accepts parameters].

[[known-implementations]]
.Evaluator's Known Implementations
[width="100%",cols="1,2",options="header"]
|===
| Name
| Description

| `BinaryClassificationEvaluator`
|

| `ClusteringEvaluator`
|

| `MulticlassClassificationEvaluator`
|

| `RegressionEvaluator`
|
|===

=== [[evaluate-paramMap]] Evaluating Model Output with Extra Parameters -- `evaluate` Method

[source, scala]
----
evaluate(dataset: Dataset[_], paramMap: ParamMap): Double
----

`evaluate` <<copy, copies>> the extra `paramMap` and <<evaluate, evaluates a model output>>.

NOTE: `evaluate` is used...FIXME

=== [[contract]] Evaluator Contract

[source, scala]
----
package org.apache.spark.ml.evaluation

abstract class Evaluator {
  def evaluate(dataset: Dataset[_]): Double
  def copy(extra: ParamMap): Evaluator
  def isLargerBetter: Boolean = true
}
----

.Evaluator Contract
[cols="1,2",options="header",width="100%"]
|===
| Method
| Description

| [[copy]] `copy`
| Used when...

| [[evaluate]] `evaluate`
| Used when...

| [[isLargerBetter]] `isLargerBetter`
| Indicates whether the metric returned by <<evaluate, evaluate>> should be maximized (`true`) or minimized (`false`).

Gives `true` by default.
|===
