== [[PipelineStage]] PipelineStage -- ML Pipeline Component

The https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.PipelineStage[PipelineStage] abstract class represents a single stage in a link:spark-mllib-Pipeline.adoc[Pipeline].

`PipelineStage` has the following direct implementations (of which few are abstract classes, too):

* link:spark-mllib-estimators.adoc[Estimators]
* link:spark-mllib-models.adoc[Models]
* link:spark-mllib-Pipeline.adoc[Pipeline]
* link:spark-mllib-estimators.adoc#Predictor[Predictor]
* link:spark-mllib-transformers.adoc[Transformer]

[[transformSchema]]
Each `PipelineStage` transforms schema using `transformSchema` family of methods:

```
transformSchema(schema: StructType): StructType
transformSchema(schema: StructType, logging: Boolean): StructType
```

NOTE: link:spark-sql-StructType.adoc[StructType] describes a schema of a DataFrame.

[TIP]
====
Enable `DEBUG` logging level for the respective `PipelineStage` implementations to see what happens beneath.
====
