== [[ValidatorParams]] ValidatorParams

[[parameters]]
.ValidatorParams' Parameters
[cols="1,1,2",options="header",width="100%"]
|===
| Parameter
| Default Value
| Description

| [[estimator]] `estimator`
| (undefined)
| link:spark-mllib-Estimator.adoc[Estimator] for best model selection

| [[estimatorParamMaps]] `estimatorParamMaps`
| (undefined)
| Param maps for the <<estimator, estimator>>

| [[evaluator]] `evaluator`
| (undefined)
| link:spark-mllib-Evaluator.adoc[Evaluator] to select hyper-parameters that maximize the validated metric
|===

=== [[logTuningParams]] `logTuningParams` Method

[source, scala]
----
logTuningParams(instrumentation: Instrumentation[_]): Unit
----

`logTuningParams`...FIXME

NOTE: `logTuningParams` is used when...FIXME

=== [[loadImpl]] `loadImpl` Method

[source, scala]
----
loadImpl[M](
  path: String,
  sc: SparkContext,
  expectedClassName: String): (Metadata, Estimator[M], Evaluator, Array[ParamMap])
----

`loadImpl`...FIXME

NOTE: `loadImpl` is used when...FIXME

=== [[transformSchemaImpl]] `transformSchemaImpl` Method

[source, scala]
----
transformSchemaImpl(schema: StructType): StructType
----

`transformSchemaImpl`...FIXME

NOTE: `transformSchemaImpl` is used when link:spark-mllib-CrossValidator.adoc#transformSchema[CrossValidator] and link:spark-mllib-TrainValidationSplit.adoc#transformSchema[TrainValidationSplit] validate and transform schema.
