== Seahorse Community Edition

Just the past month, in September, at http://strataconf.com/big-data-conference-ny-2015[the Strata + Hadoop World conference in New York], my company http://deepsense.io/[deepsense.io] announced the very first version of the community edition of Seahorse with *Seahorse Editor* and *Workflow Executor*.

*Seahorse Community Edition* makes for developing full-blown Apache Spark applications in a visual, drag-and-drop environment in which you write *no* lines of code footnote:[Sorry, developers, it may not be *it* yet, but the team is working on an Enterprise version with nice developer-centric features. Watch http://deepsense.io/[this space]!].

The Seahorse development team is looking for you, a dear early adopter, to give the product a try and report back. It is a cost- and code-free approach that you may very much like.

Seahorse Community Edition is available at https://editor.seahorse.deepsense.io[Try Seahorse Editor] page.

Visit http://seahorse.deepsense.io[seahorse.deepsense.io] to learn more about the product!
