== 10 Lesser-Known Tidbits about Spark Standalone

CAUTION: FIXME Make sure the title reflects the number of tidbits.

* Duration: ...FIXME

=== Multiple Standalone Masters

Multiple standalone Masters in link:../spark-deployment-modes.adoc#master-urls[master URL].

=== REST Server

Read link:../spark-standalone.adoc#rest-server[REST Server].

=== Spark Standalone High-Availability

Read link:../spark-standalone.adoc#recovery-mode[Recovery Mode].

=== SPARK_PRINT_LAUNCH_COMMAND and debugging

Read link:../spark-tips-and-tricks.adoc#SPARK_PRINT_LAUNCH_COMMAND[Print Launch Command of Spark Scripts].

NOTE: It's not Standalone mode-specific thing.

=== spark-shell is spark-submit

Read link:../spark-shell.adoc[Spark shell].

NOTE: It's not Standalone mode-specific thing.

=== Application Management using spark-submit

Read link:../spark-standalone.adoc#application-management-spark-submit[Application Management using spark-submit].

=== spark-* scripts and --conf options

You can use `--conf` or `-c`.

Refer to link:../spark-submit.adoc#command-line-options[ Command-line Options].
