# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - ActiveJob: ActiveJob.md
  - BlacklistTracker: BlacklistTracker.md
  - CoarseGrainedSchedulerBackend: CoarseGrainedSchedulerBackend.md
  - DAGScheduler: DAGScheduler.md
  - DAGSchedulerEvent: DAGSchedulerEvent.md
  - DAGSchedulerEventProcessLoop: DAGSchedulerEventProcessLoop.md
  - DAGSchedulerSource: DAGSchedulerSource.md
  - DriverEndpoint: DriverEndpoint.md
  - ExecutorData: ExecutorData.md
  - ExternalClusterManager: ExternalClusterManager.md
  - FairSchedulableBuilder: FairSchedulableBuilder.md
  - FIFOSchedulableBuilder: FIFOSchedulableBuilder.md
  - JobListener: JobListener.md
  - JobWaiter: JobWaiter.md
  - LiveListenerBus: LiveListenerBus.md
  - MapStatuses:
    - MapStatus: MapStatus.md
    - CompressedMapStatus: CompressedMapStatus.md
    - HighlyCompressedMapStatus: HighlyCompressedMapStatus.md
  - Pool: Pool.md
  - ResultStage: ResultStage.md
  - ResultTask: ResultTask.md
  - Schedulable: Schedulable.md
  - SchedulableBuilder: SchedulableBuilder.md
  - SchedulerBackend: SchedulerBackend.md
  - SchedulerBackendUtils: SchedulerBackendUtils.md
  - SchedulingMode: SchedulingMode.md
  - ShuffleMapStage: ShuffleMapStage.md
  - ShuffleMapTask: ShuffleMapTask.md
  - Stage: Stage.md
  - StageInfo: StageInfo.md
  - TaskScheduler: TaskScheduler.md
  - TaskSchedulerImpl: TaskSchedulerImpl.md
  - Task: Task.md
  - TaskContext: TaskContext.md
  - TaskContextImpl: TaskContextImpl.md
  - TaskDescription: TaskDescription.md
  - TaskInfo: TaskInfo.md
  - TaskLocation: TaskLocation.md
  - TaskResult: TaskResult.md
  - TaskResultGetter: TaskResultGetter.md
  - TaskSet: TaskSet.md
  - TaskSetBlacklist: TaskSetBlacklist.md
  - TaskSetManager: TaskSetManager.md
  - "*"