# https://lukasgeiter.github.io/mkdocs-awesome-nav/
nav:
  - index.md
  - Features:
    - features/index.md
    - Barrier Execution Mode: barrier-execution-mode
    - configuration-properties.md
    - developer-api.md
    - java-25.md
    - Logging: spark-logging.md
    - Plugin Framework: plugins
    - Push-Based Shuffle: push-based-shuffle.md
    - Shuffle System:
      - shuffle/index.md
      - Shuffle Handles:
        - shuffle/BaseShuffleHandle.md
        - shuffle/BypassMergeSortShuffleHandle.md
        - shuffle/SerializedShuffleHandle.md
        - shuffle/ShuffleHandle.md
      - Shuffle Readers:
        - shuffle/BlockStoreShuffleReader.md
        - shuffle/ShuffleReader.md
      - BypassMergeSortShuffleWriter: shuffle/BypassMergeSortShuffleWriter.md
      - DownloadFileManager: shuffle/DownloadFileManager.md
      - FetchFailedException: shuffle/FetchFailedException.md
      - IndexShuffleBlockResolver: shuffle/IndexShuffleBlockResolver.md
      - MigratableResolver: shuffle/MigratableResolver.md
      - ShuffleBlockPusher: shuffle/ShuffleBlockPusher.md
      - ShuffleBlockResolver: shuffle/ShuffleBlockResolver.md
      - ShuffleExternalSorter: shuffle/ShuffleExternalSorter.md
      - ShuffleInMemorySorter: shuffle/ShuffleInMemorySorter.md
      - ShuffleManager: shuffle/ShuffleManager.md
      - shuffle/ShuffleReadMetricsReporter.md
      - ShuffleWriteMetricsReporter: shuffle/ShuffleWriteMetricsReporter.md
      - ShuffleWriteProcessor: shuffle/ShuffleWriteProcessor.md
      - ShuffleWriter: shuffle/ShuffleWriter.md
      - SortShuffleManager: shuffle/SortShuffleManager.md
      - SortShuffleWriter: shuffle/SortShuffleWriter.md
      - UnsafeShuffleWriter: shuffle/UnsafeShuffleWriter.md
      - Spillable Collections:
        - Spillable: shuffle/Spillable.md
        - ExternalAppendOnlyMap: shuffle/ExternalAppendOnlyMap.md
        - ExternalSorter: shuffle/ExternalSorter.md
      - ShuffleDataIOs:
        - ShuffleDataIO: shuffle/ShuffleDataIO.md
        - LocalDiskShuffleDataIO: shuffle/LocalDiskShuffleDataIO.md
        - ShuffleDriverComponents: shuffle/ShuffleDriverComponents.md
        - ShuffleExecutorComponents: shuffle/ShuffleExecutorComponents.md
        - ShuffleMapOutputWriter: shuffle/ShuffleMapOutputWriter.md
        - LocalDiskShuffleMapOutputWriter: shuffle/LocalDiskShuffleMapOutputWriter.md
        - ExecutorDiskUtils: shuffle/ExecutorDiskUtils.md
        - SingleSpillShuffleMapOutputWriter: shuffle/SingleSpillShuffleMapOutputWriter.md
        - LocalDiskShuffleExecutorComponents: shuffle/LocalDiskShuffleExecutorComponents.md
        - LocalDiskSingleSpillMapOutputWriter: shuffle/LocalDiskSingleSpillMapOutputWriter.md
        - ShuffleDataIOUtils: shuffle/ShuffleDataIOUtils.md
    - Stage-Level Scheduling: stage-level-scheduling
  - Internals:
    - Overview: overview.md
    - SparkEnv: SparkEnv.md
    - SparkConf: SparkConf.md
    - SparkContext: SparkContext.md
    - SparkCoreErrors: SparkCoreErrors.md
    - Local Properties: local-properties.md
    - Inside Creating SparkContext: SparkContext-creating-instance-internals.md
    - SparkFiles: SparkFiles.md
    - Spark Properties: spark-properties.md
    - Executor: executor
    - External Shuffle Service: external-shuffle-service
    - MapOutputTracker:
      - MapOutputStatistics: scheduler/MapOutputStatistics.md
      - MapOutputTracker: scheduler/MapOutputTracker.md
      - MapOutputTrackerMaster: scheduler/MapOutputTrackerMaster.md
      - MapOutputTrackerMasterEndpoint: scheduler/MapOutputTrackerMasterEndpoint.md
      - MapOutputTrackerWorker: scheduler/MapOutputTrackerWorker.md
      - ShuffleStatus: scheduler/ShuffleStatus.md
    - Dynamic Resource Allocation: dynamic-allocation
    - Core: core
    - OutputCommitCoordinator: OutputCommitCoordinator.md
    - Scheduler: scheduler
    - RPC: rpc
    - Memory: memory
    - Storage: storage
    - Serialization: serializer
    - Speculative Execution of Tasks: speculative-execution-of-tasks.md
    - Deployment Architecture:
      - Architecture: architecture.md
      - Driver: driver.md
      - Master: master.md
      - Workers: workers.md
    - Writers and Committers:
      - SparkHadoopWriter: SparkHadoopWriter.md
      - HadoopWriteConfigUtil: HadoopWriteConfigUtil.md
      - FileCommitProtocol: FileCommitProtocol.md
      - HadoopMapReduceCommitProtocol: HadoopMapReduceCommitProtocol.md
      - HadoopMapRedCommitProtocol: HadoopMapRedCommitProtocol.md
      - HadoopMapReduceWriteConfigUtil: HadoopMapReduceWriteConfigUtil.md
      - HadoopMapRedWriteConfigUtil: HadoopMapRedWriteConfigUtil.md
    - Status: status
    - Network: network
    - Misc:
      - BytesToBytesMap: BytesToBytesMap.md
      - ExecutorDeadException: ExecutorDeadException.md
      - HeartbeatReceiver: HeartbeatReceiver.md
      - InterruptibleIterator: InterruptibleIterator.md
      - PartitionEvaluatorFactory: PartitionEvaluatorFactory.md
      - PartitionEvaluator: PartitionEvaluator.md
      - Utils: Utils.md
    - Tips and Tricks: tips-and-tricks
    - Spark Local: local
  - Shared Variables:
    - Accumulators: accumulators
    - Broadcast Variables: broadcast-variables
  - Monitoring:
    - ConsoleProgressBar: ConsoleProgressBar.md
    - Debugging Spark: spark-debugging.md
    - DriverLogger: DriverLogger.md
    - ListenerBus: ListenerBus.md
    - SparkListener: SparkListener.md
    - SparkListenerBus: SparkListenerBus.md
    - SparkListenerEvents:
      - SparkListenerEvent: SparkListenerEvent.md
      - SparkListenerTaskEnd: SparkListenerTaskEnd.md
    - SparkListenerInterface: SparkListenerInterface.md
    - SparkStatusTracker: SparkStatusTracker.md
    - SpillListener: SpillListener.md
    - StatsReportListener: StatsReportListener.md
    - TaskCompletionListener: TaskCompletionListener.md
    - TaskFailureListener: TaskFailureListener.md
    - Spark History Server: history-server
    - Status REST API: rest
    - Metrics:
      - metrics/index.md
      - Configuration Properties: metrics/configuration-properties.md
      - MetricsSystem: metrics/MetricsSystem.md
      - MetricsConfig: metrics/MetricsConfig.md
      - Source: metrics/Source.md
      - Sink: metrics/Sink.md
      - Sources:
        - JvmSource: metrics/JvmSource.md
      - Sinks:
        - MetricsServlet: metrics/MetricsServlet.md
        - PrometheusServlet: metrics/PrometheusServlet.md
  - Tools:
    - tools/index.md
    - AbstractLauncher: tools/AbstractLauncher.md
    - Main: tools/Main.md
    - tools/pyspark.md
    - spark-submit: tools/spark-submit
    - SparkApplication: tools/SparkApplication.md
    - JavaMainApplication: tools/JavaMainApplication.md
    - spark-shell: tools/spark-shell.md
    - spark-class: tools/spark-class.md
    - SparkLauncher: tools/SparkLauncher.md
    - SparkClassCommandBuilder: tools/SparkClassCommandBuilder.md
    - DependencyUtils: tools/DependencyUtils.md
    - AbstractCommandBuilder: tools/AbstractCommandBuilder.md
  - RDD: rdd
  - Demos:
    - demo/index.md
    - DiskBlockManager and Block Data: demo/diskblockmanager-and-block-data.md
    - Exercises:
      - One-liners using PairRDDFunctions: exercises/spark-exercise-pairrddfunctions-oneliners.md
      - Learning Jobs and Partitions Using take Action: exercises/spark-exercise-take-multiple-jobs.md
      - Spark Standalone - Using ZooKeeper for High-Availability of Master: exercises/spark-exercise-standalone-master-ha.md
      - Spark's Hello World using Spark shell and Scala: exercises/spark-hello-world-using-spark-shell.md
      - WordCount using Spark shell: exercises/spark-examples-wordcount-spark-shell.md
      - Your first complete Spark application (using Scala and sbt): exercises/spark-first-app.md
      - Using Spark SQL to update data in Hive using ORC files: exercises/spark-sql-hive-orc-example.md
      - Developing Custom SparkListener to monitor DAGScheduler in Scala: exercises/spark-exercise-custom-scheduler-listener.md
      - Working with Datasets from JDBC Data Sources (and PostgreSQL): exercises/spark-exercise-dataframe-jdbc-postgresql.md
      - Causing Stage to Fail: exercises/spark-exercise-failing-stage.md
  - Web UIs: webui
