== [[YarnClusterScheduler]] YarnClusterScheduler -- TaskScheduler for Cluster Deploy Mode

`YarnClusterScheduler` is the xref:scheduler:TaskScheduler.md[TaskScheduler] for link:README.md[Spark on YARN] in link:spark-submit.md#deploy-mode[cluster deploy mode].

It is a custom link:spark-yarn-yarnscheduler.md[YarnScheduler] that makes sure that appropriate initialization of link:spark-yarn-applicationmaster.md[ApplicationMaster] is performed, i.e. <<postStartHook, SparkContext is initialized>> and <<stop, stopped>>.

While being created, you should see the following INFO message in the logs:

```
INFO YarnClusterScheduler: Created YarnClusterScheduler
```

[TIP]
====
Enable `INFO` logging level for `org.apache.spark.scheduler.cluster.YarnClusterScheduler` to see what happens inside `YarnClusterScheduler`.

Add the following line to `conf/log4j.properties`:

```
log4j.logger.org.apache.spark.scheduler.cluster.YarnClusterScheduler=INFO
```

Refer to link:../spark-logging.md[Logging].
====

=== [[postStartHook]] `postStartHook` Callback

`postStartHook` calls link:spark-yarn-applicationmaster.md#sparkContextInitialized[ApplicationMaster.sparkContextInitialized] before the xref:scheduler:TaskSchedulerImpl.md#postStartHook[parent's `postStartHook`].

You should see the following INFO message in the logs:

```
INFO YarnClusterScheduler: YarnClusterScheduler.postStartHook done
```

=== [[stop]] Stopping YarnClusterScheduler (stop method)

`stop` calls the xref:scheduler:TaskSchedulerImpl.md#stop[parent's `stop`] followed by link:spark-yarn-applicationmaster.md#sparkContextStopped[ApplicationMaster.sparkContextStopped].
