= YarnClusterManager

`YarnClusterManager` is the only currently known xref:scheduler:ExternalClusterManager.md[] in Spark. It creates a `TaskScheduler` and a `SchedulerBackend` for YARN.

== [[canCreate]] `canCreate` Method

`YarnClusterManager` can handle the `yarn` master URL only.

== [[createTaskScheduler]] `createTaskScheduler` Method

`createTaskScheduler` creates a link:spark-yarn-yarnclusterscheduler.md[YarnClusterScheduler for `cluster` deploy mode] and a link:spark-yarn-yarnscheduler.md[YarnScheduler for `client` deploy mode].

It throws a `SparkException` for unknown deploy modes.

```
Unknown deploy mode '[deployMode]' for Yarn
```

== [[createSchedulerBackend]] `createSchedulerBackend` Method

`createSchedulerBackend` creates a link:spark-yarn-cluster-yarnclusterschedulerbackend.md[`YarnClusterSchedulerBackend` for `cluster` deploy mode] and a link:spark-yarn-client-yarnclientschedulerbackend.md[`YarnClientSchedulerBackend` for `client` deploy mode].

It throws a `SparkException` for unknown deploy modes.

```
Unknown deploy mode '[deployMode]' for Yarn
```

== [[initialize]] Initializing YarnClusterManager -- `initialize` Method

`initialize` simply xref:scheduler:TaskSchedulerImpl.md#initialize[initializes the input `TaskSchedulerImpl`].
