= BlockDataManager

*BlockDataManager* is the <<contract, abstraction>> of <<implementations, block data managers>> that manage storage for blocks of data (aka _block storage management API_).

BlockDataManager uses xref:storage:BlockId.adoc[] to uniquely identify blocks of data and xref:network:ManagedBuffer.adoc[] to refer to them.

[[implementations]]
NOTE: xref:storage:BlockManager.adoc[] is the default and only implementation of the <<contract, BlockDataManager Contract>> in Apache Spark.

[[contract]]
.BlockDataManager Contract
[cols="1m,3",options="header",width="100%"]
|===
| Method
| Description

| getBlockData
a| [[getBlockData]]

[source, scala]
----
getBlockData(
  blockId: BlockId): ManagedBuffer
----

Fetches a block data (as a xref:network:ManagedBuffer.adoc[]) for the given xref:storage:BlockId.adoc[]

Used when:

* NettyBlockRpcServer is requested to xref:storage:NettyBlockRpcServer.adoc#receive-OpenBlocks[handle a OpenBlocks message]

* `ShuffleBlockFetcherIterator` is requested to xref:storage:ShuffleBlockFetcherIterator.adoc#fetchLocalBlocks[fetchLocalBlocks]

| putBlockData
a| [[putBlockData]]

[source, scala]
----
putBlockData(
  blockId: BlockId,
  data: ManagedBuffer,
  level: StorageLevel,
  classTag: ClassTag[_]): Boolean
----

Stores (_puts_) a block data (as a xref:network:ManagedBuffer.adoc[]) for the given xref:storage:BlockId.adoc[]. Returns `true` when completed successfully or `false` when failed.

Used when NettyBlockRpcServer is requested to xref:storage:NettyBlockRpcServer.adoc#receive-UploadBlock[handle an UploadBlock message]

| putBlockDataAsStream
a| [[putBlockDataAsStream]]

[source, scala]
----
putBlockDataAsStream(
  blockId: BlockId,
  level: StorageLevel,
  classTag: ClassTag[_]): StreamCallbackWithID
----

Stores a block data that will be received as a stream

Used when NettyBlockRpcServer is requested to xref:storage:NettyBlockRpcServer.adoc#receiveStream[receiveStream]

| releaseLock
a| [[releaseLock]]

[source, scala]
----
releaseLock(
  blockId: BlockId,
  taskAttemptId: Option[Long]): Unit
----

Releases a lock

Used when:

* TorrentBroadcast is requested to xref:core:TorrentBroadcast.adoc#releaseLock[releaseLock]

* BlockManager is requested to <<BlockManager.adoc#handleLocalReadFailure, handleLocalReadFailure>>, <<BlockManager.adoc#getLocalValues, getLocalValues>>, <<BlockManager.adoc#getOrElseUpdate, getOrElseUpdate>>, <<BlockManager.adoc#doPut, doPut>>, and <<BlockManager.adoc#releaseLockAndDispose, releaseLockAndDispose>>

|===
